### ISSUE TITLE
mtbin segfaulting without output and/or empty outputs

### ISSUE THREAD

**Issue by thijsdhollander** [MRtrix3/mrtrix3#1000]
#As reported [here](http://community.mrtrix.org/t/mtbin-output/909).

We also have this in 3 of our / collaborators' studies.  It happens several iterations into the algorithm, and only for some subjects.  This may be a problem dealing with certain exceptional values (zeros, negative values in the summed tissue map, maybe NaNs?); but this is just a wild guess at this point.  The `-debug` output reveals the automatically computed mask going wonky (e.g. empty) about an iteration before the segfault happens.  And then we (over here) get:

```
mtbin: [ .  ] performing intensity normalisation and bias field correction...... 
mtbin: [SYSTEM FATAL CODE: SIGSEGV (11)] Segmentation fault: Invalid memory access
```

I've labelled it as "critical", since it basically breaks the current multi-tissue FBA pipeline.

There's sadly no chances of myself having any time soon to do bug squashing... too many crucial commitments already.

**Comment by thijsdhollander** [comment]
Ok, @rtabbara took the plunge investigating the scenario on a failing case.  We're clear on what exactly goes wrong in the cases where it does go wrong.  The problem is that it's not just a bug in the implementation; it's a combination of a few conceptual problems with the algorithm, and how it deals with outliers versus mask estimation if no (decent) mask is provided.  Without going into details now (don't have the time), it's essentially a combination of a couple of chicken and egg problems, which are very problematic in that sense indeed.  I'll try to come up with a few "executive" decisions by early next week, which should serve as robust solutions.  They will alter a few (minor) aspects of the algorithm though.  It's also very likely at this stage that part of that solution will include requiring the user to provide a brain mask.  It's very hard to *guarantee* the algorithm working *robustly* otherwise.  This should be no problem though, since users will have generated and provided such a mask typically anyway before and to the CSD step.  So well, more on Monday. :wink:

**Comment by maxpietsch** [comment]
> will include requiring the user to provide a brain mask. 

I'd be for that. For my purposes, I did change `mtbin` to take user defined masks as a starting point for the estimation. For debugging, I also found an option to treat the mask as fixed useful.

> They will alter a few (minor) aspects of the algorithm though.

These changes should also be necessary for `mtnormalise`, I presume?

**Comment by thijsdhollander** [comment]
> I'd be for that.

Nice. :smile:  There was too much possible randomness going on without such a requirement; and it was a sensible one anyway.

> For my purposes, I did change mtbin to take user defined masks as a starting point for the estimation.

There was already a `-mask` option, but the way we deal with it now is also slightly different.

> For debugging, I also found an option to treat the mask as fixed useful.

This was, surprisingly (for me) actually inherently already the case when the existing `-mask` was supplied.  In that case, the outlier detection/removal was actually *not* happening (as it was deemed part of the mask estimation, that was in turn only happening if no mask was supplied).  We also changed this: along with a `-mask` being mandatory, outlier removal is still done within that mask, and anew for each separate iteration (as when the bias field estimation gets better, what's classified as outlier may change, both ways).

> These changes should also be necessary for mtnormalise, I presume?

We didn't touch that one at the moment, due to the `mtbin` changes itself being quite urgent.  I was also a bit surprised about the existence of this one.  It seems more sensible to just have a `-no_bias` or something similar option to `mtbin`, so the behaviour is always completely consistent.  I just had a look, and noticed `mtnormalise` seems to (or it's manual seems to suggest that) by default come up with an individual scale factor per tissue type (without an option to even change that).  If that is the case (I may be misinterpreting the manual), that's something I'd never recommend in a group-wise study, where the units have to be comparable between subjects.  You want to scale each subject's complete CSD outcome (tissue types an all) by a single global scale factor to overcome global intensity differences that were present in the raw data, but you don't want to change the balance between e.g. tissue types *independently* for different subjects.  Another reason, I'd say, to ditch `mtnormalise` and accommodate it into `mtbin`, which has a single global scale factor output by default (with an option to change for very particular quite non-default scenarios).

Finally, the same seems to go for `mrmodelfield`, which seems to just do part of the bias bit of `mtbin`...? :confused:

**Comment by thijsdhollander** [comment]
It's done and over with; `mtlognorm` fixes all the problems in the universe.  The old `mtnormalise` will soon undergo the same treatment.
