### ISSUE TITLE
Terminology for "outcome" of SIFT(2)ed track densities / afdconnectivity / and the like

### ISSUE THREAD

**Issue by thijsdhollander** [MRtrix3/mrtrix3#1010]
I've never really gotten round to creating an issue about this (it's also not per se an issue, but still a worthwhile discussion that'll need some time to mature and converge, I reckon), but having written up the essence about what I think is the "issue" [over here](http://community.mrtrix.org/t/how-to-calculate-afd-after-sift2/918/5), creating this issue just became much more easy. :smile:   The outcome of this could, towards the future, enhance the documentation quite a bit.  I stumbled upon this myself, when I was preparing for an informal lecture on some MRtrix features and analysis methods for some collaborators.  As I was sitting on the train and thinking about how to explain (the limitations of) `afdconnectivity`, I thought I'd look for inspiration and context in the actual description of the `afdconnectivity` command.  That's when I first became slightly "alarmed" (a bit of an exaggeration, but still) about wordings like _"This normalisation results in a measure that is more related to **_the cross-sectional volume_** of the tract (and therefore 'connectivity')."_ .

As I was trying to come up with explanations that referred as much as possible to the FD, FC and FDC terminology we got quite standardised at the moment, I found this to be clashing a bit: as I've described on the forum, these descriptions have a certain "FC" ring to them, but the concept that they are much closer to, is in fact "FDC".

So well, I thought I'd create this issue as a place to discuss about this.  I would personally use the existing FD, FC and FDC framework/terminology as a reference (and not change that at all, we're already in the middle of a pretty big effort to push and standardise that one).  But I'm interested in seeing this discussion happen, so we don't clash too much among ourselves, for the sake of clarity for all those users out there. :slightly_smiling_face:

**Comment by thijsdhollander** [comment]
A few valuable quotes from @Lestropie on the forum, and myself clarifying my own words a bit:

> the FC metric. This isn't a "fibre cross-section", but a "change in fibre cross-section". I've tried to clarify this where I can, and would have preferred if it were part of the "official definition" of the term partly for this reason, but a compromise was needed so as not to bloat the FBA terminology.

Yep, that's all sensible.  The way I handle this, if people do stumble over it (but that's been quite rare, in my experience), is to say "compare FD or FC" or "analyse changes in FD or FC".  In a way, both FD and FC "suffer" from this issue: they're both not absolute metrics, but relative to some kind of point of reference; so normalisation has to happen for both of them.  For FD, this is done by intensity normalisation (and bias field correction).  After that, we do reason that FD is not only comparable fixel-wise between subjects, but even between different fixels of the same subject (otherwise e.g. all the SIFT-related theory wouldn't be possible).  For FC, the normalisation is done by registration to a common template.  After that, the FC "metric" is deemed to be fixel-wise comparable between subjects; so you can in principle give it a name that doesn't have "change" in it as well, if you also allowed that for FD.  Unlike FD, it's still not comparable between fixels of the same subject, since the normalisation is to the "reference" that is the template, which can still spatially vary in what it uses as a "reference" to express the subject-wise FC relative to.

But well, a long story to essentially say that I'm myself not really bothered by it.  Like I mentioned, I've never really seen a user (that is not us) stumble over this.  The way I tend to treat it, I explain FD and FC more by focussing on *what they are sensitive to*, to avoid even describing them as a metric (which may lead people to think of *absolute* metrics).  It is in this context, that the words "microscopic" or "microstructure" (for FD) and "macroscopic" or "morphology" (for FC) may come into play into such explanations.  I've found those really work well in giving new users at least some terminology that is more familiar, or at least already makes them not mix up FD and FC initially.  It clearly sets them apart, again based on *what they are sensitive to*.  This also helps making the link to relating FD and FC to the kinds of effects they may be thinking of: e.g. axon transection & initial stages of (e.g. Wallerian) degeneration versus e.g. macroscopic atrophy.

> I'd hesitate about explicitly comparing it with FDC, since the similarity is incomplete and would be of little use to anyone doing connectomics but not FBA. If you have a good understanding of both concepts, then absolutely it's closest to FDC; but I'm not sure if drawing the parallels helps or hinders education of the concept.

Sure, I was definitely not for any ultimate goal after calling it FDC or something (and I agree with the point that users don't need to _rely_ on FBA explanations to do connectomics); by goal was more the other way around: to avoid clashes for users that do know the FD/FC/FDC terminology, and may be triggered by the kinds of words chosen in the connectomics manuals to think of the "FC that they know".

But apart from that: the challenge in communicating what FBA of FD versus FC *is sensitive to* is in many ways very similar to explaining what the "connection density / SIFTed track count (potentially normalised in further ways, ...) / ..."  *is sensitive to*.  It took @draffelt (and others with him) quite a while to get that explanation right, for the audience that we're typically trying to reach; and it seems we've done quite well with the FD / FC / FDC explanations that that quest has converged upon (at least I can personally not think of better choices on that front that strike all the right balances for all of the audiences we need to take into account).  Adding words like "microscopic" and "macroscopic" to that, based on certain particular audiences at hand, seems to work well in practice too.  So I do think those things can serve as a useful guide.  And it would still of course be nice to have the terminology at least reflect the similarities between certain concepts on the FBA side of things versus the connectomics side of things. :slightly_smiling_face:

**Comment by Lestropie** [comment]
Currently finalising the first draft of a manuscript related to this. So if anybody has any particularly strong views or ideas, time to jump in.

**Comment by thijsdhollander** [comment]
So well, all of the above; especially with respect to a sort of "consistency" across FBA and connectomics, both of "FD/FC/FDC".  That and some of the normalisation related "issues" that were recently discussed on the community forum.  I will be making some points about that myself in some published words/phrases as well, so we should probably have an internal face-to-face discussion about this over here with Alan.  I can't disclose more than the above over here publicly.

**Comment by thijsdhollander** [comment]
Closing this; looks like this is a bit outdated by now. Feel free to re-open or re-start if needed.
