### ISSUE TITLE
dwinormalise & dwiintensitynorm as script algorithms

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#1064]
Following comment [here](http://community.mrtrix.org/t/preproc-and-dwiintensitynorm-dwinormalise/10450).

The difference between these two is certainly not clear from the command names. Moreover, the internals of `dwinormalise` are quite simple. Apart from the `-percentile` option (which is probably never used, but could nevertheless theoretically be added to `mrstats`), it's probably possible to embed the functionality of this entire command into the `dwiintensitynorm` script, and remove `dwinormalise`. All that is required for each subject is to get the *b*=0 volumes, calculate the median within the mask, and multiply the whole DWI series by the ratio of the target value to that median.

**Comment by thijsdhollander** [comment]
I do use `dwinormalise` on its own at times.  I actually find it to be _very_ handy in a range of scenarios where I'm pretty confident what (definition of) region I want to use for normalisation purposes.  If the names of the script and the command are too similar, I'd vote for a change of the script name to make it more clear that the script operates on groups.  I definitely don't want to get rid of the `dwinormalise` command.

**Comment by Lestropie** [comment]
OK easy.

I suppose the follow-up question then would be: if it is useful in its own right, whether or not it would be better implemented as a script rather than a binary, given all of the steps within it can be done using other commands. Probably doesn't matter a great deal, and may not be worth the effort; just thinking from a naming perspective, if you had e.g. `dwisubjnorm` and `dwigroupnorm`, to separate between subject-wise DWI normalisation and group-wise, whether having both as scripts would make more sense than one being a binary and the other a script.

Or even a single `dwinormalise` script that has subject-wise and group-wise *algorithms*, much like `dwi2response` / `5ttgen` (this would also handle their differences in interface).

Suggestions regarding the naming are welcome either way.

**Comment by jdtournier** [comment]
> Or even a single `dwinormalise` script that has subject-wise and group-wise algorithms, much like `dwi2response` / `5ttgen` (this would also handle their differences in interface).

That would get my vote...

**Comment by Lestropie** [comment]
I must admit having them as two algorithms in the one script made a whole lot of sense when it popped into my head while writing the above. It might also emphasise that these things are not set in stone. Altering issue title accordingly.
