### ISSUE TITLE
Change configure debug optimization flag

### ISSUE THREAD

**Issue by rtabbara** [MRtrix3/mrtrix3#1072]
The configure script is using the optimizer flag `-O1` for a debug build, but this results in optimized-out variables which hinders the ability to step through the code. The flag should be set to `-O0`.

Here's the part in question: https://github.com/MRtrix3/mrtrix3/blob/master/configure#L1232

**Comment by Lestropie** [comment]
Was set in 05b9ad19.

Need to make sure that both `gcc` and `clang` are happy with `-O0`.

**Comment by jdtournier** [comment]
Yes, the default used to be `-Og`, which is the recommended optimisation level for debugging with `gcc`. But `clang` doesn't understand it. The commit @Lestropie pointed out contains a link to a post suggesting `-O1` as a good compromise between optimsation and debugging that works across both `gcc` and `clang` - but I'm happy to switch to `-O0` if both compilers support it...
