### ISSUE TITLE
"Tags" for executables

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#1085]
Idea arose some time ago (possibly at ISMRM Singapore), but wan't listed on GitHub.

Each command / script could have associated with it one or more "tags", that capture some property of what the command does or the data it operates on. `generate_user_docs` would then need to generate a page for each tag, listing those commands containing that tag.

Either an example of such usage, or an independent hidden parameter, would be whether the command is designed specifically for DWI processing, or whether it is applicable more broadly.

**Comment by jdtournier** [comment]
Nice idea, but after discussion, this is likely to add maintenance burden for what might be a seldom used feature. Let's keep it in mind and re-open if the need arises.
