### ISSUE TITLE
compilation failure with 3.0_RC2 and Intel C++ compiler 17.0.1.132

### ISSUE THREAD

**Issue by boegel** [MRtrix3/mrtrix3#1089]
I'm running into the following (very similar) compilation errors when trying to compile MRtrix 3.0_RC2 with the Intel compilers (see version information below):

```
cmd/mrcalc.cpp(715): internal error: assertion failed at: "shared/cfe/edgcpfe/exprutil.c", line 5014

    auto loop = ThreadedLoop ("computing: " + operation_string(stack[0]), output, 0, output.ndim(), 2);
                ^

compilation aborted for cmd/mrcalc.cpp (code 4)
--
./core/algo/threaded_copy.h(87): internal error: assertion failed at: "shared/cfe/edgcpfe/exprutil.c", line 5014

        ThreadedLoop (message, source, from_axis, to_axis, num_axes_in_thread)
        ^

compilation aborted for cmd/labelconvert.cpp (code 4)
--
./core/algo/threaded_copy.h(87): internal error: assertion failed at: "shared/cfe/edgcpfe/exprutil.c", line 5014

        ThreadedLoop (message, source, from_axis, to_axis, num_axes_in_thread)
        ^

compilation aborted for src/dwi/tractography/mapping/mapper.cpp (code 4)
--
./core/algo/threaded_copy.h(87): internal error: assertion failed at: "shared/cfe/edgcpfe/exprutil.c", line 5014

        ThreadedLoop (message, source, from_axis, to_axis, num_axes_in_thread)
        ^

compilation aborted for cmd/mrdump.cpp (code 4)
--
./core/algo/threaded_copy.h(87): internal error: assertion failed at: "shared/cfe/edgcpfe/exprutil.c", line 5014

        ThreadedLoop (message, source, from_axis, to_axis, num_axes_in_thread)
        ^

compilation aborted for cmd/dwiextract.cpp (code 4)
--
./core/algo/threaded_copy.h(87): internal error: assertion failed at: "shared/cfe/edgcpfe/exprutil.c", line 5014

        ThreadedLoop (message, source, from_axis, to_axis, num_axes_in_thread)
        ^

compilation aborted for cmd/mrconvert.cpp (code 4)
```

Example compiler command:

```
icpc -c -std=c++11 -pthread -fPIC -O2 -xHost -ftz -fp-speculation=safe -fp-model source -std=c++11 -DMRTRIX_WORD64 -Wall -O3 -DNDEBUG -Isrc -I./core -Icmd -DEIGEN_DONT_PARALLELIZE cmd/mrconvert.cpp -o tmp/cmd/mrconvert.o
```

Any idea what the problem may be here?

Since it's an assertion failure in the Intel compilers themselves, I'm not sure this can be fixed in the MRtrix sources, it may be a problem with the compiler itself...

```
$ icc -V
Intel(R) C Intel(R) 64 Compiler for applications running on Intel(R) 64, Version 17.0.1.132 Build 20161005
Copyright (C) 1985-2016 Intel Corporation.  All rights reserved.
```

**Comment by boegel** [comment]
Maybe this is helpful...

I just tried with an older version of the Intel C++ compiler, and then I'm hitting a very similar error a lot earlier in the build process, i.e. during configure:

```
Checking JSON for Modern C++ requirements:
COMPILE /tmp/eb-C4RWeW/tmp3MXOUT.cpp:
---

#include "file/json.h"

int main (int argc, char* argv[])
{
  nlohmann::json json;
  json["key"] = "value";
}


---
EXEC <<
CMD: icpc -c -std=c++11 -pthread -fPIC -O2 -xHost -ftz -fp-speculation=safe -fp-model source -std=c++11 -DMRTRIX_WORD64 -I/tmp/vsc40023/easybuild_build/MRtrix/3.0_RC2/intel-2016b-Python-2.7.12/core /tmp/eb-C4RWeW/tmp3MXOUT.cpp -o /tmp/eb-C4RWeW/tmp3MXOUT.o
EXIT: 4
STDERR:
/tmp/vsc40023/easybuild_build/MRtrix/3.0_RC2/intel-2016b-Python-2.7.12/core/file/json.h(1180): internal error: assertion failed at: "shared/cfe/edgcpfe/il.c", line 18463

      -> decltype(to_json(j, std::forward<T>(val)), void())
                  ^

compilation aborted for /tmp/eb-C4RWeW/tmp3MXOUT.cpp (code 4)
>>

error deleting temporary file "/tmp/eb-C4RWeW/tmp3MXOUT.o": No such file or directory
ERROR:  error compiling JSON test application!

  MRtrix3 was unable to compile a test program involving JSON for Modern C++. Your compiler may not be sufficiently up-to-date.
```

**Comment by boegel** [comment]
Same problem still occurs with latest stable release of Intel C++ compiler (17.0.4.196 Build 20170411).

I'll open a ticket with Intel support to see if this is a known issue.

**Comment by bjeurissen** [comment]
As far as I know all the devs are using GCC or Clang, so I'm not sure we will be able to help much. Just out of curiosity: did you get any worthwhile performance improvements in the past when compiling mrtrix using ICC as opposed to GCC or Clang?

**Comment by Lestropie** [comment]
Yes, we're probably of limited help here unfortunately. My only experience with compilers spitting "internal error" is when `g++` on MSYS2 exceeds 4GB RAM usage on a single unit (the build chain still has 32-bit components apparently).

You could try stepping back through the *MRtrix3* history (`3.0_RC1`, `0.3.16`, `0.3.15`, ...) and see if it starts working; if `0.3.16` works but `3.0_RC1` doesn't, it probably doesn't like some C++11 component. For instance, this one:

> `-> decltype(to_json(j, std::forward<T>(val)), void())`

reminds me of GCC 4.8, which reports C++11 compatibility but in fact doesn't support certain features. Though one would expect it to do better than "internal error" in such circumstances...

**Comment by boegel** [comment]
I contacted Intel support on this, and they're looking into it (but I'm not expecting a quick solution here). They're now looking into reproducing the problem and checking whether the 18.0 beta version of the compilers still has the same problem.

For now, I proceeded with building MRtrix 3.0_RC2 with GCC (v6.3.0) instead.

**Comment by boegel** [comment]
Just got an update from Intel support:

```
I have reproduced this bug with latest compiler build and escalated to the developers to fix it (CMPLRS-45269).
```

**Comment by boegel** [comment]
Another update from Intel support:
```
The root cause was identified and the developers work on the solution.
```

**Comment by jdtournier** [comment]
@boegel: great to hear, thanks for reporting back. I'll close this issue then, and mark it `wontfix`.

**Comment by boegel** [comment]
Another update:

```
The solution is implemented. We expect it to be available with 2018 Update 1 compiler version.
```
