### ISSUE TITLE
average_response: De-mean before averaging

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#1096]
Currently, `average_response` does a direct mean of response function ZSH coefficients across subjects. This means that if the overall amplitude of the response function is larger in one subject than in others, the shape of the response function for that subject will have a greater influence on the shape of the group average response function. If equalising the intensity of WM *b*=0 signal across subjects using `dwiintensitynorm` before this is done, this could be perceived as a desirable effect: subjects with a smaller RF after `dwiintensitynorm` would have less influence on the shape of the mean response. However in the current [multi-tissue FBA documentation](http://mrtrix.readthedocs.io/en/latest/fixel_based_analysis/mt_fibre_density_cross-section.html), the `dwiintensitynorm` step is no longer performed. Hence the scanner reconstruction gain factor could influence which subjects have greater influence on the shape of the group average response.

In this case, it could be preferable to instead normalise each subject's RF to a fixed *l*=0, average, then re-scale the resulting average response to the mean *l*=0 across subjects.

What's not written in stone is how this normalisation should occur in a multi-shell context, i.e. whether to normalise independently for each shell or take e.g. a geometric mean of scaling factors across shells for that subject.

Tagged `question` for a reason. 👂

**Comment by Lestropie** [comment]
Implemented as part of #1449. Demonstration below for comment.

Two inputs:

- `[9 0 0 0 0]` (isotropic, large);
- `[1 -0.5913 0.3126 -0.127 0.0337]` (just an exemplar single-subject WM response, small).

![1](https://user-images.githubusercontent.com/5637955/52095466-1500fb80-2617-11e9-93ee-da2816264da4.png)

![2](https://user-images.githubusercontent.com/5637955/52095470-19c5af80-2617-11e9-90ae-c836437a68bf.png)

`responsemean tmp1.txt tmp2.txt average_response.txt -legacy` (identical to `average_response`): `[5.00000 -0.29565 0.15630 -0.06350 0.01685]`

![average_response](https://user-images.githubusercontent.com/5637955/52095472-1cc0a000-2617-11e9-80d1-9cf152f4a315.png)

`responsemean tmp1.txt tmp2.txt responsemean.txt`: [1.80000 -0.53217 0.28134 -0.11430 0.03033]`

![responsemean](https://user-images.githubusercontent.com/5637955/52095474-1f22fa00-2617-11e9-9595-21e620555e4c.png)

-----

First result is the average amplitude in all orientations; second result is the average shape, with the average size.

**Comment by thijsdhollander** [comment]
As mentioned somewhere in the pull request: all fine by me for now :+1: .  It's in line with ideas I've developed for `mtnormalise` when that was introduced, so can't complain too much about those basic principles for sure. :wink:

In practice, this has little impact on the resulting shape for most studies, which I think is in fact a good thing.  Also now with `dwibiascorrect` doing some basic "normalisation" (not really normalisation, but at least it makes sure things don't get wildly out of control any more in terms of amplitude), the risk of impact on the shape is reduced even further.
