### ISSUE TITLE
fixelcfestats produces warnings about invalid header when reading fixel based format

### ISSUE THREAD

**Issue by bjeurissen** [MRtrix3/mrtrix3#1102]
fixelcfestats produces a warning about invalid header information when loading the fixels. Is this a known/harmless issue? Or is this an indication that something went wrong? At first sight, it appears as if some checks are being carried out that were designed for normal images and that act funny on the sparse fixel format. If I load the fixels with mrview, everything looks normal.

Input: 
```fixelcfestats -debug template/fd files.txt design.txt contrast.txt tracks.tck stats_fd -neg```

Output:
```fixelcfestats: [DEBUG] No config file found at "/etc/mrtrix.conf"
fixelcfestats: [INFO] reading config file "/home/ben/.mrtrix.conf"...
fixelcfestats: [DEBUG] reading key/value file "/home/ben/.mrtrix.conf"...
fixelcfestats: [INFO] opening image "template/fd/index.mif"...
fixelcfestats: [DEBUG] reading key/value file "template/fd/index.mif"...
fixelcfestats: [DEBUG] sanitising image information...
fixelcfestats: [INFO] image "template/fd/index.mif" opened with dimensions 142x177x137x2, voxel spacing 1.25x1.25x1.25x1, datatype UInt32LE
fixelcfestats: [DEBUG] memory-mapping file "template/fd/index.mif"...
fixelcfestats: [DEBUG] file "template/fd/index.mif" mapped at 0x7f323e841000, size 27546864 (read-only)
fixelcfestats: [DEBUG] image "template/fd/index.mif" loaded
fixelcfestats: [DEBUG] image "template/fd/index.mif" initialised with strides = [ 2 284 50268 1 ], start = 0, using direct IO
fixelcfestats: number of fixels: 459193
fixelcfestats: [DEBUG] sanitising image information...
fixelcfestats: [WARNING] invalid voxel sizes - resetting to sane defaults
fixelcfestats: [WARNING] transform matrix contains invalid entries - resetting to sane defaults
fixelcfestats: [DEBUG] allocating scratch buffer for image "scratch fixel mask"...
fixelcfestats: [DEBUG] image "scratch fixel mask" loaded
fixelcfestats: [DEBUG] image "scratch fixel mask" initialised with strides = [ 1 459193 459193 ], start = 0, using direct IO
fixelcfestats: [INFO] opening image "template/fd/index.mif"...
fixelcfestats: [DEBUG] reading key/value file "template/fd/index.mif"...
fixelcfestats: [DEBUG] sanitising image information...
fixelcfestats: [INFO] image "template/fd/index.mif" opened with dimensions 142x177x137x2, voxel spacing 1.25x1.25x1.25x1, datatype UInt32LE```

**Comment by jdtournier** [comment]
Yes, that comes from the `Header:: open()` call, particularly the `sanitise()` bits. I guess we need to find a way to silence those when they're not deemed relevant, a bit like the [LogLevelLatch](https://github.com/MRtrix3/mrtrix3/blob/master/core/exception.h#L120) - although it would probably be better as an additional, optional argument to the `Header::open()` call, just to make sure we don't silence other unrelated warnings in the process...

**Comment by Lestropie** [comment]
I'd expected those particular errors to come from loading a fixel *data* file, not an *index* file? If it were the former, I have a few ideas about changes to the fixel format for solving such things; but the latter *needs* to have valid voxel sizes & transform. So maybe check `mrinfo` on that image, and backtrace the issue through your processing chain to see where it originates?
