### ISSUE TITLE
amp2response used as single threaded

### ISSUE THREAD

**Issue by portokalh** [MRtrix3/mrtrix3#1110]
I am new to mrtrix and try to use dwi2response (algorith fa) with multiple threads. I assume that the -nthreads parameter should be passed to amp2response, but i see that it runs single threaded. Is there hope that amp2response will run as multithreaded? thank you very much! Alexandra

**Comment by Lestropie** [comment]
Hi Alexandra,

I don't think it would be worth the development effort in trying to multi-thread this particular command. The primary computation time goes to solving a single large constrained least squares matrix problem (details [here](https://www.researchgate.net/publication/307862932_Constrained_linear_least_squares_estimation_of_anisotropic_response_function_for_spherical_deconvolution); hence multi-threading the command would require multi-threading the inner workings of this matrix solver, which would be non-trivial. In the other circumstance where that particular matrix problem solver is used in the software (multi-shell multi-tissue CSD), multi-threading is achieved by processing each *voxel* separately, which is far easier in terms of implementation but doesn't apply in the case of `amp2response`. It's also a fairly small amount of processing time spent on this command compared to many other aspects of DWI processing. So the potential benefit is probably not worth the considerable cost, relative to developing other / novel aspects of the software.

Cheers
Rob
