### ISSUE TITLE
mrdegibbs missing from macOS install

### ISSUE THREAD

**Issue by neurolabusc** [MRtrix3/mrtrix3#1137]
I used [homebrew](http://mrtrix.readthedocs.io/en/latest/installation/mac_install.html) to install mrtrix3 3.0_RC1-176-g73e60f22 on my MacOS computer. I also installed mrtrix3 on my Ubuntu (Debian-based) computer. Most of the tools are fine for both installs, but mrdegibbs is missing from the macOS install. Did I do something wrong?

**Comment by jdtournier** [comment]
Nope, the only issue is that `mrdegibbs` was only [released recently as part of release candidate 2](http://www.mrtrix.org/2017/07/31/mrtrix-3-0-release-candidate-2/) (`3.0_RC2`). It's simply a matter of updating to the latest version. Not sure whether the homebrew recipe had been updated, but no doubt @maxpietsch will confirm one way or the other (I'm not so familiar with the macOS side of things myself).

**Comment by maxpietsch** [comment]
The [formula](https://github.com/MRtrix3/homebrew-mrtrix3/blob/master/mrtrix3.rb#L39) is up tp date. `brew update mrtrix3` should get you RC2.

**Comment by neurolabusc** [comment]
Thanks for the quick response. For those unfamiliar with homebrew, it might be nice to add instructions for how to update tools. I had tried, but was told that RC1 was the latest since I had not refreshed brew - whereas I expected it would look online to see if I had the latest version. So you need to `brew update` before `brew upgrade mrtrix3`:

```
$ brew update mrtrix3
This command updates brew itself, and does not take formula names.
Use `brew upgrade <formula>`.
$ brew upgrade mrtrix3
Error: mrtrix3/mrtrix3/mrtrix3 3.0_RC1-176-g73e60f22 already installed
$ brew update
...
$ brew upgrade mrtrix3
...

```

**Comment by maxpietsch** [comment]
By default, homebrew updates the formula information (since [Aug 2016](https://github.com/Homebrew/brew/pull/679)) before it upgrades the package unless you set the environment variable `HOMEBREW_NO_AUTO_UPDATE` to 1 or `HOMEBREW_AUTO_UPDATE_SECS` to something very high.

```
man brew 
...
HOMEBREW_NO_AUTO_UPDATE
              If set, Homebrew will not auto-update before running brew install, brew upgrade or brew tap.
...
```


```
brew upgrade mrtrix3
Updating Homebrew...
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
==> Auto-updated Homebrew!
Updated Homebrew from a5b37e3b4 to cd1cb7080.
Updated 2 taps (caskroom/cask, homebrew/core).
==> New Formulae
fn                                                                                                   zim
==> Updated Formulae
cimg                  eye-d3                freetds               imagemagick ✔         imagemagick@6         libbitcoin            libbitcoin-explorer   mutt                  xa

==> Upgrading 1 outdated package, with result:
mrtrix3/mrtrix3/mrtrix3 3.0_RC2-48-gfe5084db
==> Upgrading mrtrix3/mrtrix3/mrtrix3
==> Cloning https://github.com/MRtrix3/mrtrix3.git
Updating /Users/mp/Library/Caches/Homebrew/mrtrix3--git
==> Checking out branch master
...
```
