### ISSUE TITLE
Allow manual overriding of dwibiascorrect parameters

### ISSUE THREAD

**Issue by thijsdhollander** [MRtrix3/mrtrix3#1165]
Came up during discussions in #944 and #1148.  We could even consider just making this script an interface to ANTS' N4, because who still uses the FSL approach here?  Ask anyone about the state of the art in general MR bias field correction, and they'll come up with N4.  But I'm not against keeping different approaches in the script as well... certainly ok with that.

**Comment by Lestropie** [comment]
Closed by #1328.
