### ISSUE TITLE
Feature request: add "-datatype" option for dwidenoise 

### ISSUE THREAD

**Issue by neurolabusc** [MRtrix3/mrtrix3#1174]
Would it be possible for dwidenoise to support the "-datatype" option found with mrdegibbs. At the moment, the output of dwidenoise is 32-bit float regardless of input data precision. For 16-bit input, it would be nice to have the option to support 16-bit output. In theory, this could be rescaled, so input that from a 12-bit ADC (with values 0..4096) could be saved to the range 0..65535 it the user specifies "-datatype uint16" (with the appropriate scale factor in the header).

**Comment by dchristiaens** [comment]
We've had a `-datatype` option in `dwidenoise` for a while now, which allows to select single or double precision for the eigenvalue decomposition and denoising. This is not quite what you're suggesting of course, but I'm personally not convinced that it's useful to support integer output when all calculations are done floating point precision. If you really want to, you can always round the output to the nearest integer with `mrconvert`.

Closing this one off if there are no objections.
