### ISSUE TITLE
Delimiter in matrix save

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#1184]
Partly inspired by [this post](http://community.mrtrix.org/t/the-output-of-tck2connectome/345/16).

Functions `save_matrix()` and `save_vector()` could select the column delimiter based on the file extension of the output path. So for instance, if the output path is a `.csv`, use a comma rather than a space. Similar for `.tsv`. Thoughts?

**Comment by maxpietsch** [comment]
The only problem I can see is that users might not expect the separator format to change if they forget to add the file extension. Also, probably due to the silly use of comma as decimal separator, the German version of Excel uses semicolons as delimiters for `.csv` files if I am not mistaken. So again, there might be a mismatch of expected separators.

**Comment by Lestropie** [comment]
Part of the problem is that programs like Excel / Matlab set their expected delimiters for file import based on the file extension; so it wouldn't surprise me if space-separated text files and comma-separated .csv files import exactly as expected, whereas other combinations end up with import results like that shown in the forum post. So was hoping to address that, at least for most common use cases.

But I failed to think of localisation at the time; that's likely the bigger problem. Some recommend encasing all values within double-quotes, but it's kind of ugly. It's possible to query the [decimal point separator](http://www.cplusplus.com/reference/locale/numpunct/decimal_point/), but the locale-specific list separator doesn't appear to be defined anywhere. Could infer "," if "." is used for decimals, and ";" if "," is used for decimals; but it might be too much hidden magic dust...

**Comment by Lestropie** [comment]
Closed by #1549.
