### ISSUE TITLE
mrcalc issues warning "header transformations of input images do not match" when the input images (albeit identical) are not in the same file format

### ISSUE THREAD

**Issue by ansk** [MRtrix3/mrtrix3#1198]
Example:
```
mrconvert test.mif test.nii.gz
mrconvert: [100%] copying from "test.mif" to "test.nii.gz"
mrconvert: [100%] compressing image "test.nii.gz"
mrcalc test.mif test.nii.gz -add test3.mif
mrcalc: [100%] uncompressing image "test.nii.gz"
mrcalc: [WARNING] header transformations of input images do not match
mrcalc: [100%] computing: (test.mif + test.nii.gz)
```

**Comment by jdtournier** [comment]
OK, that's unexpected... 
What does this report:
```
mrinfo test.mif test.nii.gz
```
?

**Comment by jdtournier** [comment]
OK, never mind, it's most likely a rounding / tolerance issue. I hadn't realised that the [test for whether the transforms match](https://github.com/MRtrix3/mrtrix3/blob/master/cmd/mrcalc.cpp#L587) uses the [default tolerance of zero](https://github.com/MRtrix3/mrtrix3/blob/master/core/image_helpers.h#L420)... I'll amend and put in a more sensible value like 1e-4.

**Comment by jdtournier** [comment]
PR in #1199 - I'll close this for now. 

Please do checkout the `mrcalc_transform_match_tolerance` branch and see whether that fixes the issue. Note that it'll be based off the `dev` branch, not `master`, so that may introduce other differences as well...
