### ISSUE TITLE
mrview roi colour often black and button hard to find (Windows)

### ISSUE THREAD

**Issue by LeeReid1** [MRtrix3/mrtrix3#1202]
Hi guys,

Two related non-critical, but frequently annoying, issues for mrview in Windows.
1) When opening ROIs, the colour seems to be chosen at random (?), and quite frequently the colour chosen is black. This can cause a lot of confusion, especially when trying to find a small ROI that may or may not have be generated correctly. 
2) The button indicating the colour of the selected ROI is entirely grey, save for a single pixel of colour right in the centre. Took quite a while to find out that it even was a button, or was anything to do with the colour of the ROI. My understanding is that this is not the case in linux.

![image](https://user-images.githubusercontent.com/26998292/33403825-96f275f8-d5ad-11e7-8a1b-70be0c049a34.png)

(Installed msys2 and pulled/built mrtrix about two weeks back)

**Comment by jdtournier** [comment]
I've also noticed some weird issues on my Windows laptop recently - but much worse than that... I can't figure out what the problem is exactly, but there's a chance it'll be related to the version of Qt installed. Have you tried updating your MSYS2 installation using `pacman -Syu`, to see whether that helps...? As you say, it works fine on other platforms, so I struggle to see where the problem might be...

**Comment by LeeReidCSIRO** [comment]
I’ve just updated but the problem with the button persists.
However, regarding the black:
The colours seem to be randomly chosen from the same colour palette. On closer inspection the ‘black’ is not black so much as (0,0,25). Is this a typo in the code that should read (0,0,255)??

**Comment by LeeReidCSIRO** [comment]
Just following up on this before running of for xmas break:
I can't help with the button any more, but the colour being black is a typo in 
/src/gui/mrview/tool/roi_editor/item.h

namespace {
         constexpr std::array<std::array<GLubyte,3>,6> preset_colours = { {
           { { 255, 255, 0 } },
           { { 255, 0, 255 } },
           { { 0, 255, 255 } },
           { { 255, 0, 0 } },
           { { 0, 255, 255 } },
           { { 0, 0, 25 } }
         } };
}


the last line with numbers should read 0, 0, 255

Massively overkill for me to clone/pull for the sake of adding in one character - I'll leave this to you guys to do at your own convenience. Have a good xmas :)
