### ISSUE TITLE
Debug flag issue

### ISSUE THREAD

**Issue by nikitas-k** [MRtrix3/mrtrix3#1215]
I'm trying to run dwipreproc on a single phase encoding DWI image (pe_dir = AP) on a HPC cluster. I was using the -debug flag to get a more detailed view of the process and handle any issues where they might pop up, and I get this error:

Traceback (most recent call last):
  File "/software/mrtrix3/mrtrix3-AP/bin/dwipreproc", line 858, in <module>
    app.debug('Commencing gradient direction matching; ' + str(dwi_num_volumes) + ' volumes')
  File "/software/mrtrix3/mrtrix3-AP/lib/mrtrix3/app.py", line 294, in debug
    origin = '(' + os.path.basename(nearest.filename) + ':' + str(nearest.lineno) + ')'
AttributeError: 'tuple' object has no attribute 'filename'

dwipreproc is being called via:

dwipreproc -rpe_none -pe_dir AP -export_grad_mrtrix adjencoding.b rawdata-dn.mif eddycorr.mif -eddy_options " --repol " -nthreads $ncpus -debug -tempdir . -nocleanup -force

I am running my program without the -debug flag now so I'll post the results when that's finished (either terminated or successful).

**Comment by Lestropie** [comment]
Ah yes, I can see the issue straight away. The script should work if you either:

- Don't use the `-debug` flag.

- Use Python >= 3.5.

- Wait for #1217 to be merged.

**Comment by nikitas-k** [comment]
All programs succeeded (I ran 25 parallel programs) after removing the -debug flag. Thanks @Lestropie

**Comment by Lestropie** [comment]
Closed by #1217.
