### ISSUE TITLE
identical row entries with average_response function

### ISSUE THREAD

**Issue by AlistairPerry** [MRtrix3/mrtrix3#1216]
Hello,

I'm constructing an `average response` function from `dhollander` performed on 30+ subjects.

Again, I'm on the `dev` branch - quick check of version says  `== mrinfo 3.0_RC2-335-g14dd1ca1 ==`

However, I'm noticing that after the averaging, the response function row entries for the _b0_ and diffusion-weighted shell (in this case _b3000_) are now completely identical:

> average_response *wm.txt avg_wm_resp.txt 
> more avg_wm_resp.txt
> 4449.61721 -588.75356 315.15280 -124.92589 35.45978 -7.32274 
> 4449.61721 -588.75356 315.15280 -124.92589 35.45978 -7.32274

This is also the case for the average across two subjects:
> average_response Patient_029_wm.txt Patient_030_wm.txt avg_wm_resp_2subjs.txt
> more avg_wm_resp_2subjs.txt
> 4321.62717 -585.52493 313.94894 -124.07190 34.73019 -6.26381 
> 4321.62717 -585.52493 313.94894 -124.07190 34.73019 -6.26381

And to check that the intensity-normalized individual responses functions are ok:

> more Patient_029_wm.txt 
> 3128.3105826144 0 0 0 0 0
> 895.7039791266319 -560.0014115827539 306.6889649537684 -125.1286901946021 34.98047499026599 -7.179144813659091

> more Patient_030_wm.txt 
> 3595.235595126074 0 0 0 0 0
> 1024.004181919725 -611.0484521886748 321.2089180114817 -123.0151077975939 34.47990237719558 -5.348484595086862

So it appears that `average_response` is taking the summed values across the two row entries, before averaging them.

**Comment by thijsdhollander** [comment]
Hmm, yes, that certainly shouldn't happen.  Do you encounter this as well on the `master` branch?  If not (and is hence specific to `dev`), I reckon the bug may have been introduced in this specific commit, at this line potentially: https://github.com/MRtrix3/mrtrix3/commit/07882b6f8c0f2613d2c70f8f498dddb557954cc6#diff-bc8ac539f73b5f293c7f850ba3823148R35

@Lestropie : I suppose you're more aware about the intention behind that change?

@AlistairPerry , thanks a lot for reporting!  We may be thinking of releasing `dev` onto `master` soon again, so in that case, your bug report is definitely timely!

**Comment by Lestropie** [comment]
:man_facepalming: Tested the output of the null-filling rather than the script...

**Comment by Lestropie** [comment]
Closed by #1218.

**Comment by AlistairPerry** [comment]
All fixed now thanks

mrinfo -version  `== mrinfo 3.0_RC2-357-g1d504442 ==`

Test of code:

> average_response Patient_029_wm.txt Patient_030_wm.txt test.txt
> more test.txt 
> 3361.77309 0.00000 0.00000 0.00000 0.00000 0.00000 
> 959.85408 -585.52493 313.94894 -124.07190 34.73019 -6.26381
