### ISSUE TITLE
amp2response performance

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#1231]
As raised [here](http://community.mrtrix.org/t/problem-with-dwi2response-msmt-5tt-amp2response-command-for-ex-vivo-monkey-data/1402) (even though there's an upstream problem in that particular case). 

- Don't bother constructing transformation matrices when using the `-isotropic` option.

- Pre-determine the number of voxels in the mask, and pre-allocate `cat_transforms` and `cat_data` rather than using `conservativeResize()`.

**Comment by thijsdhollander** [comment]
While this sits here, just adding something I forgot to create an issue for, but stumbled upon at some point: *if I remember well*, `amp2response` crashes (segfault) when the provided mask (i.e. second argument) is 4-dimensional, even with the size of the 4th dimension being "1" (so the mask essentially being 3D).
