### ISSUE TITLE
provide atomic read/write functions to BufferScratch

### ISSUE THREAD

**Issue by jdtournier** [MRtrix3/mrtrix3#126]
This should allow quite a bit of acceleration for applications involving track mapping (TDI, TWI, SIFT, AFD), since there would be no need to single-thread the output buffer updates.

**Comment by Lestropie** [comment]
This was never applied, and was designed around the old syntax. Revisiting this would require both a valid application and a redesign based on the image syntax overhaul. So closing this off and deleting the relevant branch.
