### ISSUE TITLE
Error with color lookuptable running labelconvert

### ISSUE THREAD

**Issue by martahedl** [MRtrix3/mrtrix3#1279]
Hi,
I tried to run labelconvert for the HCPMMP1 atlas. For that, I created both original and an ordered versions of the lookup table, as requested by labelconvert. However, I always get an error (e.g. "Odd number of quotation marks" or "Inconsistent number of columns"). I tried to save the LUT in different formats (.csv/.txt/.xlsx), without success. Moreover, I tried to use labelconvert with the AAL atlas, using LUTs which I created just as the HCPMMP1 tables, and for that atlas it worked. I must have missed something in the HCPMMP1 tables but I really don't find it - can somebody help me out?
I'd really appreciate it, and thanks in advance :) 

[HCPMMP1_LUT_ordered.xlsx](https://github.com/MRtrix3/mrtrix3/files/1860625/HCPMMP1_LUT_ordered.xlsx)
[HCPMMP1_LUT_original.xlsx](https://github.com/MRtrix3/mrtrix3/files/1860626/HCPMMP1_LUT_original.xlsx)

**Comment by martahedl** [comment]
# Lookup table for extracting the relevant grey matter parcellations from the Glasser atlas (needs verification!), as after running mri_aparc2aseg --old-ribbon --annotation glasser --s hmsc001-01 --o glasser.mgz. NEEDS VERIFICATION! FOR THE ORDERED VERSION  REQUIRED FOR MRTIRX' LABELCONVERT  ALSO CHECK glasserLUT_ordered.txt
1000 UNKNOWN 0 0 0 0
1001 L_V1 63 5 26 255
1002 L_MST 54 103 129 255
1003 L_V6 62 78 178 255
1004 L_V2 23 50 233 255
1005 L_V3 15 40 226 255
1006 L_V4 14 28 214 255
1007 L_V8 26 47 201 255
1008 L_4 33 178 20 255
1009 L_3b 35 205 21 255
1010 L_FEF 134 143 137 255
1011 L_PEF 141 166 152 255
1012 L_55b 62 88 47 255
1013 L_V3A 7 57 246 255
1014 L_RSC 153 64 133 255
1015 L_POS2 186 86 188 255
1016 L_V7 18 70 195 255
1017 L_IPS1 57 114 160 255
1018 L_FFC 57 89 117 255
1019 L_V3B 25 47 206 255
1020 L_LO1 0 49 184 255
1021 L_LO2 18 33 181 255
1022 L_PIT 34 43 171 255
1023 L_MT 31 86 104 255
1024 L_A1 235 19 47 255
1025 L_PSL 122 79 56 255
1026 L_SFL 31 49 22 255
1027 L_PCV 138 128 153 255
1028 L_STV 142 87 76 255
1029 L_7Pm 149 181 188 255
1030 L_7m 42 31 44 255
1031 L_POS1 81 54 98 255
1032 L_23d 127 56 91 255
1033 L_v23ab 29 0 14 255
1034 L_d23ab 63 17 47 255
1035 L_31pv 54 11 42 255
1036 L_5m 48 163 48 255
1037 L_5mv 153 172 136 255
1038 L_23c 205 190 194 255
1039 L_5L 64 154 64 255
1040 L_24dd 69 161 44 255
1041 L_24dv 119 159 66 255
1042 L_7AL 115 194 134 255
1043 L_SCEF 110 146 86 255
1044 L_6ma 144 179 135 255
1045 L_7Am 184 243 224 255
1046 L_7PL 169 246 237 255
1047 L_7PC 68 177 108 255
1048 L_LIPv 63 113 158 255
1049 L_VIP 50 129 137 255
1050 L_MIP 136 206 204 255
1051 L_1 20 191 38 255
1052 L_2 48 176 62 255
1053 L_3a 47 216 22 255
1054 L_6d 26 158 32 255
1055 L_6mp 64 159 38 255
1056 L_6v 71 168 50 255
1057 L_p24pr 146 136 107 255
1058 L_33pr 129 106 103 255
1059 L_a24pr 176 133 130 255
1060 L_p32pr 163 142 121 255
1061 L_a24 67 12 25 255
1062 L_d32 90 41 50 255
1063 L_8BM 105 83 81 255
1064 L_p32 95 32 52 255
1065 L_10r 25 12 1 255
1066 L_47m 96 75 66 255
1067 L_8Av 53 54 43 255
1068 L_8Ad 63 67 48 255
1069 L_9m 43 35 18 255
1070 L_8BL 34 39 20 255
1071 L_9p 38 43 28 255
1072 L_10d 38 35 24 255
1073 L_8C 101 85 84 255
1074 L_44 88 88 62 255
1075 L_45 60 63 42 255
1076 L_47l 51 49 31 255
1077 L_a47r 77 76 66 255
1078 L_6r 178 214 151 255
1079 L_IFJa 126 119 95 255
1080 L_IFJp 137 160 132 255
1081 L_IFSp 97 98 87 255
1082 L_IFSa 188 201 178 255
1083 L_p9-46v 138 149 134 255
1084 L_46 207 217 200 255
1085 L_a9-46v 145 112 128 255
1086 L_9-46d 140 117 131 255
1087 L_9a 55 52 45 255
1088 L_10v 14 35 14 255
1089 L_a10p 98 75 89 255
1090 L_10pp 55 62 58 255
1091 L_11l 129 106 118 255
1092 L_13l 82 60 69 255
1093 L_OFC 40 35 31 255
1094 L_47s 66 35 33 255
1095 L_LIPd 155 180 202 255
1096 L_6a 121 192 136 255
1097 L_i6-8 90 98 83 255
1098 L_s6-8 88 92 73 255
1099 L_43 145 138 64 255
1100 L_OP4 114 157 49 255
1101 L_OP1 99 158 35 255
1102 L_OP2-3 145 127 52 255
1103 L_52 208 72 66 255
1104 L_RI 178 61 23 255
1105 L_PFcm 190 144 89 255
1106 L_PoI2 131 124 83 255
1107 L_TA2 130 42 27 255
1108 L_FOP4 182 148 129 255
1109 L_MI 157 116 106 255
1110 L_Pir 90 66 65 255
1111 L_AVI 141 72 83 255
1112 L_AAIC 85 35 44 255
1113 L_FOP1 160 153 88 255
1114 L_FOP3 175 137 99 255
1115 L_FOP2 99 156 51 255
1116 L_PFt 129 222 134 255
1117 L_AIP 136 220 166 255
1118 L_EC 49 48 35 255
1119 L_PreS 86 57 83 255
1120 L_H 60 57 40 255
1121 L_ProS 87 59 176 255
1122 L_PeEc 61 62 51 255
1123 L_STGa 58 42 26 255
1124 L_PBelt 195 30 5 255
1125 L_A5 99 39 6 255
1126 L_PHA1 69 50 75 255
1127 L_PHA3 96 102 113 255
1128 L_STSda 77 51 34 255
1129 L_STSdp 73 57 39 255
1130 L_STSvp 71 59 57 255
1131 L_TGd 35 34 23 255
1132 L_TE1a 11 14 0 255
1133 L_TE1p 96 102 94 255
1134 L_TE2a 67 64 58 255
1135 L_TF 64 72 56 255
1136 L_TE2p 105 128 117 255
1137 L_PHT 217 252 223 255
1138 L_PH 88 131 163 255
1139 L_TPOJ1 125 90 64 255
1140 L_TPOJ2 156 162 138 255
1141 L_TPOJ3 121 148 145 255
1142 L_DVT 120 112 190 255
1143 L_PGp 155 190 228 255
1144 L_IP2 176 166 174 255
1145 L_IP1 118 121 128 255
1146 L_IP0 112 160 207 255
1147 L_PFop 187 205 145 255
1148 L_PF 26 26 226 255
1149 L_PFm 133 105 114 255
1150 L_PGi 53 62 46 255
1151 L_PGs 62 67 57 255
1152 L_V6A 41 89 166 255
1153 L_VMV1 62 61 155 255
1154 L_VMV3 49 53 159 255
1155 L_PHA2 88 90 89 255
1156 L_V4t 14 79 128 255
1157 L_FST 92 157 153 255
1158 L_V3CD 15 46 182 255
1159 L_LO3 54 94 160 255
1160 L_VMV2 67 62 161 255
1161 L_31pd 56 22 45 255
1162 L_31a 143 105 133 255
1163 L_VVC 53 61 124 255
1164 L_25 36 24 14 255
1165 L_s32 46 35 21 255
1166 L_pOFC 76 48 53 255
1167 L_PoI1 164 104 97 255
1168 L_Ig 110 123 36 255
1169 L_FOP5 163 102 105 255
1170 L_p10p 89 64 76 255
1171 L_p47r 126 123 112 255
1172 L_TGv 46 51 42 255
1173 L_MBelt 187 30 24 255
1174 L_LBelt 233 18 27 255
1175 L_A4 152 39 4 255
1176 L_STSva 40 33 22 255
1177 L_TE1m 59 45 43 255
1178 L_PI 122 50 50 255
1179 L_a32pr 130 63 87 255
1180 L_p24 123 35 74 255
2001 R_V1 63 5 26 255
2002 R_MST 54 103 129 255
2003 R_V6 62 78 178 255
2004 R_V2 23 50 233 255
2005 R_V3 15 40 226 255
2006 R_V4 14 28 214 255
2007 R_V8 26 47 201 255
2008 R_4 33 178 20 255
2009 R_3b 35 205 21 255
2010 R_FEF 134 143 137 255
2011 R_PEF 141 166 152 255
2012 R_55b 62 88 47 255
2013 R_V3A 7 57 246 255
2014 R_RSC 153 64 133 255
2015 R_POS2 186 86 188 255
2016 R_V7 18 70 195 255
2017 R_IPS1 57 114 160 255
2018 R_FFC 57 89 117 255
2019 R_V3B 25 47 206 255
2020 R_RO1 0 49 184 255
2021 R_RO2 18 33 181 255
2022 R_PIT 34 43 171 255
2023 R_MT 31 86 104 255
2024 R_A1 235 19 47 255
2025 R_PSR 122 79 56 255
2026 R_SFR 31 49 22 255
2027 R_PCV 138 128 153 255
2028 R_STV 142 87 76 255
2029 R_7Pm 149 181 188 255
2030 R_7m 42 31 44 255
2031 R_POS1 81 54 98 255
2032 R_23d 127 56 91 255
2033 R_v23ab 29 0 14 255
2034 R_d23ab 63 17 47 255
2035 R_31pv 54 11 42 255
2036 R_5m 48 163 48 255
2037 R_5mv 153 172 136 255
2038 R_23c 205 190 194 255
2039 R_5R 64 154 64 255
2040 R_24dd 69 161 44 255
2041 R_24dv 119 159 66 255
2042 R_7AR 115 194 134 255
2043 R_SCEF 110 146 86 255
2044 R_6ma 144 179 135 255
2045 R_7Am 184 243 224 255
2046 R_7PR 169 246 237 255
2047 R_7PC 68 177 108 255
2048 R_RIPv 63 113 158 255
2049 R_VIP 50 129 137 255
2050 R_MIP 136 206 204 255
2051 R_1 20 191 38 255
2052 R_2 48 176 62 255
2053 R_3a 47 216 22 255
2054 R_6d 26 158 32 255
2055 R_6mp 64 159 38 255
2056 R_6v 71 168 50 255
2057 R_p24pr 146 136 107 255
2058 R_33pr 129 106 103 255
2059 R_a24pr 176 133 130 255
2060 R_p32pr 163 142 121 255
2061 R_a24 67 12 25 255
2062 R_d32 90 41 50 255
2063 R_8BM 105 83 81 255
2064 R_p32 95 32 52 255
2065 R_10r 25 12 1 255
2066 R_47m 96 75 66 255
2067 R_8Av 53 54 43 255
2068 R_8Ad 63 67 48 255
2069 R_9m 43 35 18 255
2070 R_8BR 34 39 20 255
2071 R_9p 38 43 28 255
2072 R_10d 38 35 24 255
2073 R_8C 101 85 84 255
2074 R_44 88 88 62 255
2075 R_45 60 63 42 255
2076 R_47R 51 49 31 255
2077 R_a47r 77 76 66 255
2078 R_6r 178 214 151 255
2079 R_IFJa 126 119 95 255
2080 R_IFJp 137 160 132 255
2081 R_IFSp 97 98 87 255
2082 R_IFSa 188 201 178 255
2083 R_p9-46v 138 149 134 255
2084 R_46 207 217 200 255
2085 R_a9-46v 145 112 128 255
2086 R_9-46d 140 117 131 255
2087 R_9a 55 52 45 255
2088 R_10v 14 35 14 255
2089 R_a10p 98 75 89 255
2090 R_10pp 55 62 58 255
2091 R_11R 129 106 118 255
2092 R_13R 82 60 69 255
2093 R_OFC 40 35 31 255
2094 R_47s 66 35 33 255
2095 R_RIPd 155 180 202 255
2096 R_6a 121 192 136 255
2097 R_i6-8 90 98 83 255
2098 R_s6-8 88 92 73 255
2099 R_43 145 138 64 255
2100 R_OP4 114 157 49 255
2101 R_OP1 99 158 35 255
2102 R_OP2-3 145 127 52 255
2103 R_52 208 72 66 255
2104 R_RI 178 61 23 255
2105 R_PFcm 190 144 89 255
2106 R_PoI2 131 124 83 255
2107 R_TA2 130 42 27 255
2108 R_FOP4 182 148 129 255
2109 R_MI 157 116 106 255
2110 R_Pir 90 66 65 255
2111 R_AVI 141 72 83 255
2112 R_AAIC 85 35 44 255
2113 R_FOP1 160 153 88 255
2114 R_FOP3 175 137 99 255
2115 R_FOP2 99 156 51 255
2116 R_PFt 129 222 134 255
2117 R_AIP 136 220 166 255
2118 R_EC 49 48 35 255
2119 R_PreS 86 57 83 255
2120 R_H 60 57 40 255
2121 R_ProS 87 59 176 255
2122 R_PeEc 61 62 51 255
2123 R_STGa 58 42 26 255
2124 R_PBeRt 195 30 5 255
2125 R_A5 99 39 6 255
2126 R_PHA1 69 50 75 255
2127 R_PHA3 96 102 113 255
2128 R_STSda 77 51 34 255
2129 R_STSdp 73 57 39 255
2130 R_STSvp 71 59 57 255
2131 R_TGd 35 34 23 255
2132 R_TE1a 11 14 0 255
2133 R_TE1p 96 102 94 255
2134 R_TE2a 67 64 58 255
2135 R_TF 64 72 56 255
2136 R_TE2p 105 128 117 255
2137 R_PHT 217 252 223 255
2138 R_PH 88 131 163 255
2139 R_TPOJ1 125 90 64 255
2140 R_TPOJ2 156 162 138 255
2141 R_TPOJ3 121 148 145 255
2142 R_DVT 120 112 190 255
2143 R_PGp 155 190 228 255
2144 R_IP2 176 166 174 255
2145 R_IP1 118 121 128 255
2146 R_IP0 112 160 207 255
2147 R_PFop 187 205 145 255
2148 R_PF 26 26 226 255
2149 R_PFm 133 105 114 255
2150 R_PGi 53 62 46 255
2151 R_PGs 62 67 57 255
2152 R_V6A 41 89 166 255
2153 R_VMV1 62 61 155 255
2154 R_VMV3 49 53 159 255
2155 R_PHA2 88 90 89 255
2156 R_V4t 14 79 128 255
2157 R_FST 92 157 153 255
2158 R_V3CD 15 46 182 255
2159 R_RO3 54 94 160 255
2160 R_VMV2 67 62 161 255
2161 R_31pd 56 22 45 255
2162 R_31a 143 105 133 255
2163 R_VVC 53 61 124 255
2164 R_25 36 24 14 255
2165 R_s32 46 35 21 255
2166 R_pOFC 76 48 53 255
2167 R_PoI1 164 104 97 255
2168 R_Ig 110 123 36 255
2169 R_FOP5 163 102 105 255
2170 R_p10p 89 64 76 255
2171 R_p47r 126 123 112 255
2172 R_TGv 46 51 42 255
2173 R_MBeRt 187 30 24 255
2174 R_RBeRt 233 18 27 255
2175 R_A4 152 39 4 255
2176 R_STSva 40 33 22 255
2177 R_TE1m 59 45 43 255
2178 R_PI 122 50 50 255
2179 R_a32pr 130 63 87 255
2180 R_p24 123 35 74 255
# Subcortical parcellation  according to the original FreeSurferColorLUT.txt
8 L_Cerebellum 230 148 34 255
10 L_Thalamus 0 118 14 255
11 L_Caudate 122 186 220 255
12 L_Putamen 236 13 176 255
13 L_Pallidum 12 48 255 255
16 Brain-Stem 119 159 176 255
17 L_Hippocampus 220 216 20 255
18 L_Amygdala 103 255 255 255
26 L_Accumbens 255 165 0 255
28 L_VentralDC 165 42 42 255
47 R_Cerebellum 230 148 34 255
49 R_Thalamus 0 118 14 255
50 R_Caudate 122 186 220 255
51 R_Putamen 236 13 176 255
52 R_Pallidum 13 48 255 255
53 R_Hippocampus 220 216 20 255
54 R_Amygdala 103 255 255 255
58 R_Accumbens 255 165 0 255
60 R_VentralDC 165 42 42 255

**Comment by Lestropie** [comment]
@martahedl: OK, I see where the issue was. Here's a file with the fix, since it will be easier to one-click download for anyone interested:

[HCPMMP1_LUT_original_RS_fix.txt](https://github.com/MRtrix3/mrtrix3/files/1882604/HCPMMP1_LUT_original_RS_fix.txt)

From where did you obtain the "original" node indices / names / colours? I need to make sure that I'm not hosting anybody else's work available in an unfair manner; especially if these data were to be provided with *MRtrix3* itself, which I think would make a number of users very happy. Also, do you have a link where users can obtain the Glasser annotation files, or are they included within a newer version of FreeSurfer?

**Comment by chunhungyeh** [comment]
Hi all,

Maybe I can add some information. Here are the shared resources I have used before:

- The official data can be found from [BALSA](https://balsa.wustl.edu/study/show/RVVG).
- The one that projects HCP-MMP1.0 onto FreeSurfer surface (fsaverage) can be found [here](https://figshare.com/articles/HCP-MMP1_0_projected_on_fsaverage/3498446).

Cheers.

**Comment by martahedl** [comment]
Thanks, Chun, those were my resources as well. Additionally, the original node names can be found in the supplementary material of the original article: "Supplementary Neuroanatomical Results For A Multi-modal Parcellation of Human Cerebral Cortex" (Glasser et al., 2016, _Nature_: doi:10.1038/nature18933). Rob, is there anything else you need?

**Comment by Lestropie** [comment]
Excellent.

One little thing to confirm is whether or not the colours are correct with respect to the original publication: one of the modifications I had to do to your original code is multiply the RGB values by 255/1000 in order to constrain them to the range 0-255. I haven't had a chance yet to try using this parcellation myself, but I will do soon.

Would you be content with me adding these files to *MRtrix3*, with recognition of your contribution within file comments / pull request messages, or would you prefer to fork the *MRtrix3* repository & construct a pull request yourself so that the additions to the repository are attributed to you within Git?

**Comment by martahedl** [comment]
OK, so I went through all RGB values again and noticed the following differences :

 

- Regions L_V1 AND R_V1 should be 63 5 255 255 instead of 63 5 26

- Regions L_PF AND R_PF should be 255 255 226 instead of 26 26 226

 

[source: reading in the colortable of the ?h.glasser.annot-file, e.g. with [ver, label, ctab]=read_annotation('?h.glasser.annot')]

 

Moreover, the "A"-column should read "0" for all entries. Did you make them 255 on purpose?

 

I'd be happy if you added the files to MRtrix3, in such a way which makes it easiest for the community to access them. I guess this is option no. 1?!

 

Cheers,

Marlene.

 


Gesendet: Freitag, 06. April 2018 um 00:18 Uhr
Von: "Robert Smith" <notifications@github.com>
An: MRtrix3/mrtrix3 <mrtrix3@noreply.github.com>
Cc: "Marlene Tahedl" <marlene.tahedl@gmx.de>, Mention <mention@noreply.github.com>
Betreff: Re: [MRtrix3/mrtrix3] Error with color lookuptable running labelconvert (#1279)


Excellent.

One little thing to confirm is whether or not the colours are correct with respect to the original publication: one of the modifications I had to do to your original code is multiply the RGB values by 255/1000 in order to constrain them to the range 0-255. I haven't had a chance yet to try using this parcellation myself, but I will do soon.

Would you be content with me adding these files to MRtrix3, with recognition of your contribution within file comments / pull request messages, or would you prefer to fork the MRtrix3 repository & construct a pull request yourself so that the additions to the repository are attributed to you within Git?

**Comment by Lestropie** [comment]
> Moreover, the "A"-column should read "0" for all entries. Did you make them 255 on purpose?

Yes: "Alpha" is quantified as an "opacity", so minimum = fully transparent, maximum = fully opaque. If the values in the "A" column had been left at 0 then all nodes would be invisible :stuck_out_tongue_closed_eyes: 

> I'd be happy if you added the files to MRtrix3

On it :+1:

**Comment by martahedl** [comment]
Sorry, should have read the description first before complaining 😃

All right, thanks! Looking forward to using this atlas!


Gesendet mit der GMX Mail App

Am 10.04.18 um 03:35 schrieb Robert Smith
