### ISSUE TITLE
tckmap Invalid Memory Access with -stat_vox mean and -dec

### ISSUE THREAD

**Issue by LeeReidCSIRO** [MRtrix3/mrtrix3#1285]
tckmap throws an exception with the following command:
`tckmap -template someImage.nii.gz -dec -stat_vox mean trackFile.tck outputFile.nii.gz`

The message is 
[SYSTEM FATAL CODE: SIGSEGV (11)] Segmentation fault: Invalid memory access

This only occurs if the -dec flag is specified

**Comment by Lestropie** [comment]
@LeeReidCSIRO: Good catch :+1: It's specifically the combination of `-dec` and `-stat_vox mean` that is not being appropriately handled. At some point in the past I changed my mind as to how this particular combination should behave, but I didn't adequately clean up after myself. The fix in #1288 happily runs to completion in `gdb`, and will go straight to the `master` branch once tests & reviews are done.

Ideally commands with complex interfaces like `tckmap` and `tcksample` would have a full matrix of tests, running with every single possible combination of command-line options, even making sure that mutually-exclusive options lead to reported errors as expected. Unfortunately it's become increasingly difficult to commit time to such things...
