### ISSUE TITLE
Using tsf files to color whole tracks

### ISSUE THREAD

**Issue by roeysc** [MRtrix3/mrtrix3#1286]
Hi everyone,

I would like to (ab)use a tsf file to visualize each track with a specific color throughout its length.

My intention was to create a tsf file using tcksample, and then edit the file such that all nodes of the same track are assigned a single value (which will be interpreted as a specific color according to the color map chosen in mrview). However, I wasn't able to figure out how the different values of the nodes are saved in the tsf file, so I couldn't manipulate them. I was hoping the ASCII version of the tsf file (taken from tsf_info) could be used for visualization, but that doesn't seem to be the case.

If this is possible, could you please point me in the right direction?

Many thanks,
Best,
Roey

**Comment by Lestropie** [comment]
Hi Roey,

If you want each individual streamline to take a fixed colour along its entire length, then there is no need to use the tsf format: That format is only necessary when a value must be defined for each streamline *vertex*. A simple text file containing a column of values (one for each streamline) can be recognized and used by `mrview`'s Tractography tool.

Rob

**Comment by roeysc** [comment]
Beautiful, thank you Rob!
