### ISSUE TITLE
MRtrix image formats

### ISSUE THREAD

**Issue by neurolabusc** [MRtrix3/mrtrix3#1336]
As a feature request, the [MRtrix image formats](http://mrtrix.readthedocs.io/en/latest/getting_started/image_data.html#mrtrix-image-formats) specification should note that this format is comma separated and enforces that a [dot decimal separator](https://en.wikipedia.org/wiki/Decimal_separator). For example, `vox: 3.25,3.25,3.6,nan`. The dot decimal separator is consistent with DICOM. Since the header is human readable and editable, it seems a good idea to explicitly state this in the documentation.

**Comment by Lestropie** [comment]
Good point; indeed we've not long ago been down the [rabbit-hole](https://github.com/MRtrix3/mrtrix3/issues/1311) of locale handling and the issues it raises... This is a fairly easy addition to the documentation. Thanks for the suggestion!
