### ISSUE TITLE
Untracked file testing/src/project_version.cpp

### ISSUE THREAD

**Issue by thijsdhollander** [MRtrix3/mrtrix3#1337]
I haven't properly investigated, so this may just be a by-product of me switching between branches, but anyway: since the release of RC3, I've now properly checked out `master` again, nicely re-run `./configure` and `./build doc` to be entirely up to date, followed by `./run_tests` to, well, run the tests and get the testing data in, etc..

After all that git status brought up `testing/src/project_version.cpp`  as an untracked file, probably generated during the above process.  I haven't been following all the discussion on the version strings end of last week; but I suspect that might have been introduced then...?

**Comment by thijsdhollander** [comment]
...so well, I suppose it still had/has to be added to `.gitignore`?

**Comment by jdtournier** [comment]
> so well, I suppose it still had/has to be added to .gitignore?

Yep, spot on. Sorry, that got left off in the last minute rush...

**Comment by thijsdhollander** [comment]
Ok, no worries.  I've labelled this "bug" for now; it's not really a bug that breaks stuff of course, but more of a bug in the "proper" user experience.  Essentially just trying to indicate that this is "merely a technical thing"; also fixing this wouldn't change behaviour of the software or methods of course.

**Comment by thijsdhollander** [comment]
Fixed in #1340.
