### ISSUE TITLE
Typo in configure script, static option fails

### ISSUE THREAD

**Issue by thijsdhollander** [MRtrix3/mrtrix3#1339]
See http://community.mrtrix.org/t/standalone-installation-on-linux-fails/1642 ; confirmed the bug, and confirmed the fix, line 231:

`if noshared: build_options.application ('noshared')`

should be changed to

`if noshared: build_options.append ('noshared')`

**Comment by Lestropie** [comment]
Beyond the hot fix, this highlights that `build` and `configure` should be added to `run_pylint` from #1098.

**Comment by thijsdhollander** [comment]
Hmm yes, that's maybe a good idea indeed.  I haven't done that in #1340 , but being pragmatic, I'm definitely not against adding that in there as well.  @MRtrix3/mrtrix3-devs , opinions?  I'm fine either way; anyone who feels authorised, go and click stuff in #1340, be it after adding (somewhat related) commits or not.  I'm all good with it.

**Comment by jdtournier** [comment]
> Beyond the hot fix, this highlights that build and configure should be added to run_pylint from #1098.

Agreed. Not sure I'm looking forward to what that'll throw up though...

**Comment by jdtournier** [comment]
I've merged the hotfix, the `pylint` tests should also be added, but there's no reason to delay the fixes in #1340 for that.

**Comment by Lestropie** [comment]
Closed by #1340.
