### ISSUE TITLE
build script writing to buffered stdout

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#1345]
Currently, script `build` is writing some information to `stdout` and some to `stderr`, with higher-verbosity / higher-severity messages going to the latter. The primary terminal feedback during typical usage, i.e. the build item number and target file, is in fact going to `stdout`.

Where I've noticed this is when compiling *MRtrix3* inside a container. With local usage, the build progress typically only displays once every 100 items or so; not the expected behaviour, but not hugely problematic. Where this buffering is however annoying, which I'm encountering at the moment, is when using a cloud service that enforces a job timeout period when there is no output on `stdout` or `stderr` for some period of time. It's also kinda strange using the `-verbose` option when `stdout` is buffered, since the text output on `stdout` and `stderr` no longer properly align with one another.

While there's quite a number of solutions to the particular issue I've got, thought I'd raise the general issue here for opinions. E.g. Should *all* `build` output go to `stderr`? Or if retaining the separation between `stdout` and `stderr` is desired, we could define a [wrapper class](https://stackoverflow.com/a/107717) that calls `sys.stdout.flush()` after every `sys.stdout.write()` call.

**Comment by jdtournier** [comment]
It's probably not a bad idea to throw everything out on `stderr`, and should be trivial to do. All terminal output is already wrapped through various calls (`disp()`, `error()`, `log()`, `report()`), so changes should be minimal.

In general, I guess we've always relied on `stdout` being line-buffered

**Comment by thijsdhollander** [comment]
> It's probably not a bad idea to throw everything out on `stderr`

Yep, I also agree with this. :+1:

**Comment by maxpietsch** [comment]
I think the buffered output of `build` is also an issue for building the test commands inside homebrew's `test` function, which deadlocks and aborts occasionally.

**Comment by Lestropie** [comment]
Closed by #1348.
