### ISSUE TITLE
Help & documentation: Flag .allow_multiple()

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#1356]
Thought I had this listed somewhere, but can't find it.

Whenever a command-line option is flagged as `.allow_multiple()`, this should automatically be reflected in any automatically generated documentation.

This may be one of the contributing factors to why users often combine their ROIs into a single mask image before running `tckgen` or `tckedit`, and subsequently don't understand why an OR operation is being performed instead of an AND: They don't realise that the option can be specified more than once.

While such a description could be added to option help descriptions on an individual basis, having some sort of flag appear within the help pages & documentation would be better IMO.

**Comment by thijsdhollander** [comment]
Not a bad idea in general, I reckon.  However, for the `tckgen` and `tckedit` ROI related options in particular, it could probably be highlighted in the option text (or general commend description text) as well, if that's a case (of misunderstanding) that happens frequently.
