### ISSUE TITLE
Error using dwipreproc with 'mporder'

### ISSUE THREAD

**Issue by nikitas-k** [MRtrix3/mrtrix3#1360]
Hi there,

I'm using `dwipreproc` with the `--mporder` option with `--slspec` manually set as exported:
```
8.79
0
8.985
0.195
9.18
0.39
9.375
0.585
9.57
0.78
9.765
0.975
9.96
1.1725
10.1575
1.3675
10.3525
1.5625
10.5475
1.7575
10.7425
1.9525
10.9375
2.1475
11.1325
2.3425
11.3275
2.5375
11.525
2.735
11.72
2.93
11.915
3.125
12.11
3.32
12.305
3.515
12.5
3.71
12.695
3.905
12.89
4.1025
13.0875
4.2975
13.2825
4.4925
13.4775
4.6875
13.6725
4.8825
13.8675
5.0775
14.0625
5.2725
14.2575
5.4675
14.455
5.665
14.65
5.86
14.845
6.055
15.04
6.25
15.235
6.445
15.43
6.64
15.625
6.835
15.82
7.03
16.0175
7.2275
16.2125
7.4225
16.4075
7.6175
16.6025
7.8125
16.7975
8.0075
16.9925
8.2025
17.1875
8.3975
17.3825
8.595
```
and I run the following command:

```
dwipreproc -rpe_pair -se_epi allb0s.mif -align_seepi -pe_dir AP -export_grad_mrtrix adjencoding.b rawdataAPdn.mif eddycorr.mif -eddy_options " --repol --data_is_shelled --mb=2 --ol_type=both --slm=linear --mporder --slspec=slspec.txt " -nthreads 8 -force -eddyqc_all dwipreproc
```

I get this error:
```
dwipreproc: No slice encoding direction information present; assuming third axis corresponds to slices
Traceback (most recent call last):
  File "/software/mrtrix3/mrtrix3-3.0_RC3/bin/dwipreproc", line 220, in <module>
    slice_groups.append([int(value) for value in line.split()])
ValueError: invalid literal for int() with base 10: '8.79'

```

Is there a specific structure to slspec? The slice timing was acquired from processing the DICOM files with dcm2niix as mrconvert failed to capture the slice timing when I ran it. This is using mrtrix version 3.0_RC3 btw

Thanks in advance for your help.

**Comment by Lestropie** [comment]
Hi @nikitas-k,

The `--slspec` file input to FSL's `eddy` tool is *not* slice timing, but specification of [slice *groups*](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/eddy/UsersGuide#A--slspec). The error is appearing in `dwipreproc` because it's trying to convert a floating-point number in text form to an integer; while I could do a better job of catching such misuse and providing a more meaningful error message within the *MRtrix3* script, fundamentally the issue is in the data you are attempting to provide to `eddy`.

Regarding the absence of slice timing information: What's the nature of your DICOM data? If it's theoretically possible to obtain slice timing from your data, but `mrconvert` isn't capable of doing so (and this inability isn't rectified by [this fix](https://github.com/MRtrix3/mrtrix3/pull/1359)), it's data I could benefit from access to.

Rob

**Comment by Lestropie** [comment]
Well, if it's Siemens Mosaic, then there's a good chance the slice timing import issue has already been fixed. If it was anything other than this, then you'd be in possession of DICOM data that contains slice timing information that my code is not yet capable of extracting, in which case I'd be curious to know what vendor / scanner it came from.

**Comment by nikitas-k** [comment]
Oh that's actually perfect, I appreciate the quick response btw. Not sure why the slice timing isn't being imported as slice groups though. They are Mosaic

**Comment by Lestropie** [comment]
Representation of such data as "slice groups", I haven't seen outside of `eddy`. The fMRI community have made use of slice timings for much longer than us DWI-ers, and they've always used the raw timing per slice AFAIK. So an explicit conversion is required to produce the data in this format. In the situation where `dwipreproc` instead gets slice timing from the image header, it generates the slice groups expected by `eddy` using [this one-liner](https://github.com/MRtrix3/mrtrix3/blob/master/bin/dwipreproc#L808).

**Comment by Lestropie** [comment]
More or less; once it sees the "`--mporder`` flag within `-eddy_options`, it knows that either an explicit `slspec` file, or slice timing information in the header, are required. More details in the [documentation](http://mrtrix.readthedocs.io/en/latest/dwi_preprocessing/dwipreproc.html#using-eddy-s-slice-to-volume-correction-capability).

**Comment by nikitas-k** [comment]
Ok great, the commit  https://github.com/MRtrix3/mrtrix3/commit/89687167139493ca6d9d41a7a330b354bdfb624f is working. Although I get this error in `dwipreproc`:
```
Traceback (most recent call last):
  File "/software/mrtrix3/mrtrix3-NK/bin/dwipreproc", line 230, in <module>
    app.warning('\"slspec\" file provided to FSL eddy should contain slice indices for slice groups, not slice timing; nevertheless, slice timing has been imported from file \"' + slspec_file_path + '\"')
AttributeError: 'module' object has no attribute 'warning'
```
I suspect this is just an exception that Environment Modules (the way my institute's cluster loads software) doesn't handle. So I just commented out the line and it seems to be working now. Fingers crossed.

**Comment by Lestropie** [comment]
No, that's just me forgetting the names of my own module functions; should be `app.warn()` :roll_eyes:

**Comment by nikitas-k** [comment]
Ah I let it run last night and it made it to this part:
```
Command:  eddy --imain=eddy_in.nii --mask=eddy_mask.nii --acqp=eddy_config.txt --index=eddy_indices.txt --bvecs=bvecs --bvals=bvals --topup=field --repol --data_is_shelled --mb=2 --ol_type=both --slm=linear --mporder --slspec=slspec.txt --out=dwi_post_eddy
dwipreproc: 
dwipreproc: [ERROR] Command failed: eddy --imain=eddy_in.nii --mask=eddy_mask.nii --acqp=eddy_config.txt --index=eddy_indices.txt --bvecs=bvecs --bvals=bvals --topup=field --repol --data_is_shelled --mb=2 --ol_type=both --slm=linear --mporder --slspec=slspec.txt --out=dwi_post_eddy (dwipreproc:867)
dwipreproc: Output of failed command:
            
            Part of FSL (ID: 5.0.11)
            eddy 
            Copyright(c) 2015, University of Oxford (Jesper Andersson)
            
            Usage: 
            eddy --monsoon
            
            Compulsory arguments (You MUST set one or more of):
            	--imain	File containing all the images to estimate distortions for
            	--mask	Mask to indicate brain
            	--index	File containing indices for all volumes in --imain into --acqp and --topup
            	--acqp	File containing acquisition parameters
            	--bvecs	File containing the b-vectors for all volumes in --imain
            	--bvals	File containing the b-values for all volumes in --imain
            	--out	Basename for output
            
            Optional arguments (You may optionally specify one or more of):
            	--mb	Multi-band factor
            	--mb_offs	Multi-band offset (-1 if bottom slice removed, 1 if top slice removed)
            	--slspec	Name of text file completely specifying slice/group acuistion
            	--mporder	Order of slice-to-vol movement model
            	--s2v_lambda	Regularisation weight for slice-to-vol movement. (default 1, reasonable range 1--10
            	--topup	Base name for output files from topup
            	--field	Name of file with susceptibility field (in Hz)
            	--field_mat	Name of rigid body transform for susceptibility field
            	--flm	First level EC model (movement/linear/quadratic/cubic, default quadratic)
            	--slm	Second level EC model (none/linear/quadratic, default none)
            	--fwhm	FWHM for conditioning filter when estimating the parameters (default 0)
            	--niter	Number of iterations (default 5)
            	--s2v_niter	Number of iterations for slice-to-vol (default 5)
            	--cnr_maps	Write shell-wise cnr-maps
            	--residuals	Write residuals (between GP and observations)
            	--fep	Fill empty planes in x- or y-directions
            	--interp	Interpolation model for estimation step (spline/trilinear, default spline)
            	--s2v_interp	Slice-to-vol interpolation model for estimation step (spline/trilinear, default trilinear)
            	--resamp	Final resampling method (jac/lsr, default jac)
            	--nvoxhp	# of voxels used to estimate the hyperparameters (default 1000)
            	--initrand	Resets rand for when selecting voxels (default false)
            	--ff	Fudge factor for hyperparameter error variance (default 10.0)
            	--repol	Detect and replace outlier slices
            	--ol_nstd	Number of std off to qualify as outlier (default 4)
            	--ol_nvox	Min # of voxels in a slice for inclusion in outlier detection (default 250)
            	--ol_type	Type of outliers, slicewise (sw), groupwise (gw) or both (both). (default sw)
            	--ol_pos	Consider both positive and negative outliers if set (default false)
            	--ol_sqr	Consider outliers among sums-of-squared differences if set (default false)
            	--dont_sep_offs_move	Do NOT attempt to separate field offset from subject movement (default false)
            	--dont_peas	Do NOT perform a post-eddy alignment of shells (default false)
            	--data_is_shelled	Assume, don't check, that data is shelled (default false)
            	-v,--verbose	switch on diagnostic messages
            	-h,--help	display this message
            
            
            
            --mporder: Missing non-optional argument!
dwipreproc: 
dwipreproc: Changing back to original directory (/mnt/lustre/working/lab_michaebr/nikitasK/epilepsy/old_subjects/3.0_RC3/Diff/PE017/preproc)
dwipreproc: Script failed while executing the command: eddy --imain=eddy_in.nii --mask=eddy_mask.nii --acqp=eddy_config.txt --index=eddy_indices.txt --bvecs=bvecs --bvals=bvals --topup=field --repol --data_is_shelled --mb=2 --ol_type=both --slm=linear --mporder --slspec=slspec.txt --out=dwi_post_eddy

```
Not entirely sure what's happening here, since slspec is provided through the dwipreproc. This is the contents of slspec.txt in the temp folder:
```
1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
51
53
55
57
59
61
63
65
67
69
71
73
75
77
79
81
83
85
87
89
0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
```

**Comment by nikitas-k** [comment]
Alright so after a little digging, I found that the `mporder` option has to be given a number greater than zero to proceed in actually using the `slspec` for slice-to-volume correction: [Here](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/eddy/UsersGuide#Correcting_slice-to-volume_movement_with_eddy)

I get this error:
```
$ eddy --imain=eddy_in.nii --mask=eddy_mask.nii --acqp=eddy_config.txt --index=eddy_indices.txt --bvecs=bvecs --bvals=bvals --topup=field --repol --data_is_shelled --mb=2 --ol_type=both --slm=linear --mporder=6 --slspec=slspec.txt --out=dwi_post_eddy
eddy: msg=--mb and --slspec mutually exclusive
terminate called after throwing an instance of 'EDDY::EddyException'
  what():  eddy: msg=--mb and --slspec mutually exclusive
Aborted (core dumped)
```

Turns out: `--mb=#` and `--slspec` indeed provide the same thing as referenced here:
https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=FSL;d28a23ec.1801
and throw an error rather than just handle it elegantly.

**Comment by nikitas-k** [comment]
My mistake @Lestropie I didn't read https://mrtrix.readthedocs.io/en/dev/dwi_preprocessing/dwipreproc.html#using-eddy-s-slice-to-volume-correction-capability
but this was instructive regardless. Thanks for your help.
