### ISSUE TITLE
New commands: mrcentre, labelcentre

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#1370]
Adding this explicitly since it's come up a number of times in quick succession.

I have a [gist](https://gist.github.com/Lestropie/06afe8c2eedfd48b9d34ab41539d337f) for a stand-alone command that calculates the centre of mass of an image (taking into account image intensities). This can be useful for e.g. reporting MNI coordinates of statistically significant elements upon transformation to the MNI template.

I could quite easily write a similar command `labelcentre`, which would provide the centre of mass of each parcel within a label image, for applications such as [this forum thread](http://community.mrtrix.org/t/node-coordinates-in-mni-space/1657).

Given a few people have wanted the functionality, it makes sense to me to add it to the main repo. Open to suggestions for alternative command names.

**Comment by maxpietsch** [comment]
Makes sense to me. I've written a similar command with the catchy name [mrreg_init](https://github.com/MRtrix3/mrtrix3/blob/mrreg/cmd/mrreg_init.cpp) that also takes masks and can optinally align using a rigid transformation. However, it currently is still in the `mrreg` branch. It's time to overhaul that branch...
