### ISSUE TITLE
Need easy to edit, user-editable FAQ section

### ISSUE THREAD

**Issue by jdtournier** [MRtrix3/mrtrix3#1394]
Something that seems to keep coming up is the idea of a FAQ page with quick tips and ways to perform common operations. One barrier to getting this underway is the overhead of adding entries and maintaining such an FAQ. What might help would be to have a page/section separate from the main docs (but linked to from the docs) that would be quick and easy to update, not require a full commit/test/review cycle to the main repo, and that users could more directly contribute to. 

The obvious candidate here is the GitHub Wiki. It's currently disabled, but we could just re-enable it, provide a front page with a link to the main docs, and then point users to the sidebar for the full list of FAQ entries (this means one page per entry). We could also provide a brief set of instructions to add a new entry, to help keep it consistent. The advantages are: much easier for anyone to add content; it's markdown (simpler than ReST); the sidebar provides a full listing (no need to maintain a ToC); we can make it editable by anyone (less burden on us); it's immediate and doesn't require the full hour's delay that a push to the main repo would entail... 

Thoughts?

**Comment by Lestropie** [comment]
Anything that opens the potential for user contributions and taking a load off my own back gets a :+1: from me :-P

The challenge would be getting the separation between official documentation and user-editable documentation right. Currently in the docs:

- "Tips and tricks" contains info on DICOM handling, and a description of `foreach`. The former could go either way; the latter would ideally instead be encapsulated within the help page of `foreach` after porting it to the Python library. 

- "Troubleshooting" contains: Crashes/errors/performance issues, display issues, FAQ, and advanced debugging instructions. The contents of FAQ are things that could probably be individual pages in the wiki; the others, I honestly don't know.

The other thing to consider is level of access. Open access is fine if people are adding pages with their own information; but for something like e.g. "What tracking parameters should I use for HCP data?", different users may have different opinions, and we wouldn't want to enable a back-and-forth editing war. Is there a "pull request" equivalent for the GitHub wiki?

**Comment by jdtournier** [comment]
Yes, that one will always be tricky. There's 3 categories that I can see here:

- our officially-endorsed tips & tricks, including `foreach`, and most of the troubleshooting section (not FAQ)

- the user-editable FAQ on the wiki (or elsewhere), with the understanding that this is not necessarily officially endorsed, and even if a member of the team adds an item, it's not necessarily been endorsed by the rest of the team.

- user or team recommendations about what pipeline to use for specific datasets, etc. I think these should reside on the forum... We could have a generic FAQ entry entitled "what parameters should I use for specific dataset?", and outline that these are subject to discussion and better suited to the forum.

> Is there a "pull request" equivalent for the GitHub wiki?

Not as far as I know - it's either open to editing by team members only, or everyone. Personally, I don't think we want to have an official approval process, this gives the recommendations a seal of approval and puts the onus on us to ensure accuracy. I'd rather we leave it open and monitor what gets added so we can retrospectively remove or amend bad advice - or block users if they're repeat offenders or outright spamming. But at least there will be an implicit understanding that these are not our official recommendations as such.

**Comment by thijsdhollander** [comment]
Fully agreed! Much better than the GitHub wiki, and much more likely to get contributions from users as well, I reckon.

**Comment by jdtournier** [comment]
OK, I'll get this set up then. Draft announcement coming up on the staff forum...

**Comment by Lestropie** [comment]
Still need to decide how to resolve this against the main documentation. Currently the two FAQs listed on Discourse are not actually from the RST FAQ section.

**Comment by jdtournier** [comment]
> Still need to decide how to resolve this against the main documentation

Indeed. One of the items I've copied over is actually from our troubleshooting section, which I'd earlier argued should stay on the main docs... :blush: 

I'm not sure my opinion on this is fully settled. But _currently_, my thoughts are that the main docs should cover our software and how to use it. Anything that relates to troubleshooting should only be included in the main docs if it is a common issue, a stable one (not tied to some specific OS version, or the presence of some other package, etc.), and very much intrinsic to our software, rather than its interactions with specific OS features. 

What I think should go in the FAQ is anything that relates to troubleshooting or installation where the issue is uncommon, tied to specific OS's / versions and likely to evolve over time due to factors outside our control. For example, the issues we have with `anaconda` on macOS would be good there: it's not improbably that the `anaconda` team might change their approach so that it doesn't cause problems any more, or causes different problems. 

The 2 topics I've added to the wiki right now also fit that category: the shared memory thing is specific to Linux, and the location of that folder is not unlikely to change over time (we certainly don't have control over it). The dirty page handling is going to be distro-specific (different distros will probably have different default parameters), and also I'm not 100% comfortable with suggesting the fix, in that it requires admin rights and a pretty good understanding of what you're doing. So I think they fit in nicely on the wiki. 

Another issue that feels should be on the wiki is the display problem for remote connections and virtual machines & containers. This is very much about support for OpenGL 3.3, irrespective of _MRtrix3_ as such, and it seems the situation is very much in flux at the moment, with `mesa` providing some support for software rendering (but hard to figure out what's needed to get it to work), and Wayland around the corner. I really think that one needs to be able to evolve and respond to user input relatively frequently.

Also, the information in the wiki won't be versioned in step with the main docs, so this feels like a natural home for issues like this, which are tied to relatively generic factors outside our control, and affect all/most versions of the software generically. And a live wiki feels right for this: we can provide immediate recommendations to users, without needing to go through the commit/test/review/merge cycle, and also potentially hide this new information from users until a new release (if committing to `dev`). In fact, I expect we might find ourselves responding to queries on the forum by writing a FAQ topic on the matter, and referring the user to the new entry...

Anyway, I'm not sure I've articulated myself very well here... I think I could probably distil this into something that looks closer to an actual policy, but hopefully you get what I'm talking about...? It's (quite) a bit different from the opinion I'd expressed earlier in this thread, since I'm now suggesting that just about all of our troubleshooting and FAQ sections go into the wiki. But who says I can't change my mind... :man_shrugging:

**Comment by thijsdhollander** [comment]
> I think I could probably distil this into something that looks closer to an actual policy, 

A bit overkill, I reckon.  I think I largely agree with most, if not all things, you've written up here as a general guideline.  It's very hard to define a strict policy, and you'll see, the moment you define one, the first case that comes up is already an exception to it.  Eventually, we'll be spending more time on the bureaucracy that is involved with writing a policy; which defeats the purpose of making the whole FAQ contributions thing more streamlined and flexible.  I'd say: let's just kick this off, and feel out the inherent "policy" as we go.  It may be much easier to make the decision for concrete cases than "hypothetically", "theoretically", and "in general".  You'll see, it'll simply work out and shape itself in practice (as wiki's quite often do). :wink:

**Comment by jdtournier** [comment]
Sorry, I wasn't suggesting we'd write down an official policy on this... 😨 Just trying to articulate some relatively succinct position that we can all agree on, at which point we can start migrating topics over, etc. I do agree things will evolve - this is _MRtrix_, after all... :wink:

**Comment by thijsdhollander** [comment]
Alright, we're on the same page then. 😉  In that case, I generally agree with the strategy you wrote up to separate FAQ vs documentation. I was thinking along the same lines too; it makes good sense, I reckon.

**Comment by Lestropie** [comment]
I've ported a bunch of documentation over to the community forum, but likely not everything that will eventually move. No PR for removing the relevant pages from the documentation yet. 

Possibly one thing contributing to my still being unclear what should or should not be moved is the naming of the category as "FAQ", which, in the current form of the documentation, only refers to a subset of what's being proposed to move over. I wonder if instead naming the new forum category "wiki", and then additionally using relevant tags for threads (e.g. "faq", "error", "performance", "tips and tricks"), would clarify things. E.g. One of the points made above is that anything that needs to be versioned with the software needs to remain in the repo docs; but technically that could apply to anything where even a trivial command-line example is provided, in reality there's a spectrum from "will never change" to "highly volatile across software versions", which makes it hard to draw a line on what moves vs. what stays on that criterion. It may also be more likely for users to contribute to something called "wiki" as opposed to "FAQ", as they're not likely to be "receiving the same question multiple times" in their position.
