### ISSUE TITLE
dwiintensitynorm

### ISSUE THREAD

**Issue by maxpietsch** [MRtrix3/mrtrix3#1408]
`dwiintensitynorm` currently can not handly nifti files lacking an option to import gradient information. Is this something we want to change? 

A single gradient option that is applied to all input images could tempt users swapping pre- and post-eddy gradient tables. I'd suggest adding an option for a gradient table directory directory or adding a comment to the command description that `.mif` files with gradient information are required as input.

**Comment by jdtournier** [comment]
OK, I'd favour adding a comment that `.mif` files are required -- I don't think this command will be used a great deal in the future now that we have `mtnormalise` (I certainly wouldn't advocate its use any more)...

**Comment by thijsdhollander** [comment]
Yeah, I tend to agree.  I mean, happy to have the option added of course, but it may indeed not be worth the effort to implement it; while it's a pretty minor effort for users to convert to `.mif`.  The effort of organising gradient tables in a gradient table directory may actually require more (mental) effort for most users, with all sorts of opportunities for confusion and mistakes in the process.  Most of those users would probably also nicely follow the (single tissue) FBA instructions, which naturally would lead them to conversion to `.mif` up front.
