### ISSUE TITLE
mrconvert: question about extracting from 4D volume

### ISSUE THREAD

**Issue by nooralsh** [MRtrix3/mrtrix3#1424]
Hi -- I have a set of fmri volumes in which every other timepoint is phase-encoded oppositely to its preceding timepoint (ie vol 0 is A-P, vol 1 is P-A, vol 2 is A-P, etc). I need to use all similarly encoded timepoints as two separate volumes, ie all A-P as one volume and all P-A as another. 

I know I can extract every other volume using `mrconvert` with the option `-coord 3 0,2,4,6,8,10,...,n` but is there an easier or more versatile way of defining which alternating volumes to extract? Especially since not all volumes might have the same number of timepoints.

Any help would be appreciated! Thanks.

**Comment by nooralsh** [comment]
Actually.. I think I solved my own issue already, oops.

**Comment by Lestropie** [comment]
Hi @nooralsh,

Just a quick follow-up:

In an ideal world, it would be possible to select these volumes using [the `-pe` option in `dwiextract`](http://mrtrix.readthedocs.io/en/latest/reference/commands/dwiextract.html#options-for-selecting-volumes-based-on-phase-encoding). However my suspicion is that while I've done my best to ensure that *MRtrix3* will correctly identify from DICOM if the phase encoding direction varies between volumes and [represent such information appropriately](http://mrtrix.readthedocs.io/en/latest/concepts/pe_scheme.html), the *sequences* used to acquire such data will unfortunately fail to properly encode the flipping of phase encoding direction within the DICOM headers.

This was certainly the case in my communication with the person responsible for Siemens DWI WIP development; are you able to add any information here from your own fMRI data?

Rob

**Comment by jdtournier** [comment]
As another quick follow-up: the `-coord` option in `mrconvert` actually accepts a [number sequence](https://mrtrix.readthedocs.io/en/3.0_rc2/getting_started/command_line.html#number-sequences-and-floating-point-lists), and also understands the `end` keyword. This allows you to specify `-coord 3 0:2:end` to do what I _think_ you're trying to do. Could do with being better documented though, I agree...

**Comment by nooralsh** [comment]
@jdtournier -- That is _exactly_ the solution I was looking for! Thank you for the suggestion, made my code much simpler. 

@Lestropie -- I would guess that the DICOM headers didn't include the correct information in the first place, which is why they got converted as a sort of accordion of images.. Unfortunately, I didn't collect these fMRI data myself and cannot comment as much on their acquisition! I used `dcm2niix` to convert them but will check out `dwiextract` and see how it handles them. Thanks!
