### ISSUE TITLE
New script: dwicat

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#1428]
(name suggestions welcome)

As raised in multiple locations:

A convenience script for concatenating multiple DWI series where the intensity scaling of image reconstruction may have varied due to recalibration. This would involve:

- Extracting the *b*=0 volumes from each series.
(Easiest would be to require .mifs at input so that gradient tables are embedded)

- Using `mrhistmatch scale` or `mrstats -output median` to determine the global intensity fluctuations between acquisitions.

- Concatenate all data into a single 4D image, applying appropriate multiplicative factors.

It should also check for variations in TE and TR between the input series, and warn where appropriate.

**Comment by Lestropie** [comment]
Bump

**Comment by jdtournier** [comment]
Sounds good, agree on the principle, and will definitely come in handy. I'd prefer the simpler name of `dwicat` personally. We could also make the intensity normalisation conditional on detecting a sufficiently large difference in scaling, along with a clear report about this? Also, I'd advocate using the raw DICOMs as input - though mifs would be fine too, of course.

**Comment by thijsdhollander** [comment]
Yep, 100% agreed with all of @jdtournier's comments.

**Comment by Lestropie** [comment]
> Also, I'd advocate using the raw DICOMs as input - though mifs would be fine too, of course.

Any risk of interaction with `dwidenoise`?

**Comment by Lestropie** [comment]
Closed by #1626.
