### ISSUE TITLE
MRView: unexpected translation/wrap of background image on screen capture

### ISSUE THREAD

**Issue by dnvaughan** [MRtrix3/mrtrix3#1461]
I like to use MRview to take screen captures of functional activation maps overlaid on a T1 template. Recently upgraded to ubuntu 18.04 and updated my mrtrix installation (after a long time!).

Initially the T1 (the MNI template) and functional overlay (generated by SPM12) load fine:
![image](https://user-images.githubusercontent.com/22635572/46393863-539aae00-c72a-11e8-8d0a-e4c8175720a7.png)

Then I take a screenshot, which is saved correctly.
On the next scroll of image position within mrview, the display jumps to this:
 
![image](https://user-images.githubusercontent.com/22635572/46394162-9741e780-c72b-11e8-960d-13e24146c1c9.png)

As you can see, the background T1 image appears to be translated, wraps around the window, and is out of alignment with the overlay image. 

Version info: 
MRview -  version 3.0_RC3-91-gd2cd716d, 64 bit release version, built Oct 3 2018
Qt version 4.8.7.
![image](https://user-images.githubusercontent.com/22635572/46394082-46ca8a00-c72b-11e8-94d9-69ecf05c1a16.png)

Please let me know what other info will help to sort this out. 
Thanks very much,
David.

**Comment by maxpietsch** [comment]
Might be related to #1375 and #1369. Did you open the `view tool` at any point? If so, please try again without.

**Comment by dnvaughan** [comment]
@maxpietsch : I've just tested this and you're correct.  

It does not occur if I just load the background, load the overlay and take a screen capture.
However, if I open the 'View Options' tool (and make no changes on that tab), then the problem occurs after the next screen capture.

Hope this helps point to where the problem is. Unfortunately it's not a solution for me, as I need to change the intensity scaling of the background image before I do the screen capture.

**Comment by maxpietsch** [comment]
Thanks for testing! Closing this one in favour of #1369. You can set the image intensity range via command line as well: `-intensity_range`, similarly the overlay intensity: `-overlay.intensity`.

**Comment by dnvaughan** [comment]
Thanks Max. I don’t understand issue #1369, so have no idea if fixing that will help this problem too.

The suggestion to use the command line would be good one, if it worked.
Unfortunately -overlay.intensity just sets the text box entries on the overlay tool tab, and doesn’t update the actual image or the overlay color bar.
