### ISSUE TITLE
Fedora 27 install issues

### ISSUE THREAD

**Issue by lkoelman** [MRtrix3/mrtrix3#1470]
I had following installation issues under Fedora 27:

- In  Fedora 27 `moc` is called `moc-qt4` or `moc-qt5` depending on qt version so configure script can't find it -> solved by adding symbolic link
- Neither g++ nor clang++ like `/usr/include` to be included using `-isystem` (there are a lot of bugreports about this if you google) -> solved by removing the substitution of `-I` by `-isystem` in lines 1191-1194 of configure file

I don't know if either of these solutions are recommended but they did the trick for me.

**Comment by jdtournier** [comment]
Thanks for the feedback. To address each point:

> 1. In Fedora 27 moc is called moc-qt4 or moc-qt5 depending on qt version so configure script can't find it -> solved by adding symbolic link

This is indeed a problem, but not one I think we can or should do anything about. If both `moc-qt4` and `moc-qt5` are present, there's a fundamental ambiguity as to which to choose. Ultimately it should be up to the system/user to select the desired version. Most systems should provide a means of selecting which version of Qt to compile against - on Ubuntu, I think it's done via a `QT_SELECT` environment variable or something, or via their `update_alternatives` script (I'm not sure about the names, this is from memory). In other systems, these binaries might not even be in the default PATH, so users have to add the relevant version into their PATH explicitly. RORY EASY

**Comment by jdtournier** [comment]
I should also mention that another solution for your first problem is to set the `MOC` environment variable at the configure stage, e.g.:
```
MOC=moc-qt4 ./configure
```

There's lots of variables you can set if needed. Type `./configure -help` for the full breakdown.

**Comment by jdtournier** [comment]
One more thing: forgot to mention that #1435 is currently merged to `dev`, but not yet on `master`. It'll be part of the next release - hopefully within the next few weeks.

**Comment by lkoelman** [comment]
Great that it should be easily resolved then without my hacky solutions. Might be useful to add this information (about MOC environment variable) in the installation instructions under the Fedora part.

**Comment by jdtournier** [comment]
Not that hacky... Your symbolic link is what I'd have done (had I not known about the environment variable), and the `-isystem` issue can't be fixed without precisely the sort of hack you resorted to.

As to documenting this: guess I really need to finalise #1394...

**Comment by jdtournier** [comment]
I assume this can be closed off - feel free to reopen if needed.
