### ISSUE TITLE
MRView: better handling of high dimensional data

### ISSUE THREAD

**Issue by jdtournier** [MRtrix3/mrtrix3#1474]
Currently, there is no support for data with dimensionality greater than 5D, even though it would be relatively trivial to implement. It would be overkill to add keyboard shortcuts to navigate dimensions above 5 (currently left/right navigate 4th dimension, Shift+left/right navigate 5th dimension). However, higher dimensions should be accessible via the view tool, but the interface doesn't allow this at the moment (I thought it did a while back?), and the goto shortcut is specific to either 'volume' or 'volume group'. 

I think it should be simple to provide controls for the additional dimensions on the View tool. And the goto dialogs could trivially be merged into a single dialog with entries for each dimension > 3.

**Comment by maxpietsch** [comment]
6466ff8dfd6a689243 implements the possibility of changing volume groups up to 9 dimensions in the view tool. (The `-volume` command-line option already supports any number of dimensions.)

![Screenshot 2019-07-17 23 30 19](https://user-images.githubusercontent.com/10046944/61413153-18e5b900-a8eb-11e9-9cae-1a57889d38cc.png)

I have not implemented a new goto dialogue as I do not know how to define a popup that reads multiple integers. QT's standard dialogues seem to support only one value.

**Comment by Lestropie** [comment]
- How does it go having the axis number within the text box when you try to type in a position manually rather than using the arrows? Would it be better for the axis numbers to be labels outside of the text boxes?

- I don't think it would be any more difficult to have axes beyond that of the main image hidden rather than disabled. Would that be preferable? Or does it stretch out the remaining text boxes too much horizontally? (though it'd likely be possible to restrict their maximum width to prevent such)

**Comment by maxpietsch** [comment]
- The text box (SpinBox) can be used just like any SpinBox, the dimension text is just a [prefix](https://doc.qt.io/qt-5/qspinbox.html#prefix-prop) that is not editable. If that's confusing, 79aa0a1f0 uses the text width to scale a label in front of the SpinBox:
![Screenshot 2019-07-18 11 34 47](https://user-images.githubusercontent.com/10046944/61447038-7a8c3e80-a950-11e9-8f93-3fd234fe8002.png)


- Hiding the disabled SpinBox would be nice but requires some work. The only way I found is to split them up into a grid of [QGroupBox](https://doc.qt.io/qt-5/qtwidgets-widgets-groupbox-example.html)es that can be disabled. But I think group boxes would require more space and have borders and be separated by a lack of background colour. I think some of this can be adjusted via [CSS](https://doc.qt.io/qt-5/stylesheet-examples.html) but I haven't looked into it.

**Comment by jdtournier** [comment]
I actually quite like the labels inside the spinbox... Seems to work fine on my system too. 

I've just pushed another branch (`mrview_highdim2`) based off this one using a different tack: the number of entries shown is dynamically determined from the image shown at runtime, up to arbitrary dimensionality (no hard limit). It'll lay them out in rows of 3. Haven't tested with anything higher than 5D though... I'd need to generate some 7D data to verify that it works OK with the 3-wide layout...

No idea how to handle the goto-volume menu entry - happy to leave it as-is for now...

**Comment by jdtournier** [comment]
I merged these changes into #1642 - closing this issue.
