### ISSUE TITLE
mrconvert fails seemingly randomly

### ISSUE THREAD

**Issue by thijsdhollander** [MRtrix3/mrtrix3#1475]
...in context of `dwi2response`, further in context of TractSeg.  See original issue description over here: https://github.com/MIC-DKFZ/TractSeg/issues/20 .

**Comment by jdtournier** [comment]
Is this issue resolved...? Seems it might not be MRtrix-related...?

**Comment by thijsdhollander** [comment]
Yep, it's fine; mostly put this here initially to draw some attention to the issue going on over there.  There's an issue for it on the TractSeg end anyway, so let's close this off.
