### ISSUE TITLE
HCP install issue

### ISSUE THREAD

**Issue by tiborauer** [MRtrix3/mrtrix3#1477]
Hi,

I tried to install MRtrix3 on our HPC. I followed the steps as outlined in [documentaion](https://mrtrix.readthedocs.io/en/latest/installation/hpc_clusters_install.html), but 
`python configure` throw me an error (as in configure.log): 

EXEC <<
CMD: /usr/local/apps/psycapps/gcc/bin/g++ -c -std=c++11 -DMRTRIX_BUILD_TYPE="release version" -pthread -fPIC -m -fPIC /tmp/tmpbzr26ee_.cpp -o /tmp/tmpbzr26ee_.o
EXIT: 1
STDERR:
g++: error: unrecognized command line option '-m'
>>

**Comment by jdtournier** [comment]
OK, that's unexpected. Indeed, `-m` is not an option I'd expect `g++` to understand, but it's also not one that the `configure` script should insert for no reason... At what stage of the configure cycle does this happen? I assume pretty early on? One reason could be that you might have an environment variable like `CFLAGS` or `ARCH` set...? What do these commands report:
```
$ echo $CFLAGS
$ echo $ARCH
```
If these are set, try un-setting them first, see if that helps...

**Comment by tiborauer** [comment]
Thanks for the fast and efficient answer!

CFLAGS was not empty, indeed. I have unset is and then I could build MRtrix.
