### ISSUE TITLE
switch to HTTPS on the forum?

### ISSUE THREAD

**Issue by jdtournier** [MRtrix3/mrtrix3#1480]
This is how the forum shows up in Chrome:

![untitled](https://user-images.githubusercontent.com/3221000/47914759-a5089b00-de98-11e8-9ab3-cc2fe2943f4e.png)

Might be worth thinking about doing something about it in due course. I note there are [instructions for switching over to HTTPS](https://meta.discourse.org/t/setting-up-https-support-with-lets-encrypt/40709), but there's a few thinks to double-check first. Thoughts / help welcome...

**Comment by thijsdhollander** [comment]
Yep, I was literally thinking the same thing less than a week ago; the forum sure looks quite frightening at the moment in Chrome, being so explicitly labelled as "not secure".  By the way, same thing for www.mrtrix.org ...
