### ISSUE TITLE
Installation issues on MacOS Mojave 

### ISSUE THREAD

**Issue by lvinokur** [MRtrix3/mrtrix3#1488]
I have encountered the following issue trying to install mrtrix on the new MacOS (Mojave, 10.14.01)
I am trying to install the dev branch, updated and also ran the ./configure script prior to building.
./build script generates the following errors:

```
ERROR: (131/413) [CC] tmp/src/gui/dwi/render_frame.o

ERROR: (129/413) [CC] tmp/src/gui/lighting_dock.o

clang++ -c -std=c++11 -DMRTRIX_BUILD_TYPE="release version" -DMRTRIX_MACOSX -fPIC -mmacosx-version-min=10.13 -DMRTRIX_WORD64 -idirafter /opt/local/include -DMRTRIX_TIFF_SUPPORT -idirafter /opt/local/include -DEIGEN_FFTW_DEFAULT -idirafter /opt/local/include -Wall -O3 -DNDEBUG -Isrc -I./core -Icmd -isystem /Users/leavinokur/eigen -DEIGEN_DONT_PARALLELIZE -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.9 -std=gnu++11 -fPIC -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -idirafter /usr/local/Cellar/qt5/5.8.0_1/lib/QtOpenGL.framework/Headers -idirafter /usr/local/Cellar/qt5/5.8.0_1/lib/QtSvg.framework/Headers -idirafter /usr/local/Cellar/qt5/5.8.0_1/lib/QtWidgets.framework/Headers -idirafter /usr/local/Cellar/qt5/5.8.0_1/lib/QtGui.framework/Headers -idirafter /usr/local/Cellar/qt5/5.8.0_1/lib/QtCore.framework/Headers -idirafter /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Headers -idirafter /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AGL.framework/Headers -idirafter /usr/local/Cellar/qt5/5.8.0_1/mkspecs/macx-clang -F/usr/local/Cellar/qt5/5.8.0_1/lib src/gui/lighting_dock.cpp -o tmp/src/gui/lighting_dock.o

failed with output

clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk' [-Wmissing-sysroot]
In file included from src/gui/lighting_dock.cpp:16:
In file included from src/gui/color_button.h:19:
In file included from src/gui/opengl/gl.h:19:
In file included from ./core/mrtrix.h:20:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/cstdio:100:
/Library/Developer/CommandLineTools/usr/include/c++/v1/stdio.h:108:15: fatal error: 'stdio.h' file not found
#include_next <stdio.h>
```

The issue then persists for a few more elements of the ./build items

```
ERROR: (130/413) [CC] tmp/src/gui/projection.o
ERROR: (131/413) [CC] tmp/src/gui/dwi/render_frame.o
```
mrtrix was installed under a similar setup in a previous mac model which also ran 10.13, so this is an attempt to install both on a new physical laptop (which had been migrated from the previous one) and also on the new OS - so I am not sure whether to attribute it to a problematic migration or the new OS. xcode seems so be functional - i will try to test it on my side somehow.

Thanks!
Lea

**Comment by chunhungyeh** [comment]
Hi @lvinokur,

I had no problem installing and running MRtrix3 on Mojave 10.14.1, which was upgraded from High Sierra on my laptop. Looked like your configuration was still using macOS 10.13, likely the result of a direct migration. Have you tried a clean re-installation of MRtrix3 from scratch? I think you also need to upgrade your package manager (``macports`` or ``homebrew``) to the version for Mojave.

Cheers.
Jimmy

**Comment by lvinokur** [comment]
Hi All,
Thanks for the help here - yes I think there are quite a few things to update before I try again :). 
Jimmy you are right - the system was directly migrated from an old mac.
I am now updating Xcode , while Qt was installed from scratch since it had not been migrated properly 

[build.log](https://github.com/MRtrix3/mrtrix3/files/2589010/build.log)
[configure.log](https://github.com/MRtrix3/mrtrix3/files/2589013/configure.log)

I coldn't upload the config file since it is not in a supported  format - should I rename it first ?
Cheers

**Comment by lvinokur** [comment]
OK it works!
What it took:
- updating Xcode
- fixing a typo in the $PATH for the qt directories
- fixing the nonsense in the EIGEN_CFLAGS 

:)

**Comment by jdtournier** [comment]
:+1:
