### ISSUE TITLE
Streamline length calculation

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#1501]
Related to #1185 & marginally to #1153, raised on the [forum](http://community.mrtrix.org/t/tract-lengths/1991).

Calculation of streamline lengths was originally based on the product of (number_of_points - 1) and the step size. Since the introduction of downsampling & GM-WM interface cropping in `tckgen`, which can result in the final step at either end of the streamline being shorter than the step size, any calculations of step size now use the product only for the central section of the streamline, and explicitly calculate the lengths of the first and last segments.

This obviously assumes a constant step size within the central segment, which could be invalidated in a range of scenarios, e.g. various modes of `tckresample`, `tcknormalise`, track data from external softwares.

I'm wondering if the computational speed benefit of using the product of the step size is not really worth the hassle, and it would be better to instead just explicitly calculate the distance between streamline vertices in all instances where a streamline length is required. This would remove the need for the `-explicit` option in `tckstats`, and make the behaviour as expected in all commands regardless of the nature of the data.

**Comment by jdtournier** [comment]
Yes, I'd support that approach - assuming it's not going to become a massive bottleneck for the applications affected... But even if it is, I think there is an argument to say that it's necessary anyway.

**Comment by thijsdhollander** [comment]
Fully support it as well. But just wondering: which applications are these? Not a lot, I guess? tckstats, a few TWI contrasts, maybe a mode somewhere in tck2connectome, ... that's about all I can see off the top of my head. Am I missing something significant? In any case: definitely accuracy over speed here, I reckon.

**Comment by Lestropie** [comment]
+ `afdconnectivity`, `tckedit`, `tckgen`. `tckgen` could potentially still use the fast version, since it's not "receiving" track data and thus has full control; but special handling would be required for the sake of #1153, and also for downsampling (since this reduces the piecewise length; looked briefly into quantifying length of a continuous spline in a non-piecewise fashion but doesn't look easy).

**Comment by thijsdhollander** [comment]
Sounds all good to me. `tckgen` should indeed be able to get around it almost entirely.  For the others, I don't think the impact on the speed is a problem (weighed up against the accuracy).

**Comment by Lestropie** [comment]
Closed by #1507.
