### ISSUE TITLE
`mrinfo`  can't read *.tck file generated by MATLAB code

### ISSUE THREAD

**Issue by meetaig** [MRtrix3/mrtrix3#1508]
Hello,
I am trying to implement writing out *.tck files in my own code using C++. As an example file to see if I am doing it right, I was using the MATLAB function  `write_mrtrix_tracks` provided with mrtrix (in `mrtrix3/matlab/`). My application produces the same file as the MATLAB code (minus some of the bytes given as a placeholder for the raw data offset, which I compute exactly), but I was unable to load it. Then I tested loading the file generated by MATLAB and was surprised to see the following error message:
```
user: matlab $ mrinfo matlab_tracks.tck
mrinfo: [ERROR] unknown format for image "matlab_tracks.tck"
mrinfo: [ERROR] error opening image "matlab_tracks.tck"
```
Which is surprising, because the file is generated with mrtrix code, not my own. Could there be a bug in said file? In the documentation it states, that the `file` and `datatype` fields are the only required ones. TCKGEN on the other hand writes a lot more information into the header. Is there an additional required field that was left out of the documentation? Loading the data in `mrview` does not do anything, not even show the error message above. So it seems it simply does not draw anything into the view.

Here is the MATLAB code that I use to generate the file:
```
tracks = struct;
tracks.data = {...
[[6, 7, 2];...
[6, 7, 3];...
[6, 7, 4];...
[6, 7, 5];...
[6, 7, 6];...
[6, 7, 7];...
[6, 7, 8];...
[6, 7, 9];...
[6, 7, 10];...
[6, 7, 11]]};
write_mrtrix_tracks(tracks, 'matlab_tracks.tck');
```
This is obviously test data, so the values don't mean anything. Nonetheless, I am a but confused on what I am doing wrong. Is there an extra requirement for how the triples must be written? Is the initial offset of 20 (in line 27 of the `write_mrtrix_tracks` file) of any significance, other than providing up to 7 digits (minus the characters needed for newlines, spaces and key values) for the number of bytes for the header?

Any pointers in what goes wrong would be appreciated :)

- meetaig

**Comment by maxpietsch** [comment]
You're looking for `tckinfo`: https://mrtrix.readthedocs.io/en/latest/reference/commands/tckinfo.html

**Comment by meetaig** [comment]
I was in fact looking for that, yes! Thank you!. Any suggestions why the track does not show up in the tractography plot?

**Comment by jdtournier** [comment]
> Any suggestions why the track does not show up in the tractography plot?

Are you sure it doesn't show up? It's quite hard to spot, depending on the image you're displaying it alongside. You need to have an image open first for the viewer to set its viewport, and then the tracks should show up OK - but you may also need to fish around for them, due to the default crop-to-slab behaviour. Try ticking off the crop-to-slab tick-box from the tractography tool so you can find it easily.

I just tried your code on my Win10 laptop, and then displayed your single streamline using:
```
mrview image.mif  -tractography.load matlab_tracks.tck -tractography.slab -1 -focus 6,7,8 -plane 0
```
and it shows up as expected...

**Comment by meetaig** [comment]
Ah, the crop to slab thing was apparently the problem, as well as that I assumed the origin to be in the bottom right corner (or whatever the 3d equivalent is). I centered the coordinates and it worked just fine! Thanks for the pointers!
