### ISSUE TITLE
macOS Mojave dark mode issues

### ISSUE THREAD

**Issue by bjeurissen** [MRtrix3/mrtrix3#1520]
On macOS Mojave, dark mode was introduced. Using Qt version < 5.12, this results in text and background having the same colour sometimes, making the text completely illegible.

The good news is that updating to Qt 5.12 fixes those issues, resulting in a good dark mode experience.

However, there is one area where text to background contrast is not optimal and that is the text next to the buttons in the button bar:
![screenshot 2018-12-15 at 11 17 36](https://user-images.githubusercontent.com/5675416/50041988-9697cc80-005d-11e9-996d-f10382181b85.png)

Not sure if this is something that we can/need to fix ourselves or something that will fix itself over time. Is there something different with the text setup for the button bar?

**Comment by jdtournier** [comment]
We don't do anything particularly exotic on that front. [This is where the the top bar is set up](https://github.com/MRtrix3/mrtrix3/blob/master/src/gui/mrview/window.cpp#L325L332) (menus are added as buttons with drop down menus). This one is up to Qt, I reckon...

**Comment by bjeurissen** [comment]
That looks indeed harmless, there is nothing related to colour there... It's indeed up to Qt.

**Comment by cmpetty** [comment]
Just to add something quickly that i've noticed using dark mode.  I can no longer see any of the values in the side-bar text input fields.  You can see in the screenshot where i've selected the text on FOV.  The values are there, just appear to be white font on white text input background color.

this is with the following, both from homebrew:
qt: stable 5.12.2 (bottled), HEAD [keg-only]
mrtrix3/mrtrix3/mrtrix3: stable 3.0_RC3-157-gf74685cd  

![Screen Shot 2019-05-07 at 12 24 20 PM](https://user-images.githubusercontent.com/2243287/57316325-85f6fa00-70c3-11e9-886c-c527b6651621.png)
