### ISSUE TITLE
5ttgen fsl error "Command failed: fast T1_BET.nii.gz"

### ISSUE THREAD

**Issue by RajanikantPanda** [MRtrix3/mrtrix3#1538]
Hello,
I am running 5ttgen using this command- 5ttgen fsl T1.nii 5ttseg.mif

I am getting the fallowing error:
```
5ttgen: [ERROR] Command failed: fast T1_BET.nii.gz (fsl.py:143)
5ttgen: Output of failed command:
        Image Exception : #3 :: Attempted to multiply images of different sizes
        terminate called after throwing an instance of 'armawrap::AWException'
          what():  Attempted to multiply images of different sizes
```

[5ttgen error.docx](https://github.com/MRtrix3/mrtrix3/files/2783503/5ttgen.error.docx)

Debuging error attached.

Any help would be greatly appreciated
Raja

**Comment by RajanikantPanda** [comment]
Hello,

I have solved this issues. Below I describe how I fixed it, may be some one get useful: 

I have checked my image "T1_BET.nii.gz" and found its a valid image. Then I ran " fast T1_BET.nii.gz " and found same error. 
Finlay I realize it was the problem of my current FSL (version 6.0.0), hence I re install one of previous FSL (FSL 5.0.11 version) using this command “ python fslinstaller.py -V 5.0.1 ” . This solve the above issue.

But I face another error states:
Command: fsl5.0-run_first_all -m none -s L_Accu,R_Accu,L_Caud,R_Caud,L_Pall,R_Pall,L_Puta,R_Puta,L_Thal,R_Thal -i T1.nii -o first
5ttgen: [ERROR] FSL FIRST has failed; only 0 of 10 structures were segmented successfully (check /media/panda/PC_RAJ/fMRI/DTItest/Subjects/subj_02/Outputs/5ttgen-tmp-2FEOA4/first.logs)

This was because in my fsl, fsl-first-data files were not there. Which i installed from neurodebin from bellow link.

http://neuro.debian.net/install_pkg.html?p=fsl-first-data

Now I am able to run 5ttgen successfully. 
Thank you
Raja

**Comment by jdtournier** [comment]
Glad to hear it!

**Comment by Lestropie** [comment]
> Finally I realize it was the problem of my current FSL (version 6.0.0)

That's unusual; I've run these scripts on FSL6 without encountering this specific issue...

> This was because in my fsl, fsl-first-data files were not there. 

Again unusual: the script specifically [checks](https://github.com/MRtrix3/mrtrix3/blob/master/lib/mrtrix3/_5ttgen/fsl.py#L52-L54) for the presence of that data before executing. This would suggest that perhaps FSL6 is generating that directory even if it is not acquiring the data with which to fill it. If anybody else manages to encounter the same set of circumstances I'd be curious to know whether this is in fact the case, as it would indicate that the pre-execution check for the FIRST atlas data needs to be revised.
