### ISSUE TITLE
Stable 3.0.0 release?

### ISSUE THREAD

**Issue by duncanmmacleod** [MRtrix3/mrtrix3#1539]
I'm wondering if a stable 3.0.0 release is pending? It seems the RC series has been going for a while.

**Comment by Lestropie** [comment]
:see_no_evil: :speak_no_evil: :hear_no_evil: 

Jokes aside: Yes, we do need to tie this off. One of the milestones for that was submission of a manuscript, which was completed a week ago. The main things we need to address now are release mechanisms (#902): there's a `pacman` package for Windows MSYS2 that needs testing, we want pre-compiled binaries on GitHub, there's some proposed containers (#1522, #1372), and we need to liaise with platforms like NeuroDebian. Anyone in the userbase with experience in any of these aspects is more than welcome to assist :crossed_fingers:

**Comment by thijsdhollander** [comment]
> It seems the RC series has been going for a while.

Yep, that said, don't get your hopes up for significant changes beyond what has come your way via those RCs though; apart from mostly pre-compiled binaries.  I get this question a lot from people assuming that MRtrix3 isn't "stable" yet, and will suddenly be much more stable when "release" happens; that's definitely not the case: it's been pretty stable for a long time, and new features as well as bug fixes of the kind of those that came via RCs (as well as hot fixes for bugs between RCs) will still be happening in a very similar fashion after "release" for sure.  See, e.g., this community forum thread: http://community.mrtrix.org/t/mrtrix-3-release/1403 .

So well, in summary: don't expect the level of stability to change significantly on the moment that at some point will be known/labelled as "release".

**Comment by duncanmmacleod** [comment]
My interest is just in getting a blessed reference point from which to build a conda package for `conda-forge`, which doesn't support pre-releases. This all sounds very promising, thanks.

For the interested reader: the conda recipe is ready, and provides separate C and Python library packages. I also have debian packaging experience, but not a lot of free time.

**Comment by jdtournier** [comment]
@duncanmmacleod: just to keep you in the loop, we discussed this recently, and settled on the following strategy:

- one more release candidate, to be released in the next few weeks.
- a couple of months of community testing
- full 3.0 release

The main outstanding issues will relate to binary distribution, so if you're willing to contribute with a conda package, that's actually a huge help for us - distribution on Linux in particular is a real headache, so it's great to know projects like this are on board.

**Comment by gdevenyi** [comment]
How's that "one more release candidate" coming? Its been almost a year since the last one.

**Comment by jdtournier** [comment]
😂😭 still working on it... Plan is to release once we've worked our way through the list in [this milestone](https://github.com/MRtrix3/mrtrix3/issues?q=is%3Aopen+is%3Aissue+milestone%3A"3.0_RC4+release")...

**Comment by Lestropie** [comment]
Closed by #2021.
