### ISSUE TITLE
Simplify CI for merging to dev

### ISSUE THREAD

**Issue by jdtournier** [MRtrix3/mrtrix3#1559]
Given the high frequency of testing failures on AppVeyor at the moment, I think we need to re-think our approach. The CI takes ages and times out routinely, which is a bit of a bottleneck for development. I don't think we should get rid of the testing for merges to `master` - we need to know that all the tests pass on that branch. But I think there is scope for simplifying and speeding things up quite a bit for merges to `dev`. 

The main thing I'd like to ensure is that a full configure - build - test cycle has been run on the code before merging to `dev`. I'd like to find a way to allow developers to run these checks and record success on their own systems, and this would then be sufficient to merge to `dev`. This should catch the bulk of important errors. It would also be nice to run the `pylint` and `sphinx` tests too, but it can be a bit of a pain for developers to set up the environment for that (not that hard though). 

I've been thinking about ways to do this with guarantees, but I don't think it can be done: if we allow devs to run the tests, there is no way I can think of that would guarantee no-one can fake a successful outcome. I'm not sure that's a serious problem though: we have to rely on some level of trust, and the problematic changes will rapidly get picked up as soon as another developer tries to merge their changes with them. It would also probably provide for a more heterogeneous testing environment than we currently have, which I reckon is not a bad thing: issues specific to some architecture won't be picked up every time, but they will be picked up over time. And any merge to `master` will have to undergo the full CI testing on the servers anyway.

My idea would be to have a script that runs everything we need to verify, including merging to `dev`, etc. and records the outcome to the repo in some way. The simplest way to do this would be to commit the outcomes to a file with filename set to the SHA1 of the merge commit on an otherwise empty branch of the repo (so it doesn't interfere with the SHA1 of the commit we're trying to merge). All we'd need to do in the CI is verify that a file exists on that branch with a filename matching the SHA1 of the merge commit being tested. The commit message would also record the architecture and any other relevant information that we might like to consult later (the user and time are recorded as part of the commit anyway). 

The advantage there is that devs can run all the tests on their local system (which is typically much quicker than the CI servers) and fix any issues before they even push to the repo. So by the time the PR is created, it would be ready to merge within minutes (just long enough for the CI instance to spin up). 

At the moment, this is just an idea that I've been mulling over for a while, but I thought I'd voice it to gauge whether there's any support for it. I'll try to mock something up for it over the next few days / weeks...

**Comment by Lestropie** [comment]
Feels like solving the wrong problem to me. We're not exactly at the worldwide cutting-edge of software engineering and being the first enlightened ones to discover that CI is not the right solution, because one specific service happens to enforce a job duration limit (which it looks like it might be [possible to extend on request](https://help.appveyor.com/discussions/questions/24498-options-for-splitting-up-build-custom-tests#comment_45889948)), which occasionally interferes with our maybe 1-2 PRs a week average. Feels to me like removing it would be a substantial backwards step. I'd rather address AppVeyor as AppVeyor, and redirect the effort from here to other things.

**Comment by thijsdhollander** [comment]
Hmm, I reckon I mostly side with Rob on this one.  This all sounds really complicated (overkill?) to me...  Not sure I'm a big fan of that.  As Rob mentions, it's really just AppVeyor in it's current form / setup / whatever / ... that frustrates an efficient workflow (and thus me / us at times; see https://github.com/MRtrix3/mrtrix3/pull/1449#issuecomment-460583758 and beyond).
TravisCI, on the other hand, works very well now, I reckon.  There's only one job that does a full run, and thus takes a little bit longer than the other jobs.  But, with the functionality of being able to restart individual jobs, it's easy to restart if something goes wrong (and lately, I haven't seen that happen anymore at all).

So well, I reckon focus should be on AppVeyor here: what can we do to deal with that?

1. Is it *really*, ***really***, even necessary *at all*?
2. Might it be possible to only require AppVeyor (in addition to TravisCI) for merges to `master`?  Or is it not possible to define different "levels" of testing for different branches?
3. If all above fails, can the job duration limit be extended?  Or can we somehow split things up in different jobs?  Other creative solutions?

**Comment by thijsdhollander** [comment]
...or even, you know, just switch of AppVeyor for 2-3 weeks while we process most pull requests to do with RC4, and then switch it on again before things go to `master`.  Yeah, it's ad hoc; but it works.

**Comment by daljit46** [comment]
@MRtrix3/mrtrix3-devs can we close this one? It doesn't seem relevant anymore. Our CI workflow is decently fast now and once we merge the changes in #2877, it will be even faster.
