### ISSUE TITLE
ROI tool - once you start to edit a ROI, interpolation of the background image no longer toggles

### ISSUE THREAD

**Issue by draffelt** [MRtrix3/mrtrix3#158]

**Comment by jdtournier** [comment]
I've also noticed this in a number of different contexts. I have a feeling it'll have something to do with keyboard focus going to some specific widget rather than the main application window, but I haven't had a chance to investigate this seriously yet...

**Comment by rtabbara** [comment]
I can no longer replicate this problem. I think the fix for #173 also sorted out this issue, but just want to check with everyone else before we close it off.

**Comment by rtabbara** [comment]
*bump*

**Comment by jdtournier** [comment]
Seems fine to me... Let's close.
