### ISSUE TITLE
connectome2tck -exemplars segfaults when highest index node in parcellation has no track assignment

### ISSUE THREAD

**Issue by SyamGadde** [MRtrix3/mrtrix3#1581]
connectome2tck.cpp calculates the value ``max_node_index`` by finding the maximum index in the assignments file.  However, if the highest ROI index in the "exemplar" parcellation image does not appear in the assignment file (i.e. no tracks hit that region), then the application segfaults.  Or if compiled with -debug, it fails earlier at the assertion
```
        assert (index <= max_node_index);
```

My workaround is to detect this issue beforehand by finding the maximum value in the assignments file and thresholding the parcellation to that value, but it would be good to fix.  It may be a matter of simply adjusting max_node_index if a higher value is seen in the exemplar image, but there may be a more appropriate fix.

Thanks!

**Comment by Lestropie** [comment]
Talk about an obscure use case :rofl: 

Thanks for the concise and clear report @SyamGadde :+1:  I think your suggested fix is the way to go, as long as the user is warned about such (as those maximum indices differing may indicate that a more egregious user error has been made). Fix is coming in #1582.
