### ISSUE TITLE
Mrtrix overlooks FSLDIR when a default installation is available

### ISSUE THREAD

**Issue by gagdiez** [MRtrix3/mrtrix3#1587]
I found that the 'if' in lines 77 to 78 in the file [fsl.py](https://github.com/MRtrix3/mrtrix3/blob/master/lib/mrtrix3/fsl.py#L77-L78) can result in mrtrix overlooking a user-installation of FSL, and eventually failing (see [this post](http://community.mrtrix.org/t/5ttgen-fsl-error-solved/2407)).

This happens for example when the computer has an old/obsolete yet default installation of FSL in /usr/bin, which is a common situation in most research institutions. Since on the computer, the executable '/usr/bin/fsl5.0-fast' exists, then it is used instead of '$FSLDIR/bin/fast'.

This ends up completely overlooking the user-installation of FSL since scripts as fsl5.0-fast have the following code inside:

 ```
# Set up the FSL paths if necessary                                             
# do not allows user-override, as this wrapper is used via                      
# versioned symlinks                                                            
 . /etc/fsl/5.0/fsl.sh  
```                                                         

We can solve this problem by checking if FSLDIR is set up, and in the affirmative case, using the binaries from it. 

I can help with the code for the patch if necessary.

Best,
Guillermo.

**Comment by Lestropie** [comment]
This *should* be rectified in #1459. We however chose to not push this change directly to `master` at the time, as it would potentially silently alter behaviour. So the underlying executable selection will change when `dev` gets merged into master, which will be [3.0_RC4](https://github.com/MRtrix3/mrtrix3/milestone/5). Assuming this change still stays in `dev`, the more direct solution would I suppose be to "clean up" any obsolete FSL installation(s) at your end. But maybe we should throw out an announcement on the forum just in case the behaviour is affecting anybody else and they haven't realised.
