### ISSUE TITLE
ROI tool: multiple selection

### ISSUE THREAD

**Issue by fsadeghian** [MRtrix3/mrtrix3#162]
Hi mrtrixers,

In new ROI tool, there is no feature of selecting all/some opened ROIs at the same time. It is a handy option to have if is possible. I noticed it as a lack of current version in my pretty much first use of ROI tool bar.  

Thanks,
Farnoosh

**Comment by maxpietsch** [comment]
Still within than one year between feature request and implementation :) @fsadeghian, I hope this is what you had in mind.

**Comment by maxpietsch** [comment]
Reverted as discussed in #372 as it causes more problems than it solves.
