### ISSUE TITLE
configure & gsl-config weirdness

### ISSUE THREAD

**Issue by jdtournier** [MRtrix3/mrtrix3#163]
On some systems, `./configure` mysteriously falls over at the GSL detection stage. It turns out this is caused by `gsl-config` returning a non-ASCII string, instead producing a multi-byte version of the string (I've seen 2 bytes/character and 4 bytes/character). Essentially this consists of a string where each (ASCII) character is separated 1 or 3 binary zero bytes...

I have no idea why `gsl-config` would do this. It's a simple shell script, and the same script copied over to an unaffected system behaves as expected. There must be some translation happening somewhere between `gsl-config` writing to its stdout stream, and that data being piped into `configure` (via Python's subprocesss.Popen() call), but I'm out of ideas for what that could be and what triggers it...

One simple fix would be to filter out zero bytes from the string returned by `gsl-config`, which would probably work for the majority of cases (most encodings preserve the ASCII codes for the first 127 characters, it seems), but will probably fail eventually. It would really be preferable to understand what is actually going on...

Suggestions / insights / actual solutions welcome...

**Comment by jdtournier** [comment]
OK, I've just come across [one StackOverflow post](http://stackoverflow.com/a/18717024) that comes close to explaining this behaviour... I'll investigate with the people affected.

**Comment by jdtournier** [comment]
@davesl: any chance you could see whether this commit fixes the issues you were having with the configure script...?

**Comment by davesl** [comment]
Hi Donald,

Apologies for not replying sooner, I was in China and didn't fully
appreciate how blocked google would be.

I'm back in the lab now so I will test everything again this week and
update you. I'll also try to add a few paragraphs of descriptions to the
wiki in order to help others.

Best,
David

**Comment by jdtournier** [comment]
@davesl : any chance we can close this off...? Thanks! Donald.

**Comment by davesl** [comment]
I've re-tested the ./package_mrtrix -standalone process after using git pull and then HPC transfer. It looks like everything is working correctly.

I'm running a full pipeline test which should be finished by tomorrow morning. However the basic dwi2response, dwi2fod, tckgen etc. commands have all run without issue.

I think you can close this off and assume that it's working. The qsub script is also working well. I will write a brief description of the HPC install and job running process on the wiki.

Best,
D

**Comment by jdtournier** [comment]
Good to hear, thanks!
