### ISSUE TITLE
What to do about spaces in header entries with spaces in keys?

### ISSUE THREAD

**Issue by jdtournier** [MRtrix3/mrtrix3#1633]
This affects images produced by `fixelcfestats`, as [discussed here](http://community.mrtrix.org/t/error-with-read-mrtrix/2628). 

I think we'll need to improve the MatLab handling (clearly there's no issues with handling these within the C++ code), but I also think it might be better to avoid spaces in key names in general, and modify `fixelcfestats` to avoid spaces in the first place. This should be OK to do, as far as I can tell, these headers entries are not queried anywhere else in the code.

Thoughts?

**Comment by Lestropie** [comment]
I'd do both: Fix the MatLab handling on `master`, and remove the the spaces from header keys at write time on `dev`.
