### ISSUE TITLE
mrview: keyboard shortcuts on macos

### ISSUE THREAD

**Issue by maxpietsch** [MRtrix3/mrtrix3#1641]
On opening an image, keyboard shortcuts work but once a tool (view tool for instance) is or was opened they stop working. This behaviour can also be triggered from the command line without opening a tool menu: `mrview 1.mif -overlay.load 2.mif`. 

Opening a popup window (`info-->about Qt`) or expanding the tool to multi-window layout brings back the keyboard shortcuts. Opening a tool docked inside the side bar of the main window removes the shortcuts again irrespective of an open popup window.

Switching between already opened (docked) tools has no effect on the shurtcuts.

Tested with c5c7f9c81037c445892f0, Qt 5.12.0.

**Comment by maxpietsch** [comment]
This is still an issue with Qt 5.14.0

**Comment by jdtournier** [comment]
I assume this was fixed with #1877...?
