### ISSUE TITLE
dwigradcheck doesn't respect -force flag

### ISSUE THREAD

**Issue by soichih** [MRtrix3/mrtrix3#1647]
We are running dwigradcheck command with -force flag to override already existing output file.

```
dwigradcheck raw1.mif -grad raw1.b -mask ${mask}.mif -export_grad_mrtrix cor1.b -tempdir ./tmp -force -nthreads $NCORE -quiet

```

However, this command fails if the output file (cor1.b in this case) already exist.

```
...
dwigradcheck: [ERROR] Command failed: mrinfo data.mif -grad grad_flipnone_perm012_scanner.b -export_grad_mrtrix /mnt/disks/sec/prod/5d2e1b4278d9fa1cee2aa79d/5d2e89cb78d9fa1cee2af416/cor1.b (dwigradcheck:212)
dwigradcheck: Output of failed command:
              mrinfo: [ERROR] output file "/mnt/disks/sec/prod/5d2e1b4278d9fa1cee2aa79d/5d2e89cb78d9fa1cee2af416/cor1.b" already exists (use -force option to force overwrite)
dwigradcheck: Script failed while executing the command: mrinfo data.mif -grad grad_flipnone_perm012_scanner.b -export_grad_mrtrix /mnt/disks/sec/prod/5d2e1b4278d9fa1cee2aa79d/5d2e89cb78d9fa1cee2af416/cor1.b
dwigradcheck: For debugging, inspect contents of temporary directory: /mnt/disks/sec/prod/5d2e1b4278d9fa1cee2aa79d/5d2e89cb78d9fa1cee2af416/tmp/dwigradcheck-tmp-BEUH1D/
```

**Comment by Lestropie** [comment]
Hi @soichih,

Thanks for the very clear and concise report. Following merge of #1648, the issue will be resolved by pulling in the latest version of the `master` branch.

Rob

**Comment by soichih** [comment]
Thanks @Lestropie ! 

I just noticed a similar issue with mrdegibbs also.

**Comment by Lestropie** [comment]
It would be quite unusual for such an issue to occur in a C++ command. Being a Python script, `dwigradcheck` requires a more explicit handling of the `-force` command-line option, as shown in the [diff for #1648](https://github.com/MRtrix3/mrtrix3/pull/1648/files); whereas for `mrdegibbs`, the use of the `-force` option is managed quite deeply within the image handling API. Can you post the full command usage, as well as the version of *MRtrix3* (`mrdegibbs -version`)?

**Comment by soichih** [comment]
Sorry yes, I think I've misinterpreted some error message from mrdegibbs (or maybe it wasn't mrdegibbs..)
