### ISSUE TITLE
Error with bulid in Mac

### ISSUE THREAD

**Issue by Heechberri** [MRtrix3/mrtrix3#1667]
Hi,

I am trying to follow the installation guild @ https://mrtrix.readthedocs.io/en/latest/installation/mac_install.html, and I have reached the step ./build which I encountered the below error.

 

> MRtrix build type requested: release
> 
> Detecting OS: darwin
> OS X deployment target: 10.14
> Checking for C++11 compliant compiler [clang++]: 4.2.1 - tested ok
> Detecting pointer size: 64 bit
> Detecting byte order: little-endian
> Checking for variable-length array support: yes
> Checking for non-POD variable-length array support: yes
> Checking for zlib compression library: 1.2.11
> Checking for Eigen 3 library: 3.3.90
> Checking Eigen 3 memory alignment requirements: OK
> Checking shared library generation: yes
> Checking for Qt moc: moc (version 5.13.0)
> Checking for Qt qmake: qmake (version 5.13.0)
> Checking for Qt rcc: rcc (version 5.13.0)
> Checking for Qt: 5.13.0
> writing configuration to file './release/config': ok
> 
> c4104421:mrtrix3 revive_imac$ ./build
> (  2/443) [CC] release/cmd/tckgen.o
> (  1/443) [CC] release/cmd/labelconvert.o
> (  4/443) [CC] release/lib/formats/pipe.o
> (  3/443) [CC] release/cmd/dirmerge.o
> ERROR: (  3/443) [CC] release/cmd/dirmerge.o
> ERROR: (  4/443) [CC] release/lib/formats/pipe.o
> ERROR: (  1/443) [CC] release/cmd/labelconvert.o
> ERROR: (  2/443) [CC] release/cmd/tckgen.o
> 
> ERROR: (  3/443) [CC] release/cmd/dirmerge.o
> 
> clang++ -c -std=c++11 -mno-avx -DMRTRIX_MACOSX -fPIC -mmacosx-version-min=10.14 -DMRTRIX_WORD64 -isystem /Users/revive_imac/eigen-git-mirror -Wall -O2 -DNDEBUG -Isrc -Icmd -I./lib -Icmd -isystem /Users/revive_imac/eigen-git-mirror cmd/dirmerge.cpp -o release/cmd/dirmerge.o
> 
> failed with output
> 
> In file included from cmd/dirmerge.cpp:17:
> In file included from ./lib/command.h:22:
> In file included from ./lib/app.h:28:
> In file included from ./lib/cmdline_option.h:28:
> In file included from ./lib/mrtrix.h:38:
> ./lib/types.h:179:40: error: redefinition of 'Vector3' as different kind of symbol
>   typedef Matrix<MR::default_type,3,1> Vector3;
>                                        ^
> /Users/revive_imac/eigen-git-mirror/Eigen/src/Core/Matrix.h:539:1: note: previous definition is here
> EIGEN_MAKE_TYPEDEFS(3, 3)
> ^
> :...skipping...
> 
> ERROR: (  3/443) [CC] release/cmd/dirmerge.o
> 
> clang++ -c -std=c++11 -mno-avx -DMRTRIX_MACOSX -fPIC -mmacosx-version-min=10.14 -DMRTRIX_WORD64 -isystem /Users/revive_imac/eigen-git-mirror -Wall -O2 -DNDEBUG -Isrc -Icmd -I./lib -Icmd -isystem /Users/revive_imac/eigen-git-mirror cmd/dirmerge.cpp -o release/cmd/dirmerge.o
> 
> failed with output
> 
> In file included from cmd/dirmerge.cpp:17:
> In file included from ./lib/command.h:22:
> In file included from ./lib/app.h:28:
> In file included from ./lib/cmdline_option.h:28:
> In file included from ./lib/mrtrix.h:38:
> ./lib/types.h:179:40: error: redefinition of 'Vector3' as different kind of symbol
>   typedef Matrix<MR::default_type,3,1> Vector3;
>                                        ^
> /Users/revive_imac/eigen-git-mirror/Eigen/src/Core/Matrix.h:539:1: note: previous definition is here
> EIGEN_MAKE_TYPEDEFS(3, 3)
> ^
> /Users/revive_imac/eigen-git-mirror/Eigen/src/Core/Matrix.h:521:67: note: expand:...skipping...
> 
> ERROR: (  3/443) [CC] release/cmd/dirmerge.o
> 
> clang++ -c -std=c++11 -mno-avx -DMRTRIX_MACOSX -fPIC -mmacosx-version-min=10.14 -DMRTRIX_WORD64 -isystem /Users/revive_imac/eigen-git-mirror -Wall -O2 -DNDEBUG -Isrc -Icmd -I./lib -Icmd -isystem /Users/revive_imac/eigen-git-mirror cmd/dirmerge.cpp -o release/cmd/dirmerge.o
> 
> failed with output
> 
> In file included from cmd/dirmerge.cpp:17:
> In file included from ./lib/command.h:22:
> In file included from ./lib/app.h:28:
> In file included from ./lib/cmdline_option.h:28:
> In file included from ./lib/mrtrix.h:38:
> ./lib/types.h:179:40: error: redefinition of 'Vector3' as different kind of symbol
>   typedef Matrix<MR::default_type,3,1> Vector3;
>                                        ^
> /Users/revive_imac/eigen-git-mirror/Eigen/src/Core/Matrix.h:539:1: note: previous definition is here
> EIGEN_MAKE_TYPEDEFS(3, 3)
> ^
> /Users/revive_imac/eigen-git-mirror/Eigen/src/Core/Matrix.h:521:67: note: expanded from macro 'EIGEN_MAKE_TYPEDEFS'
> template <typename Type>                                          \
>                                                                   ^
> In file included from cmd/dirmerge.cpp:17:
> In file included from ./lib/command.h:22:
> In file included from ./lib/app.h:28:
> In file included from ./lib/cmdline_option.h:28:
> In file included from ./lib/mrtrix.h:38:
> ./lib/types.h:180:40: error: redefinition of 'Vector4' as different kind of symbol
>   typedef Matrix<MR::default_type,4,1> Vector4;
>                                        ^
> /Users/revive_imac/eigen-git-mirror/Eigen/src/Core/Matrix.h:540:1: note: previous definition is here
> EIGEN_MAKE_TYPEDEFS(4, 4)
> ^
> /Users/revive_imac/eigen-git-mirror/Eigen/src/Core/Matrix.h:521:67: note: expanded from macro 'EIGEN_MAKE_TYPEDEFS'
> template <typename Type>                                          \
>                                                                   ^
> 2 errors generated.
> 
> ERROR: (  4/443) [CC] release/lib/formats/pipe.o
> 
> clang++ -c -std=c++11 -mno-avx -DMRTRIX_MACOSX -fPIC -mmacosx-version-min=10.14 -DMRTRIX_WORD64 -isystem /Users/revive_imac/eigen-git-mirror -Wall -O2 -DNDEBUG -Isrc -Icmd -I./lib -Icmd -isystem /Users/revive_imac/eigen-git-mirror lib/formats/pipe.cpp -o release/lib/formats/pipe.o
> 
> failed with output
> 
> In file included from lib/formats/pipe.cpp:16:
> In file included from ./lib/file/utils.h:25:
> In file included from ./lib/app.h:28:
> In file included from ./lib/cmdline_option.h:28:
> In file included from ./lib/mrtrix.h:38:
> ./lib/types.h:179:40: error: redefinition of 'Vector3' as different kind of symbol
>   typedef Matrix<MR::default_type,3,1> Vector3;
>                                        ^
> /Users/revive_imac/eigen-git-mirror/Eigen/src/Core/Matrix.h:539:1: note: previous definition is here
> EIGEN_MAKE_TYPEDEFS(3, 3)
> ^
> /Users/revive_imac/eigen-git-mirror/Eigen/src/Core/Matrix.h:521:67: note: expanded from macro 'EIGEN_MAKE_TYPEDEFS'
> template <typename Type>                                          \
>                                                                   ^
> In file included from lib/formats/pipe.cpp:16:
> In file included from ./lib/file/utils.h:25:
> In file included from ./lib/app.h:28:
> In file included from ./lib/cmdline_option.h:28:
> In file included from ./lib/mrtrix.h:38:
> ./lib/types.h:180:40: error: redefinition of 'Vector4' as different kind of symbol
>   typedef Matrix<MR::default_type,4,1> Vector4;
>                                        ^
> /Users/revive_imac/eigen-git-mirror/Eigen/src/Core/Matrix.h:540:1: note: previous definition is here
> EIGEN_MAKE_TYPEDEFS(4, 4)
> ^
> /Users/revive_imac/eigen-git-mirror/Eigen/src/Core/Matrix.h:521:67: note: expanded from macro 'EIGEN_MAKE_TYPEDEFS'
> template <typename Type>                                          \
>                                                                   ^
> 2 errors generated.
> 
> ERROR: (  1/443) [CC] release/cmd/labelconvert.o
> 
> clang++ -c -std=c++11 -mno-avx -DMRTRIX_MACOSX -fPIC -mmacosx-version-min=10.14 -DMRTRIX_WORD64 -isystem /Users/revive_imac/eigen-git-mirror -Wall -O2 -DNDEBUG -Isrc -Icmd -I./lib -Icmd -isystem /Users/revive_imac/eigen-git-mirror cmd/labelconvert.cpp -o release/cmd/labelconvert.o
> 
> failed with output
> 
> In file included from cmd/labelconvert.cpp:19:
> In file included from ./lib/command.h:22:
> In file included from ./lib/app.h:28:
> In file included from ./lib/cmdline_option.h:28:
> In file included from ./lib/mrtrix.h:38:
> ./lib/types.h:179:40: error: redefinition of 'Vector3' as different kind of symbol
>   typedef Matrix<MR::default_type,3,1> Vector3;
>                                        ^
> /Users/revive_imac/eigen-git-mirror/Eigen/src/Core/Matrix.h:539:1: note: previous definition is here
> EIGEN_MAKE_TYPEDEFS(3, 3)
> ^
> /Users/revive_imac/eigen-git-mirror/Eigen/src/Core/Matrix.h:521:67: note: expanded from macro 'EIGEN_MAKE_TYPEDEFS'
> template <typename Type>                                          \
>                                                                   ^
> In file included from cmd/labelconvert.cpp:19:
> In file included from ./lib/command.h:22:
> In file included from ./lib/app.h:28:
> In file included from ./lib/cmdline_option.h:28:
> In file included from ./lib/mrtrix.h:38:
> ./lib/types.h:180:40: error: redefinition of 'Vector4' as different kind of symbol
>   typedef Matrix<MR::default_type,4,1> Vector4;
>                                        ^
> :

any idea how I can fix this?

Thank you!
Regards,
Vae

**Comment by bjeurissen** [comment]
I have the impression you are using an unstable version of eigen (with a release number greater than the latest stable release 3.3.7). How did you install eigen?

**Comment by Heechberri** [comment]
Hi,

Thanks for getting back to me!

I tried to run brew install eigen and I was notified that It was already
previously installed on the computer, perhaps as a part of an installation
for another program. Should I reinstall it? would it affect other programs
that also need it?

**Comment by bjeurissen** [comment]
I have checked, and eigen 3.3.90 is indeed the unstable code from the development branch. Instead you have to use the latest stable version of eigen which is 3.3.7.

I think this means you previously installed eigen using the ``--HEAD`` or ``--devel`` option of ``brew``. I would remove eigen using ``brew uninstall eigen`` and then install it again with ``brew install eigen``. Given that eigen is a template library, I don't think this will affect any of your installed programs. Also, it is highly unlikely that there are any applications out there that specifically rely on the development version of eigen.

**Comment by Heechberri** [comment]
Hi,

I see. So I should uninstall the current version and  reinstall 3.3.7?

**Comment by bjeurissen** [comment]
I don't use brew myself, so maybe @maxpietsch or @dchristiaens can pitch i

Potentially 3.3.7 is already installed, but just not activated.

If you run
```
brew info eigen3
```
it should list the installed versions.

If 3.3.7 is already installed, you can activated it with

```
brew switch eigen 3.3.7
```
Otherwise you will have to install 3.3.7 and potentially also activate it using ``brew switch``

**Comment by bjeurissen** [comment]
Btw, issues like this typically get sorted by posting on the community forum: http://community.mrtrix.org. 

Github issues are typically only filed if you think there is an error in the software or an important feature missing or if you think something can be improved.

**Comment by maxpietsch** [comment]
```
brew unlink eigen
brew install eigen
```

**Comment by Heechberri** [comment]
Hi all,

thanks for the help!

I have managed to solve the problem. I discovered that I also typed in the
wrong file location (pointing to the unstable eigen release) when I was
setting the CFLAG variable for eigen. Now everything seems to be installed
and working. If I have any problems in the future I will post it to the
suggested link on top.

Thanks!
