### ISSUE TITLE
linear interpolation introduces bright edge?

### ISSUE THREAD

**Issue by maxpietsch** [MRtrix3/mrtrix3#1681]
Not sure if this is a bug. Does it make sense that linear interpolation introduces bright edges adjacent to zeros? Also, this behaviour seems to be direction-dependent.

```
$ mrcheckerboardmask im.mif chm.mif
$ cat r.txt
0.99503719020999 0.0995037190209989 7.61558355706674e-19 0
-0.0993921550997974 0.993921550997974 -0.0473407854434019 0
-0.00471058421299366 0.0471058421299366 0.998878796468121 0
0 0 0 1

$ mrcat \
   $(mrcalc im.mif chm.mif -mult - | mrtransform - -linear r.txt -template im.mif -) \
   $(mrtransform im.mif -linear r.txt -template im.mif -) \
   $(mrcalc chm.mif im.mif nan -if - | mrtransform - -linear r.txt -template im.mif -) \
   $(mrtransform chm.mif -linear r.txt -template im.mif -interp nearest -) - | mrview -
```
volume 1-4:
![screenshot0000](https://user-images.githubusercontent.com/10046944/63291887-64a9ca80-c2bc-11e9-87c7-004d5467d61d.png)
![screenshot0001](https://user-images.githubusercontent.com/10046944/63291888-64a9ca80-c2bc-11e9-9bdc-3b17125c4481.png)
![screenshot0002](https://user-images.githubusercontent.com/10046944/63291889-64a9ca80-c2bc-11e9-8efc-835b5f4170dc.png)
![screenshot0003](https://user-images.githubusercontent.com/10046944/63291890-65426100-c2bc-11e9-9aa9-5ca1c5ce51f9.png)

`mrcalc \
  $(mrcalc im.mif chm.mif -mult - | mrtransform - -linear r.txt -template im.mif -) \
   $(mrtransform im.mif -linear r.txt -template im.mif -) -sub - | mrview - `:

![cbm_minus_im0000](https://user-images.githubusercontent.com/10046944/63293400-f6ff9d80-c2bf-11e9-83ca-b47d018f6ca9.png)

**Comment by jdtournier** [comment]
I'm not sure I'm following. None of the commands you posted use a non-default interpolator - I don't see the `-interp` option anywhere other than to regrid the checkerboard itself with nearest-neighbour. The default interpolator is cubic, and I'm pretty sure that should result in some overshoot near edges. What happens if you add the `-interp linear` option to your `mrtransform` calls?

**Comment by thijsdhollander** [comment]
It's just cubic interpolation by default... there's not only "bright" edges, but you can see the undershoot as well in some of the presented images.  I'm not really seeing evidence of direction dependence either; I think it's just the particular transform you used: such slight rotations can have that particular "visual effect" I think you might be observing.

**Comment by maxpietsch** [comment]
Ok, I assumed linear was the default interpolator in `mrtransform` (as in `mrregister`). Overshoot goes away with `-interp linear`.
