### ISSUE TITLE
foreach: foreach is a shell reserved word in zsh

### ISSUE THREAD

**Issue by bjeurissen** [MRtrix3/mrtrix3#1708]
`foreach` is a reserved keyword in zsh, which makes our script with the same name only available as `command foreach`. This is not a huge deal, but we should be aware that on future macos versions, zsh will become the default shell instead of bash (https://support.apple.com/en-ca/HT208050?fbclid=IwAR0Z1-TK9h3oInv_byv9fDa9EbxxxZoqSaI4Osfq5_fxDi7jXvKjS3YAKvk). Maybe we should consider renaming `foreach` to something slightly more exotic?

**Comment by Lestropie** [comment]
:grimacing:

**Comment by maxpietsch** [comment]
- feach, for_each
- fordo
- applyto
- lsdo
- iterdo
- map
- itermap
- listmap
- seqmap

**Comment by maxpietsch** [comment]
Any opinions on what to rename `foreach` to?

**Comment by Lestropie** [comment]
Given existing user familiarity, and the absence of an unambiguous better solution, I'm probably leaning towards `for_each`.
