### ISSUE TITLE
MRView: rendering of streamlines with proper transparency

### ISSUE THREAD

**Issue by jdtournier** [MRtrix3/mrtrix3#177]
One of the features we lost in this version of MRView is the ability to render tracks with proper transparency. This is because the approach taken in the previous version was a bit of a hack and scaled badly. It would be good to sort this out with proper order-independent transparency techniques.

The big issue here is that rendering transparent objects normally requires you to render back to front, so that each layer only affects the layers below. When rendering ~1 million tracks, it is pretty much impossible to do this. Even one streamline has the potential to double back on itself depending on the viewpoint. The approach taken in the previous incarnation of MRView was to break up the streamlines into points, sort them by depth in eye coordinates (on the CPU), and render the lot in that order. Clearly, there were lots of issues with performance, and the point-wise display meant this was only acceptable quality-wise for the right combination of step size, point size, and FOV...

So how could we handle this properly _without_ sorting on the CPU, keeping all rendering on the GPU? I've been thinking about this a bit, and looking into order-independent transparency methods, most of which seem to require at least OpenGL 4... And as we've discussed recently (issue #91), we want to avoid moving away from OpenGL 3.3 for as long as possible. Besides, I'm not sure these approaches would fit the bill for us anyway.

So having thought about this for a while, I think there is a way to do this within OpenGL 3.3. In a nutshell, it would render front to back, like the ray-tracing approach in the volume render mode. Using this approach, it is still possible to figure out the right maths for the transparency (essentially the alpha value of the destination fragment accumulates the alphas of the incoming fragments, becoming more and more opaque as it goes). So the idea would be to use a multi-pass rendering approach, which would look like this:
1. render tracks to a texture-backed framebuffer object, including depth and alpha components;
2. render tracks again to another identical framebuffer object, this time using the depth values stored in the first framebuffer object to exclude the upper-most fragments - i.e. those that were rendered at the last iteration. This involves checking whether the depth of the incoming fragment is less than or equal to the depth value stored;
3. blend the two framebuffers into the first, updating the alpha value and storing the depth of the furthest fragment;
4. Repeat from 2 for a number of passes - obviously more passes would be required if the transparency is low.
5. Render the final framebuffer onto the main framebuffer.

For this to work, we need to avoid any form of floating point error in the depth buffer. I reckon the only way to guarantee this is to bypass the system depth buffering (disable it), and compute depth manually in the fragment shader. That way we can write the depth values with the same precision as they would be computed, and guarantee that the computation used in the first pass is identical to that in the subsequent passes... That can be achieved using a generic framebuffer-attached texture - I think I use something  like that in the volume render to allow depth testing...

Assuming this can be made to work, the next question is whether it would be compatible with the other tools & modes... My main worry here is the volume render, which itself uses transparency throughout in the same way. Maybe the only way to allow both to co-exist peacefully is to render both tracks and volume within the same shader - although that's starting to look pretty horrendous...

Anyway, food for thought...

**Comment by rtabbara** [comment]
@jdtournier I've put a proposed solution to this in the <code>geometry_shader</code> branch so please check it out. The basic idea is that at low opacity rendering should behave close to having depth testing off, while conversely as we approach 1.0, we should have something which is more opaque (no depth testing). So my hack is that for opacity < 1.0, we render the stream lines twice, once without and once with depth testing and then do a weighted blending based on the opacity.

I think the result works quite well and has the advantage that we're not relying on any additional frame buffers which should be good for performance and hopefully means that it plays well with transparency from other tools/modes.

**Comment by jdtournier** [comment]
Interesting solution... It seems to do a decent job, even allowing transparency in volume render mode, which wasn't possible before. We'll have to see whether this will be sufficient on the long run...

**Comment by jdtournier** [comment]
Just for completeness: turns out the approach I was proposing above has already been [proposed by nvidia themselves](https://developer.nvidia.com/content/order-independent-transparency)...
