### ISSUE TITLE
dwifslpreproc: Slice timing import numeric type

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#1773]
As reported on [forum](https://community.mrtrix.org/t/dwifslpreproc-invalid-slspec-file/2909).

Unlike `3.0_RC3`, which uses `explicit code` to import data from the specified "slspec" file, `dev` [uses](https://github.com/MRtrix3/mrtrix3/blob/95b144df3d9eb837fae08129cc292c3fb8490eac/bin/dwifslpreproc#L221) `matrix.load_numeric()` with `dtype=int` parameter. Presumably this is not working, as the observed "slspec" file in the scratch directory contains scientific notation floating-point numbers. So either the `dtype` parameter is not working as it should, or the function iss failing outright and instead the data are being read as [slice timing](https://github.com/MRtrix3/mrtrix3/blob/95b144df3d9eb837fae08129cc292c3fb8490eac/bin/dwifslpreproc#L225).

@ansk: Can you confirm whether or not [this warning](https://github.com/MRtrix3/mrtrix3/blob/95b144df3d9eb837fae08129cc292c3fb8490eac/bin/dwifslpreproc#L227) appears at the terminal? That would at least inform which of these two code paths is being used.

**Comment by ansk** [comment]
Hi, @Lestropie,

this warning does not appear. Here is my output of `dwifslpreproc`:

```
dwifslpreproc started at  Sun Oct 20 21:54:08 CEST 2019
dwifslpreproc: 
dwifslpreproc: Note that this script makes use of commands / algorithms that have relevant articles for citation; INCLUDING FROM EXTERNAL SOFTWARE PACKAGES. Please consult the help page (-help option) for more information.
dwifslpreproc: 
dwifslpreproc: Generated scratch directory: /vypoctysup3/skoch/THAL_dwi/data/dwifslpreproc-tmp-U0Y80W/
Command:  mrconvert /vypoctysup3/skoch/THAL_dwi/data/THAL_C00615_20171209_1128_1/preproc/020_degibbsed.mif.gz /vypoctysup3/skoch/THAL_dwi/data/dwifslpreproc-tmp-U0Y80W/dwi.mif -json_export /vypoctysup3/skoch/THAL_dwi/data/dwifslpreproc-tmp-U0Y80W/dwi.json
dwifslpreproc: Changing to scratch directory (/vypoctysup3/skoch/THAL_dwi/data/dwifslpreproc-tmp-U0Y80W/)
Command:  dirstat dwi.mif -output asym
Command:  mrconvert dwi.mif - | dwiextract - se_epi.mif -bzero
Command:  mrinfo dwi.mif -export_grad_mrtrix grad.b
dwifslpreproc: 1 spatial axis of DWIs has non-even size; this will be automatically padded for compatibility with topup, and the extra slice erased afterwards
Command:  mrconvert se_epi.mif -coord 2 56 - | mrcat se_epi.mif - se_epi_pad2.mif -axis 2
Command:  mrconvert dwi.mif -coord 2 56 - | mrcat dwi.mif - dwi_pad2.mif -axis 2
Command:  mrconvert se_epi_pad2.mif topup_in.nii -strides -1,+2,+3,+4 -export_pe_table topup_datain.txt
Command:  topup --imain=topup_in.nii --datain=topup_datain.txt --out=field --fout=field_map.nii.gz --config=/usr/local/fsl/etc/flirtsch/b02b0.cnf --verbose
Command:  mrinfo dwi_pad2.mif -export_pe_eddy applytopup_config.txt applytopup_indices.txt
Command:  dwiextract dwi_pad2.mif -pe 0.0,1.0,0.0,0.0347 - | mrconvert - dwi_pad2_pe_1.nii -json_export dwi_pad2_pe_1.json
Command:  applytopup --imain=dwi_pad2_pe_1.nii --datain=applytopup_config.txt --inindex=1 --topup=field --out=dwi_pad2_pe_1_applytopup.nii --method=jac
Command:  mrconvert dwi_pad2_pe_1_applytopup.nii.gz dwi_pad2_pe_1_applytopup.mif -json_import dwi_pad2_pe_1.json
Command:  dwiextract dwi_pad2.mif -pe 0.0,-1.0,0.0,0.0344 - | mrconvert - dwi_pad2_pe_2.nii -json_export dwi_pad2_pe_2.json
Command:  applytopup --imain=dwi_pad2_pe_2.nii --datain=applytopup_config.txt --inindex=2 --topup=field --out=dwi_pad2_pe_2_applytopup.nii --method=jac
Command:  mrconvert dwi_pad2_pe_2_applytopup.nii.gz dwi_pad2_pe_2_applytopup.mif -json_import dwi_pad2_pe_2.json
Command:  mrcat dwi_pad2_pe_1_applytopup.mif dwi_pad2_pe_2_applytopup.mif - -axis 3 | dwi2mask - - | maskfilter - dilate - | mrconvert - eddy_mask.nii -datatype float32 -strides -1,+2,+3
Command:  mrconvert dwi_pad2.mif eddy_in.nii -strides -1,+2,+3,+4 -export_grad_fsl bvecs bvals -export_pe_eddy eddy_config.txt eddy_indices.txt
Command:  eddy_cuda --imain=eddy_in.nii --mask=eddy_mask.nii --acqp=eddy_config.txt --index=eddy_indices.txt --bvecs=bvecs --bvals=bvals --topup=field --very_verbose --repol --cnr_maps --mporder=16 --s2v_niter=10 --slspec=slspec.txt --out=dwi_post_eddy --verbose
dwifslpreproc: CUDA version of 'eddy' was not successful; attempting OpenMP version
Command:  eddy_openmp --imain=eddy_in.nii --mask=eddy_mask.nii --acqp=eddy_config.txt --index=eddy_indices.txt --bvecs=bvecs --bvals=bvals --topup=field --very_verbose --repol --cnr_maps --mporder=16 --s2v_niter=10 --slspec=slspec.txt --out=dwi_post_eddy --verbose

dwifslpreproc: [ERROR] eddy_openmp --imain=eddy_in.nii --mask=eddy_mask.nii --acqp=eddy_config.txt --index=eddy_indices.txt --bvecs=bvecs --bvals=bvals --topup=field --very_verbose --repol --cnr_maps --mporder=16 --s2v_niter=10 --slspec=slspec.txt --out=dwi_post_eddy --verbose (dwifslpreproc:851)
dwifslpreproc: [ERROR] Information from failed command:
dwifslpreproc:
               EddyInputError:  Slice-to-vol is not yet implemented for the CPU version.
               Terminating program
dwifslpreproc:
dwifslpreproc: [ERROR] For debugging, inspect contents of scratch directory: /vypoctysup3/skoch/THAL_dwi/data/dwifslpreproc-tmp-U0Y80W/
dwifslpreproc: Scratch directory retained; location: /vypoctysup3/skoch/THAL_dwi/data/dwifslpreproc-tmp-U0Y80W/
```

Antonin

**Comment by Lestropie** [comment]
Thanks; turns out to have been a fairly trivial omission (#1775). Hopefully will catch a number of outstanding gotchas when I finally merge #1614; but it seems an increasing number of people are sick of waiting for release and are using `dev` and catching my bugs :confounded:

**Comment by ansk** [comment]
Hi, @Lestropie ,
confirming that slspec.txt is now in decimal notation. However, there is still some error in format, line 31 has two columns:


```
# command_history: /hydradb/hydra_io/vypocty/skoch/bin/mrtrix3_dev/bin/dwifslpreproc -force /vypoctysup3/skoch/THAL_dwi/data/THAL_C00615_20171209_1128_1/preproc/020_degibbsed.mif.gz /vypoctysup3/skoch/THAL_dwi/data/THAL_C00615_20171209_1128_1/preproc/030_after_dwifslpreproc.mif.gz -nocleanup -rpe_header -eddyqc_all /vypoctysup3/skoch/THAL_dwi/data/THAL_C00615_20171209_1128_1/preproc/eddyqc_all_mp16_n10 -eddy_options ' --very_verbose --repol --cnr_maps --mporder=16 --s2v_niter=10 --slspec=/vypoctysup3/skoch/THAL_dwi/scripts/slspec_diff_tra_mddw_d64_b1000_2500_v01.txt '  (version=3.0_RC3-1066-g9f413da7)"
# comments: 
0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56 57
1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
51
53
55
# comments:

```

This is causing `eddy_quad` to fail and also maybe following error in `eddy_cuda` when `--estimate_move_by_susceptibitlity` option is used:

```
Basisfield:: msg=hadamard: Image dimension mismatch
EDDY:::  MoveBySuscCF.cpp:::  NEWMAT::ReturnMatrix EDDY::MoveBySuscCFImpl::grad(const ColumnVector&):  Exception thrown
EDDY::: Eddy failed with message EDDY:::  MoveBySuscCF.cpp:::  virtual NEWMAT::ReturnMatrix EDDY::MoveBySuscCF::grad(const ColumnVector&) const:  Exception thrown
```

Antonin

**Comment by Lestropie** [comment]
>  line 31 has two columns (number 57 should not be there)

Actually it should... `topup` crashes if provided with an image containing a spatial axis with an odd number of voxels (at least it still did last time I checked). In order for `dwifslpreproc` to succeed on such data, it pads out any such axis by duplicating the final slice (you can see this in your terminal printout in the generation of images appended with "`_pad2`". In cases where this is necessary along the slice encoding axis (as is the case for your data), this padded axis is given the same slice acquisition time as the duplicated slice. Therefore, when the slspec file is generated, this multi-band group will have one more member than the other groups.

> `Basisfield:: msg=hadamard: Image dimension mismatch`

Pretty sure this is an unrelated error; see latest on forum [here](https://community.mrtrix.org/t/eddys-estimate-move-by-susceptibility-option-causing-crash-on-denoised-data/2754/24).

**Comment by ansk** [comment]
@Lestropie, thanks for the explanation.

However, I found another problem with `eddy_quad` which exits with following error reading `slspec.txt` file:

```
eddy_quad dwi_post_eddy -idx eddy_indices.txt -par eddy_config.txt -m eddy_mask.nii -b bvals -f field_fieldcoef.nii.gz -s slspec.txt
Traceback (most recent call last):
  File "/usr/local/fsl/bin/eddy_quad", line 54, in <module>
    main(args.eddyBase, args.eddyIdx, args.eddyParams, args.mask, args.bvals, args.bvecs, args.output_dir, args.field, args.slspec, args.verbose)
  File "/usr/local/fsl/fslpython/envs/fslpython/lib/python3.7/site-packages/eddy_qc/QUAD/quad.py", line 122, in main
    slspec = np.genfromtxt(slspecFile, dtype=int)
  File "/usr/local/fsl/fslpython/envs/fslpython/lib/python3.7/site-packages/numpy/lib/npyio.py", line 2031, in genfromtxt
    raise ValueError(errmsg)
ValueError: Some errors were detected !
    Line #29 (got 2 columns instead of 1)
```
Antonin

**Comment by Lestropie** [comment]
Hmmmm okay, this is going to get awkward. Looks like `eddy_quad` is - implicitly, due to use of a NumPy function - making a hard assumption that all slice groups have an equal number of slices. But conversely there's a decent chance of either `eddy_quad` or `eddy` itself generating some other error if it is discovered that the number of slices in the image and the total number of entries in the slspec file don't match (don't recall for the latter; have not tested the former). 

Fundamentally this all comes back to `topup` crashing out if provided with an odd-sized image due to using a naive downsampling algorithm, and me trying to provide a wrapper script for such that will successfully process any user data provided to it. It's possible that newer versions of `topup` have a fix for this, in which case the axis padding hack is no longer requiring it, and explicitly not performing such would intrinsically fix this issue; though I'd still have an outstanding problem in `dwifslpreproc` because ideally all FSL versions should be "supported".

**Comment by ansk** [comment]
@Lestropie, could there be a solution to drop the padded slice on `dwi_post_eddy.nii.gz` and restore `slspec.txt` to original (i.e. single column in my case) before calling `eddy_quad`? Maybe this should be done anyway on the output file, to retain original data size.

Antonin
