### ISSUE TITLE
dwipreproc: Odd number of slices

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#1781]
Downstream of #1084 and #1169. Mostly the result of discussion in #1773 with @ansk and communication with `eddy_qc` developer. 

For an input image with an odd number of voxels specifically in the slice encoding direction, currently `dwipreproc` pads the image by duplicating and concatenating the last slice (as it does for the other two spatial axes), and also adds that slice to the vector of slice acquisition times, with the same time as the duplicated slice. This is to prevent a `topup` crash when it tries to naively downsample the image by a factor of 2. When this is done, in subsequent generation of the slspec file for eddy, the multiband group corresponding to the duplicated slice will have one more entry than all other groups.

It however seems as though having a different number of slices between different slice groups is considered strictly invalid. Though `eddy` currently successfully processes such data, in `eddy_quad` it leads to a NumPy error upon attempting to import these data. Therefore an alternative solution is required.

Options:

1. If `eddy` is happy to process such data, then `dwipreproc` could instead not only crop the padded slice for the sake of the output DWI having the same dimensionality as the input DWI, but also remove the excess slice from any and all other outputs from `eddy` prior to running `eddy_quad` (not only images but also text files). In reality this should be done anyway if such image padding is performed in the slice encoding axis and `-eddyqc_text` or `-eddyqc_all` are specified, independently of getting the `eddy_quad` command to execute.

2. Do not pad the images in this case; instead, use a modified `topup` config file that does not downsample the images during its optimisation iterations ([FSL thread](https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=ind1702&L=FSL&D=0&P=120897)). 

3. Delete `dwipreproc` from the repository, tell people to process their data the hard way, and restore a healthy sleeping pattern for myself.

**Comment by jdtournier** [comment]
I'm guessing #3 is looking pretty appealing right now?

**Comment by Lestropie** [comment]
Bump due to [forum thread](https://community.mrtrix.org/t/dwifslpreproc-discrepancy-when-running-eddy-vs-eddy-cuda9-1/4457/7).

**Comment by Lestropie** [comment]
Re-bump due to [feedback on forum thread](https://community.mrtrix.org/t/dwifslpreproc-discrepancy-when-running-eddy-vs-eddy-cuda9-1/4457/12); it seems that it is indeed possible to undo the padding operations to get EddyQC to work.

In light of such, I'm tempted to implement this, rather than option 2 (#2010), since the latter would result in even longer `topup` runtimes.

**Comment by Lestropie** [comment]
Closing for removal from milestone list; PR #2286 is outstanding.
