### ISSUE TITLE
population_template: Investigate variability

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#1786]
Merged #1614 because I was finally content with the arrangement of the testing, but there is still inconsistent test failures with `population_template` (and `dwinormalise group` due to downstream effects) that need to be isolated.

Basically, on some systems the `population_template` results match the test data (which I'm pretty sure was generated using the current `master` branch, then manually cropped to match the changes from `mrcrop` to `mrgrid` in #1609) very accurately, whereas on other systems it's quite different. Given the number of potential influencing variables, I probably need some assistance in generating sufficient data in order to isolate precisely which variable is influencing the results.

So what I would need is to have people do `./run_tests population_template` on `dev`, as well as running all of the command strings in that test but using `master`, on as many different systems as possible (containers and OS's). I'll then have to manually inspect the various results to try to figure out what's driving this variation in outcomes.

**Comment by Lestropie** [comment]
Okay, I can't find any cross-system variability after all, must have been a red herring from prior tests. Still some variation between `master` and `dev` to sort out though.

**Comment by Lestropie** [comment]
@maxpietsch: You mentioned at some point making registration work as expected with NaNs; has anything related to this made it to `dev`? `population_template` output is diverging between `master` and `dev` in the non-linear phase, and it might be at least in part due to changes in handling at mask edges.

**Comment by maxpietsch** [comment]
I don't think anything has changed in `mrregister` unless the interpolation has changed -- voxels with NaNs are ignored. So if the edge values are nan instead of zero this might affect nonlinear registration where Gaussian blurring is applied for regularisation. Is the input identical?

I implemented nan-masking in `population_template` in the `mrreg` branch which masks out areas not inside the mask to exclude those areas from the template (instead of effectively zeroing them) to avoid cropped images biasing the average intensity.

**Comment by Lestropie** [comment]
Still haven't yet debugged this one fully, but what I've found thus far (in case based on the description somebody intuitively knows what the cause might be):

- Results when masks are provided for input images are only very subtlely different between `master` and `dev`. Enough to cause test failures when e.g. the extent of a mask changes slightly, but no noticeable classification of "right" vs. "wrong", so can maybe just re-generate the test data.

- Results change quite a bit on the very first test, where no input masks are provided. Differences only start arising at the non-linear stage. `dev` seems to converge to a stable solution faster than does `master`, but there might be some doubt about whether it's a good solution.

**Comment by Lestropie** [comment]
Can anybody shed insight on the discrepancy between:

- `mrregister`: Both `-rigid_metric.diff.estimator` and `-affine_metric.diff.estimator` have default values of `None`, but can optionally be set to `L1`, `L2` or `LP`;

- `population_template`: `-linear_estimator` can be set to `l1`, `l2` or `lp`; help text indicates that *default value is `l2`*; if this option is not provided, `-*_metric.diff.estimator` are not passed to `mrregister`, which would seemingly invoke `None` rather than `L2`.

My best inference is that:

- In both cases, "`none`" (or some variant) should be offered as valid options (even if it is the default);

- The help text of `population_template -linear_estimator` should state that the default value is `none`; the current statement that the default value is `l2` is simply incorrect.

**Comment by maxpietsch** [comment]
The default estimator in `mrregister` is the sum of squares `l2`, so not passing that on (=`None` in `population_template`) is equivalent to explicitly setting it to`l2`.

**Comment by Lestropie** [comment]
From the `mrregister` code [here](https://github.com/MRtrix3/mrtrix3/blob/3.0_RC3/cmd/mrregister.cpp#L335-L353) and [here](https://github.com/MRtrix3/mrtrix3/blob/3.0_RC3/cmd/mrregister.cpp#L668-L676), it looks to me like there's a different code path between "none" and "L2".

Reason I'm poking and prodding is that [this test](https://github.com/MRtrix3/mrtrix3/blob/dev/testing/scripts/tests/population_template#L13) - which is supposed to do exactly the same as the FOD data `population_template` test before it, just that it includes passing in all the default option values explicitly via the command-line to make sure they are parsed correctly - gives a slightly different result if "`-linear_estimator l2`" is specified, as opposed to omitting it.

**Comment by maxpietsch** [comment]
>  gives a slightly different result if "-linear_estimator l2" is specified, as opposed to omitting it.

Ok, that's interesting. I did implement a robust version of gradient descent for the robust metric but from memory I don't think it made it to dev yet. I think the only difference between the two L2 metrics is the aggregation of the cost function at the voxel level so I'd expect differences solely due to numerical issues. I'll have a look at this next week when I have more time.

**Comment by Lestropie** [comment]
The difference in outcomes is very small, it just happens to be enough to trigger a test failure. That test executes with all of the defaults provided via the command-line explicitly, but compares to data generated with no command-line options provided.

The bigger problem is I think the discrepancy between the command-line options indicating 3 choices, but the code having 4 branches.
