### ISSUE TITLE
dwigradcheck permission error

### ISSUE THREAD

**Issue by jchen33344** [MRtrix3/mrtrix3#1808]
When I try to run:
dwigradcheck dwi_designer.nii -fslgrad dwi_designer.bvec dwi_designer.bval

I get an error: 
PermissionError: [Errno 1] Operation not permitted: '/media/labspace/Projects/MESO/ALLSUBJS/M0021/tract_smooth_compare/tract_smooth/dwigradcheck-tmp-MBI44F/bvecs'

Full Error Message:
Traceback (most recent call last):
  File "/home/shuz01/mrtrix3/bin/dwigradcheck", line 51, in <module>
    shutil.copy(path.fromUser(app.args.fslgrad[0], False), path.toTemp('bvecs', False))
  File "/home/shuz01/anaconda3/lib/python3.7/shutil.py", line 249, in copy
    copymode(src, dst, follow_symlinks=follow_symlinks)
  File "/home/shuz01/anaconda3/lib/python3.7/shutil.py", line 144, in copymode
    chmod_func(dst, stat.S_IMODE(st.st_mode))
PermissionError: [Errno 1] Operation not permitted: '/media/labspace/Projects/MESO/ALLSUBJS/M0021/tract_smooth_compare/tract_smooth/dwigradcheck-tmp-MBI44F/bvecs'

I was able to get it to run by replacing shutil.copy with shutil.copyfile in the dwigradcheck file.

**Comment by maxpietsch** [comment]
Thanks for reporting! I had issues with `shutil.copy` not being able to set the mode bit on `cifs` mounts with file_mode=0777 ([code here](https://github.com/MRtrix3/mrtrix3/pull/1575/commits/43ca41f3666cbc017e4ae2d5f60d335533f604b3#diff-d027788de891ccb6a10b194602c928e8R83)). How is the location of the temporary folder mounted (`mount`)?

**Comment by jchen33344** [comment]
> mode bit

Hi,
My folder is mounted with file_mode=0777, so that should be why shutil.copy is not working for me. Thanks for sharing your code!

**Comment by jdtournier** [comment]
I'm assuming we can close this issue? Feel free to re-open if that's not the case.
