### ISSUE TITLE
Create mif file from scratch

### ISSUE THREAD

**Issue by Al3xCalibur** [MRtrix3/mrtrix3#1863]
How can I create a mif file from scratch?
I read the [link](https://mrtrix.readthedocs.io/en/latest/getting_started/image_data.html), it's perfect for the header. But i don't know how to generate the raw data for a 2D image (JPG, PNG ...) and for a 3D object (like .OBJ, ...).
If it's possible, i would like to see the specifications.

**Comment by bjeurissen** [comment]
Probably better to ask questions like these on the community forum: https://community.mrtrix.org

That said, the data part of a .mif file is just a linear array of binary numbers in the data type specified in the header.

For an example on how to read and write .mif files from scratch, have a look at the functions in https://github.com/MRtrix3/mrtrix3/tree/master/matlab. It's Matlab code, but translating it to your language of choice sould be straightforward.

**Comment by Lestropie** [comment]
To expand just a little:

- We will hopefully have Python functions for reading & writing `.mif` files in the future in addition to the MatLab functions; see #1721.

- The mapping of xD image data into a 1D array of numbers on disk is handled using the concept of *strides*. If this is relevant to your application, it is best explained in Appendix A of the [*MRtrix3* manuscript](https://www.sciencedirect.com/science/article/abs/pii/S1053811919307281).
