### ISSUE TITLE
mrregister: Centre of mass in affine transformation files

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#1878]
Forked from initial posting in #1549; while it was discovered in the process of dealing with branch merging there, it warrants independent consideration.

Added to release milestone as I think we should make a decision on this before people start generating files containing such data.

-----

The modified `save_transform()` & `load_transform()` from #1798 that include a centre position are on reflection incongruent with #1603. See post-`dev`-merge code [here](https://github.com/MRtrix3/mrtrix3/blob/a4f6fffaedf314e2019a09ef7c2f5f2fd9672da1/core/math/math.h#L281-L305).

What I think would make more sense would be:

- For save:

    - Construct a `KeyValues` instance;

    - Insert into it an entry with key `centre` and value being the text string of the `Vector3`;

    - Pass that to the existing `save_transform()`.

- For load, have a wrapper function that:

    - Calls `load_transform()`;

    - Uses the existing `File::KeyValue::Reader` (which would require modification to support a comment symbol to strip from the start of each relevant line) to populate a `KeyValues` instance;

    - Validates the presence of the key "`centre`" & converts the value string to a `Vector3`;

    - Returns the transform and centre.

**Comment by maxpietsch** [comment]
Is the change from

```
#centre -1 -4 -2
1 0 0 0
0 1 0 0
0 0 1 0
0 0 0 1
```

to

```
# centre: -1 -4 -2
# command_history: mrregister ...
1 0 0 0
0 1 0 0
0 0 1 0
0 0 0 1
```

what you'd expect for a linear transformation file with a valid key-value format?

**Comment by Lestropie** [comment]
The format is correct. I however tweaked (8c25b371) the function so that it wasn't missing functionality relative to the simpler version; I also moved the transform before the centre in the argument list, as it seemed strange to me for a function called "`save_transform()`" to have the input transform as a middle argument :man_shrugging: 

The C++ key-value handling struck me as lacking overall looking at it now because in Python there's a dedicated function for scraping header key-value fields, whereas in C++ the dedicated key-value parser is designed for binary files with text data in the header (which don't have a comment prefix). The modified `load_matrix_2D_vector()` you put there that grabs any key-values purely so that `load_transform()` can acquire the affine centre location is a bit of a hack: there's theoretically text files other than matrix data that may have header key-values, and there's theoretically header key-values other than "`centre`" that may be of interest. But I'm happy to defer a more general solution for such to a second Issue; the priority here was making sure that such changes in the future won't lead to data incompatibility.
