### ISSUE TITLE
Installation docs: Update for release

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#1881]
Online documentation needs to be updated to reflect alternative installation mechanisms to compilation from source.

This is a key outstanding requirement for release (which I can't do myself as others have been making the relevant changes here).

Please add / edit as necessary:

- [ ] document and link to wiki section on forum
  - [ ] add new section about getting help, with link to forum, wiki, etc. 
- [ ] document binary installers for each platform
  - [ ] mention NeuroDebian too
- [ ] document Docker repos
- [ ] read-through for any errors / outdated statements

**Comment by jdtournier** [comment]
Please add / edit as necessary:

- [ ] document binary installers for each platform
- [ ] document Docker repos
- [ ] read-through for any errors / outdated statements

**Comment by Lestropie** [comment]
@MRtrix3/mrtrix3-devs : Should reflect on this in finalising #1985 ahead of #2021. NeuroDebian & Docker will likely change *after* #2021 merge; anything else from here that we need to address now?

**Comment by jdtournier** [comment]
I think we should be good to go. One of the main reasons for taking the binary installation docs out of the main repo was precisely so we could add or modify information about various installation vectors without needing to modify the main repo. So we can add sections about these to the main website as necessary without it necessarily influencing the main release.
