### ISSUE TITLE
run_tests: Conditionally update data repo

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#1897]
This has given me the irrits a couple of times when trying to not only get the repo pointing to the correct test data but also to move the branch pointers on the test data repos around.

The `run_tests` script always does a submodule update. This means that if you have been manipulating branches on the data repo, and want to do `run_tests` to verify things, then even if the main repo is currently pointing to the correct commit, the submodule will change into a detached head state, despite the fact that the data locally checked out have not actually changed whatsoever. Comparing the current most recent commit hash to the intended target, and skpping the update if they already match, would avoid this.

Might not fix all of the difficulties with submodule management, but might at least remove one potential source of confusion?

**Comment by jdtournier** [comment]
Sounds sensible enough to me. I've also found that a bit annoying...

**Comment by Lestropie** [comment]
Based on testing while doing #2100, I think this has been resolved through a `git` update.
