### ISSUE TITLE
dev: save_numeric broken

### ISSUE THREAD

**Issue by maxpietsch** [MRtrix3/mrtrix3#1967]
`population_template` fails on `dev` on macOS with python 3.7.4 in `save_numeric`'s `with os.open` call. I think there is a context manager wrapper missing in dc64d1a46fd94be96bae8d9c593289712e19a236. 

This reproduces the error on macOS and ubuntu.

```python
import os
with os.open('test', os.O_WRONLY | os.O_CREAT) as f:
    f.write('test')

# Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
# AttributeError: __enter__
```

**Comment by Lestropie** [comment]
Ugh, not sure how that got in; was quite sure that was all tested with & without `-force` with & without a pre-existing file...
