### ISSUE TITLE
dwinormalise group: Update for population_template changes

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#1971]
On `dev`, `dwinormalise group` currently does not succeed, because the names of the files output by `population_template` have changed. 

I'm hesitant to make a quick fix because of the added complexity of multi-contrast, and because it's not clear to where the change should be applied.

In the unit test, `dwinormalise group` runs `population_template` with an input directory containing the images `sub-02.mif` and `sub-03.mif`. The output warp images (as well as other `population_template` outputs) are named `2.mif` and `3.mif`. Not sure if the removal of the common prefix is intentional.

**Comment by maxpietsch** [comment]
`dwinormalise group` uses `population_template`'s scratch directory in which abbreviated filenames are used. I'd use the output of `-warp_dir` and discard the scratch directory.

**Comment by Lestropie** [comment]
Good point. Looks like I just carried that over from `dwiintensitynorm`.
