### ISSUE TITLE
DICOM: caret-to-space substitution

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#2000]
In [this line of code](https://github.com/MRtrix3/mrtrix3/blob/3.0_RC3/core/file/dicom/element.cpp#L390), strings imported from DICOM substitute all caret characters with space characters. This dates back to 0.2.

This led to confusion locally as it was believed firstly that subject names were not conforming to the DICOM standard, and secondly that dcmedit was failing to re-introduce this character.

@jdtournier: Any recollection of why this is present? If purely an aesthetic change, it might be better to stay faithful to the raw data.

**Comment by jdtournier** [comment]
I think it was purely cosmetic, but I can't remember if I'm honest... 

You're probably right, we should stick to what was entered. I'll fix this up now.
