### ISSUE TITLE
population_template: progress indicator exceeds 100%

### ISSUE THREAD

**Issue by bjeurissen** [MRtrix3/mrtrix3#2003]
``population_template`` progress indicator exceeds 100% on ``dev``, e.g.:

```
population_template: [126%] Optimising template with linear registration (stage 10 of 12; affine)...
```

**Comment by maxpietsch** [comment]
Did you use masks, multiple contrasts, any non-default options?

**Comment by bjeurissen** [comment]
masks, multiple contrasts, copy input, and nan-masking

**Comment by bjeurissen** [comment]
At the end of all linear registration stages it does display 100% progress. Just not in the process of getting there ...
