### ISSUE TITLE
Contributors list not complete

### ISSUE THREAD

**Issue by jdtournier** [MRtrix3/mrtrix3#2039]
Looks like the [list of contributors](https://github.com/MRtrix3/mrtrix3/graphs/contributors) on GitHub is not exhaustive, and missed quite a few people. GitHub shows 25 contributors to `master`, but the raw `git` history shows 34, by my reckoning. Using this command:
```
$ git log --format='%aN <%aE>' | awk '{arr[$0]++} END{for (i in arr){print arr[i], i;}}' | sort -rn 
```
and curating somewhat for duplicates gives:
```
3270 Robert Smith <robert.smith@florey.edu.au>
3000 J-Donald Tournier <jdtournier@gmail.com>
940 Dave Raffelt <draffelt@gmail.com>
755 Max Pietsch <mail@maxpietsch.com>
654 Thijs Dhollander <thijs.dhollander@gmail.com>
307 Daan Christiaens <daan.christiaens@gmail.com>
210 Rami Tabbara <rtabbara@gmail.com>
166 maxpietsch <maxpietsch@users.noreply.github.com>
133 David Raffelt <draffelt@gmail.com>
102 Ben Jeurissen <ben.jeurissen@gmail.com>
20 Lee Reid <lee.reid@csiro.au>
18 Jonas Rosnarho-Tornstrand <jr19@perinatal089-pc.isd.kcl.ac.uk>
13 Daniel Blezek <blezek.daniel@mayo.edu>
10 FRIGO Matteo <matteo.frigo@inria.fr>
8 Sascha Frydman <sascha.frydman@gmail.com>
8 Chun-Hung Jimmy Yeh <jimmy.chyeh@gmail.com>
6 Matteo Mancini <ingmatteomancini@gmail.com>
4 Kenneth Hoste <kenneth.hoste@ugent.be>
3 WillBrennan <WillBrennan@users.noreply.github.com>
2 Tom Close <tom.g.close@gmail.com>
2 Marmaduke Woodman <mmwoodman@gmail.com>
2 Jelle Veraart <Jelle.veraart@ua.ac.be>
2 gfagiolo <gfagiolo@VAGABUND3RD.isd.csc.mrc.ac.uk>
1 Stephen L <lrq3000@gmail.com>
1 rdpauw <Robby.DePauw@Ugent.be>
1 Pannek, Kerstin (H&B, Herston - RBWH) <Kerstin.Pannek@csiro.au>
1 Michael Krause <krause@mpib-berlin.mpg.de>
1 maedoc <mmwoodman@gmail.com>
1 Kristian Loewe <kl@kristianloewe.com>
1 jvohryzek <jakub.vohryzek@gmail.com>
1 Emilie McKinnon <mckinnon@musc.edu>
1 Claude Bajada <claude.bajada@um.edu.mt>
1 civier <orenciv@gmail.com>
1 CanWood <CanWood@users.noreply.github.com>
```

One possibility that I've come across to explain this might be that if users don't set their email address in their profile, GitHub won't match them to the commits. But not sure otherwise...

**Comment by civier** [comment]
Hello Donald,

I'm on the github list, so no problem.
I wonder, though, is the institution logos on the main page of the website (https://www.mrtrix.org/) reflect the institutions of the contributors? I had extremely minor contribution to date (promise to do better), but my institution, Swinburne University of Technology, will be very happy to be included :-) I can send you a logo if necessary.

Best,
Oren

**Comment by thijsdhollander** [comment]
> One possibility that I've come across to explain this might be that if users don't set their email address in their profile, GitHub won't match them to the commits. But not sure otherwise...

Yes, that is 100% certainly the explanation; no need to look for others.  This page in the GitHub documentation clarifies that unambiguously: https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address

**Comment by Lestropie** [comment]
Related to incomplete contributor lists: @jdtournier The contributor list for the front page of the website needs to be updated, but I can't seem to find any script for the auto-generation.

**Comment by jdtournier** [comment]
not obvious, but here it is...
https://github.com/MRtrix3/MRtrix3.github.io#frontpage-_datafrontpagecontributorsjson

**Comment by jdtournier** [comment]
OK, I guess there's remaining issues here:

- The email address mismatch explains why some contributors don't show up in the GitHub page, but are listed in the raw git logs. 

- The contributors front page list is [updated within the `gen_blog` script](https://github.com/MRtrix3/MRtrix3.github.io/blob/master/gen_blog.py#L25-L40), on the [repo that hosts the website](https://github.com/MRtrix3/MRtrix3.github.io). It gets run once a day from the server that hosts the community forum. And there's a [file for additional contributors](https://github.com/MRtrix3/MRtrix3.github.io/blob/master/_data/frontpage/additional_contributors.txt), where we can add the GitHub usernames of contributors that don't otherwise show up. 

I'll add the remaining contributors manually, and close this issue.
