### ISSUE TITLE
How do I create a NaN mask?

### ISSUE THREAD

**Issue by hhal** [MRtrix3/mrtrix3#2046]
I'm currently running the Fixel-Based Analysis pipeline and ready to create the population template.

Here I want to make use of the -nanmask flag as a mask for both registration and aggregation during this process. I'm working with stroke patients so I want to exclude their lesion site during registration and aggregation. I've the masks, but their have the conventional 0 - 1 format. How do I generate NaN mask from this?

I've tried the mrthreshold function with and used -nan to set all values that do not meet the criteria to NaN, ben then all other voxels (outside the brain) will automatically change to 1. Is that a problem when providing a NaN Mask? 

Any other suggestions on how to generate a NaN mask?

THanks a lot

**Comment by maxpietsch** [comment]
The `-nanmask` option does not take an argument; when it is provided it generates nan-masks from existing binary masks provided via `-mask_dir`.

> I've tried the mrthreshold function with and used -nan to set all values that do not meet the criteria to NaN, ben then all other voxels (outside the brain) will automatically change to 1. 

This is expected if your thresholding criterion is true for all but the lesion area. 

In case you need "nan-masks" you can create these from binary masks that define include areas (assuming mask.mif  is true only inside the brain and excluding lesions) with `mrcalc mask.mif 0.5 -gt 1 nan -if nan-mask.mif` but you won't need this for `population_template` as it is done internally. To combine lesion masks and brain masks, `mrcalc` should be handy as well as long as both share the same grid and header transformation (`mrinfo`).

If you need further help with this, please consider posting in our [community](https://community.mrtrix.org/) forum, which we set up for usage-related questions.

**Comment by hhal** [comment]
Thanks a lot for the quick reply! In understood that -nanmask didn’t require an input and will get its input from the directory provided by -mask_dir, yet I didn’t know that the nanmask will be automatically generated from the masks in that directory. Easy!

Thanks
