### ISSUE TITLE
mrthreshold: replace -abs with -above and -below

### ISSUE THREAD

**Issue by draffelt** [MRtrix3/mrtrix3#205]
Sometimes it would be handy to compute a mask based on a range of values. I realise this can be done currently with multiple steps, however it would be nice to have it in one command. 

If both options are input we would need to compare the magnitude of the -above and -below to determine if an || or && operation should be used. 

The only issue is that it might break a few scripts...being such a fundamental command.  Any objections?

**Comment by jdtournier** [comment]
Could that not be done using:

```ShellSession
mrcalc in.mif <above> -gt in.mif <below> -lt -mult in.mif -mult out.mif
```
??

Not too pretty admittedly, but the main feature of `mrtheshold` is the automatic threshold determination. If you're using predefined thresholds, you might as well use `mrcalc`...

Incidentally, this would be much easier with a more natural syntax like what I suggested in issue #27. This would then look like (assuming thresholds are 0 & 1):

```ShellSession
mrcalc '(a>0)*(a<1)*a' in.mif out.mif
```

Might be thinking about doing something about this?

**Comment by Lestropie** [comment]
We discussed it a bit earlier today, tend to think the feature of `mrthreshold` is _applying_ thresholds, doesn't necessarily matter how those thresholds are determined, whether automatic or manual. If it's a regular enough operation I can see the `mrcalc` solution being a bit clunky, especially for those not versed with stack-based syntax unless we do #27. But I'm not pushing strongly either way.

**Comment by draffelt** [comment]
I agree it's not that hard for most technical users to figure out, however it might not be that obvious for some RA users (with either syntax). 

I agree with Rob in that if someone needs to threshold an image, the first place they would look is mrthreshold. In most cases I use it with the -abs option (and don't use mrcalc -lt). The automatic stuff is just a bonus as far as I see it. Is there any reason why we can't have the ability to do it in either command?

**Comment by jdtournier** [comment]
Yes, I agree it doesn't have to be either/or. If you find you use the command enough for this type of operation (or at least you would if it could do it), then by all means go for it, it shouldn't take much to implement. I agree it's probably the first place people will look... 

And I like the idea of `-above ` and `-below ` options rather than `-abs`, it's more explicit that way. Not sure how many scripts use `mrthreshold` with the `-abs ` option currently, but I wouldn't worry about this at the moment - we haven't officially released yet...

**Comment by thijsdhollander** [comment]
I also like the suggested `above` and `below` options (most), but if needed for any reason, `abs` could be modified to accept either a single threshold (as it is now, applying the "above" logic), or a range.  In combination with the `invert` option, all options are also possible.

...but I actually also prefer `above` / `below` more. :-)

**Comment by jdtournier** [comment]
I think the issue is that a range isn't enough to specify whether you want to include the stuff inside or outside that range...

**Comment by thijsdhollander** [comment]
Well, just as the default behaviour for a single threshold provided to `abs` would be a lower threshold (aka `above`), the default behaviour for a range would be lower-upper (I figure that's how most people think about a range naturally).  `invert` is still there to get the opposite.

With `above` and `below`, that choice about default behaviour gets shifted to whether they are combined using `||` or `&&` logic, although the behaviour could in that case indeed be chosen depending on both values, as @draffelt suggested.  I do wonder whether that might actually confuse people as well.

...but the reasons I am in the end actually mostly in favour of `above`/`below`, are that

1) it reads naturally when the full command is written, and
2) there's also a `top N` and a `bottom N`, and a `toppercent N` and a `bottompercent N`.

These latter pairs of options can in principle be combined using `||` or `&&` logic based on similar choices; especially useful for the percent ones I reckon.

**Comment by jdtournier** [comment]
I'd forgotten about `-invert`... You're right, I agree this would actually make good sense.

Who wants to take it on? Feel free to hit the 'assign yourself button... :grin:

**Comment by Lestropie** [comment]
Superseded by #1636.
