### ISSUE TITLE
ubuntu focal no longer packages build dependencies (libqt4-opengl-dev)

### ISSUE THREAD

**Issue by gdevenyi** [MRtrix3/mrtrix3#2056]
**Describe the bug**

As of 20.04, the instructions for building from source no longer work because ``libqt4-opengl-dev`` doesn't exist.
```sh
$ sudo apt-get install git g++ python libeigen3-dev zlib1g-dev libqt4-opengl-dev libgl1-mesa-dev libfftw3-dev libtiff5-dev libpng-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'python-is-python2' instead of 'python'
E: Unable to locate package libqt4-opengl-dev
```

The replacement package is likely ``libqt5opengl5-dev``, I haven't yet tested if mrtrix3 will build against it.

**Comment by Lestropie** [comment]
Hi @gdevenyi,

Thanks for the report. We're currently in the process of revising some of the instructions for building from source; see #2049. This includes more explicitly recommending Qt5 over Qt4, and altering the example dependency installations to access Qt5 packages. I've also there tried to emphasize that the provided package name lists are suggestions only, and that with the wide range of distributions it's possible that package names may not be precisely identical; though it would be preferable for Ubuntu 20.04 to work from the provided example without modification.

Cheers
Rob
