### ISSUE TITLE
Sync focus between multiple instances of MRview. 

### ISSUE THREAD

**Issue by draffelt** [MRtrix3/mrtrix3#206]
Had somebody request this recently. We have discussed this before. Should be able to handle cross platform interprocess communication with Qt. 

http://doc.qt.io/qt-5/ipc.html

**Comment by jdtournier** [comment]
Yes, it's been discussed multiple times. The issue has always been about how to implement this in a clean and intuitive fashion. Main thing is that you don't necessarily want your multiple instances of MRView to sync, so we need some mechanism to tell the relevant instances that they need to sync. Maybe if we had a big sync button on the toolbar, it might be easy enough to use?

Other options are whether we have a global sync (i.e. once sync'd, they all sync together), or a more fine-grained approach, where we can say window A syncs with window B, and window C with window D. Personally, I think the latter is going to be very unwieldy for no tangible gain...

Other thing we discussed is _what_ to a sync aside from the focus. There's all kinds of things we might want to keep consistent across instances: projection plane (when locked to plane), full projection matrix (when not locked), intensity window, FoV, window size... And also slightly less important ones: current volume (although to be fair we need that in the view toolbar first), colourmap, interpolation, what annotations are shown, etc. Ideally we'd chose sensible defaults and provide a mechanism to select what is to be synced...

Admittedly some of these probably seem unnecessary, but I reckon by default you'd probably want most of these on - I guess it all depends on what you want this for...

**Comment by Lestropie** [comment]
Closed by #1940.
