### ISSUE TITLE
error in write_mrtix.m

### ISSUE THREAD

**Issue by julienbesle** [MRtrix3/mrtrix3#2092]
Hello,

I get an error at line 145 of write_mrtrix.m:

![image](https://user-images.githubusercontent.com/13522364/85011322-05ca1180-b16a-11ea-9d46-61c3da4acd82.png)

This line does not seem to be correct Matlab syntax and was introduced in b637293

(sorry for the screen capture)

**Comment by Lestropie** [comment]
Hi Julien,

Thanks for the report. I must have added that line after I had done all of my testing of the other MatLab changes I was doing at the time and failed to do one last check. Fix coming in #2094, and we'll hopefully push out a `3.0.1` tag with a bunch of teething issues fixed soon.

Cheers
Rob

**Comment by Lestropie** [comment]
Ah, Octave supports `+=` syntax; that's why :man_facepalming:

**Comment by julienbesle** [comment]
Hello,
Thanks for fixing. This fixes the error in Matlab, but the output file has incorrect values (at least when writing out integers). 
Here is an example written with either the current version of write_mrtrix.m (incorrect) or with an older version (95b144d) that writes the correct values to the file. 95b144d is the last commit that gives correct values. All versions I have tried after that either fail with a Matlab error or write incorrect values to the file.

This is the correct output. Written values are integers between 8100 and 8233 in this example.
![image](https://user-images.githubusercontent.com/13522364/86769496-eb43d380-c057-11ea-83cd-67bcef380d78.png)


This is the incorrect output: note the small value were the crosshair is located. Written values range between 10^-42 and 10^-39.
![image](https://user-images.githubusercontent.com/13522364/86769214-796b8a00-c057-11ea-99f8-6cd94a056ba4.png)
