### ISSUE TITLE
update install procedure for MSYS2 binary package

### ISSUE THREAD

**Issue by jdtournier** [MRtrix3/mrtrix3#2098]
Need to deprecate the `pacman` repo on our web server, and instead direct people to use a direct download from the release package. This is mostly to make sure we can track the number of downloads.

**Comment by jdtournier** [comment]
Fix in MRtrix3/MRtrix3.github.io#12 - seems to work fine on my laptop (though the display in `mrview` seems a bit borked, but that's more likely to be due to my recent driver 'update'...)

**Comment by Lestropie** [comment]
Closed by MRtrix3/MRtrix3.github.io#12.
