### ISSUE TITLE
MRview: segfault on close

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#21]
This one may be a little hard to track down... Initially I thought it was only a Windows thing (get the error popup window after closing), but now it looks like Linux is segfaulting on close as well.

There's a chance that the problem is buried deep within QT somewhere; I get a lot of "Conditional jump or move depends on uninitialised value(s)" within shared libraries. Backtrace on gdb is completely useless.

Thought I'd just list what little we have, so maybe an idea comes out of it.

Got this from valgrind on Linux:

```
==9519== Thread 2 QXcbEventReader:
==9519== Jump to the invalid address stated on the next line
==9519==    at 0xEF562B9: ???
==9519==  Address 0xef562b9 is not stack'd, malloc'd or (recently) free'd
==9519== 
==9519== 
==9519== Process terminating with default action of signal 11 (SIGSEGV)
==9519==  Access not within mapped region at address 0xEF562B9
==9519==    at 0xEF562B9: ???
```

Had noticed at one point (think it was on my home Windows machine) that I'd get the crash window popping up if I opened MRview on its own, but if I provided an image path on the command-line, I wouldn't get the error window...?

May have come from moving from QT4 to QT5; I certainly wasn't getting segfaults on my work machine previously. And I seem to recall when I did my first Windows installation that I used a pre-built QT4, and I wasn't getting the error popup on close like Donald said he had with a Windows install. Edit: Yup, no segfault on QT4. Do get a whole lot of invalid reads deep within QT code though.

**Comment by bjeurissen** [comment]
Just tested on Windows 10  with QT 4.8.7. I still get the segfault message on the commandline on closing mrview (unless I provide an image path on the commandline).

**Comment by bjeurissen** [comment]
Same problem with Qt 5.5

**Comment by jdtournier** [comment]
> unless I provide an image path on the commandline

Well that's interesting... Any chance we can get a backtrace on a debug build...?

**Comment by jdtournier** [comment]
Just thought I'd add: there is a chance this might be related to #299...
