### ISSUE TITLE
Docs: Move fixel format?

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#2107]
Currently the [information on the fixel directory format](https://mrtrix.readthedocs.io/en/latest/getting_started/image_data.html#fixel-image-directory-format) is buried within the "[Images and other data](https://mrtrix.readthedocs.io/en/latest/getting_started/image_data.html)" page. 

I'm thinking it might be better for this to instead have its own dedicated page, probably within the "Fixel-Based Analysis" group, with the "Images and other data" page maybe just having a hyperlink to it.

**Comment by Lestropie** [comment]
Could potentially add something on the fixel-fixel connectivity matrix format too.

**Comment by jdtournier** [comment]
Yes, I reckon that would be a good idea. I've also found myself looking for these docs, and slightly surprised to find them there...
