### ISSUE TITLE
replace Jet with a perceptually uniform colour map

### ISSUE THREAD

**Issue by maxpietsch** [MRtrix3/mrtrix3#2116]
Turbo seems like a good candidate to replace Jet unless there is reason to keep Jet around?

https://ai.googleblog.com/2019/08/turbo-improved-rainbow-colormap-for.html
https://gist.github.com/mikhailov-work/0d177465a8151eb6ede1768d51d476c7
Apache-2.0

**Comment by Lestropie** [comment]
#1683
