### ISSUE TITLE
mrview on Windows

### ISSUE THREAD

**Issue by nadluru** [MRtrix3/mrtrix3#212]
Dear Donald and all of MRtrix team,

I have just now begun to try out mrtrix3. The main reason I waited so long is that I remember mrtrix3 does not support X-forwarding anymore.

I followed the "Installing on Windows" wiki page and was able to successfully install the mrtrix3. By successfully I mean no error messages in the build process and also checking commands like "dwi2fod -h" work properly.

However mrview seems to be having issues with running on WIndows. I also noticed a previous issue that was closed about 11 days ago and since I pulled the latest version just yesterday that stderr thing is not an issue I hope.

Here's the behavior:
1) mrview -h opens a new command window (not Git Bash but Windows command prompt) with proper help text printed. dwi2fod -h on the other hand displays the help text in the same Git Bash shell.

2) If I just type mrview it waits for a minute or so and just comes back to the prompt without doing anything.

3) If I type mrview fa.mif for e.g. it also apparently does nothing for a while and comes back to the prompt. I was using fa.mif generated from 0.2.11 version. Does that matter?

Could you kindly help resolve this issue?
Thanks so much for making such a great package and for your help!
Sincerely,
Nagesh

**Comment by Lestropie** [comment]
1) Don't know that there's a whole lot we can do about this. The geniuses at Microsoft made console and GUI commands behave quite differently in Windows; a GUI command can't write to the terminal, and a terminal command can't create visual elements without forking another process. One side effect of this is that we can't print debugging information to the terminal during GUI commands. In fact I hadn't even thought of the consequences of what would happen to the help pages for `mrview` / `shview`, and am pleasantly surprised that it opens up a new cmd window with the help info; it's better than showing nothing...

We could conceivably try some trickery to _maybe_ get this working as desired, but it would be purely for the sake of the help pages in `mrview` and `shview` on Windows only; so it's difficult to justify the time, added complexity, or likelihood of other things going wrong.

2) & 3) This sounds like an anti-virus / firewall issue to me. I just updated and re-compiled on my Windows machine and both of these still work fine (also, it doesn't matter at all if the image being loaded was generated using the old software). Every time I update `mrview`, Kaspersky prompts me to enable permission for something or another; it's possible that you have software that's blocking formation of the window (with or without some sort of security prompt), and `mrview` 'gives up' after a certain time out. So try disabling any security software (including the Windows firewall) and running again.

**Comment by nadluru** [comment]
Thanks for the tip that this might be due to a possible security setting! I was indeed trying it on a relatively strict machine. I will try the steps on my laptop instead and update this thread if it is indeed the case. Thanks again!

**Comment by nadluru** [comment]
It works on my laptop which is less restrictive! Now I wonder what are the security constraints that mrview might be breaking! I ask because I work in a lab that has restrictions close to a clinical setting and I think understanding which constraints can be loosened is important for labs like that. I will work with our IT admin and update this thread if I can find more specifics about this!

**Comment by nadluru** [comment]
Hi Robert,

I just thought if you could note explicitly what Kaspersky prompted you for in terms of permissions and post that to this thread! That might help me and our IT admin where to start.

Thank you so much!
Best,
Nagesh

**Comment by Lestropie** [comment]
> mrview.exe from the Low Restricted Group is attempting to create an embedded key or parameter in protected registry key included in the Operating system / Security settings group.
> Registry key:
> hklm\SYSTEM\CONTROLS...\NVIDIA OPENGL DRIVER
(three times)

I can't actually see the relevant key in my registry, but if I look in:
`SYSTEM/ControlSet001/services/eventlog/Application/NVIDIA OpenGL Driver`
I can see the following being created on running `mrview`:
`EventMessageFile: %SystemRoot%\System32\nvoglv64.dll`
`TypesSupported: 0x00000007`

**Comment by nadluru** [comment]
Thank you so much Robert. I will followup on this and update again.

**Comment by nadluru** [comment]
Hi Robert,

I just brought in our IT admin and was trying to reproduce the problem in front of him and suddenly everything works!! My computer did have a reboot in between so that might have done the trick!

So just restarting after installation might be needed for some settings on a Windows machine. Since a restart was not needed on my laptop. Anyways I think I will close this issue now.

Thank you for your support!
Sincerely,
Nagesh

**Comment by nadluru** [comment]
Hello again,

Sorry that I prematurely closed the issue.

When I first opened the issue I was trying to open mrview from a Windows installation but logged in remotely via remote desktop protocol. When I checked with our IT admin it worked and I thought it could have been because of a restart. But what I realized afterwards is that it was because I logged in locally to that system.

So basically mrview somehow is sensitive to local vs. remote logins to a Windows machine! In general other applications (e.g. Word, TexMaker etc.) are not sensitive to this. I did specifically ask our IT admin if this could be a policy related issue but it stumped him and he asked me to contact you guys about this. He did help me get the error log message (which did not help the admin) that was produced during mrview via remote login attempt. Al though I doubt the message itself is going to be helpful directly, I am pasting it below. Perhaps someone can try this remote login thing to reproduce the error and help the investigation!

For now I have a solution that is just use mrview locally but would be really helpful to see if this can be fixed!

Thank you all for building such great package and providing amazing support!
Sincerely,
Nagesh

Error message:
===============
Faulting application name: mrview.exe, version: 0.0.0.0, time stamp: 0x00000000
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0000000000000000
Faulting process id: 0x118c
Faulting application start time: 0x01d0794f89bd9aa3
Faulting application path: y:\gates\NageshScriptsETC\NageshCode\GitHub\MRtrix3\mrtrix3\bin\mrview.exe
Faulting module path: unknown
Report Id: cbcba1b7-e542-11e4-bfd1-3417ebafe245
===============

**Comment by jdtournier** [comment]
Hey Nagesh,

That would most likely be due to the fact that MRView uses OpenGL for the rendering, which requires direct access to the graphics card. I reckon your remote desktop software doesn't support OpenGL - maybe you can check the documentation for it? By the way, I'm talking about the remote desktop _server_, i.e. what's running on the remote system you've logged into, not the system you're sitting at. And it would need to support OpenGL 3.3 specifically.

I've no idea whether there are remote desktop servers that do support OpenGL (I'd be surprised if there weren't), but on the Linux side, most VNC servers don't...

Another way to test this theory is to try running some other OpenGL application (e.g. a 3D game). If that displays OK, then the problem _might_ be elsewhere. Although it wouldn't be conclusive in that case unless you _know_ the application you ran was using OpenGL 3.3 or above... It might have been using OpenGL 2, or more likely DirectX, which is likely to be supported given that it's Microsoft's own alternative to OpenGL...

Anyway, that's my 2 cents.
Cheers,
Donald

**Comment by nadluru** [comment]
Hey Donald,

Thanks for pointing out the subtle difference between the RDP server on the machine and the machine itself. I will check to see if this makes a difference. I will update this thread again.

Thanks so much again!
Sincerely,
Nagesh

**Comment by jdtournier** [comment]
@nadluru: any progress on this? Can I close this off...?
