### ISSUE TITLE
Dwibiascorrect options not detected in MATLAB

### ISSUE THREAD

**Issue by davisn11** [MRtrix3/mrtrix3#2133]
Hello! I am currently trying to run this code as a test for a larger research pipeline and have been running into a few issues. I am really new to MRtrix3 and coding in general so I apologize for my naivety and newbie questions.

So, I am trying to run this block in MATLAB
```
niiseqst = [diffseq];
for ii=1:length(niiseqst)
        dirt = filestar([Expfolder niipath ...
            num2str(niiseqst(ii),'%03.0f') '*' filesep]);
        filen = [dirt 'data_dn_ur_rc.nii.gz'];
        fileorig = strrep(filen,'.nii','.orig.nii');
        bvalfile = [dirt 'data.bval'];
        bvecfile= [dirt 'data.bvec'];
        system(['cp ' filen ' ' fileorig]);
        if ~server
            antspath = '/Users/research/dir/new/install/dir/bin/';
        else
            antspath = '/Users/research/dir/new/install/dir/bin/';
        end;
        system(['PATH=$PATH:' antspath '; ' ...
            'dwibiascorrect -fsl -fslgrad bvecfile bvalfile' ...
            ' -force ' fileorig ' ' filen]);
end;
```

But I end up getting "Error: argument -fslgrad: expected 2 argument(s)
Usage: dwibiascorrect algorithm [ options ] ...
       (Run dwibiascorrect -help for more information)". I thought the bvecfile and bvalfile are the inputs for fslgrad? Previously we had them defined as "dirt 'data.bvec' dirt 'data.bval' ", but I was still getting the same error, so what am I doing wrong here?

Thank you for your help!

**Comment by jdtournier** [comment]
I think the main reason is that the first `-fsl` shouldn't be an option, but an argument - i.e. it should look like 
```
dwibiascorrect fsl -fslgrad ...
```

**Comment by jdtournier** [comment]
And by the way, you'll probably find the [MRtrix3 community forum](https://community.mrtrix.org/) is a better place to ask these types of questions.

**Comment by davisn11** [comment]
Thank you for your quick reply! I apologize, I didn't see the community forum when I was searching for help. I will delete this and move over there.

**Comment by davisn11** [comment]
Moved to the community forum.
