### ISSUE TITLE
Permit integer multiplier postfixes at command line

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#215]
`tckgen -number 10M` is much less prone to error than `tckgen -number 10000000`...

**Comment by thijsdhollander** [comment]
How about allowing E notation (i.e. 10e6, or 1e7, etc..) for any numeric argument (even if integer)?

**Comment by jdtournier** [comment]
Just checked, 1e3 gets interpreted as 1 (this uses the C++ `>>` operator). Would need special handling, but might indeed be better that way...

**Comment by Lestropie** [comment]
Not quite sure what's going on with all these self-assignment removals...

Personally I think I prefer the metric postfixes to scientific notation for integer inputs. Parsing integers vs. floats follow different code paths already, and E notation is really intended for floats. And you'd have to reject negative exponents, which otherwise works with options that expect a float in.

**Comment by jdtournier** [comment]
> Not quite sure what's going on with all these self-assignment removals...

??

I have to admit I'd also prefer having `k` and `m` (`g`??) suffixes, it is probably clearer. And since we have to implement the parsing for this anyway, I reckon why not...

**Comment by jdtournier** [comment]
That said, would support something like `1.2m`...?

**Comment by thijsdhollander** [comment]
> Not quite sure what's going on with all these self-assignment removals...
I noticed that as well: I'm pretty sure it happened exactly when everyone was "removed" from the "old" repository (before being added to the GitHub organisation).

On the postfixes: I was certainly not suggesting to *not* do the metric postfixes, just suggesting to allow E notations across the board as well.  If you're already parsing extensions at some point anyway, would it not be possible to have everything (integers/floats) going through the same pipeline (of checking various postfixes), initially being treated as floats?  After that, if it's supposed to be an integer, but ends up not being one, there could be an error (or other sensible behaviour; although no definition would probably be sensible/intuitive in these cases, so an error seems the safer option)?  In this way, it would probably inherently also allow for things like `1.2m`.

In any way, the current situation where 1e3 gets interpreted as either 1 or 1000 *depending on the input type* seems to be a potential source of mistakes on the users' end.

**Comment by jdtournier** [comment]
Up to you. Personally, I think it's probably more trouble than it's worth - this really is only a bit of UI polish, things work just fine as they are. Most people will figure things out pretty quickly... Just go for whatever's easiest.
