### ISSUE TITLE
mrgrid: nearest neighbor interpolation returning unexpected values

### ISSUE THREAD

**Issue by leonyichencai** [MRtrix3/mrtrix3#2158]
Hello! I've been using mrgrid in the following fashion to resample NIFTIs to be isotropic:

mrgrid -voxel 2.200000 -interp nearest img.nii.gz regrid img_iso.nii.gz

The input image consists of integer values from 0 to 48 and is a float64 image. I expect the output image to also be a float64 image with integer values between 0 and 48. However, I'm getting decimal values like 0.25, 2.75, 3.75, 30.5, etc back out as well. Is this expected behavior? Thanks!

I'm using version 3.0.0:

== mrgrid 3.0.0 ==
64 bit release version, built May  1 2020, using Eigen 3.3.4
Author(s): Max Pietsch (maximilian.pietsch@kcl.ac.uk) & David Raffelt (david.raffelt@florey.edu.au) & Robert E. Smith (robert.smith@florey.edu.au)
Copyright (c) 2008-2019 the MRtrix3 contributors.

[img.nii.gz](https://github.com/MRtrix3/mrtrix3/files/5185484/img.nii.gz)

**Comment by jdtournier** [comment]
Ok, that doesn't sound right. I have a feeling this might be due to the oversampling that kicks in when downsampling. Is your target resolution coarser than the original? Try adding the option `-oversample 1` option to your command, see if that makes any difference. It should be disabled for nearest-neighbour interpolation, but maybe there's a glitch in there...

**Comment by Lestropie** [comment]
Converting the original image to one with a native integer datatype prior to passing it to `mrtransform` will almost certainly result in the intended behaviour (there's too many applications that would be broken if that weren't the case). That will hopefully keep you going with your analysis while we hunt down the source of the issue.

**Comment by leonyichencai** [comment]
It looks like explicitly specifying `-oversample 1` did the trick!

**Comment by jdtournier** [comment]
Thanks, that's really helpful. I think I've found [the source of the problem](https://github.com/MRtrix3/mrtrix3/commit/b7893e808ace0253c4513a74921900c6f3846468#diff-42475dda9888b8d883e18e107ab202f7L136). Should be a simple fix, we'll make sure to make it part of the next bug fix release.
