### ISSUE TITLE
mrcolour: png upside down

### ISSUE THREAD

**Issue by maxpietsch** [MRtrix3/mrtrix3#2179]
`mrcolour` produces pngs that are upside down. macOS, `PNG library: Header: 1.6.37; library: 1.6.37`

```
wget https://github.com/MRtrix3/script_test_data/raw/master/BIDS/sub-02/dwi/sub-02_dwi.nii.gz
mrconvert sub-02_dwi.nii.gz -coord 3 0 -coord 0 15  sag.mif
mrcolour sag.mif gray sag.png

mrconvert sub-02_dwi.nii.gz -coord 3 0 -coord 1 15  cor.mif
mrcolour cor.mif gray cor.png
```
![cor](https://user-images.githubusercontent.com/10046944/94407960-7246aa80-0174-11eb-9db9-b7e4e019d21e.png)
![sag](https://user-images.githubusercontent.com/10046944/94407962-72df4100-0174-11eb-8fc8-127c5dbfba8b.png)

**Comment by Lestropie** [comment]
Applies to the PNG format generally, not specifically to `mrcolour`.

I spent some time getting this right, so not quite sure what happened at the tail end of #1541 to send it skewiff again.

**Comment by Lestropie** [comment]
@jdtournier suggested that user stride request could be used to attribute image axes to 2D PNG axes. This *might* be possible. I need to essentially re-write the relevant section of code as it is to try to address this, so I'll try to keep this prospect in mind.

**Comment by Lestropie** [comment]
Closing as issue became part of the expanded scope of #2713.
