### ISSUE TITLE
mrtransform -template of SH image unnecessarily reorients, segfaults

### ISSUE THREAD

**Issue by thijsdhollander** [MRtrix3/mrtrix3#220]
`mrtransform` `some_SH_image.mif` `resampled_SH_image.mif` `-template` `some_template.mif`

...goes "SH series detected, performing apodised PSF reorientation" when it is actually not needed in this scenario (the image is not being transformed, just regridded).
After that, it reslices, followed by a segfault.  The last `-debug` outputted line reads `[DEBUG] threads "loop threads" completed OK`.  The `resampled_SH_image.mif` is created, but not written (all zeros).

No problems when the -noreorient option is provided in the otherwise same scenario.

**Comment by draffelt** [comment]
Thanks, I'll be sorting out mrtransform of SH images next week
