### ISSUE TITLE
distutils.spawn.find_executable to shutil.which

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#2210]
The *MRtrix3* Python API depends on the `distutils` module for the `find_executable()` function. Apparently usage of this module is discouraged in favour of `setuptools`, and it is indeed [intended for deprecation](https://www.python.org/dev/peps/pep-0632/#id13). But even then, with `setuptools` being to "download, build, install, upgrade, and uninstall Python packages", it's not necessarily a sensible dependency to have.

As of Python 3.3, the widely-used `shutil` module has [the `which()` function](https://docs.python.org/3.8/library/shutil.html#shutil.which), which serves the same purpose.

So if following through with #2047, I would suggest making the minimum dependency 3.3 ([released Sep 2012](https://www.python.org/downloads/release/python-330/)), and making use of this function throughout.

**Comment by bjeurissen** [comment]
Makes sense!

**Comment by jdtournier** [comment]
I'd be happy enough this that too. It really should be OK to mandate Python 3.3 by now, but I expect we'll find it'll still cause friction in some cases...
