### ISSUE TITLE
brew upgrade mrtrix3: Error: An exception occurred within a child process

### ISSUE THREAD

**Issue by neurolabusc** [MRtrix3/mrtrix3#2240]
**About**

This happened to me when I updated what an. unrelated tool (`brew upgrade gmp`, gmp 6.1.2_2 -> 6.2.1) which triggered a cascade of library upgrades. Clearly, at least one of these libraries is used by mrtrix, as it generated the error shown below. Now explicitly running`brew upgrade mrtrix3` also elicits the error.

**To Reproduce**

The command 
`brew upgrade mrtrix3`
Generates an error
```
Error: An exception occurred within a child process:
  MethodDeprecatedError: Calling BuildOptions#include? is disabled! There is no replacement.
Please report this issue to the mrtrix3/mrtrix3 tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/mrtrix3/homebrew-mrtrix3/mrtrix3.rb:169
```
**Platform/Environment/Version**

Please provide the following information:

-  OS:  macOS: 10.14.6
- `brew -v` Homebrew 2.6.0
-  *MRtrix3* version mrinfo reports 3.0_RC3_latest-73-g8252c3b6 ==  (probably before upgrade)

**Comment by maxpietsch** [comment]
Hi @neurolabusc,

Thanks for reporting! I think https://github.com/MRtrix3/homebrew-mrtrix3/commit/1a10c4f20998d18047b13d1ccecccf474da5d74a fixes this issue. Could you please confirm (after `brew update`)?

**Comment by neurolabusc** [comment]
@maxpietsch it is fixed. Thanks. for your quick response.
