### ISSUE TITLE
Hot and cool colour map without the black

### ISSUE THREAD

**Issue by draffelt** [MRtrix3/mrtrix3#226]
It might be handy to have an additional hot and cool colour bar that does not start from black. This would be used when overlaying significant results, so that the minimum supra-threshold p-value would start from red (or blue) and not black (which can be hard to see). Currently I get around this by setting the lower windowing value to be slightly lower than the threshold, however then the colorbar min value is not set to the threshold value (this is not an issue for day to day tasks, but annoying when you want to include the colour bar in a paper)

**Comment by rtabbara** [comment]
@draffelt @jdtournier Took a look at this and have pushed out a proposed solution. Now, when thresholding, the colour map is restricted to the range of visible colours.  This change should apply to both overlays and vector plots.

**Comment by draffelt** [comment]
@rtabbara As I said today, I think this is a much better solution to having additional colour maps.

We will want this change to also be made for track scalar files. I'll give you some example data tomorrow.

**Comment by rtabbara** [comment]
This should now work with track scalar files
