### ISSUE TITLE
Segmentation fault for small number of directions in dirorder

### ISSUE THREAD

**Issue by mattlyon93** [MRtrix3/mrtrix3#2271]
Whilst doing some testing using a small subset of b-vector directions, I came across the following error whilst using `dirorder`

> dirorder: [SYSTEM FATAL CODE: SIGSEGV (11)] Segmentation fault: Invalid memory access

Using the commandline

`diroder -cartesian /tmp/bvec_test /tmp/bvec_out`

where `bvect_test` was a simple bvec array generated from `dirgen` as follows:
```
# command_history: dirgen -cartesian 4 /tmp/dirs2  (version=3.0.2)
-0.768068368363638 0.430205845005412 -0.474335232132717
0.0433100803783766 -0.968382485647422 -0.245681904968476
0.851710966808829 0.450298932048355 -0.267991232717941
0.126952687168782 -0.0878776968375553 -0.988008363132191
```

Presumably this is related to the small amount of directions?

MRtrix3 version: 3.0.2, on Ubuntu 20.04

**Comment by Lestropie** [comment]
Hi Matt,

Thanks for the report. You're correct in that it's the very small number of directions that is the problem. The code [here](https://github.com/MRtrix3/mrtrix3/blob/3.0.2/cmd/dirorder.cpp#L94-L97) necessitates that there be at least 6 directions in the input to not segfault (and at least 7 before the reordering algorithm can actually do anything meaningful). We'll add a check to prevent the outright error, and maybe we should think about whether there's a way to have the reordering algorithm take the relative order of the first six directions into account in its optimisation.

Cheers
Rob

**Comment by Lestropie** [comment]
Correction: The reordering algorithm does actually attempt to optimise the order of all directions, including the first six; the limitation is that if there are fewer than seven directions, then the command is unable to characterise which direction is best to use as the very first.
