### ISSUE TITLE
MRView screen capture: allow rotation about axes in different coordinate systems

### ISSUE THREAD

**Issue by jdtournier** [MRtrix3/mrtrix3#229]
Previously, the axis of rotation was defined relative to eye coordinates. This was fixed with 6548f53, which assumes the axis of rotation is relative to world coordinates, which is more likely to be the desired behaviour. Still, it would be good to add a combobox allowing selection of the coordinate system for the axis of rotation: world (default), image, or eye/camera.

**Comment by rtabbara** [comment]
Added in 071ac6d
