### ISSUE TITLE
Testing: Move logfile location

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#2295]
Now that `run_tests` appends the name of the test performed to the file name, the *MRtrix3* root directory can get clogged with testing log files if a lot of different tests are performed. Preferable would be to have these files written to `testing/log/`.

**Comment by daljit46** [comment]
@Lestropie this seems outdated with our switch to CMake. Can we close this?

**Comment by Lestropie** [comment]
I'd actually prefer to do this and include it in `3.1.0` if that doesn't incorporate `cmake`. This is constantly irritating me. Should not be a difficult change.

**Comment by Lestropie** [comment]
Resolved by a41514d0228b286209049fc8a0e613b6cc6326ea.
