### ISSUE TITLE
MRView screen capture: add stop & rewind buttons

### ISSUE THREAD

**Issue by jdtournier** [MRtrix3/mrtrix3#231]
Currently, if we set a large number of frames and press go, there is no option to stop in case we made a mistake - we have to let it run or kill the viewer. Would be good to have a stop button to abort in this case, especially for expensive renders with a large number of frames...

A related issue is that it's not possible to set parameters and run them to see what they would do, then rewind to the same position to either try different parameters or record what we'd previewed. It would be good to have a rewind or undo button to reset all view parameters and frame index to what they were before the preview / record button was pressed.

Maybe we should also rename the 'preview' button to 'play'?

**Comment by draffelt** [comment]
Can we not just make the default preview behaviour reset to the start position when it ends?  In that case preview would be a more appropriate name than play.

**Comment by jdtournier** [comment]
Sure, that would help. But I still find myself needing to re-record some bits where it didn't come out quite right, and being able to rewind would be useful.

**Comment by rtabbara** [comment]
@jdtournier  I'll comment here but commit 071ac6d also looks at #229 and #230.

* Rotation can now be specified by World/Camera.

* Added stop and rewind controls within the screen capture tool. The included svg images for the control buttons come from the [Tango Desktop Project](http://tango.freedesktop.org/Tango_Icon_Library) which is in the public domain so I think we should be ok with respect to licensing.

* Rewind button simply plays back the preview in reverse. Talking to Dave and Rob, to remove any ambiguity on the behaviour of a rewind, any change in capture parameters or resetting the view will reset the start frame index to 0 to highlight to the user that they're creating a new animation.

* Rejigged how the volume parameters alter the image volume to make it reversible. Volume target control has been changed from an <code>AdjustButton</code> to a <code>QSpinBox</code> as the underlying value is ultimately cast to a <code>size_t</code> when setting the volume. As a result, if target < num. of frames then no volume change will occur, so not sure if you're happy with that behaviour.

**Comment by jdtournier** [comment]
@rtabbara : Thanks for taking this on, very much appreciated.

Just one concern:

> Rewind button simply plays back the preview in reverse. Talking to Dave and Rob, to remove any ambiguity on the behaviour of a rewind, any change in capture parameters or resetting the view will reset the start frame index to 0 to highlight to the user that they're creating a new animation.

I don't think this is the best way to deal with this. The use case I have in mind is that I'm half-way through making an animation (so I've already saved a bunch of frames), and I just want to check that the next set of parameters will actually do what I expect before recording proper. So I want the rewind button to reset the view _exactly_ as it was when I hit 'preview' - including the frame index if it was non-zero. Other similar use case: I hit record and realised my parameters were not quite right. In this case, I also want to come back to the _exact_ same state I was in before hitting 'record'. 

So what I'd rather see is that as the user hits the preview or record button, we save all the state information (probably best at the beginning of the `run()` function). If the user hits rewind, we set the UI with the saved state, to return everything as it was. 

So maybe 'rewind' wouldn't be quite the right word. We need something that indicates we're returning to the last key frame... 'Undo' might be a better word for it...?

**Comment by jdtournier** [comment]
Sorry, didn't twig about this one:

> Rejigged how the volume parameters alter the image volume to make it reversible. Volume target control has been changed from an AdjustButton to a QSpinBox as the underlying value is ultimately cast to a size_t when setting the volume. As a result, if target < num. of frames then no volume change will occur, so not sure if you're happy with that behaviour

Not sure this is necessary, and might make certain (admittedly rare) cases a bit tricky. What I'm thinking is that you need to change something about what is displayed at some point while running through volumes, and if you expressly prevent the target volume from being a floating-point value, you might end up not being able to make that switch when you need to. And I think if we use an approach like what I'd suggested in my previous comment, we should be able to save the state and re-apply without any issues. 

That said, I don't anticipate this will happen a great deal... It's just that we can support that use case with very little effort, so why not...?

**Comment by jdtournier** [comment]
@rtabbara : I just had a play with your changes, it all (mostly) looks good, just a few issues to iron out though:

- related to my last post: running through volumes doesn't work if the number of volumes between current and  target is less than the number of frames requested - I'm guessing this will be due to the cast to `size_t`. This is why I'd implemented an approach based on floating-point values. I might seem a bit weird at first, but it's the simplest way to advance by (for example) 20 volumes in 100 frames...

- I notice you only allow 2 digits on the volume counter in the screen capture tool - we routinely acquire images with hundreds of volumes... Of course, this wouldn't be issue if we decide to switch back to the AdjustButton, but needs fixing if otherwise.

- I notice the View tool popped up with a volume index of zero when the volume had already been changed to something else. Might need to call whatever the update function is on show()...

- I can't call two previews back to back. If I run a preview (say a 360 rotate), clicking the preview button again does nothing. Clearly, I should be able to keep going from there. Not sure whether this is related to how the rewind is implemented, but if we decide to go for the approach I'd mentioned above, I don't think this would be an issue...

- Finally, I got a segfault when playing around with the volume controls on the screen capture. Not sure whether it was related to me playing around with the volume index in the View tool at the same time...

So, a few decisions to make on the UI, which are up for discussion with @draffelt & @Lestropie  (and anyone else with a view on the matter), and then there may be a few remaining niggles to sort out...

Cheers,
Donald.

**Comment by rtabbara** [comment]
@jdtournier Thanks taking a thorough look at this. I think I've sorted out the issues you've mentioned in 145c64b94a. In particular, I've replaced rewind with a restore control, that restores the view state prior to the last play sequence. The underlying cache of states is stacked, so you can use restore multiple times (I've chosen a max. of 10 play sequences, but we can always adjust that).

**Comment by jdtournier** [comment]
Cool, that sounds great - I wasn't sure about asking for a full undo stack... but great that you took the initiative!

And I much prefer _restore_ to both _undo_ or _rewind_ - good choice.

I'll have a look at this when I have a minute...

**Comment by jdtournier** [comment]
Ahem - just gave it a shot:

```
QObject::connect: No such slot MR::GUI::MRView::Tool::Capture::reset()
QObject::connect: No such slot MR::GUI::MRView::Tool::Capture::reset(int)
```

and the preview button did nothing when I set the rotation angle to 360 and the number of frames to 100... Worked eventually after I'd tried other types of motion, for some reason. 

But once I'd got to work, it worked great... One minor non-essential improvement if you have the time and the inclination would be to store and restore the UI parameters as well as the actual view settings - this would mean you could go back 2 steps and modify from there (rather than remember all the settings you used for that set of frames). Would be useful, I think. But really, a single level of restore is by far the most useful, and the UI doesn't need to restored in that case - it's only possible / an issue because you've added a full restore stack...

**Comment by rtabbara** [comment]
@jdtournier Sorry, both issues should be sorted now. 

<blockquote>
One minor non-essential improvement if you have the time and the inclination would be to store and restore the UI parameters as well as the actual view settings
</blockquote>

Is it ok to create a new issue for this? There's 3 open issues related to these changes and it would be great for my self-esteem if we could knock them off.

**Comment by jdtournier** [comment]
By all means. Anything to bolster the self-esteem of our contributors!

**Comment by rtabbara** [comment]
Added in 071ac6d

**Comment by jdtournier** [comment]
@rtabbara: just noticed a few quirks with the capture tool... Just trying to grab a single frame, first frame is fine, second grab overwrites the first, despite the frame counter having been incremented. My guess is it's being reset by the record button, which shouldn't happen...

Also, I couldn't change the frame index manually at all. We need to be able to do set it manually, it comes in handy when doing long captures, etc.

**Comment by rtabbara** [comment]
@jdtournier Originally, I was confused with the behaviour that the start index could be greater than the total number of frames. In particular, if you let the animation run a few times, the start index rises ever higher and pretty soon you're needing to do modular arithmetic in your head to figure out where you are in the animation. Doing maths in your head is never enjoyable.

So I slightly changed the design of this so that start index is bound between 0 and the num. of frames to line up with my expectation that these parameters represent the current and total time of the animation. Now, when your start index = num. of frames and you play/record, the start index is reset to 0 and the animation restarts.

If you're not happy with that, then it's an easy enough change. Alternatively, if you want to capture the same animation multiple times then we could add a repeat combo box and append a suffix r0, r1, ..., to the file names (in the case that repeat > 0). This has an added benefit that when a user is digging through their screen-shots they can more easily group their animations together.

**Comment by jdtournier** [comment]
OK, it looks like we have different ideas about how the capture tool is supposed to work. The way we designed it initially (actually, I think it was mostly @draffelt) was that you could capture a set of frames with a given set of UI parameters, then change UI parameters to grab the next set of frames from that point, with the index carrying on from the last set of frames. This makes it possible to quickly grab fairly complex movies by simply setting up your operation for the _next_  _n_ frames, then setting up the operation for next _m_ frames after that, etc, with frame numbers incrementing smoothly, and no glitches in the transitions. 

For this to work, the index _has_ to be allowed to take on arbitrary values, and should only be reset to zero if explicitly requested by the user, or if the name of the output file changes (what it was before). The rewind operation also can modify it, but only to set it back to what it was at the start of the current operation.

Does that make sense...?

**Comment by rtabbara** [comment]
@jdtournier I've reverted the screen capture behaviour so hopefully it should now be what you're after. Please let me know how it goes.

**Comment by jdtournier** [comment]
@rtabbara just had a go with your latest changes - it makes creating movies so much easier... It just so happens that I needed to create a movie today, but using the `mrview_no_odf_preview` branch (which still used the old UI), and it was painful... This makes it way easier. 

Thanks for all your efforts on this one! Time to close it off, I think.
