### ISSUE TITLE
ENH dwidenoise: Optionally output degrees of freedom map

### ISSUE THREAD

**Issue by tsalo** [MRtrix3/mrtrix3#2312]
**Is your feature request related to a problem? Please describe.**

I am interested in using `dwidenoise` on fMRI data, as proposed in [Adhikari et al. (2019)](https://doi.org/10.1007/s11682-018-9941-x), but I am concerned about the reduced degrees of freedom associated with using denoised data in later analyses. If possible, I'd like to be able to access those degrees of freedom.

**Describe the solution you'd like**

I think it would be great if there was an option for `dwidenoise` to output the averaged degrees of freedom map for the denoised data.

**Describe alternatives you've considered**

At the moment, I just ignore the variable degrees of freedom in my analyses, but I don't think that's optimal.

**Additional context**

This stems from this discussion on [the community forum](https://community.mrtrix.org/t/degrees-of-freedom-after-applying-dwidenoise/4790).

**Comment by dchristiaens** [comment]
Hi Taylor,

I added an option `-rank` to output what you're after. Can you test it?
```
git fetch
git checkout denoising_outputrank
./build bin/dwidenoise
```

Cheers
Daan

**Comment by tsalo** [comment]
It seems to work well, thank you! I was a little surprised to find that the rank values for a test file were all integers. I don't know how `dwidenoise` defines local neighborhoods to run MP-PCA on, but I assumed that the approach involved moving searchlights, with each voxel's denoised output reflecting an average of denoised versions from overlapping searchlights. If that's the case, wouldn't non-integer ranks be possible?

**Comment by dchristiaens** [comment]
The rank is indeed strictly an integer. The implementation in `dwidenoise` follows the approach in Veraart et al., where MP-PCA is used in rectangular image patches around each voxel to denoise the signal _in that centre voxel_. Using a (weighted) average of the result in all overlapping patches, as you suggest, has been used in other papers and might be slightly better. However, this is not implemented yet.

**Comment by tsalo** [comment]
Thanks for the clarification!

**Comment by Lestropie** [comment]
@dchristiaens Want to make a PR for this for `3.1.0`? I've used it myself in a couple of contexts.

**Comment by dchristiaens** [comment]
Sure, PR created in #2340 😉 Closing this thread.
