### ISSUE TITLE
Error in connectome2tck documentation

### ISSUE THREAD

**Issue by nicdc** [MRtrix3/mrtrix3#2326]
Hello developers,

Noticed a small error on the connectome2tck documentation page in the example usage, where in two places instead of: 
connectome2tck 

the command used is:
tck2connectome

Doesn't look like it has tripped anyone up so far, and I'm happy to make the edits if that's possible..

Cheers,
Nick

![image](https://user-images.githubusercontent.com/33220837/119368548-6be0e200-bcb3-11eb-8029-e74bf4e90cf4.png)

**Comment by jdtournier** [comment]
I would encourage to make the changes yourself and submit them as a pull request - [some instructions on how to do that on the GitHub docs](https://docs.github.com/en/github/getting-started-with-github/quickstart/fork-a-repo#:~:text=A%20fork%20is%20a%20copy,without%20affecting%20the%20original%20project.). That way you get the credit for your changes. :wink: 

The place to make these modifications is [cmd/connectome2tck.cpp](https://github.com/MRtrix3/mrtrix3/blob/master/cmd/connectome2tck.cpp#L111). But the changes will also need to be propagated to the corresponding help page in the `docs/` folder before the automated testing will accept them. You can do by making your changes, then:
```
./build
./docs/generate_user_docs.sh
```
then you can `git commit` the changes to both the `cmd/connectome2tck.cpp` file (which you will have made) and `docs/reference/commands/connectome2tck.rst` file (which will have been made by the `generate_user_docs.sh` script. Hope this makes sense, don't hesitate to ask if you need help here!
