### ISSUE TITLE
Copyright header check failure

### ISSUE THREAD

**Issue by nicdc** [MRtrix3/mrtrix3#2337]
Hi developers, 

I was trying to add labelconvert files for the Schaefer 2018 atlas to the share folder, but the check keeps failing at the "check copyright headers" step. 

I copied the notice as is from another file, but that didn't fix it. What am I missing? (pull request #2330 )

Thanks,
Nick

**Comment by jdtournier** [comment]
I'm not sure, but given that the diff shows (non) differences for basically the entire file (not just the copyright header), I'd suspect this will be due to the use of DOS rather than Unix newlines... Did you prepare this file on a Windows system...?

**Comment by nicdc** [comment]
Oh, yes I did! Will redo in Unix..

Thanks!

**Comment by nicdc** [comment]
@jdtournier , it worked now. Thanks!
