### ISSUE TITLE
mrview: Overlay colour map inversion not updated

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#2339]
When dealing with multiple overlay images, it appears as though the check box on the colour map button for toggling inversion of the colour map is not updated when the overlay image selection changes. This means that the presented status of colour map inversion does not match what is being displayed for the selected overlay(s), and in that instance the colour map inversion control needs to be toggled twice in order to enact a change.

**Comment by tbschuster** [comment]
Closed with #2354
