### ISSUE TITLE
revpe_distcorr: Support LR phase reversal

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#235]
I initially omitted specifying the phase-encode axis from the revpe_distcorr script to make it as accessible as possible, and intuitive for the most common use case. But it would be preferable to still be able to process data with L>>R phase encode reversal.

I was thinking, instead of requiring an integer argument for the phase encode axis, I could instead have two separate scripts: `revpe_distcorr_ap` and `revpe_distcorr_lr`, that call the same back-end script but don't require that magic-number PE axis at the command-line which may confuse some users. Thoughts?

**Comment by jdtournier** [comment]
Well, we're acquiring data cycling through all 4 PE directions... But I don't think you necessarily need to support that case... :smile:

**Comment by Lestropie** [comment]
Well... yes. The idea was to support the most common use case without requiring an extensive understanding of the `topup` and `eddy` interfaces. Once you start dealing with fancy acquisitions like that, you need a different interface.

But if I moved 95% of `revpe_distcorr` to the `lib/` directory, and had `revpe_distcorr_ap` and `revpe_distcorr_lr` as interface scripts, you could probably still use the bulk of the code in your case; you'd just need to either provide the FSL config files at the command line, or hard-code a script for your particular acquisition.

The main question is whether you think having two separate scripts e.g. `revpe_distcorr_ap` and `revpe_distcorr_lr` is more user-friendly than requiring the user to type the phase-encode axis as an argument every time they run it.

**Comment by jdtournier** [comment]
Well, my personal preference would be to keep the number of commands down - especially for a command that does the same thing with different arguments, which is essentially what this is. If you had syntax like `revpe_distcorr lr ...`, I think it would be clearer: the command is clearly: do distortion correction; the information needed to do that is that's it's LR... And you wouldn't even affect the character count...

**Comment by Lestropie** [comment]
Yes, I guess if it accepted either an integer for the PE axis or an 'LR' / 'AP' designation that would be OK. And if people try to run the script without it, I should be able to detect as such and give an appropriate error.

**Comment by jdtournier** [comment]
By the way, do you distinguish between AP & PA, etc...? Presumably you'll support all 4 directions?

**Comment by Lestropie** [comment]
Currently, the precise assumptions are:
* Phase encode (and reversal) occurs along axis 1 (which is about to become not-an-assumption).
* The DWI volume is acquired with the same PE direction as the _first_ image in the reversed-PE pair.
So if your DWIs happened to be acquired P>>A, you'd just provide the P>>A b=0 image _before_ the A>>P b=0 image, then the DWIs. Only difference would be that the estimated field offsets would be inverted; but for the sake of regularisation / image reconstruction this would have no effect... AS LONG AS the DWIs have the same PE direction as the FIRST volume in the pair.

If you're doing anything more fancy than that, you'll need to manually provide the config files (which will be difficult to support without creating a new script). I designed this script as it is purposefully so that most users would _not_ need to provide those files.

**Comment by jdtournier** [comment]
Sounds sensible.
