### ISSUE TITLE
mrtrix3 docker - fslsplit missing

### ISSUE THREAD

**Issue by chiara111p111** [MRtrix3/mrtrix3#2360]
Hi everyone,

I've recently started using MRtrix3 container to do a dMRI analysis (eddy preprocessing and quad analysis). 
In particular I've used dwifslpreproc command:

`docker run --rm -it \
                        -v $input_folder/$pos/$pzt/$weight/dMRI_SS/1:/input \
                        -v $output_folder/$pos/$pzt/$weight/:/work \
                        mrtrix3 dwifslpreproc \
                        /input/$nifti \
                        /work/dwi.mif \
                        -rpe_none \
                        -eddy_options " --slm=linear --cnr_maps" \
                        -pe_dir AP \
                        -fslgrad /input/$bvec /input/$bval \
                        -eddyqc_all directory -force`

The problem presented after I insert _--cnr_maps_ option. Doing so, I obtained this warning:

`[WARNING] Error running automated EddyQC tool 'eddy_quad'; QC data written to "/work/directory" will be files from "eddy" only`

and quad analysis wasn't done.

Rerunning in debug mode I've found that the error is given by fslsplit missing:

`Running $FSLDIR/bin/fslsplit dwi_post_eddy.eddy_cnr_maps.nii.gz dwi_post_eddy.qc/cnr
/bin/sh: 1: /opt/fsl/bin/fslsplit: not found
Traceback (most recent call last):
  File "/opt/fsl/bin/eddy_quad", line 54, in <module>
    main(args.eddyBase, args.eddyIdx, args.eddyParams, args.mask, args.bvals, args.bvecs, args.output_dir, args.field, args.slspec, args.verbose)
  File "/opt/fsl/fslpython/envs/fslpython/lib/python3.7/site-packages/eddy_qc/QUAD/quad.py", line 377, in main
    quad_cnr_maps.main(pp, data, eddyOutput)
  File "/opt/fsl/fslpython/envs/fslpython/lib/python3.7/site-packages/eddy_qc/QUAD/quad_cnr_maps.py", line 38, in main
    fslpy.fslsplit(eddy['cnrFile'], data['qc_path'] + '/cnr')
  File "/opt/fsl/fslpython/envs/fslpython/lib/python3.7/site-packages/eddy_qc/utils/fslpy.py", line 28, in fslsplit
    jobout = check_output(cmd, shell=True)
  File "/opt/fsl/fslpython/envs/fslpython/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/opt/fsl/fslpython/envs/fslpython/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '$FSLDIR/bin/fslsplit dwi_post_eddy.eddy_cnr_maps.nii.gz dwi_post_eddy.qc/cnr' returned non-zero exit status 127.`

I don't know if something went wrong while building the docker image or there is something wrong elsewhere.
I'm working on Ubuntu 18.04.4 LTS.

Kindly regards,
Chiara

**Comment by Lestropie** [comment]
Thanks for the report Chiara.

Construction of the containers on executing a set of pre-specified tests that are intended to identify those components of external neuroimaging software packages that need to be retained to preserve functionality, versus those that can be deleted to reduce container size (as well as the scope of those packages that are distributed externally to their own creators). So it seems that including that option follows a code path that those tests do not currently execute, and requires commands that are excluded through that process. I will need to include the `--cnr_maps` flag in one of those tests, re-generate the minified dependencies, modify the container recipes, and re-build the container. While this won't work for `3.0.3` as that is an immutable tag, I should at least be able to build a new working container and push it to DockerHub where it will appear as "`latest`" until the next *MRtrix3* tag update.

I'll try to post progress updates here.

**Comment by Lestropie** [comment]
Closed by 1d345b0, to be merged to `master` as part of #2370.
