### ISSUE TITLE
Updates to dwi2qbi

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#24]
* Command is still using the old multi-threading interface.
* It seems to be using the one normalisation boolean flag both for b=0 normalisation on image load, and min-max normalisation after FRT. These should be two different options.

**Comment by jdtournier** [comment]
Is this issue still current? It seems to be using the Image::ThreadedLoop interface since commit c760019ab... Although the issue about the two different normalisations remains outstanding...

**Comment by Lestropie** [comment]
Closing since `dwi2odf` was intentionally omitted from the `updated_syntax` port.

If anyone _really_ wants it, maybe it should be re-implemented as an algorithm option in `dwi2fod`? (Perhaps with a rename to `dwi2odf`?)

**Comment by thijsdhollander** [comment]
Nah, QBI is not worth renaming dwi2fod for, I'd say.  Let's just silently forget about QBI altogether... :smile:

**Comment by draffelt** [comment]
Agreed
