### ISSUE TITLE
RGB Volume overlay not working

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#240]
In volume render mode, opening the main image as RGB renders fine, but opening the same image as an overlay when in volume render mode results in a whole lot of white.

**Comment by thijsdhollander** [comment]
Ok, don't ask me how I stumbled upon this, but: apparently, when selecting "RGB" as the colour map in the Overlay tool, the overlay in question suddenly ignores the scaling range settings in the Overlay tool, *but lives by the intensity scaling settings in the View options tool*.  You can see this in action most easily by adding a clip plane to your main image, then RMB adjusting the contrast/brightness: the RGB overlay will happily play along...
