### ISSUE TITLE
mrview: libQt5Core.so.5 missing from mrtrix3 docker container

### ISSUE THREAD

**Issue by ulloaa** [MRtrix3/mrtrix3#2428]
I pulled the docker container for mrtrix 3.0.3, then I converted to singularity. All commands seems to work except for mrview:

mrview
mrview: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory

Is libQt5Core.so.5 missing from the docker container?

Thanks,

**Comment by Lestropie** [comment]
`mrview` worked under Singularity for me and I think one other person testing it when the containers were put together. But to be honest, the operation of GUI commands within containers is still black magic to me...

First thing I would ask is to test:
-  Building the Singularity container directly from the Singularity recipe;
-  Building the Singularity container directly from the Docker recipe.

Also if you could quote exactly what you used to "convert" from Docker to Singularity.
(I recall back when I first participated in the BIDS Apps work, there was a ` docker2singularity` project that was used, but it essentially became deprecated when Singularity itself began supporting Docker recipes)

What works / doesn't work for you will hopefully give some clue as to where something needs to change, and would also give me a better probability of replicating the specific issue; fixing issues is exceptionally difficult when a developer can't replicate it locally.

**Comment by ulloaa** [comment]
Thanks for the quick response!

I pulled the mrtrix docker container (from docker hub) using the singularity recipe:

```
Bootstrap: docker
From: mrtrix3/mrtrix3:3.0.3
 
%environment
   export LC_ALL=C
```

and this is the error I get when running `mrview` (all other, non-GUI commands work):

`mrview: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory`

I looked carefully inside the container, though, and I do see `libQt5Core.so.5` in the directory:

`/usr/lib/x86_64-linux-gnu/`

However, `libQt5Core.so.5` is the only library not found, as shown by `ldd`:

```
ldd mrview
	linux-vdso.so.1 (0x00002aaaaaad5000)
	libmrtrix.so => /opt/mrtrix3/bin/./../lib/libmrtrix.so (0x00002aaaaadbb000)
	libQt5Widgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 (0x00002aaaab074000)
	libQt5Gui.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00002aaaab6cb000)
	libQt5Network.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Network.so.5 (0x00002aaaabc56000)
	libQt5Core.so.5 => not found
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00002aaaabdf9000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00002aaaabe8d000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00002aaaabeae000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00002aaaac032000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00002aaaac1b5000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00002aaaac1cf000)
	/lib64/ld-linux-x86-64.so.2 (0x00002aaaaaaab000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00002aaaac392000)
	libtiff.so.5 => /usr/lib/x86_64-linux-gnu/libtiff.so.5 (0x00002aaaac5b0000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00002aaaac631000)
	libQt5Core.so.5 => not found
	libQt5Core.so.5 => not found
	libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00002aaaac66a000)
	libQt5Core.so.5 => not found
	libGLX.so.0 => /usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x00002aaaac767000)
	libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00002aaaac79b000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00002aaaac858000)
	libwebp.so.6 => /usr/lib/x86_64-linux-gnu/libwebp.so.6 (0x00002aaaac85d000)
	libzstd.so.1 => /usr/lib/x86_64-linux-gnu/libzstd.so.1 (0x00002aaaac8ca000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00002aaaac969000)
	libjbig.so.0 => /usr/lib/x86_64-linux-gnu/libjbig.so.0 (0x00002aaaac991000)
	libjpeg.so.62 => /usr/lib/x86_64-linux-gnu/libjpeg.so.62 (0x00002aaaacb9f000)
	libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00002aaaacc0a000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00002aaaacd29000)
	libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00002aaaacde7000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00002aaaace14000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00002aaaacf55000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00002aaaad167000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00002aaaad1db000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00002aaaad207000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00002aaaad40b000)
	libbsd.so.0 => /usr/lib/x86_64-linux-gnu/libbsd.so.0 (0x00002aaaad611000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00002aaaad62b000)
```

Even after adding `/usr/lib/x86_64-linux-gnu/` to `LD_LIBRARY_PATH` inside the container, `mrview` is unable to see  `libQt5Core.so.5`.

I think you are correct to suspect that something must have gone wrong during the conversion. Sorry I labeled my post "BUG". Feel free to remove this label. I will go ahead and build the container directly from the Singularity recipe.

**Comment by smeisler** [comment]
Hi,

There was a similar issue in DSI Studio discussed here: https://github.com/frankyeh/DSI-Studio/issues/69

If you are facing issues specifically in CentOs7, perhaps the changes to the dockerfile that solved the problem there may be relevant.

```
# Fix issues: Singularity container cannot load libQt5Core.so.5 on CentOS 7
RUN strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
RUN ldconfig
```

Best,
Steven

**Comment by Lestropie** [comment]
I've pushed a [container](https://hub.docker.com/layers/200683051/mrtrix3/mrtrix3/test_mrview_centos/images/sha256-d59b55a7b8665bc160366cd918fbd44b91fa9d5bb03e0d20c6ae0aede3a5d730?context=repo) that includes the proposed modification. However I don't have a CentOS system on which to either replicate the problem or evaluate the fix. If @ulloaa or anyone else out there can test this solution it would be much appreciated:
```
sudo singularity build MRtrix3_CentOStest.sif docker://mrtrix3/mrtrix3:test_mrview_centos
singularity exec -B /run MRtrix3_CentOStest.sif mrview
```

**Comment by smeisler** [comment]
I get the following error:

```
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
```

**Comment by Lestropie** [comment]
I saw this same error when experimenting with getting `mrview` to work without warning / error in Docker (see #2461). I've got a feeling that in that context, that particular error was produced when I failed to first execute the "`xhost +local:root`" line. If you run with a clean environment but through `sudo` does that work?

I imagine that if environment variables are cleaned, you may need to re-introduce some set of minimal envvars to get GUI to work; you could try combinations of:

- $DISPLAY
- $XDG_RUNTIME_DIR
- $UID

The other command-line flag I introduced there was "--device /dev/dri/". Don't know what the equivalent for Singularity looks like, but if the envvars above don't work this will need to be looked into.

**Comment by Lestropie** [comment]
I was able to replicate that error message outside of CentOS, and found that the solutions proposed in 
d520709 work. I will do a final batch of testing to see if the proposed CentOS fix is deleterious on any other system as part of #2370.
