### ISSUE TITLE
DWI to ADC map

### ISSUE THREAD

**Issue by smcch** [MRtrix3/mrtrix3#2429]
Hi!

Sorry for this silly question, but how can I use the function **dwi2adc**.  I can't find any example or tutorial.
I have the DWI NIFTI, bvals and bvec files. What is the right way to write the command?

Thanks

**Comment by dchristiaens** [comment]
You can get the docs with `dwi2adc -help` or read them online [here](https://mrtrix.readthedocs.io/en/latest/reference/commands/dwi2adc.html#dwi2adc).

Please direct user questions to the [forum](https://community.mrtrix.org) and use GitHub for technical issues only.

**Comment by Lestropie** [comment]
The `dwi2adc` interface is unfortunately quite clumsy right now, in that it requires trace-weighted volumes rather than individual DWIs, and requires construction of a gradient table to correspond to those trace-weighted volumes. #2195 would make this command behave as one would intuitively expect.
