### ISSUE TITLE
MRview tools: Visibility eye button

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#244]
1. Flip button depress behaviour so that default state is depressed which means 'visible', and clicking causes the button to raise.

2. Add a second icon, with an eye with a red cross through it. Show this icon when the button is raised (i.e. 'can't see anything').

**Comment by thijsdhollander** [comment]
So I fixed this in d938666a43ee994326110faf787397a8c36acfec , but not like in the description above.  While thinking about it, I remembered that a push-type button changing its label/icon is universally considered rather bad UI design: users always get confused whether the icon refers to either the current state, or the action that will happen when clicking the button.  The best way to have a switch behaviour done by a normal push-type button, is simply having 1 label/icon that depicts its main function.  When the button is pressed, it means the function is engaged; when depressed... well, you get the picture.  Just like the play (or pause, or record) buttons on that good old cassette deck.  Or also: just like a check box.
The main function here being "hiding everything", the solution was simply to make the icon depict that.  Hence, not an eye; but an eye with a red cross through it.  It only affects the actual loaded things/overlays when engaged: i.e. only then does it override the individual visibility check boxes by hiding everything.

While I was at it, I also made the tools tips for all the "hide all *somethings*" consistent.  And then also the load/close tool tips.  And then also some capitalisation things.  On the latter: I noticed that 90+ % of all tool tips and certain other specific kinds of texts were starting with an upper case and have all the other words lower case (except for possible acronyms, such as "ROI").  Suddenly I started seeing 9% that didn't, scattered around in random places (having either no upper case for the first word, or all, or even just some words capitalized -- the stuff of nightmares!).  Fixed those, and quite probably still missed 1%.
