### ISSUE TITLE
Problems during installation[command]: [bug report title]

### ISSUE THREAD

**Issue by 406354348** [MRtrix3/mrtrix3#2457]
./configure: line 2: $'\r': command not found
./configure: line 17: $'\r': command not found
./configure: line 19: $'\r': command not found
./configure: line 22: $'\r': command not found
./configure: line 159: syntax error near unexpected token `('
'/configure: line 159: `        The command to invoke Qt's qmake (default: qmake).

**Comment by Lestropie** [comment]
Thanks for the report. Most likely a developer's `git` is not configured correctly, and this has resulted in Windows-style newline characters making their way into repository code that is supposed to conform to Unix-style convention. We will need to look into this one quickly.

At your end you might have some success by locally editing file `configure`, specifically with a text editing tool that has the functionality to do a bulk line ending encoding change across an entire file. Select "Unix encoding '`\n`'", save, and re-try running.

**Comment by bjeurissen** [comment]
> Thanks for the report. Most likely a developer's `git` is not configured correctly, and this has resulted in Windows-style newline characters making their way into repository code that is supposed to conform to Unix-style convention. We will need to look into this one quickly.

Wouldn’t the CI tests have caught that?

**Comment by 406354348** [comment]
I edit the configure file and change it to UNIX encoding, but there will still be syntax errors, which can be found in the Linux system.
(dki) jht@lab333tesla-Precision-7920-Tower:/data/jht/mrtrix3$ bash ./configure 
./configure: line 159: syntax error near unexpected token `('
./configure: line 159: `        The command to invoke Qt's qmake (default: qmake).'
(dki) jht@lab333tesla-Precision-7920-Tower:/data/jht/mrtrix3$ bash ./build
./build: line 23: usage_string: command not found
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/358.
from: can't read /var/mail/timeit
./build: line 118: syntax error near unexpected token `and'
./build: line 118: `if sys.executable[0].isalpha() and sys.executable[1] == ':':'

**Comment by Lestropie** [comment]
@406354348 can you let us know what OS you are operating on? And if it happens to be Windows, which platform (ie. MSYS2 or WSL); and if MSYS2, can you confirm that you are using the [correct shell shortcut](https://www.mrtrix.org/download/windows-msys2/)? There can be issues with selection of the right version of Python if the wrong shortcut is used, which could maybe conceivably lead to something like this.

**Comment by bjeurissen** [comment]
In the above you are running``bash ./configure`` causing python code to be interpreted by bash, which is not possible.

Instead run ``./configure`` to use the interpreter specified after the script or if that does not work ``python3 ./configure``
