### ISSUE TITLE
Singularity build: Do not remove /tmp/*

### ISSUE THREAD

**Issue by celstark** [MRtrix3/mrtrix3#2469]
The [Singularity build file](https://github.com/MRtrix3/mrtrix3/blob/026e850d171ec2a12f09865d31b8332d23d7ecf6/Singularity#L65) has, at the end of it:
`rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*`

This is a known issue in that it tries to **remove /tmp on the host** during build:
https://github.com/apptainer/singularity/issues/2538
https://github.com/ReproNim/neurodocker/issues/246
https://github.com/ReproNim/neurodocker/commit/412f4819319d6e1693cb43f31f88267cc63af28b

By default `/tmp` in the container is bound to `/tmp` in the host. So, if your users do something like `sudo singularity build` and have the rights, you're in a whole mess of trouble.  If you want your own temp space, make a sub-folder and remove that.  But, don't remove everything in /tmp or /var/tmp.

**Comment by Lestropie** [comment]
Whoops! Wrote a response, and committed a change to resolve, but apparently failed to hit the send button on the message.

Thanks for the report @celstark; I've added the fix to the contents of #2370 that are awaiting merge for version `3.0.4`.
