### ISSUE TITLE
mrview load multiple overlays

### ISSUE THREAD

**Issue by maxpietsch** [MRtrix3/mrtrix3#247]
-overlay.load in mrview can only be specified once. How can one pass multiple images to it?

**Comment by jdtournier** [comment]
Ahem... By fixing the code. Does 1f0efb4 do it for you?

**Comment by maxpietsch** [comment]
I tried that as well. I get [ERROR] multiple instances of option "overlay.load" are not allowed.

**Comment by jdtournier** [comment]
Weird... I'll look into that when I have a minute.

**Comment by Lestropie** [comment]
1f0efb4 specifies the `.allow_multiple()` on the _argument_, not the _option_. So try:
`mrview -overlay.load image1 image2`

**Comment by jdtournier** [comment]
Duh. Sorry, being an idiot...

Can't have `allow_multiple ()` on option arguments, it leads to ambiguous parsing of the command-line (can't figure out if argument 2 is for the option or the next main argument, etc). 

Just need to set that on the Option itself...

**Comment by maxpietsch** [comment]
Fixed with 2108cadff2ffd6eff6d24cfd6b2517c51e3ae26a.
