### ISSUE TITLE
./build: progress indication misbehaves on a system with many cores

### ISSUE THREAD

**Issue by bjeurissen** [MRtrix3/mrtrix3#2492]
On a system with 128 "cores" (Ubuntu 20.04 LTS, 2 x AMD EPYC 7452 with hyper-threading), I noticed the total number of compilation jobs seems to change between threads:

```
...
(386/391) [LB] bin/warpinit
(384/396) [LB] bin/warpcorrect
(379/392) [LB] bin/tsfinfo
(380/391) [LB] bin/mrdegibbs
(382/392) [LB] bin/amp2response
(392/391) [LB] bin/dwidenoise
(393/396) [LB] bin/tckmap
(394/392) [LB] bin/mrmetric
(395/391) [LB] bin/mraverageheader
(396/396) [LB] bin/mrmath
(397/397) [LB] bin/mrtransform
```

**Comment by jdtournier** [comment]
Yep, that's been the case for quite a while... Never found the time or motivation to fix it unfortunately. I might have a look again if I find the time, but as always, not very likely in the near future...
