### ISSUE TITLE
mrcentre: build errors

### ISSUE THREAD

**Issue by chrisadamsonmcri** [MRtrix3/mrtrix3#2498]
Please use this form for *bug reports only*; for installation problems, and general questions and support, please consult the [community forum](http://community.mrtrix.org/search?expanded=true).

**Describe the bug**

During build cmd/mrcentre.cpp returns compile errors.

Lines 61, 66, 72 are missing template arguments for Eigen::Vector3.

**To Reproduce**

./configure
./build

**Platform/Environment/Version**

Please provide the following information:

-  OS: Ubuntu 22.04

-  *MRtrix3* version e27a543fb3a2cb71abf70da631a1f902d00e0c53

Fix:

Replace  Eigen::Vector3 with  Eigen::Vector3d in each line.

**Comment by dchristiaens** [comment]
The command `mrcentre` has been renamed to `mrcentroid` in a9f90977367b3b2ca2710d868ccc6369e1dce75d.

To fix the compile error, please try running:
```
./build clean
./build
```
