### ISSUE TITLE
Overlay threshold issue

### ISSUE THREAD

**Issue by draffelt** [MRtrix3/mrtrix3#250]
When I overlay a binary mask then threshold the minimum value, the threshold needs to be > 0.5 before the background (all zero) voxel become transparent.

**Comment by thijsdhollander** [comment]
Also, when thresholding the maximum value, the threshold needs to be >= 1.495 for the foreground (all 1) to become opaque.

**Comment by jdtournier** [comment]
Probably related to using an integer data type? I'll have a look at the shader code...

**Comment by jdtournier** [comment]
OK, there's something off with the scaling - the (zero) background does not show as black with a bitwise image, but does with the same image in uint8 format...
