### ISSUE TITLE
ENH dwi2mask (dev): SynthStrip

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#2500]
https://www.sciencedirect.com/science/article/pii/S1053811922005900
https://surfer.nmr.mgh.harvard.edu/docs/synthstrip/

Simply one to add to the list.
On initial inspection it appears to be single-volume input only, ie. can't use multiple shells.

**Comment by bjeurissen** [comment]
Tried using it and seem to work as advertised

**Comment by Lestropie** [comment]
- [ ] Initial familiarization
    - [ ] Install latest FreeSurfer version
    - [ ] Execute `mri_synthstrip` on exemplar data
    - [ ] Examine command-line interface and options available

- [ ] Generate template `dwi2mask` algorithm
    - [ ] Ensure that the `dev` branch of *MRtrix3* is installed and working
    - [ ] Create copy of an existing `dwi2mask` algorithm with a new name
    - [ ] Ensure that "new" algorithm is accessible from the command-line through the `dwi2mask` interface
    - [ ] Ensure that behaviour of new algorithm is identical to that copied

- [ ] Generate implementation of SynthStrip-based `dwi2mask` algorithm
    - [ ] Generate mean *b*=0 image from DWI input
    - [ ] Convert to NIfTI format as required for compatibility with FreeSurfer
    - [ ] Capture output of SynthStrip and convert back into *MRtrix3* `.mif` format
        - [ ] Check if the SynthStrip output file has the same orientation as the image that was input to `dwi2mask`; if it does not, modify strides of `.mif` file to match that of the user's input DIW series
        - [ ] Make output file of bitwise data type
    - [ ] Implement command-line options that echo SynthStrip options, and feed any user-specified options to the SynthStrip command
    - [ ] Integrate SynthStrip algorithm into the `dwi2mask consensus` algorithm
    - [ ] *(Optional)* When generating NIfTI for input to SynthStrip, modify strides such that image conforms to the orientations used in network training; this will obviate the need for SynthStrip to perform this step internally

- [ ] Add external dependencies for new `dwi2mask` algorithm to containers
    - [ ] Repeat instructions in #2529 in this context

- [ ] Generate Pull Request
