### ISSUE TITLE
Conversion .bvec in .dvs file

### ISSUE THREAD

**Issue by Lolibike95** [MRtrix3/mrtrix3#2510]
Hi I am trying to convert a .bvec file into a .dvs format, since the idea is to use it into another scanner. Anyone knows a script or anything I can use in order to convert automatically?

**Comment by bjeurissen** [comment]
GitHub issues are meant to raise issues related to the development of MRtrix (bugs, feature requests, ...).

For seeking general advice, particularly from other MRtrix users, please use the community forum at https://community.mrtrix.org/.

You will find that other users have already inquired about converting to dvs: https://community.mrtrix.org/search?q=dvs
