### ISSUE TITLE
New release tag?

### ISSUE THREAD

**Issue by liamtimms** [MRtrix3/mrtrix3#2518]
Hi,

It would be helpful if mrtrix3 could tag a new release soon with the fixes that have been merged since the last tagged release. I have no issues when building mrtrix3 using the git main branch but run into compiler errors when using the last point release. 

Thank you

**Comment by jdtournier** [comment]
Hi Liam, 

This is very much on our todo list - but as always, it's difficult to find the time. We'll hopefully get there in the next few weeks...
You can track the current progress by looking at `[the 3.0.4 milestone](https://github.com/MRtrix3/mrtrix3/milestone/10)`. 
All the best, 

Donald
