### ISSUE TITLE
tckmap compilation on Windows

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#252]
```
[CC] cmd/tckmap__debug.o
ERROR: [CC] cmd/tckmap__debug.o

g++ -c -std=c++11 -pthread -DMRTRIX_WINDOWS -mms-bitfields -march=native -DMRTRIX_WORD64 -Wall -Wno-unused-function -Wno-unused-parameter -O0 -g -D_GLIBCXX_DEBUG=1 -D_GLIBCXX_DEBUG_PEDANTIC=1 -Isrc -Icmd -Ilib -Icmd -Ic:/gsl-1.15/include -DHAVE_INLINE cmd/tckmap.cpp -o cmd/tckmap__debug.o

failed with output

c:/Qt/482/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/as.exe: cmd/tckmap__debug.o: too many sections (36469)
C:\Users\rob\AppData\Local\Temp\ccSBFBub.s: Assembler messages:
C:\Users\rob\AppData\Local\Temp\ccSBFBub.s: Fatal error: can't write cmd/tckmap__debug.o: File too big
c:/Qt/482/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/as.exe: cmd/tckmap__debug.o: too many sections (36469)
C:\Users\rob\AppData\Local\Temp\ccSBFBub.s: Fatal error: can't close cmd/tckmap__debug.o: File too big
```

Will have to see if a newer version of GCC can deal with it...

EDIT: Nope, doesn't look like it... going to have to reduce the templating a little bit.

**Comment by jdtournier** [comment]
:astonished: wow! Serves you right for all the template gymnastics... :wink: Hopefully this doesn't happen in release mode...?

**Comment by Lestropie** [comment]
No, release seems to be fine. But I'll drop some of the not-likely-used templates.

**Comment by jdtournier** [comment]
:+1: 

Other option would be to split this up into multiple cpp files, each one instantiating its own data type. You can use C++11's new extern template declaration for that (I've just started to use it on the `updated_syntax` branch). But I reckon it wouldn't hurt to cut back on the number of templates a little bit...
