### ISSUE TITLE
ENH New DWI pre-processing command

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#2527]
Not sure what to call the issue as I'm not sure whether the approach should be implemented as an algorithm for an existing script or whether it should be standalone.

In MRtrix3_connectome I came up with the idea of combining brain masking, bias field correction, and intensity normalisation, into a single step. Relevant code is [here](https://github.com/bids-apps/MRtrix3_connectome/blob/0.5.3/mrtrix3_connectome.py#L1467-L1615). It's primarily a wrapper around `mtnormalise`, but:
-   Target output is bias field corrected and intensity normalized DWIs. Multi-tissue normalisation is the *mechanism* by which such is estimated, but unlike `mtnormalise` itself where the primary output is normalized ODFs, here it's the DWIs that are modulated.
-   The CSF *b*=0 intensity can be used as the reference image intensity.
-   The brain mask is estimated and refined based on `mtnormalise`, by selecting voxels where the sum of tissue signal fractions is at least 50%.

I would like to have this mechanism implemented as a stand-alone command that MRtrix3_connectome would simply invoke. Those who use *MRtrix3* but not MRtrix3_connectome would also be able to see if this approach works on their data. There may be some debate about whether such a script should be distributed with *MRtrix3* or whether it should be a stand-alone module.

Code placement and naming is difficult as it shares functionality with `dwi2mask`, `dwinormalise` / `mtnormalise`, and `dwibiascorrect` / `mtnormalize`.

**Comment by bjeurissen** [comment]
If it works well, I think it would be good to distribute with MRtrix3. Brain masking, bias field correction, and intensity normalisation are exactly the things that routinely break, so it would be really great to have a robust solution in place. I also like that it modulates the DWI's instead of the ODFs as it makes the pipeline more generic.

**Comment by Lestropie** [comment]
Closing as discussion can occur over at #2552.
