### ISSUE TITLE
ROI analysis ==> ROI editor

### ISSUE THREAD

**Issue by thijsdhollander** [MRtrix3/mrtrix3#254]
I mentioned somewhere in #219 that "ROI editor" seems a more sensible name, because that's what the tool actually is.  @jdtournier liked the suggestion as well.  What does everyone else think?

**Comment by draffelt** [comment]
Sounds good to me

**Comment by thijsdhollander** [comment]
Done, should be consistently changed everywhere now.  If anyone does still come across any mention of the old name, don't hesitate to change it.
