### ISSUE TITLE
mrview: Creating ProgressBar from another thread

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#256]
Whenever I create a ProgressBar within my connectome toolbar, I get the following in the terminal:

```
QObject::startTimer: Timers can only be used with threads started with QThread
QObject::killTimer: Timers cannot be stopped from another thread
```

Not critical, but kind of annoying; sometimes if a user selects some option that's going to take some time to load, I want to show a progressbar so they know the program hasn't hung.

**Comment by jdtournier** [comment]
OK, this is going to be a bit fiddly to deal with. In general, we want to keep all the GUI-related activity in the same thread - the rendering calls are unlikely to be thread-safe. I'm guessing the problem with the progressbar has to do with the delayed display feature: it'll only pop up after half a second or so. In a threaded loop, any one of the threads might trigger this - and any one of the threads might interact with the Qt class displaying the progressbar, it's not currently thread-safe... It should be easy to ditch the QTimer and use our own version, which would get rid of the message you're seeing - but we also need to make the update calls thread-safe. 

This should all be handled by overriding the progressbar's `display_func()` and `done_func()` calls for GUI applications, and will probably need special handling if Qt will only allow the same thread to update the progressbar. Not a trivial task...

On a related note, I'm also wondering whether it's worth ditching the non-threaded progressbar version. Currently the `display_func()` and `done_func()` calls default to a non thread-safe version, and get overridden to a thread-safe version in the thread backend before any actual threads are launched. Given how ubiquitous multi-threading has become in MRtrix, I reckon we get rid of that feature and simplify things to a single thread-safe version... Thoughts?

**Comment by Lestropie** [comment]
Right now I've got the ProgressBar class sitting in the slot function, and worker threads mutex before incrementing it. What I'm not sure about is whether or not the slot function itself is in fact executed in the main thread: when I start an intensive processing task in a slot function, I often get a GL window update while the heavy processing is still taking place, which would suggest it's not. Not being able to create progress dialogs in slot functions would not be very nice.

Related note: As long as the progress bar update only has to mutex every 1/30th of a second rather than each call, that's OK with me. If the progress bar's in a tight single-threaded loop, unnecessarily mutexing every time would be wasteful.

**Comment by jdtournier** [comment]
Yes, I'm pretty sure Qt calls the slot function directly within the same thread - even before returning from the `emit()` call, in fact. So that would m¡¡ explain that message.

As to locking the mutex within the tight loop, that's already how it works - even for the command line version... You have no choice on that front. However, `display_func()` is assumed expensive, and only invoked when an update is actually necessary...

**Comment by Lestropie** [comment]
Have not been able to reproduce original issue given #1586 pending. I'm pretty sure it's been quite some time since I've actually seen this specific warning. If nobody else has seen it for a while either, we might just close this?
