### ISSUE TITLE
switching from RGB colourmap to other "flattens" 4th dimension

### ISSUE THREAD

**Issue by maxpietsch** [MRtrix3/mrtrix3#257]
A bit difficult to describe:

Display a 4D image on any but the last slice position in dimension 4 with RGB colourmap. After changing the colourmap, the intensity values (shown, the cursor is fine) do not match the data of that slice but the combination of multiple slices. Changing the current slice position fixes the shown intensities.

**Comment by rtabbara** [comment]
@maxpietsch Think I tracked down the issue you're encountering. There's a fix for this in 36c6ac0.

Previously a 2d texture was only updated in the event of a slice or volume change. However, a change in the colourmap can require us to refresh the texture as we're potentially altering the underlying data format (e.g. from RGB to single-valued and vice versa).
