### ISSUE TITLE
Colours of ROI overlay in ROI tool too bright (as if windowed)

### ISSUE THREAD

**Issue by thijsdhollander** [MRtrix3/mrtrix3#259]
The colour that is shown/used in the overlay of a ROI (using the ROI tool) is not the colour as shown in the bottom left of the ROI tool panel.  It appears as if the actual colour used takes the RGB values as specified in the "Select Color" dialog box --these are in a 0-**255** range--, but then windows/thresholds/caps/.. these values at 100, and uses the resulting numbers as if in a 0-100 range.
Example: I select a nice orange somewhere in the middle of the basic colours in the "Select Color" dialog box.  It has RGB values 255,85,0 (each component in a 0-255 range); but in the overlay, it appears as 100,85,0 in a 0-100 range; that is, much too yellow.

**Comment by thijsdhollander** [comment]
So I had a simplistic go at fixing this in 80c9c7c1313fa06a8412f5608684a065c89b08b0 ... It feels a bit to silly to be true though... I have the feeling it has to do with all the types being thrown around (GLubyte, qreal, ...).  There might be a "more correct" way of fixing the original issue: anyone with a bit more experience in this (part of the code) is welcome to give my simplistic commit a check. :smirk:

**Comment by jdtournier** [comment]
I have a feeling this might be related to what was done to address issue #174 - @rtabbara specifically mentions 'punching up' the colour for the single colour mapping. And looking at `src/GUI/mrview/colourmap.cpp`, line 60, there is a factor of ~2.7, which is remarkably close to your factor of 2.55...

If that's the cause, then reverting the colour to its actual value would be the proper fix.

**Comment by thijsdhollander** [comment]
Yes, that seems to be it: did the engineering trial-and-error approach by testing either 2.55 and 2.7, screenshotting the results and using the Gimp's colour picker tool to compare the colours shown with the actual selected colours.  Using 2.7 is *almost* exact (whereas 2.55 is not quite as exact), but the results can still be off by 1 (out of 255) at times; I suppose this is due to rounding errors...

**Comment by thijsdhollander** [comment]
...now used the exact same value as it appears in `src/GUI/mrview/colourmap.cpp`... rounding errors are still present though.

**Comment by jdtournier** [comment]
Sorry, why not fix the colourmap itself...? Maybe you can discuss with @rtabbara, see what the rationale was for doing this in the first place, and whether the scaling in the colourmap is needed at all...

**Comment by thijsdhollander** [comment]
Okay, checked #174 a bit closer; it's indeed weird to have this factor in the colour map itself.  Took out the factor all together for the time being, so this issue is fixed in a clean way.

**Comment by rtabbara** [comment]
@thijsdhollander Thanks for picking this up and the fix.
