### ISSUE TITLE
tckgen: possible concurrency issues

### ISSUE THREAD

**Issue by jdtournier** [MRtrix3/mrtrix3#260]
While working on #225 and trying to port the tractography stuff, I got to have a good look at the newer seeding code (hadn't had a look into that side of things for a while...). If I understand correctly, the idea at the moment is to instantiate a single seeder class shared between threads, and invoke its virtual `get_seed()` method presumably with the expectation that it is thread-safe. I can see that some of the more obvious cases where concurrency would cause problems are handled with a mutex, but most seeders still use the shared random number generator _without_ locking. I'm assuming this is not desirable behaviour...

In general, each thread will have its own copy of a random number generator. We should try to refactor the code to allow using each thread's RNG, which would bypass any concurrency issues without needing to lock a mutex. The easiest for the seeder classes would be to modify the `get_seed()` call to take the RNG as an additional argument. 

We should also look for any other places where RNGs are declared, whether in a shared or thread-specific way, and try to modify things to allow passing the main thread's RNG. This would avoid a lot of these issues, keep things clean, and possibly also make it simpler to reproduce results if we supply a set RNG seed (although for tractography, this will only be guaranteed in a single-threaded context anyway).

**Comment by jdtournier** [comment]
Other option is to use [thread-local storage](http://en.cppreference.com/w/cpp/language/storage_duration) to hold a distinct RNG per thread... Although my preference is to use the more explicit approach I suggested above.

**Comment by Lestropie** [comment]
Yes, I keep forgetting to come back to this; I'm sure the topic came up at some point...

I guess I thought at the time that if there were a class for which multi-threading collisions wouldn't be a problem, it'd be an RNG. But you're right, shouldn't be too hard to pass each tracking thread's RNG through the function stack.

**Comment by jdtournier** [comment]
@Lestropie, agree the randomness of the numbers produced probably won't be affected - depending on the actual implementation of the generator. In any case, no need to do anything about this right this minute, I'll make sure I deal with it when porting over to Eigen in #225 (halfway through at the moment)...

**Comment by Lestropie** [comment]
Hopefully dealt with more elegantly as part of #342, and will therefore be included in `master` once #225 is merged.
