### ISSUE TITLE
mrview: 'help' menu?

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#261]
Currently the 'help' menu in mrview is really more of an 'about' menu.

This could be changed; or in the future when we have help information specifically for mrview, this could provide a link to e.g. the website.

**Comment by thijsdhollander** [comment]
So I changed it to "Info" (tooltip "information") for now.  That better represents the contents, but can even accommodate "helpish" items in the future as well!  The names of the menu entries match those of the titles of the windows that they open up.
