### ISSUE TITLE
Prevent deep multi-threading

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#263]
Many low-level operations are now multi-threaded. However if some high-level functionality is multi-threaded, and itself calls multi-threaded low-level operations, one could end up with e.g. 64 threads running instead of 8, which could cause slowdown.

It may be better to set an atomic flag to indicate that a multi-threaded process is running; and if another function requests number_of_threads(), it should return 0 and instead run in a strictly single-threaded manner, until the flag is released.

**Comment by Lestropie** [comment]
In a similar vein to this:

Some functors contain a progress bar, yet may be called within a loop which itself has a progress bar. A static atomic flag could be added to the progress bar by which a particular instantiation 'claims' the terminal output, and other progress bars do not appear.

**Comment by Lestropie** [comment]
On reflection, these could be toggled via [`static MR::Thread::__Backend backend`](https://ark.intel.com/products/64583/Intel-Xeon-Processor-E5-2680-20M-Cache-2_70-GHz-8_00-GTs-Intel-QPI).

**Comment by jdtournier** [comment]
I assume that link should have been [this one](https://github.com/MRtrix3/mrtrix3/blob/dev/core/thread.h#L89)...?

And yes, I agree this might be a good way to handle things. We could add a static method in there to query [the number of registered threads](https://github.com/MRtrix3/mrtrix3/blob/dev/core/thread.h#L87), and maybe compare that to the[ number that it's supposed to use](https://github.com/MRtrix3/mrtrix3/blob/dev/core/thread.h#L243)?

**Comment by Lestropie** [comment]
:rofl: Clipboard fail...

I probably didn't think about this enough: One thread within a multi-threading queue still needs to obtain terminal "privileges" for constructing a progress bar. So this mechanism in particular would still need its own dedicated atomic flag: Couldn't rely on one thread "claiming" the terminal before any other threads are even spawned. This should be handled by creating a ProgressBar within the constructor of any multi-threading class. But for preventing execution of nested multi-threading, simply testing if `backend` is non-zero should suffice (as far as I can tell).

I kept bouncing back to this while thinking about #984. But that's fundamentally a destructor throwing issue, not a multi-threading issue; keep seeing similarities where there are none... :-/

**Comment by Lestropie** [comment]
OK, I'm not convinced I can address the progress bar aspect of this.  Gave it a go with a `static std::atomic_lock` in the `ProgressBar` class for "claiming" terminal output... but it's entirely common for a worker thread to construct a ProgressBar instance before the outer loop does, meaning that the progress displayed at the terminal is in fact that of one specific worker thread rather than the expected outer loop message. I don't see an easy way to get this working as intended...

**Comment by jdtournier** [comment]
Do we have specific instances of where the progressbar is called within one or more threads? I'm struggling to understand the specifics of the issue...

**Comment by Lestropie** [comment]
I *did*; I'm just having trouble remembering what it was...

The issue is that if multiple ProgressBar instances are created by different threads, but you want only one of them to actually be displayed (so that they don't all flash on top of one another / concatenate in weird orders on the command-line), you need some mechanism by which to choose which ProgressBar instance to display and which to hide. The most logical solution to this is that the first instance to be created becomes the one that is displayed; any other instances constructed while that first instance still exists should detect that some other instance has "claimed" the command-line, and therefore the newer instance should self-censor. Now where this issue is most likely to arise is when you have a source / sink functor displaying a ProgressBar to indicate progress in a multi-threaded context, but the underlying task being performed by the worker threads itself tries to spawn a ProgressBar. There, one would cross their fingers and hope that the "outer loop" ProgressBar is created first, hence "locking out" the worker threads from printing anything to the command-line. However my attempt 5 days ago indicated that this was wishful thinking: what you commonly end up seeing on the terminal is a progress bar describing and tracking progress of one specific instance of the underlying task, rather than the progress of completing the total set of tasks to be performed.

**Comment by Lestropie** [comment]
Re-directing conversation from #1703.

> Where things might fall over is in a context where the top-level multi-threaded operation does not itself instantiate a ProgressBar at all, but invokes multiple tasks that do instantiate their own ProgressBar. 

If an underlying task is sufficiently computationally expensive to justify a `ProgressBar`, then the top-level operation warrants a `ProgressBar` even more so. So any not-entirely-sensible progress bars cropping up under such a scenario would be justifiably resolved on an individual basis.

> The only worry I have is with Thread::Queues where the source or sink instantiates the progressbar within its execute() call, rather than declaring the progressbar as a member. 

There are certainly some that have a `std::unique_ptr<ProgressBar>` as a member. Searching across these should expose any where such is initialised in the functor rather than the constructor, and I would expect that any such cases should be possible to change to the latter without too much hassle.

**Comment by Lestropie** [comment]
Closed by #1554.
