### ISSUE TITLE
mrview: [ERROR] GLSL log [vertex shader]: ERROR: 0:28: Use of undeclared identifier 'colourmap_colour'

### ISSUE THREAD

**Issue by bjeurissen** [MRtrix3/mrtrix3#2662]
When changing the color of a tck-file to File and then requisition the colormap 'Color', I get a GLSL crash because of an undeclared identifier 'colourmap_colour':

<img width="851" alt="Screenshot 2023-06-23 at 13 19 01" src="https://github.com/MRtrix3/mrtrix3/assets/5675416/467b266d-f8d5-4b82-8593-790a3cac9a81">

~~Not sure if this is specific to macOS.~~

**Comment by bjeurissen** [comment]
Same problem on Ubuntu 20.04

**Comment by bjeurissen** [comment]
This is the shader that crashes:

```glsl
#version 330 core
layout (location = 0) in vec3 vertex;
layout (location = 1) in vec3 prev_vertex;
layout (location = 2) in vec3 next_vertex;
layout (location = 3) in float amp;
uniform mat4 MVP;
uniform float line_thickness;
uniform vec3 screen_normal;
uniform float crop_var;
uniform float slab_width;
uniform float offset, scale;
uniform float scale_x, scale_y;
out vec3 v_tangent;
out vec2 v_end;
out float v_include;
out vec3 v_colour;
void main() {
  gl_Position = MVP * vec4(vertex, 1);
  v_tangent = next_vertex - prev_vertex;
  vec2 dir = mat3x2(MVP) * v_tangent;
  v_end = line_thickness * normalize (vec2 (dir.y/scale_x, -dir.x/scale_y));
  v_end.x *= scale_y; v_end.y *= scale_x;
  v_include = (dot(vertex, screen_normal) - crop_var) / slab_width;
  float amplitude = clamp ( scale * (amp - offset), 0.0, 1.0);
  vec3 color;
  color.rgb = amplitude * colourmap_colour;
  v_colour = color;
}
```
with the offending line being:

```glsl
  color.rgb = amplitude * colourmap_colour;
```

resulting in:

```
mrview: [ERROR] GLSL log [vertex shader]: ERROR: 0:26: Use of undeclared identifier 'colourmap_colour'
libc++abi: terminating due to uncaught exception of type MR::Exception
```

**Comment by bjeurissen** [comment]
If I understand correctly, the problem is that these two lines have not been executed in this particular use case:

https://github.com/MRtrix3/mrtrix3/blob/a5e5ae85c4a2f16efb720139b589523c6c755321/src/gui/mrview/displayable.h#L258

https://github.com/MRtrix3/mrtrix3/blob/a5e5ae85c4a2f16efb720139b589523c6c755321/src/gui/mrview/displayable.h#L280-L281

I suspect it must be a small fix, since all the other colormaps work.

**Comment by jdtournier** [comment]
@bjeurissen, check out #2667 and let me know if that works correctly now... I'll close this for now.
