### ISSUE TITLE
mrview dev branch: orientlabel is not backward compatible

### ISSUE THREAD

**Issue by treanus** [MRtrix3/mrtrix3#2687]
Dear developers,

seems the option -orientationlabel of mrview, has changed to -orientlabel recently?

That breaks backward compatibility, I guess?

KR,
Stefan

**Comment by Lestropie** [comment]
Correct: #2582

`dev` is a dangerous place to live if backward compatibility is a concern. We try to limit such things to minor tagged updates only (all of our 0 instances of such since production release... :disappointed: )
