### ISSUE TITLE
Unused files in the codebase

### ISSUE THREAD

**Issue by daljit46** [MRtrix3/mrtrix3#2696]
There are a few C++ source files in the codebase that are not used anywhere. I think these should either be removed completely or at least moved somewhere more appropriate. The files in question are:

- [src/registration/transform/robust.cpp](https://github.com/MRtrix3/mrtrix3/blob/dev/src/registration/transform/robust.cpp)
- [src/stats/permstack.cpp](https://github.com/MRtrix3/mrtrix3/blob/dev/src/stats/permstack.cpp)
- [src/stats/permstack.h](https://github.com/MRtrix3/mrtrix3/blob/dev/src/stats/permstack.h)

@jdtournier @Lestropie

**Comment by Lestropie** [comment]
`src/registration/transform/robust.cpp`: Need to check relevance to #2586, for which some code seems to have crept into #2678. It's possible it might be that the lack of use of the file may be indicative of an erroneously unused feature.

`permstack.*` I looked into this at one point and concluded that it was a vestigial leftover from #1543. As of `3.0.0` "shuffles" can now be permutations and/or sign flips, and signed integer matrices are used to represent this more general case; these are generated as required for the queue in `core/math/stats/shuffle.h`. So I think I should myself delete these two given I deprecated them.

**Comment by daljit46** [comment]
Note that `src/registration/transform/robust.cpp` also includes a `src/registration/transform/robust.h` which doesn't exist, so it can't even be compiled.

**Comment by Lestropie** [comment]
`robust.cpp` was added in fa108f5becec85930bd5a0fe70c0c917c4ac6a0d; the corresponding `.h` file seemingly [still resides](https://github.com/MRtrix3/mrtrix3/blob/6f052d4b5f95ad3dc8b17861ee095cc873f25820/src/registration/transform/robust.h) on the `mrreg` branch. @maxpietsch able to provide any insight on what should or should not be on `dev`?
