### ISSUE TITLE
clang-format in usage()

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#2701]
On having to edit the contents of a command's `usage()` function for the first time following merge of #2652, I'm immediately repulsed by the formatting of particularly `OPTIONS`. It's become much harder to navigate.

One prospect that I don't recall discussing in the relevant threads was to simply explicitly disable `clang-format` via code comments ([eg](https://bcain-llvm.readthedocs.io/projects/clang/en/latest/ClangFormatStyleOptions/#disabling-formatting-on-a-piece-of-code)).

Alternatively we can try to find a different syntax that plays better with `clang-format`; but that would likely lead to a hard backward compatibility break.

**Comment by daljit46** [comment]
Yes, I think using ``// clang-format off`` && ``// clang-format on`` to achieve a custom style for a particular piece of code would be the most appropriate.
