### ISSUE TITLE
Question about tck2connectome to compute filber length

### ISSUE THREAD

**Issue by duzc-Repos** [MRtrix3/mrtrix3#2707]
Hi, I computed the mean streamline length between each node pair following the example usage:
'tck2connectome tracks.tck nodes.mif distances.csv -scale_length -stat_edge mean -symmetric`
I was confused with the 0 values in output matrix. Does it mean that no fiber is constructed between that node pairs or the real average fiber length is very close to 0?

**Comment by Lestropie** [comment]
There must be no streamlines between those two regions. If there were streamlines of non-zero length, then the reported mean length would be non-zero.

The streamline length necessary to result in misleading truncation of the reported calculation to zero is of the order of 0.0000000000000001m; I'm guessing that your minimum streamline length is much larger than that. Indeed even if you did not set any minimum length for tractography, the fact that one streamline endpoint was assigned to one node and the other to a different node means that there must be some distance between the two endpoints of the streamline, and therefore the streamline length would have to be non-zero.
