### ISSUE TITLE
ODF preview and lighting dialogs disappear when detaching the main ODF tool

### ISSUE THREAD

**Issue by jdtournier** [MRtrix3/mrtrix3#273]
This is most likely due to the `hide_event()` handler being invoked - see #266 for details. Not sure what the best way to handle this would be - maybe store the state of these dialogs on hide and call show again in `show_event()` if necessary...?

**Comment by thijsdhollander** [comment]
So, this now seems to be fully fixed in #266 .  For completeness sake, I also tested the same scenario for the lighting dialog in relation to the tractography tool: it's also working correctly.

**Comment by jdtournier** [comment]
fixed with 2ea8eaa
