### ISSUE TITLE
Python modifications for cmake

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#2730]
Part of #2689, but wanted a clean page to contemplate how best to adapt the API / Python executables to the modified filesystem structure & installation process for `cmake`.

-----

1.  Some of the logic in `bin/mrtrix3.py` is tailored for running Python executables that are part of external MRtrix3 projects. Relevant documentation [here](https://mrtrix.readthedocs.io/en/3.0.4/tips_and_tricks/external_modules.html#handling-python-commands). There, the logic proceeds something like: 1) If a symbolic link to the main repo `bin/mrtrix3.py` has been made within the external project, that can be used to find the API. 2) Often external projects are built by constructing a softlink to the `build` script in the main repo and running that directly; that softlink can therefore be used to find the API. Use of `PYTHONPATH` is a fallback, but if used would kick in before any of this logic.

    This is being made redundant; indeed it's unclear at this point in time exactly what external projects will look like after the cmake changes.

    **Suggestion**: Remove all support for external modules within the code. `PYTHONPATH` will remain a viable solution. At the point at which we address compilation of external C++ binaries we will also address external Python executables.

2.  It is intended to be possible for a user to define a symbolic link to the executable, and attempting to run that executable will still find the Python API based on a relative path from the resolved symbolic link.

3.  The `run` module includes logic to ensure that if an *MRtrix3* executable is invoked, it is the coinciding version of that executable that is invoked rather than the first that appears in `PATH`, and also there are certain command-line options that may be added to `run.command()` invocations based on the availability of "standard" *MRtrix3* command-line options.

    The logic behind this may need to be revised. Currently, it just looks at the contents of `../../bin/`. So if the software is installed into a location that is shared with other software, eg. `/usr/local/`, that logic will catch a large set of non-MRtrix3 commands. 

    **Suggestion**: The build stage of cmake could collect a list of *MRtrix3* executables, and write it to a text file within `lib/mrtrix3/` in the build directory. `lib/mrtrix3/__init__.py` would then read from this file.

4.  It was hypothesized that it would be nice to be able to:

    1.  Run *MRtrix3* Python scripts from either an installed location or the build directory, and for point 3 above to still be satisfied.
    
    2.  Modify the contents of Python executables within the source directory, and have those changes reflected in the build directory without having to re-run the build step of cmake.
    
        However on reflection it may be tricky to support *both* this feature *and* point 2 above. It would be treating softlinks in different ways, and also ideally this modify-without-build feature would apply to the API and script algorithms also.

    **Suggestions**: For point i., as long as the directory structure is consistent between build and install, and there isn't any softlink trickery, it should work out of the box. For point ii., just rely on cmake build to copy any Python updates made in the source code into the build directory. 

5.  Already [mentioned](https://github.com/MRtrix3/mrtrix3/pull/2689#issuecomment-1748012497) in #2689, but relevant here also: Placement of the script algorithms.

    Before the `cmake` changes, there are executable Python scripts in `bin/`, APIs in `lib/mrtrix3/`, and algorithm source code in `lib/mrtrix3/<exename>/*.py`. Thus far for cmake this has all just been moved into new directory `python/*` but the relative structure is unchanged.

    **Suggestions**: There's multiple options here. One I'm increasingly liking as suggested by @aaroncapon is to move the sub-directories of `python/lib/mrtrix3/` (ie. the script algorithms) into `python/src/mrtrix3/`, and within the build / installation directory populate `src/mrtrix3/` with these contents. @daljit46 do you see any issue with the build / installation containing a `src/mrtrix3/` directory?

**Comment by Lestropie** [comment]
6.  Check again why the `5ttgen` algorithms need to be placed in "`_5ttgen/`"; this traces back to f0bb21d, and I'm sure it was necessary at the time, but I don't recall exactly what was playing up that forced me to add that little hack.

**Comment by daljit46** [comment]
I don't think there should be any problem with changing the structure of the build/installation.

For point 2, I'm struggling to understand what benefit would end users get from this feature.
Also, what exactly is the advantage of resolving the symbolic link and locate the actual `lib` directory? Is this related to external modules? If so, then can we just remove this feature until we figure out a strategy to allow people to create external modules with the new build system?

**Comment by Lestropie** [comment]
RE Point 2, nothing to do with external modules; purely if eg. `mrconvert` lives at `/install/bin/mrconvert` and someone creates link `/user/bin/mrtrix3_mrconvert` as a softlink to `/install/bin/mrtrix3_mrconvert` and then runs `/user/bin/mrconvert`. Should be less of a concern here given the presence of an explicit installation step. Not sure that there's actually any manipulation that can be done to facilitate this though: it's wholly dependent on whether `bin/mrtrix3.py` will be found by Python upon executing the softlink.

**Comment by Lestropie** [comment]
Discussion required to consider alternative mechanism for executing Python commands / locating PI

Virtual environments have been raised as a prospect, but it requires greater understanding of how they work and how they might contribute to a solution.

Note in discussion that anything that relies on the use of softlinks may not be viable for persisting support of MSYS2.

As a starting point, here's FSL's `bin/immv`:

```
~/src/mrtrix3$ cat /usr/local/fsl/bin/immv
#!/usr/local/fsl/bin/python3.11
# -*- coding: utf-8 -*-
import re
import sys

from fsl.scripts.immv import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

1.  In the case of FSL, `/usr/local/fsl/bin/python3.11` is a full-size binary. In @jdtournier's example, the shebang pointed to a softlink, which just directed to the system default Python interpreter. The theory is that Python will include the directory of the invoked softlink in its set of locations in which to look for modules.

2.  In the case of MRtrix3 scripts, rather than importing `main()` from the invoked script and executing that, we would instead want to import `usage()` and `execute()`, and then execute `app.execute()`, providing to that these two functions as parameters.

3.  As shown, I think this would require that the scripts containing the bulk of the executable code reside within a sub-directory relative to the API, which is a different structure to what we currently have.

4.  By generating small-scale executable Python scripts that refer to the bulk of code stored elsewhere, the latter could have the .py suffix, which may make it possible to have algorithm code stored within a sub-directory relative to those scripts with the very same names as those scripts.

5.  For algorithm-based commands, source-code-wise at least I like the idea of creating a directory with the name of the command, placing all of the algorithm files within that directory, and then the file that contains the `usage()` and `execute()` functions goes into `__init__.py` or `__main__.py`.

I'll muck around with some proposal structures and see what I see.
