### ISSUE TITLE
Decimal separator issue when reading DICOM?

### ISSUE THREAD

**Issue by bjeurissen** [MRtrix3/mrtrix3#2758]
Noticed something reminiscent of #447 today in the output of ``mrinfo``:

```
************************************************
Image name:          "TEST (.) [MR] t1_mprage_sag_p2_iso"
************************************************
  Dimensions:        176 x 256 x 256
  Voxel size:        1 x 1 x 1
  Data strides:      [ 3 -1 -2 ]
  Format:            DICOM
  Data type:         unsigned 16 bit integer (little endian)
  Intensity scaling: offset = 0, multiplier = 1
  Transform:               0.9988     0.03141     0.03837      -97.46
                         -0.03139      0.9995   -0.001206      -97.36
                         -0.03839  -3.073e-08      0.9993      -143.5
  EchoTime:          0.00243
  FlipAngle:         9,8
  InversionTime:     0.9
  PhaseEncodingDirection: j-
  PixelBandwidth:    180
  RepetitionTime:    1.9
```

The funny bit being the apparent decimal separator ``,`` in the FlipAngle. Note that I am directly feeding mrinfo a DICOM directory.

**Comment by Lestropie** [comment]
Won't be a decimal point separator. It's not reporting "`9 + 4/5`", it's reporting the list "`[9, 8]`". Some frames report a flip angle of 9, others report a flip angle of 8, and that is being collated as a list. Or alternatively it's finding an excitation angle of 9 and a refocus angle of 8 (I wanted to capture both in DWI since some protocols don't use 90 + 180 and this might be of interest downstream).

**Comment by bjeurissen** [comment]
That makes sense. I was suspecting something like that, but I had not seen it on any other datasets. Maybe adding a space after the comma can help convey the list aspect?

**Comment by Lestropie** [comment]
Changing the formatting here would be probably too tricky to justify, but theoretically possible. The data are just being presented as they are stored in the header. That in turn is the direct result of how 1D matrix data are serialised into string---regardless of destination or context---such that they can be deserialised back into numerical form. And separating such data by "`, `" everywhere in the code base might lead to compatibility problems elsewhere. So what you'd need to do is, in the pretty print of `mrinfo`, attempt to load header key-values as matrix data, and if successful, serialise with a different separator. So could be done, but not something I'm investing in myself given I don't have the ambiguity of *erroneous* decimal point symbols. :sunglasses:
