### ISSUE TITLE
mrview: window drawing glitch with qt6 (on macOS?)

### ISSUE THREAD

**Issue by bjeurissen** [MRtrix3/mrtrix3#2762]
I am experiencing this issue with qt6 (on macOS):

https://github.com/MRtrix3/mrtrix3/assets/5675416/7f4c1422-6ea7-4605-badb-90d2119e339d

**Comment by daljit46** [comment]
What exact Qt version can you reproduce this with?

**Comment by bjeurissen** [comment]
> What exact Qt version can you reproduce this with?

I have had this with any Qt6 version that I have tested, currently with 6.4.1

**Comment by bjeurissen** [comment]
Seems to be fixed with Qt version 6.6.1

**Comment by daljit46** [comment]
Nice! Perhaps it was related to [this](https://bugreports.qt.io/browse/QTBUG-107666) then.

**Comment by bjeurissen** [comment]
> Nice! Perhaps it was related to [this](https://bugreports.qt.io/browse/QTBUG-107666) then.

It looks a lot like it, although I am pretty sure I experienced it in earlier versions, whereas this is a regression from 6.3.2 -> 6.4.0. But maybe I was affected by another drawing bug in a previous release that presented somewhat similarly...
