### ISSUE TITLE
mrview screenshot: camera coords for translate and voxel coords for rotate

### ISSUE THREAD

**Issue by draffelt** [MRtrix3/mrtrix3#277]
Had a use case today where Shawna wanted to take screenshots for surgical planning oriented off-axis (to be inline with a particular bundle). She wanted to then take several shots translating through camera plane. Would be good to have an extra 'camera' combo box option in the translate section, with units of mm.

I also notice voxel coords are not available for rotations. You never know, a user might want rotate about an image axis while viewing from an off axis orientation.

**Comment by rtabbara** [comment]
Support for these features added in 72ccbd61d3c64ec0f70b3c1c1dc2199b8cc7338d and 9c79141820580953d4b24328e1aceb2b30d93854

**Comment by rtabbara** [comment]
Housekeeping of issues, I believe this is ok to close.
