### ISSUE TITLE
configure fail on ubuntu 18

### ISSUE THREAD

**Issue by yawu66** [MRtrix3/mrtrix3#2776]
Hi experts,
I tried to install the Mrtrix3 on ubuntu 18 but failed.  Any suggestions are appreciated.
Thanks,
Yawu
[configure.log](https://github.com/MRtrix3/mrtrix3/files/13920248/configure.log)

**Comment by jdtournier** [comment]
This looks like an issue with an incorrectly configured FSL install - newer versions need to be handled differently. See [this discussion on the forum](https://community.mrtrix.org/t/mrtrix3tissue-installation-error/7156/3?u=jdtournier) for details.
