### ISSUE TITLE
Help Please! mrcat code

### ISSUE THREAD

**Issue by NEWroscientist** [MRtrix3/mrtrix3#2783]
Hello ,
I am a trying to stitch 2 images from 2 different folders and me being new to coding itself; cant fingure out how to write the command such that mrcat command is executed and corresponding files from 2 different folders are stitched together.

File1= Parent folder > Folder1 > Takef 1>file.mif
File2= Parent folder> Folder 2 > Taker 1> file.mif

The picture of the syntax is attached, Please , if anyone could rescue.

![image](https://github.com/MRtrix3/mrtrix3/assets/156869160/1f4de802-ae73-4a77-b49e-9a245347fa4d)

**Comment by bjeurissen** [comment]
Please use https://community.mrtrix.org/ to ask questions related to usage. The issue tracker is intended for bugs and feature requests.
