### ISSUE TITLE
Somehow package_mrtrix is not actually creating mrtrix3.tar.gz

### ISSUE THREAD

**Issue by dchristiaens** [MRtrix3/mrtrix3#279]
To install mrtrix3 on our server, I had a look at the package_mrtrix script. I launched an Ubuntu 14.04 VM locally, pulled the master, built without the GUI, and ran `./package_mrtrix -standalone`, as in Donald's example on the Wiki, but no file is actually created. When I comment the cleanup at the end `rm -rf _package/`, I can manually compress the contents of that folder and all works great. However, out of the box the lines
```bash
  cd _package 
  echo - compressing files into mrtrix3.tar.gz
  tar cfz ../mrtrix3.tar.gz mrtrix3
```
do not appear to do what they should. Outside the scope of the script, the exact same commands work fine. Any ideas what's going on here?

**Comment by jdtournier** [comment]
No idea. I'll take a look when I have a minute... Just to check: there is no error message? No 'command not found', etc...?

**Comment by dchristiaens** [comment]
No, nothing. Weird right? I mean, there's an easy workaround and it's definitely not critical given the background of the people that are going to use this script, but I'd still like to understand why it's not working :-)

**Comment by jdtournier** [comment]
Yep, strange indeed... But I have seen funny behaviour like this on occasion. Do you know whether the tar process even runs...? Does it pop up even briefly if you monitor with top (run with a short update interval)? The one thing that might explain this is a frank segfault in tar - these are often (and annoyingly) silent when they occur within a script... As to why a program as venerable as tar would crash out, well... Maybe if there was something really weird about the environment it was running in. Is LD_LIBRARY_PATH set, perchance...?

**Comment by dchristiaens** [comment]
LD_LIBRARY_PATH is not set, it's a "clean" VM. I tried your "top" suggestion too and I don't see tar showing up in the list, but it may be gone in the blink of an eye... I had a look in the strace output too, and I can;t find anything tar-related in there which may suggest it is not being called, although those files tend to be very cryptic.

**Comment by dchristiaens** [comment]
Just noticed that when I do not include the `-standalone` option, a tar-file is created just fine.

**Comment by jdtournier** [comment]
Hmm... Just tried it, and I can't replicate... Just a thought: presumably your language settings are non-US? Sometimes this can have weird effects that I don't understand - see #163 for example. Might be worth trying on a fresh account with en-US for the region & language settings...?

**Comment by dchristiaens** [comment]
Language is set to US-english. Numeric format, currency and time zone are set to Germany though, if that could have something to do with it. Anyway, if you can't replicate it we may conclude that it comes down to my VM. I can work around this issue easy enough. Just in case someone else would report a similar problem, my thought would be to remove the call to tar from the script and leave it to the user to copy the package folder in whatever way he prefers.

**Comment by jdtournier** [comment]
Yes, that might be an option. Happy for you to do that if you feel like it...? :smile:

**Comment by dchristiaens** [comment]
Sure, I'm happy to take this on.

**Comment by jdtournier** [comment]
:+1:

**Comment by jdtournier** [comment]
I see you've also edited the wiki to match - thanks! :+1:
