### ISSUE TITLE
mrconvert: Positibility of converting Nii/MIF files back to DICOM.

### ISSUE THREAD

**Issue by opennog** [MRtrix3/mrtrix3#2797]
I'd just like to ask if it was ever considered to allow mrconvert to convert images from compressed formats (i.e., nii/mif) back to DICOM. 
This would facilitate integration of mrtrix-related analysis within hospital settings. 

Thank you for the information.
Best!

**Comment by Lestropie** [comment]
Hi @opennog,

There's an existing issue listing over at #2238. Definitely would be nice to have, but where such capability can be achieved using other packages, other features tend to take priority.

Outside of *MRtrix3*, I'm also myself interested in being able to take a set of BIDS derivatives from one or more BIDS Apps, and convert them as a coherent DICOM session for hospital transfer. So it's worth keeping an eye on that space in case that's where the efforts end up being invested first.

Cheers
Rob
