### ISSUE TITLE
MRView: Graphics performance metrics HUD

### ISSUE THREAD

**Issue by rtabbara** [MRtrix3/mrtrix3#282]
Might be a nice to be able to toggle a HUD that is overlaid in the corner of the main view highlighting FPS, GPU memory used etc?

**Comment by jdtournier** [comment]
Funny that, I had pretty much the same thought last night... It would be useful to get a better idea of performance. Only snag is measuring FPS only really works if we do continuous updates. I guess it could work if we just display the FPS averaged over the last 5-10 frames, and you'd then need to interact with the display to get an accurate reading. I guess that would be good enough. 

No point in displaying the time spent in `paintGL()`, OpenGL calls are not necessarily synchronous...

**Comment by jdtournier** [comment]
Closed as part of pull request #281.
