### ISSUE TITLE
Rebuild not pulling test updates

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#2832]
In trying to finally resolve #2702 I ran into a trap with the current `cmake` configuration.

I first configure, build, then run a test. The test fails. I determine that the problem is not with the implementation of the thing I'm testing, but with the test itself. So I change the test, and re-run `cmake --build`. However the tests still fail as though I had not made any change.

**Comment by daljit46** [comment]
This is a limitation of the way the tests are generated by CMake, which is something that happens at configure time.
I'm not sure there is an easy way to "build" the tests the same way as C++ source files, but I'll investigate possible ways to get around this.

**Comment by Lestropie** [comment]
Closing; any discussion can happen in #2834.
