### ISSUE TITLE
Change help output to remain in terminal window after quitting out of less. 

### ISSUE THREAD

**Issue by draffelt** [MRtrix3/mrtrix3#284]
If we use the -X option when defining less as the mrtrix help command in app.cpp, then when you quit after viewing the help, the output remains in the terminal window. This is good when you are typing a long command and need to look up multiple options. Currently, I find myself typing half the command, then having to hit the home key to comment out the line, re-run the help to check the options, then hitting the up arrow to continue typing the command. Would be much easier to be able to view the help output as you are typing the command.

Any objections if I change this?

We also might want to do the same for errors generated from the build script.

**Comment by jdtournier** [comment]
Other option is to set `HelpCommand: less -X` in the MRtrix config file...?

But generally happy with this - just worried about whether we can rely on this behaviour across all platforms...

**Comment by Lestropie** [comment]
I prefer having both the help and the build output disappear. So if the default changes, the current behaviour needs to be accessible using the config file.

**Comment by thijsdhollander** [comment]
I do think the -X option makes more sense as a *default*.  I find myself all the time in the exact same scenario @draffelt just described as well... (even worse (?), I often open up a second terminal, just for the help)
"Advanced users" who might not/less need this behaviour should indeed be allowed to set/override `HelpCommand` via the MRtrix config file, if they wish so. (but these are the type of users that should also be quite capable to figure that out)

**Comment by draffelt** [comment]
Ok, so the -X option is available for less in linux, mac and cygwin. I've therefore made this the default behaviour. Rob, as Donald said you can set `HelpCommand: less` in the config to revert back to the old behaviour.
