### ISSUE TITLE
Issue with Incorrect Positioning of .tck Files from MRtrix3 in DSI Studio

### ISSUE THREAD

**Issue by Luoyu-Wang** [MRtrix3/mrtrix3#2872]
I have recently been working with .tck fiber tractography files generated by MRtrix3, and all processing steps were conducted within the DWI space. However, upon attempting to open these .tck files in DSI Studio, I noticed that the positioning of the tracts seems to be misaligned with my DWI dataset.

Has anyone else encountered a similar issue? I would like to understand what could be causing this discrepancy and seek advice on how to resolve it. Are there specific conversion or compatibility settings that I might have missed? Any guidance and suggestions would be greatly appreciated.

Thank you all for your time and assistance!

**Comment by Lestropie** [comment]
Given this is not a direct bug report or feature request, but rather relates to the interaction between different softwares and spatial reference systems, I think it would be better posed over at the [community forum](https://community.mrtrix.org/).

Thanks
Rob
