### ISSUE TITLE
mrview crop to slab graphical issue

### ISSUE THREAD

**Issue by pkyee** [MRtrix3/mrtrix3#289]
After the recent update, the crop to slab option in mrview is not functioning properly. Displays the .tck file but also with graphical errors. Attached an image of this issue.
![screenshot0000](https://cloud.githubusercontent.com/assets/13255478/8595855/aeee5dca-2619-11e5-9753-7bc50836bbb1.png)

**Comment by jdtournier** [comment]
That is indeed not very pretty... Can you supply this information?

- the output of `mrview -version`
- the command-line output of `mrview -info` (just the 3 lines about the GL information)

**Comment by pkyee** [comment]
mrview -version output:
64 bit release version, built Jul  7 2015, using GSL 1.16
Author(s): J-Donald Tournier (d.tournier@brain.org.au) & Dave Raffelt (d.raffelt@brain.org.au)
Copyright (C) 2008 Brain Research Institute, Melbourne, Australia.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


mrview -info output:
mrview: [INFO] GL renderer:  Gallium 0.4 on NVE7
mrview: [INFO] GL version:   3.3 (Core Profile) Mesa 10.3.2
mrview: [INFO] GL vendor:    nouveau

**Comment by jdtournier** [comment]
Sorry, I think you missed out the crucial first line from the `mrview -version` output - it should look like:

    == mrview 0.3.12-541-gbd8b0c4d ==

Otherwise, it looks like you're using the open-source "nouveau" driver for nvidia cards - any reason you can't use the proprietary ones? The open-source ones have only recently managed to reach support for OpenGL 3.3, it wouldn't be surprising to find there are remaining bugs in the implementation...

**Comment by pkyee** [comment]
Sorry, here is the full output:

== mrview 0.3.12-542-g67bf2cd6 ==
64 bit release version, built Jul  7 2015, using GSL 1.16
Author(s): J-Donald Tournier (d.tournier@brain.org.au) & Dave Raffelt (d.raffelt@brain.org.au)
Copyright (C) 2008 Brain Research Institute, Melbourne, Australia.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

I will try to update the driver on my end, thanks!

**Comment by jdtournier** [comment]
OK, I'll wait to hear back...

**Comment by pkyee** [comment]
Using the NVIDIA drivers has resolved the issue. Thank you.

**Comment by jdtournier** [comment]
@pkyee - just thought I'd chase this up since it might have signalled subtle bugs within MRView's OpenGL handling... Everything works fine with the open-source nouveau drivers with Mesa 10.6.2 (the current version on Arch Linux).

**Comment by pkyee** [comment]
It seems like I was the only one experiencing this in my lab too (everyone was on NVIDIA drivers). Have not run into this issue since. Thank you for the followup.
