### ISSUE TITLE
Pull NIfTI headers from existing host

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#2978]
Following on from [prior comment](https://github.com/MRtrix3/mrtrix3/pull/2859#issuecomment-2292588542) in #2859.

Rather than making a repository in the MRtrix3 organisation to store the header files for the NIfTI image format, there may instead be existing repositories from which those files could be pulled during configuration as third-party dependencies as per #2859, and therefore removed from this repository:

https://nifti.nimh.nih.gov/pub/dist/src/nifti2/nifti1.h
https://nifti.nimh.nih.gov/pub/dist/src/nifti2/nifti2.h

**Comment by daljit46** [comment]
Closed by #2979.
