### ISSUE TITLE
build issue: ld.lld

### ISSUE THREAD

**Issue by haampie** [MRtrix3/mrtrix3#2986]
**Describe the bug**

Sometimes `ld.lld` can be located as an executable, but not used by the compiler: `-fuse-ld=lld` fails.

Locating happens here

https://github.com/MRtrix3/mrtrix3/blob/025eb0fe509be4b4681920c3300848b55d04bfa2/cmake/LinkerSetup.cmake#L11

Setting the linker flag here:

https://github.com/MRtrix3/mrtrix3/blob/025eb0fe509be4b4681920c3300848b55d04bfa2/cmake/LinkerSetup.cmake#L16-L22

Two requests:

1. Please make this opt-in. `lld` may work well, but let it be a user choice instead of overriding toolchain defaults.
2. Test for `-fuse-ld=lld` with try-compile instead of searching for `ld.lld` the executable.

**Platform/Environment/Version**

Please provide the following information:

-  OS: Ubuntu 22.04
-  *MRtrix3* version: dev branch

**Comment by daljit46** [comment]
Closed y #2989.
