### ISSUE TITLE
build issue: cmake fails if not git repo

### ISSUE THREAD

**Issue by haampie** [MRtrix3/mrtrix3#2987]
**Describe the bug**

The following is problematic:

https://github.com/MRtrix3/mrtrix3/blob/025eb0fe509be4b4681920c3300848b55d04bfa2/cmake/FindVersion.cmake#L20

Having a git executable does not imply mtrix3 sources are from a git repo.

They may have been downloaded from a tarball export, e.g. https://github.com/MRtrix3/mrtrix3/archive/refs/heads/dev.tar.gz.

You have to verify the mrtrix3 sources are a git checkout before running git commands.

It can lead to very weird issues as well when mrtrix3 is extracted from a tarball in a place where one of the parent directories is an unrelated git repo. The FindVersion.cmake logic will look at tags completely unrelated to the mrtrix3 project.

**To Reproduce**

Do a build from this archive: https://github.com/MRtrix3/mrtrix3/archive/refs/heads/dev.tar.gz.

**Platform/Environment/Version**

-  *MRtrix3* version: dev branch

**Comment by daljit46** [comment]
Hi, thanks for reporting this. Yes, this is clearly a logic bug and the intention of the code wasn't to rely on the existence of a git executable to assume that we're dealing with a git repo. We should probably run something like `git -C ${PROJECT_SOURCE_DIR} rev-parse` to check for that.

> It can lead to very weird issues as well when mrtrix3 is extracted from a tarball in a place where one of the parent directories is an unrelated git repo. The FindVersion.cmake logic will look at tags completely unrelated to the mrtrix3 project.

This is also something already on my list as part of #2901. In particular, relying on `${CMAKE_SOURCE_DIR}` is a bad idea in general and we should be either using `${PROJECT_SOURCE_DIR}` or `${CMAKE_CURRENT_SOURCE_DIR}`.
