### ISSUE TITLE
MRView: handle OpenGL resource deallocation at exit

### ISSUE THREAD

**Issue by jdtournier** [MRtrix3/mrtrix3#299]
There is a problem with releasing OpenGL resources, explained in the [QOpenGLWidget Qt docs](
http://doc.qt.io/qt-5/qopenglwidget.html#resource-initialization-and-cleanup), in that the context is not guaranteed to be current when members classes are destructed - in C++, destruction occurs in the opposite order to construction, so the destructor for the OpenGL context will be invoked after all the destructors for the member objects. This means there is no mechanism to ensure the right context is current when these members are destructed - and that includes all the textures, framebuffer objects, vertex array objects, etc. This is bound to cause random segfaults somewhere down the track. It would be good to figure out a way to handle this more cleanly. The `aboutToBeDestroyed()` signal is one such option.

**Comment by Lestropie** [comment]
I reckon this has been dealt with in full; I certainly haven't been able to get any errors of late (which includes a number of fixes that were done on the `odf_dixel` branch and are now in `updated_syntax`. So closing this now; if errors pop up down the track, the framework for handling it is in place, and they can be dealt with on an individual basis.
