### ISSUE TITLE
MRview: Unexpectedly quits on trying to load .tck files

### ISSUE THREAD

**Issue by rodneyanderson** [MRtrix3/mrtrix3#300]
Since updating this morning, when trying to load .tck files, mrview unexpectedly quits. In the terminal it reads: 

QObject::connect: Cannot connect (null)::fieldOfViewChanged() to MR::GUI::MRView::Tool::Tractogram::on_FOV_changed()
Segmentation fault: 11

I am using:
OS X Yosemite 10.10.4

Qt version 5.4.1

== mrview 0.3.12-707-ge6258aa0 ==
64 bit release version, built Jul 23 2015, using GSL 1.16

mrview: [INFO] GL renderer: NVIDIA GeForce GT 750M OpenGL Engine
mrview: [INFO] GL version: 4.1 NVIDIA-10.4.2 310.41.35f01
mrview: [INFO] GL vendor: NVIDIA Corporation

**Comment by thijsdhollander** [comment]
I can confirm this one too... getting the exact same scenario/error, closing off with a `Segmentation fault (core dumped)`.

**Comment by Lestropie** [comment]
Fixed by 26d27bd0e.
