### ISSUE TITLE
mrview: alt-scroll to change image

### ISSUE THREAD

**Issue by draffelt** [MRtrix3/mrtrix3#303]
I have to use the 'function' key on my laptop to access page up/down and flick between images. And my page/up down buttons are annoyingly small. It would be nice if I could hold alt and scroll instead. 

Currently ctrl-scroll is zoom, shift-scroll steps through the slices as larger increments. But alt-scroll is unassigned. 

Any objections?

**Comment by jdtournier** [comment]
Have you tried right-click + scroll...?

However, I have to say it doesn't work great with a touchpad - not enough control. Alt+scroll would have the same issue. Pretty good with a normal scroll mouse though.

**Comment by draffelt** [comment]
Ah, right click scroll works good. I didn't know it was available. 

I'm wondering if alt-scroll would be easier to find instead? since we already have shift-scroll and crtl-scroll. And ctrl-scroll seems to be universal for zoom, so it users are already used to this sort of action.

**Comment by thijsdhollander** [comment]
Oh wow, I also didn't know about the right-click + scroll... it's super handy!

I reckon we'll need to have a list of keyboard/mouse shortcuts compiled at some point... Some are indeed "universal intuition", such as scrolling through content with a scroll wheel, or ctrl-scroll for zoom, or middle mouse / scroll wheel drag to translate... but the majority of commands definitely goes way beyond that.

On the page up/down and Fn/function key issue: it certainly is an issue on a current generation of more mobile devices, but it does seem that there is a current/next trend to actually reverse the logic with the F-keys: the "extra" functionalities that got crammed into them becoming the primary ones, and the traditional F-keys becoming the secondary ones (for wich the Fn/function key needs to be pressed).  So hopefully, over time, the page up/down keys become more accessible again on a majority of devices...

**Comment by jdtournier** [comment]
> Oh wow, I also didn't know about the right-click + scroll... it's super handy!

Yep, it's been in there for years... Funny thing is, I don't tend to use it at all. On my laptop (where I have the same problem as @draffelt), the touchpad scrolling is too sensitive to control, I end up flicking over multiple images in one go... This is what I meant with Alt+scroll having the same issue.

> I'm wondering if alt-scroll would be easier to find instead? since we already have shift-scroll and crtl-scroll. And ctrl-scroll seems to be universal for zoom, so it users are already used to this sort of action.

Yes and no. It might make sense, but shift-scroll is already not commonly known, I doubt adding the Alt shortcut would help in that regard. More to the point, Alt is often reserved for window manager interactions, depending on how your system is set up - this is why I added config file options to set each of these modifiers. On my GNOME desktop, Win (meta) is used for window manager interactions, whereas on Unity and others, Alt would be used for most of those actions. So you'd need to make sure there was flexibility in the assignment of that modifier (not difficult though, most of the work is already done in the `MRView::Window` constructor). 

> I reckon we'll need to have a list of keyboard/mouse shortcuts compiled at some point... 

We do... There was such a page for the previous version, but I haven't got round to sorting out the equivalent page for this one. Any help appreciated.

> On the page up/down and Fn/function key issue: it certainly is an issue on a current generation of more mobile devices, but it does seem that there is a current/next trend to actually reverse the logic with the F-keys: the "extra" functionalities that got crammed into them becoming the primary ones, and the traditional F-keys becoming the secondary ones (for wich the Fn/function key needs to be pressed). So hopefully, over time, the page up/down keys become more accessible again on a majority of devices...

I wouldn't bet on it... The current trend is to use touchpad or touchscreen gestures to perform the actions that would traditionally have been associated with PgUp/PgDn. The function keys getting highjacked is already a bit of a problem - they're almost unusable on MacOSX, being mostly bound to funny window manager actions (exposé, etc.). We're already using the number keys for mouse modes, and for colourmaps with the Ctrl modifier. So it would get very messy very quickly to try to cram view modes and tools into those as well. Maybe we'll need to start implementing Emacs-like shortcuts... I guess one way around this is the more traditional menu-based navigation, like Alt-V, 1 to use view mode 1, Alt-T, 2 to open tool 2, etc... Any suggestions welcome.

**Comment by draffelt** [comment]
OK, seems like Alt-scroll is not the best default to change images. Will close this for now.
