### ISSUE TITLE
dwidenoise: Low-frequency phase removal

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#3037]
Pinging @dchristiaens, @jdtournier.

There is some concern that the complex data denoising may currently be sub-optimal due to the presence of strong phase cycles:

1.  Locally, in a project doing denoising of fMRI data (@bahmantahayori), the temporal SNR seems to be better for magnitude-denoised data than complex-denoised data.

2.  [Lucilo's work](https://www.sciencedirect.com/science/article/pii/S1053811919305348) included a method for estimating and removing a linear phase term from the data prior to denoising. Presumably this was deemed necessary for a reason.

3.  Donald noted [here](https://community.mrtrix.org/t/dwidenoise-applied-to-complex-data/6546/3?u=rsmith) that the absence of phase correction could be a problem. I'm a little sceptical of the method proposed there though---it feels like double-dipping---and apparently it wasn't enough to resolve the performance of complex fMRI denoising relative to magnitude denoising for our data.

4.  In [this article](https://direct.mit.edu/imag/article/doi/10.1162/imag_a_00060/118691/Denoising-diffusion-MRI-Considerations-and), they have seemingly made a similar observation about poor performance of `dwidenoise` complex data denoising. There they do something different:

    > MPPCA applied to complex data (rotated along the real axis), denoted as MPPCA*. We applied the MrTrix3 implementation of the magnitude MPPCA to the complex data rotated to the real axis (we found that this approach was more stable in terms of handling phase images and achieved better denoising, compared to the MrTrix3 complex MPPCA implementation).

    ~~My best reading of this is that they have split the complex domain into two domains on either side of the imaginary axis. For complex values with a negative real part, they "rotate onto the (negative part of the) real axis", ie. take the negative of the magnitude; for complex values with a positive real part, they "rotate onto the (positive part of the) real axis", ie. take the magnitude. They then just run "real-valued" MPPCA. If this is the correct interpretation, and it does better than complex denoising, that's disconcerting.~~

    I think my original interpretation here is wrong. What they were instead referring to here was the bit I [quoted below](https://github.com/MRtrix3/mrtrix3/issues/3037#issuecomment-2492548417):

    > The smooth residual phase-­field was estimated using a low-­pass filter with a narrowed tapered cosine filter (a Tukey filter with an FWHM of 58%).

5.  For data from the CMRR sequence prior to version R017, with SENSE1+ reconstruction, the complex reconstruction of each slice stack is independent of all other slice stacks. This means that the phase can be totally incoherent between adjacent slices, even in the absence of motion-induced phase ramps (below is *b*=0):
    
    ![Screenshot from 2024-11-19 15-51-36](https://github.com/user-attachments/assets/3a36a3e1-6cf9-4e71-bab3-1d25167cf3bd)

    This is going to increase the rank of the signal. In pre-release version R017 of that sequence they estimate the multi-coil reconstruction differently so that it is smooth along the slice encoding direction (below is *b*=0 with new sequence, though different scanner):

    ![Screenshot from 2024-11-19 15-53-38](https://github.com/user-attachments/assets/bb7e5d14-1091-4fa8-9356-c88fee2f7e8a)

-----

Putting all of this together, it seems to me that we are in need of some kind of mechanism internal to `dwidenoise` for regressing out uninformative phase differences. My intuition is that it would not be too difficult to use the same method as Lucilo used, on a slice-by-slice basis. However that would not resolve the issue specific to the CMRR sequence of having substantial phase differences between adjacent slices. I can imagine an exceptionally crude algorithm that leaves the central slice unmodified, and for the slice above and below, computes the optimal slice-wise phase offset to minimise the phase difference between it and the adjacent slice, then repeats until the whole FoV is processed. Alternatively, according to:

> By assuming stationarity and employing the Fourier shift theorem, the linear phase ramp and offset are respectively estimated as the harmonic corresponding to the position of the maximum of the Fourier transform of the complex image and the phase at this maximum.

, would this tend to yield a close-to-zero phase for most of the image, and therefore *intrinsically* handle inter-slice phase offsets?

**Comment by BahmanTahayori** [comment]
Thanks @Lestropie for opening this issue. About [this paper ](https://direct.mit.edu/imag/article/doi/10.1162/imag_a_00060/118691/Denoising-diffusion-MRI-Considerations-and) the code is [available ](https://github.com/SPMIC-UoN/EDDEN/blob/main/NIFTI_COMP_to_REAL.m). It seems  _rotation along/to the real axis_  is a simplified explanation of what is done in lines 255-285, removing static and dynamic phase components. This is done by multiplying the complex data with the complex conjugate of the mean phase and the filtered phase. I am not familiar with Tukey window but it seems that it is used for apodization. Perhaps, it is doing the linear phase removal!

As discussed previously, I tried this [two-pass MPPCA approach](https://community.mrtrix.org/t/dwidenoise-applied-to-complex-data/6546/3) approach, however, the magnitude-only result showed a higher tSNR and the detected activation volume/mean t-score within the language ROI after all processings (fmriprep+TEDANA+ibt) were higher for the magnitude-only approach.

**Comment by Lestropie** [comment]
I had a quick go at linear phase removal. Selecting just the maximal magnitude location from the k-space data has a large discretisation penalty. it might be possible to find the peak location in *interpolated* k-space and generate the demodulation harmonic from that. This would however still be exclusively linear. [This article](https://direct.mit.edu/imag/article/doi/10.1162/imag_a_00060/118691/Denoising-diffusion-MRI-Considerations-and) uses the following:

> The smooth residual phase-­field was estimated using a low-­pass filter with a narrowed tapered cosine filter (a Tukey filter with an FWHM of 58%).

That might provide the ability to correct smooth phase variations with more complex spatial profiles than just a linear ramp.

**Comment by bjeurissen** [comment]
I have used this https://pubmed.ncbi.nlm.nih.gov/26241680/, matlab code here: https://github.com/cornelius-eichner/real-diffusion

**Comment by jdtournier** [comment]
How about just using the phase estimated from a first-pass denoising step...? Not sure how valid that might be, but it certainly gives you a decent phase estimate!

**Comment by Lestropie** [comment]
> How about just using the phase estimated from a first-pass denoising step...?

I was only recently made aware of this suggestion on the forum. This to me intuitively feels completely wrong. I don't know how you can make an assumption of Gaussian noise, and therefore the eigenvalues following the MP distribution, for data that have been explicitly manipulated based on a low-rank approximation. Even if it's only a rotation that's applied, I'm nevertheless uncertain whether the real & imaginary components will remain Gaussian.

It's also a very expensive solution for production release.

Lucilo's approach seems to work well for fMRI data, as long as the k-space data are upsampled by a factor of 2. I'd rather try both the interpolated-kspace-peakfinding, and the Tukey windowed approach (which is probably better for diffusion data).

> I have used this ...

Looks effective, but I'm wary of these efforts persistently expanding in scope, and translating that optimiser from Matlab to C++ may be nontrivial.

**Comment by Lestropie** [comment]
Closed by bba4fe17b4eaa152adc2cb152161f5bd73bf740c as part of #3029.
