### ISSUE TITLE
gen_planar_ROI: Rename

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#305]
This command now stands out like a sore thumb: it's the only command name left with an underscore in it. And there's two of them.

Can I suggest `maskgen`? This should probably also have the capability of generating both planar and spherical ROI masks.

**Comment by thijsdhollander** [comment]
Maybe rather `roigen` ?  Just because a ROI doesn't have to be a mask per se.  And maybe as well to avoid confusion with `dwi2mask`.

It could indeed have capabilities for spherical ROIs, but maybe also (over time) a few other ones that are offered by the ROI tool in mrview as wel?  E.g. a rectangle, maybe also a 3D box (specifying 2 corners), etc...?

**Comment by Lestropie** [comment]
> Maybe rather roigen ? Just because a ROI doesn't have to be a mask per se. And maybe as well to avoid confusion with dwi2mask.

Mmm... I'd disagree. A ROI _has to be_ a mask; a mask _doesn't have to be_ a ROI. A ROI that's anything other than binary is ambiguous; sure, you can e.g. threshold a float image, but that's just a case of implicit or explicit conversion. Plus, anything this command will be generating will be binary.

> It could indeed have capabilities for spherical ROIs, but maybe also (over time) a few other ones that are offered by the ROI tool in mrview as wel? E.g. a rectangle, maybe also a 3D box (specifying 2 corners), etc...?

Exactly; hence the generic name.

**Comment by thijsdhollander** [comment]
Getting a bit confused, I kind of fully agree with most things you just stated... :

> A ROI that's anything other than binary is ambiguous

Fully agree.  We have a ROI editor in mrview, it generates and interacts with binary images.  So a ROI image is a binary image.

> Plus, anything this command will be generating will be binary.

Ok, agreed as well.  It currently generates a binary image of essentially a planar region.  It can be even more generic and generate other (and even more) stuff that can currently be "manually" drawn in the ROI editor, such as spheres, rectangles, boxes, etc...

So I've been using the term "ROI" all the time here... no?

I was thinking of the term "mask" as a (typically binary) image that will be / is used with the intention to mask out stuff.  If it's not stated what (e.g. a white matter mask), then typically (not necessarily in principle) people think of a (whole) brain mask.  Hence the command `dwi2mask` which takes a dwi image and outputs a whole brain mask.  A mask is somehow a ROI that has the purpose to mask stuff.  Whereas a ROI could also be used to e.g. include/exclude tracks, calculate measures/stats, etc... in relation to that region.

So I'm misunderstanding something I guess... to confirm: the intention is to also include stuff-that-the-ROI-editor-does in the command, right (or did I get the intention wrong there)?  I mean, if the command would then be called `maskgen`, should the tool in mrview then also not be called "mask editor"? :confused:

**Comment by Lestropie** [comment]
Linguistically, sure we use the two terms in different contexts; but this depends on the _intent_ or _context_ of use of the data. With the command naming scheme, we've got a small set of prefixes / suffixes that detail the _data_ to be input / output by that command. In that respect, the _data_ involved for 'masks' and 'ROIs' are the same; indeed someone could generate a binary image using this command and use it as a tracking 'mask' rather than an include 'ROI', it's not up to the command to constrain what the generated data may be used for.

In terms of which term is better defined as a superset of the other... _shrug_ . Guess I think of a whole-brain 'mask' not necessarily being 'of interest', whereas any application of a 'region of interest' can be formulated as a masking operation of some form... Arm-wrestle over it? :-P

I'd rather not have commands in the repo with both `roi*` / `*roi` and `mask*` / `*mask` names; the data's the same, it would just add complexity to the naming scheme. And I don't think you could rename all `mask` commands to `roi`, as you'd end up with `dwi2roi`, which doesn't work. When I think of the most succinct term to use to refer to an explicitly binary image, 'mask' comes to mind for me. But happy to hear the consensus.

**Comment by Lestropie** [comment]
Actually, think it just clicked: a mask is data-driven, a ROI is manually defined. So in that respect, `roi` is slightly better here; the question is whether or not that effect is out-weighed by the inconsistency in the command naming convention...?

**Comment by jdtournier** [comment]
I reckon I'd be happier with `roigen` on this one. For one, I agree with @thijsdhollander that the _intent_ of the output is slightly different. But more importantly, as currently implemented, you couldn't use the output as a regular mask in for example, `mrstats`: the dimensions will not match that of the original image (or any other image, for that matter). It just takes up as much volume as it needs to. So for a planar ROI, you'd get a X×Y×1 image for example, which most subsequent commands (aside from `tckgen`) couldn't use without modification...

**Comment by jdtournier** [comment]
And I don't see any inconsistency here. Sure, we're introducing another prefix, but if anything it makes the purpose more explicit - the whole logic used for naming remains entirely consistent, as far as I can tell.

**Comment by thijsdhollander** [comment]
>And I don't see any inconsistency here. Sure, we're introducing another prefix, but if anything it makes the purpose more explicit - the whole logic used for naming remains entirely consistent, as far as I can tell.

Exactly; I also agree clear/explicit naming is the way to go (and doesn't have to be incompatible with consistent naming).  If you'd push the logic of "1 name == 1 type of data" *too* far, you'd also have to give up the difference between e.g. the "fod", "sh" (, "qbi", ...) pre/postfixes at some point, probably turning them all into "sh" for instance... but that's clearly not really what you want to end up with...

**Comment by Lestropie** [comment]
> But more importantly, as currently implemented, you couldn't use the output as a regular mask in for example, mrstats: the dimensions will not match that of the original image (or any other image, for that matter). It just takes up as much volume as it needs to. So for a planar ROI, you'd get a X×Y×1 image for example, which most subsequent commands (aside from tckgen) couldn't use without modification... 

o.0 Hadn't realised that, will need to have a look. Suspect that if the command's functionality is expanded, that feature would be the odd one out; most would need a template image.

>  If you'd push the logic of "1 name == 1 type of data" too far, you'd also have to give up the difference between e.g. the "fod", "sh" (, "qbi", ...) pre/postfixes at some point

Well with `sh` / `fod` you need to discriminate between `amp2sh` and `dwi2fod`, which are two very different processes; also `fod2fixel` wouldn't make sense with generic SH data. So I think the distinction there is a little clearer than that between a mask and a ROI. Really wish there were a better term to specify 'binary image' that didn't have usage connotation... :-/

Discoverability has to win out, so if `roigen` makes more sense to both of you let's go with that. Will probably just do the rename though, added functionalities for that are not very high on the priority list.
