### ISSUE TITLE
fixelcalc command

### ISSUE THREAD

**Issue by draffelt** [MRtrix3/mrtrix3#314]
Would be handy for task such as computing effect sizes (percentage change wrt controls) on beta outputs from cfefixelstats. Also, for performing a log transform of the FBM related measure (change in cross-sectional area). 

I guess we will need to re-use some of the mrcalc code. 

We would then remove fixelmult. Should we remove the fixelthreshold, since this can be achieved with the -gt option?

**Comment by draffelt** [comment]
Don't think we will need this if fixel data is stored as a standard image.

**Comment by jdtournier** [comment]
I was thinking about this. It'll need some changes in the image handling backend to prevent promotion of data to full 3D volumes. At the moment, images with dimensionality less than 3 have their missing spatial axes added and a default transform assigned. This is to simplify downstream commands so they can assume that these conditions are satisfied. 

I agree storing the data as standard images provides the most flexibility, but I'm not sure how to handle this. Options are:

- don't promote to 3D, leave transform unset if not present. Deal with potential um under assumptions in commands that are designed to operate on >3D data by adding a convenience `assume3D()` function to simply throw an Exception if the data don't match expectations. Probably my preferred option. Keeps the header info closer to reality, which is always a good thing.

- promote to 3D, but store as 1D (or 2D if appropriate) when writing out. Would require special handling to either keep track of the original dimensionality, or assumptions about what it might be (i.e. that any trailing axes with unit size should be ditched). I don't really like that very much, especially if we rely on assumptions, but it would mean applications can always rely on the assumptions I'd mentioned. 

The thing is, I'm not sure how big a deal these assumptions are in practice - i.e. how many applications might break if we relax that condition. Probably not that many, might be getting worried about not very much...
