### ISSUE TITLE
MRview: Place arbitrary slices through 3D texture

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#316]
Just to add to all the fun you've been having with volume render clip planes...

I've seen in other softwares where you essentially take a slice through the image volume at any angle, and from an off-axis view you can see e.g. tracks going through the slices. Should be easy to draw using the 3D texture and a triangle fan, and some of the UI interactability should be common with the clip plane stuff.

Key would be _not_ to operate in volume render mode; do it in single slice mode, and your depth testing stays intact.

**Comment by jdtournier** [comment]
This idea kind of already came up as part of #290. Here's what I'd posted on that thread:

> As to the 3 orthogonal planes view, [...] that assumes you really think this view mode is useful... I had that implemented in a precursor to MRView (way back circa ~2003...), but never bothered reimplementing it for later versions - I've never missed it much...

I guess I'm sticking to that view... It kind of looks cool, but I found it really wasn't particularly useful. Besides, I have a feeling it'll look a bit substandard without proper perspective projection (currently everything is orthographic), which you'd be welcome to add, but would require some potentially quite low-level changes to the backend (notably the `Projection` class in `src/gui/projection.h`). Actually, I've been thinking perspective projection might be a nice option for the volume render, but haven't found the motivation to implement it... 

In any case, I'm not going to stop anyone from having a go at this if they feel like it. Just bear in mind there'll be a bit of special handling for getting the ODFs & vectors on the plane(s), and/or displaying/rendering ROI & overlays...

**Comment by Lestropie** [comment]
Yeah had thought about the hassles of getting the main image / overlays depth testing correct. Not overly fussed myself, but it's something I do see people using, and wouldn't be surprised if requests start coming it, particularly since the UI handling of crop planes works so well & should be transferable.

**Comment by jdtournier** [comment]
Getting the main image depth testing to work is dead simple, that's not what I'd be worried about. The bigger problem is _how_ you'd render overlays and/or ROIs in that mode. There's currently no mesh render (although we're talking about it), and using the ray-tracing approach would basically entail re-implementing much of the volume render mode. Also handling the location of the FODs and/or vectors so they lie on a regular grid on the plane(s) of interest would need to be done right (cf. issue #52). None of this is impossible, it's just a lot of housekeeping, and I'm not convinced there's all that much benefit to be derived from it.

But then maybe I've got the wrong end of the stick, and you're actually talking about having the option of displaying just the crop slice in the volume render mode...?

**Comment by Lestropie** [comment]
> But then maybe I've got the wrong end of the stick, and you're actually talking about having the option of displaying just the crop slice in the volume render mode...?

No, was meaning single-slice mode.

I think you could get the main image & overlays / ROIs to work correctly (just need to put them at the correct depth, and place each overlay / ROI at a marginally smaller depth than the previous rather than disabling depth testing for them). Hadn't thought a great deal about having overlays / ROIs / FODs / fixels also shown on the added planes, had really only intended for the main image to be sliced. To me FODs are a real stumbling block, even on the main image: You don't want the main image to obscure the 'distant' half of the FOD, but you _would_ want additional planes in front of the main window to obscure them.

Food for thought, but we've got better things to do.

**Comment by jdtournier** [comment]
close...?

**Comment by Lestropie** [comment]
It's flagged as wishlist, but we could remove it from the list unless there's significant requests or someone feels particularly compelled.

**Comment by jdtournier** [comment]
personally I'd flag as `wontfix` and close...
