### ISSUE TITLE
Connectome tool: 'Primary' matrix file list view

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#320]
Hopefully this will give an appropriate compromise between users not being able to figure out the logic behind the tool, and me not wanting to lose functionality I need by simplifying the initial entry point.

Have a list view where matrix files can be loaded, but only one selected at a time. Relevant visual properties can be set through their comboboxes via the 'primary connectome' (i.e. the matrix file selected), or an external matrix file (as is done currently). If the selected 'primary connectome' (lemme know if you think of a better term) changes, all relevant visual properties update.

Importantly, set certain edge-wise visual properties such as edge visibility and edge colour should be set to this by default; so when someone opens a connectome file, they immediately get some sensible visualisation of it. But these properties can also be set via external files that are independent of the particular connectome currently selected.

Also, change the current command-line option for this tool to `-connectome.init` (where the parcellation file must be passed), and `connectome.load` can then be used to load matrix files.

**Comment by thijsdhollander** [comment]
Sounds like a good idea!

Another small one related to (initial) accessibility without impacting flexibility/functionality I had lingering around in the back of my head: maybe it's worth *considering* moving the "LUT" and "Config" settings a bit "downwards" in the Connectome tool's GUI.  I have the feeling they are the ones that might initially trip up most (new) users; but maybe more importantly: they're initially not *strictly* necessary for users to "load their connectome" (in the broad sense of the expression), i.e. to get immediate visual feedback in the viewing panel that "their connectome is there".  The tool shows the main elements of a connectome (nodes & edges) just fine without LUT/Config, but in the current ordering of things, they're the next thing (going top-down through the tool) the user encounters after loading a node image, *but before they get to showing the edges*.  I feel that getting the LUT/Config settings a bit out of the way in the initial top-down approach most users might have, might also help them to see, understand and appreciate the "logic" of the connectome tool better.  I can see/understand though why you put them up there, and grouped them together with the node image under the "basic setup" category.  Objectively thinking about it, it seems they *potentially* fit in many places:

1. "Basic setup": I see your logic there, as I mentioned above.  It does mean users might feel they *need* to "overcome" them before moving on.
2. "General display options": in a certain way you could reason they have to do with how things are displayed (the LUT maybe more than the Config); but that's maybe stretching the specific logic a bit you already have in place in this section.
3. "Node visualisation": same reasoning here (again more the LUT than the Config)
4. "Edge visualisation": clearly they never fit in this category
5. In the "Connectome node list" dock: they're not part of the actual list, but they manipulate mostly stuff that has to do with the "labelling" (colour/name-wise), the "legend" if you will.  At the moment the names are actually only shown in that dock, so it doesn't feel entirely illogical to have the option to set the Config-that-yields-those-names in that dock.

In a similar kind of overall reasoning, it's maybe also worth *considering* moving the entire "General display options" category down a bit, say (for instance) to below the Node/Edge visualisation categories.  Suppose the LUT/Config would be moved into some of these categories, or maybe even further down, and the "General display options" would be moved down as well a bit, you'd end up having quite a self-explanatory work flow to get your connectome to initially "show": first select the mandatory node image (unavoidable first requirement), then go over the node visualisation options that immediately apply to the nodes you just loaded, then go over the edge visualisation to get the edges in as well, and only then consider further "General display options".  The LUT could potentially be thrown in along the way (potentially in the Node visualisation category), or maybe only a bit later (in the "General display options" or even further down in the connectome node list).  The Config potentially only comes to mind at the stage where you reach the connectome node list and start caring about interacting with the nodes (i.e. selecting them).

So yeah, a lot of small potential *considerations*; main motivation being that the user gets visual feedback about their "connectome" (nodes/edges) being successfully loaded as quickly as possible along the journey of exploring / interacting with the connectome tool (initially).

**Comment by Lestropie** [comment]
I think these were the first GUI elements I coded in, so I hadn't fully wrapped my head around what data was for what.

I think what I'm going to do is:
* Remove the option for setting node transparency according to the lookup table. Many such tables don't have an alpha channel, and those that do appear to just have everything fully opaque. And it's hard to see a case where this field could even be used meaningfully in the absence of any other information.
* Move the LUT selection controls to within Node visualisation, below 'colour', but have it only appear if the user has selected 'colour by LUT'.
* The config file import I'm not so sure. Right now its contents are only used in the node list, but in the future it may also be used for e.g. label overlays, in which case its applicability would extend beyond the node list so putting its control there wouldn't really work (particularly as it can be moved and even hidden entirely). I might extend the tooltip and see if that's enough.

If you disagree with any of these, throw a small light object approximately two metres to your right. :-P
