### ISSUE TITLE
transformcalc: -flirt_import incorrectly inverts matrix

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#338]
As reported by Chris Adamson on Google+: Apparently if you provide the input and reference images in the same order as what they were provided to flirt, the command actually outputs the inverse transformation.

**Comment by draffelt** [comment]
I suspect transformcalc was working exactly as Donald intended. FLIRT outputs a forward transform, and so did transformcalc. However mrtransform assumes the input is a reverse transform that maps from template to moving. We might change this in the future, however for now I've modified transformcalc to output the reverse mapping.
