### ISSUE TITLE
MRview: track scalar file render is broken

### ISSUE THREAD

**Issue by draffelt** [MRtrix3/mrtrix3#341]
The colour tracks by track scalar file is not rendering the correct scalar colour. I've seen this issue before when the indexing of the scalar buffers is out. My guess it that something was changed when updating the streamline rendering a while back.

To replicate, generate a tsf file with fixel2tsf, then compare the tsf colours with the fixel colours using the same windowing. 

When only 1 streamline is rendered the colours match the fixel colours/values, however when multiple streamlines are coloured, the colours are 'patchy'.  Multiple streamlines passing through the same fixel are also coloured differently.

**Comment by Lestropie** [comment]
I'd take a wild guess and say it's because `tractogram.cpp:618,628,655,661` are incrementing from 1 rather than 0, which is introducing misalignments between the track and scalar data. But I don't have data on hand to test with and my processor's already being flogged.

**Comment by rtabbara** [comment]
@Lestropie :+1:

**Comment by thijsdhollander** [comment]
Yep, fix as suggested by @Lestropie and implemented by @rtabbara fixes it for me.

**Comment by thijsdhollander** [comment]
(second part included)
