### ISSUE TITLE
alternative way to deal with lack of thread_local support on MacOSX

### ISSUE THREAD

**Issue by jdtournier** [MRtrix3/mrtrix3#342]
This is mostly for me to not forget once we merge #225...

As discussed on #225 ([this comment](https://github.com/MRtrix3/mrtrix3/pull/225#issuecomment-129782921) and the next few), `clang++` support for the standard C++11 `thread_local` is incomplete... However, there is some suggestion on various forums that's it's OK within function scope - it's only at global scope that it's a problem (it's to do with initialisation, apparently - when does the constructor for such an object get called - or something like that). It might be possible to support a thread-local RNG (or any other class) using a construct such as:

``` C++
inline Math::RNG& rng () {
  static thread_local Math::RNG thread_local_rng;
  return thread_local_rng;
}
```

The reason this _might_ work is that instantiation is delayed until the point of first execution, which Apple's version of `clang++` might be happy to handle...

If that works, it would be cleaner than the current pointer-based workaround using the `__thread` keyword...

@dchristiaens, feel free to try this out if you feel the need... Otherwise I'll give it a crack when I have a minute to play around on my MacOSX relic...

**Comment by dchristiaens** [comment]
I gave it try as you can see in the commit, but on Xcode clang it gives the exact same error as before:
```
src/dwi/tractography/rng.cpp:11:16: error: thread-local storage is unsupported for the current target
        static thread_local Math::RNG thread_local_rng;
               ^
1 error generated.
```
As you can see, I already tried putting the function implementation in a separate cpp file. If I do it inline like you suggested, I just get the exact same error at each point where it is called. Any other ideas you may want to try?

**Comment by jdtournier** [comment]
Ah crap... Oh well, guess we'll need to stick with the `__thread` idea then. But it might still be worth using is as a local static variable to keep things a bit cleaner - i.e. something like:
~~~C++
inline Math::RNG& rng () {
#ifdef MRTRIX_MACOSX
  static __thread Math::RNG* thread_local_rng = new Math::RNG;
  return *thread_local_rng;
#else
  static thread_local Math::RNG thread_local_rng;
  return thread_local_rng;
#endif
}
~~~
The MacOSX version will never get destroyed, so you'd get memory leakage if enough threads get launched, but I don't see any circumstances where that would be problem at the moment...
