### ISSUE TITLE
tck2connectome segfaults if streamlines outside image

### ISSUE THREAD

**Issue by chrisadamsonmcri** [MRtrix3/mrtrix3#351]
I tried tck2connectome with the wrong seed image (it was in a different space) and it just segfaulted when it tried to look up a location outside the image. There should be a warning message or something of that nature rather than a segfault.

**Comment by Lestropie** [comment]
Yep; seems the `-assignment_end_voxels` is not something I paid enough attention to when I wrote it, most of the effort went into the more advanced mechanisms.

Check out the `tck2connectome_segfault_fix` branch, recompile and re-test; if it fixes the problem (which it almost certainly should), I'll merge the fix into master.
