### ISSUE TITLE
Unix-style configuration file location not found on Windows (e.g. msys)

### ISSUE THREAD

**Issue by bjeurissen** [MRtrix3/mrtrix3#356]
When running MSYS, mrtrix does not adhere to the linux and Mac convention for locating the config file (it uses the actual native home directory and does not use the . prefix, as opposed to using the virtual linux-style home directory and using the .prefix). This is perfectly ok when running mrtrix from the native window commandline, but can be a bit counter intuitive if you are running MSYS or the like.

**Comment by jdtournier** [comment]
That dates back to the good log days of MRtrix 0.2... I think nowadays we'd be _strongly_ recommending using msys or similar. And regardless, there's no harm in using the same location across all platforms. Happy to change that to make it the same across all platforms.

Only snag is making sure existing users are notified when this happens. Maybe best to stick it on the updated_syntax branch? There's so many changes pending on there, one more won't hurt...

**Comment by jdtournier** [comment]
Closed with 9f81d41
