### ISSUE TITLE
tcksift2

### ISSUE THREAD

**Issue by pmccolganni** [MRtrix3/mrtrix3#374]
Dear Mrtrix team,

Is the tcksift2 command available to use? I have updated the to the latest version, but only have tcksift2.cpp file not the tcksift2.o ?

Thanks

Peter

**Comment by Lestropie** [comment]
Hi Peter,

Yes, the command's definitely there and working. Were there any issues reported by the configure or build scripts after the update? (The `.o` files are not downloaded as part of the code repository; they are created by the build script on your local machine)

Rob

**Comment by pmccolganni** [comment]
Thanks Robert,


When I run build, I get the following error (on Mac OS);


ERROR: [CC] src/dwi/tractography/weights.o


g++ -c -DMRTRIX_MACOSX -fPIC -DMRTRIX_WORD64 -DMRTRIX_NO_NON_POD_VLA -mmacosx-version-min=10.9 -Wall -Wno-unused-function -Wno-unused-parameter -O2 -DNDEBUG -Isrc -Icmd -Ilib -Icmd -I/opt/local/include -DHAVE_INLINE src/dwi/tractography/weights.cpp -o src/dwi/tractography/weights.o


failed with output


In file included from src/dwi/tractography/weights.cpp:1:

In file included from src/dwi/tractography/weights.h:26:

In file included from lib/app.h:29:

lib/file/path.h:124:63: error: no type named 'initializer_list' in namespace 'std'

    inline bool has_suffix(const std::string&name, const std::initializer_list<const std::string> &suffix_list)

                                                         ~~~~~^

lib/file/path.h:124:79: error: expected ')'

    inline bool has_suffix(const std::string&name, const std::initializer_list<const std::string> &suffix_list)

                                                                              ^

lib/file/path.h:124:27: note: to match this '('

    inline bool has_suffix(const std::string&name, const std::initializer_list<const std::string> &suffix_list)

                          ^

lib/file/path.h:128:17: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]

      for(const auto& suffix : suffix_list) { flag = flag || has_suffix(name, suffix); }

                ^

lib/file/path.h:128:32: error: use of undeclared identifier 'suffix_list'

      for(const auto& suffix : suffix_list) { flag = flag || has_suffix(name, suffix); }

                               ^

lib/file/path.h:128:30: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]

      for(const auto& suffix : suffix_list) { flag = flag || has_suffix(name, suffix); }

                             ^

In file included from src/dwi/tractography/weights.cpp:1:

In file included from src/dwi/tractography/weights.h:26:

In file included from lib/app.h:30:

lib/args.h:70:5: error: unknown type name 'constexpr'

    constexpr ArgFlags None = 0;

    ^

lib/args.h:70:23: error: expected ';' after top level declarator

    constexpr ArgFlags None = 0;

                      ^

                      ;

lib/args.h:71:5: error: unknown type name 'constexpr'

    constexpr ArgFlags Optional = 0x1;

    ^

lib/args.h:71:23: error: expected ';' after top level declarator

    constexpr ArgFlags Optional = 0x1;

                      ^

                      ;

lib/args.h:72:5: error: unknown type name 'constexpr'

    constexpr ArgFlags AllowMultiple = 0x2;

    ^

lib/args.h:72:23: error: expected ';' after top level declarator

    constexpr ArgFlags AllowMultiple = 0x2;

                      ^

                      ;

:

bw

Peter


________________________________
From: Robert Smith <notifications@github.com>
Sent: 06 October 2015 12:32
To: MRtrix3/mrtrix3
Cc: McColgan, Peter
Subject: Re: [mrtrix3] tcksift2 (#374)


Hi Peter,

Yes, the command's definitely there and working. Were there any issues reported by the configure or build scripts after the update? (The .o files are not downloaded as part of the code repository; they are created by the build script on your local machine)

Rob

-
Reply to this email directly or view it on GitHub<https://github.com/MRtrix3/mrtrix3/issues/374#issuecomment-145827316>.

[https://avatars1.githubusercontent.com/u/4328435?v=3&s=400]<https://github.com/MRtrix3/mrtrix3/issues/374#issuecomment-145827316>

tcksift2 · Issue #374 · MRtrix3/mrtrix3 · GitHub
Dear Mrtrix team, Is the tcksift2 command available to use? I have updated the to the latest version, but only have tcksift2.cpp file not the tcksift2.o ? Thanks Peter
Read more...<https://github.com/MRtrix3/mrtrix3/issues/374#issuecomment-145827316>

**Comment by Lestropie** [comment]
OK, looks like either your configuration file hasn't been updated (run `./configure` before `./build`), or your compiler has incomplete C++11 support. We've had experience with particular versions of particular compilers that report as being C++11 compliant when we query them, but won't actually compile many of the C++11 features that the MRtrix3 code now makes use of.

If re-running the configure script before building does not fix the issue, you'll need to look into getting your compiler upgraded. There's a few variables in terms of Mac installation, so I can't give you bulletproof advice, but the [wiki page](https://github.com/MRtrix3/mrtrix3/wiki/Installing-on-MacOSX) might at least point you in the right direction.

Cheers
Rob
