### ISSUE TITLE
Image interpolation: Introduce base class

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#381]
Currently these have the same interface, and some degree of duplicated code, but don't derive from a base class.

**Comment by jdtournier** [comment]
Well, they kind of do, they _should_ all inherit from the `Transform` class, which is where most of the duplication takes place. The only things that would be implemented specifically in the interpolator classes are the `voxel()` and `value()` calls, which are going to be different for each interpolator anyway. The remaining duplication is mostly going to be about the other convenience calls like `scanner()` and `image()`, which call `voxel()` internally and are indeed going to be identical across all interpolators, but they need to be reimplemented anyway: if you had a base class with these calls, its version of `voxel()` would be invoked, you'd need to override anyway.

There may be a few other bits of code duplicated between interpolators (haven't looked in a while), but in these cases it'll probably be easier to have one interpolator inherit from the other. 

On the other hand, it might be handy to have an explicit base class for SFINAE-type template deduction. Is this what you have in mind?

**Comment by Lestropie** [comment]
* Consistency with `lib/adapter` / `lib/filter`

* Define the common interface using virtual functions; even if there's no consistency in the implementations, the interface is still intended to be the same, and should be enforced to be the same for any new additions. Sure the base class might be small, but there are others there in the code that are smaller that serve the same purpose.

* Would enable SFINAE I guess; wasn't really my train of thought though.

**Comment by jdtournier** [comment]
Not against consistency, but we really don't want to be using virtual functions for performance-critical code - and the calls we'd be talking about making virtual would presumably fit in that category (assuming we're talking about `voxel()` and `value()` here). The minute you specify a call as virtual, you're forcing the compiler to do a call by function pointer: that's one pointer deference into the class's virtual table, one more to get the pointer to the actual function, and then all the overhead of pushing the function onto the stack and unwinding the stack afterwards - not to mention preventing the compiler from optimisations that might have been possible with an inline call. That's the main reason there are so few virtual functions in MRtrix.

**Comment by Lestropie** [comment]
True. But could even just have that documented there in the base.h file; say that's the template, but this is why it's not a virtual function. Honestly didn't look at them much when I wrote this, just wanted the idea down so I could come back to it later; I'll figure out then whether or not there's a benefit.

**Comment by Lestropie** [comment]
OK, so had a go at this today since I'd done #26 and was in the mood for both syntax updating and fixing things that have been bugging me for a long time. I think the new code is slightly more consistent; a couple of things related to bounds checking also moved out of the `Transform` class and into `Interp::Base`, since that's where they're used exclusively. It also cleans up the class inheritance a little bit. And no virtual functions.
