### ISSUE TITLE
advanced debugging: movie does not want to open a .mih file

### ISSUE THREAD

**Issue by kimbraeckman** [MRtrix3/mrtrix3#389]
Hi,

I am trying to open a .mih file with the mrview command. It works fine but the file I want to open is converted from raw bruker data:

gast096e:~ medisip$ mrview /Users/medisip/NODDI_shell2.mih 
mrview: [ERROR] cannot stat file "/Users/medisip//Users/medisip/Dropbox": No such file or directory
Segmentation fault: 11

also a window pops up that states:
mrview quit unexpectedly

I tried the advanced debugging:
gast096e:mrtrix3 medisip$ ./configure -debug debug; ./build debug

MRtrix build type requested: debug

Detecting OS: darwin
Checking for C++11 compliant compiler [clang++]: 4.2.1 - tested ok
Detecting pointer size: 64 bit
Detecting byte order: little-endian
Checking for variable-length array support: yes
Checking for non-POD variable-length array support: no
Checking for zlib compression library: 1.2.5
Checking for GNU Scientific Library: 1.16
Checking whether GSL compiles with -DHAVE_INLINE: yes
Checking shared library generation: yes
Checking for Qt moc: moc (version 5.5.1)
Checking for Qt qmake: qmake (version 5.5.1)
Checking for Qt rcc: rcc (version 5.5.1)
Checking for Qt: 5.5.1

writing configuration to file './config.debug': ok

[CC] lib/thread__debug.o
[CC] src/dwi/tractography/ACT/gmwmi__debug.o
[CC] cmd/tckstats__debug.o
[CC] lib/image/handler/default__debug.o
[CC] cmd/peaks2amp__debug.o
[CC] src/dwi/tractography/SIFT2/tckfactor__debug.o
[CC] cmd/fixelcfestats__debug.o
[CC] cmd/tckfixcount__debug.o
[CC] cmd/fixel2tsf__debug.o
[CC] src/dwi/tractography/SIFT2/fixel_updater__debug.o
[MOC] src/gui/mrview/tool/vector__debug_moc.cpp
[CC] cmd/roigen__debug.o
[CC] lib/image/adapter/reslice__debug.o
[CC] lib/image/format/mrtrix_gz__debug.o
[CC] lib/file/dicom/tree__debug.o
[CC] lib/image/format/mri__debug.o
[CC] src/gui/mrview/mode/slice__debug.o
[CC] src/gui/mrview/adjust_button__debug.o
[MOC] src/gui/mrview/tool/connectome/connectome__debug_moc.cpp
[CC] src/gui/opengl/font__debug.o
[CC] lib/image/format/ram__debug.o
[MOC] src/gui/mrview/tool/odf__debug_moc.cpp
[CC] src/gui/mrview/tool/view__debug.o
[CC] src/dwi/tractography/SIFT2/reg_calculator__debug.o
[CC] cmd/dwi2response__debug.o
[CC] src/gui/mrview/tool/connectome/node_overlay__debug.o
[CC] src/gui/mrview/mode/base__debug.o
[CC] cmd/dwi2qbi__debug.o
[MOC] src/gui/mrview/tool/roi_editor/roi__debug_moc.cpp
[CC] lib/image/format/analyse__debug.o
[CC] lib/mrtrix__debug.o
[CC] cmd/mrthreshold__debug.o
[CC] src/connectome/connectome__debug.o
[CC] lib/file/mgh_utils__debug.o
[MOC] src/gui/mrview/mode/lightbox__debug_moc.cpp
[CC] cmd/mrmath__debug.o
[CC] cmd/dwi2fod__debug.o
[CC] cmd/amp2sh__debug.o
[CC] lib/image/format/mrtrix_utils__debug.o
[CC] cmd/mrtransform__debug.o
[CC] src/mesh/mesh__debug.o
[CC] src/dwi/tractography/connectome/connectome__debug.o
[CC] src/gui/mrview/colourmap__debug.o
[MOC] src/gui/mrview/window__debug_moc.cpp
[CC] cmd/label2colour__debug.o
[CC] src/dwi/tractography/SIFT/track_contribution__debug.o
[CC] src/gui/mrview/tool/connectome/matrix_list__debug.o
[CC] src/gui/dwi/renderer__debug.o
[CC] src/dwi/tractography/resample__debug.o
[CC] cmd/tsfinfo__debug.o
[CC] src/dwi/directions/mask__debug.o
[CC] src/gui/shapes/sphere__debug.o
[CC] src/dwi/tractography/mapping/mapper_plugins__debug.o
[CC] src/dwi/tractography/SIFT/sifter__debug.o
[CC] src/dwi/tractography/mapping/voxel__debug.o
[CC] cmd/tckgen__debug.o
[CC] src/dwi/tractography/SIFT2/streamline_stats__debug.o
[CC] cmd/dirmerge__debug.o
[CC] src/gui/dialog/image_properties__debug.o
[CC] src/gui/mrview/image__debug.o
[CC] src/gui/mrview/tool/roi_editor/roi__debug_moc__debug.o
[CC] cmd/mrconvert__debug.o
[CC] cmd/shconv__debug.o
[CC] cmd/sh2response__debug.o
[CC] src/gui/mrview/mode/lightbox__debug_moc__debug.o
[CC] cmd/dwi2adc__debug.o
[CC] cmd/fixel2voxel__debug.o
[CC] src/dwi/tractography/mapping/writer__debug.o
[CC] cmd/warpinit__debug.o
[CC] lib/image/format/xds__debug.o
[CC] cmd/dwiextract__debug.o
[RCC] src/gui/mrview/icons.cpp
[CC] src/dwi/tractography/properties__debug.o
[CC] lib/math/LU__debug.o
[CC] cmd/dwi2tensor__debug.o
[CC] src/gui/dialog/report_exception__debug.o
[CC] src/dwi/tractography/mapping/mapper__debug.o
[CC] cmd/tck2connectome__debug.o
[CC] cmd/dirorder__debug.o
[CC] src/gui/mrview/displayable__debug.o
[CC] cmd/dirgen__debug.o
[MOC] src/gui/mrview/tool/overlay__debug_moc.cpp
[CC] src/gui/mrview/tool/overlay__debug_moc__debug.o
[CC] lib/file/ofstream__debug.o
[CC] cmd/5tt2vis__debug.o
[CC] cmd/fixelthreshold__debug.o
[CC] src/dwi/tractography/weights__debug.o
[CC] lib/image/stride__debug.o
[MOC] src/gui/mrview/colourmap_button__debug_moc.cpp
[MOC] src/gui/color_button__debug_moc.cpp
[CC] cmd/tsfdivide__debug.o
[CC] cmd/tsfsmooth__debug.o
[CC] src/dwi/tractography/seeding/gmwmi__debug.o
[CC] src/dwi/tractography/SIFT/proc_mask__debug.o
[CC] lib/image/name_parser__debug.o
[CC] src/dwi/directions/predefined__debug.o
[CC] src/gui/dialog/dicom__debug.o
[CC] cmd/tckimport__debug.o
[CC] cmd/dcminfo__debug.o
[CC] cmd/dirflip__debug.o
[CC] src/gui/mrview/tool/connectome/connectome__debug_moc__debug.o
[CC] src/gui/projection__debug.o
[CC] src/gui/opengl/lighting__debug.o
[CC] lib/image/format/nifti1_gz__debug.o
[CC] cmd/tcksample__debug.o
[CC] src/dwi/tractography/editing/editing__debug.o
[CC] src/gui/gui__debug.o
[CC] cmd/connectome2tck__debug.o
[CC] src/gui/mrview/window__debug_moc__debug.o
[CC] lib/image/format/dicom__debug.o
[CC] cmd/tensor2metric__debug.o
[CC] src/gui/mrview/colourmap_button__debug_moc__debug.o
[CC] cmd/tsfthreshold__debug.o
[CC] src/gui/mrview/icons__debug.o
[CC] src/gui/mrview/tool/vector__debug_moc__debug.o
[CC] src/gui/mrview/tool/connectome/selection__debug.o
[CC] src/dwi/sdeconv/rf_estimation__debug.o
[CC] src/gui/dialog/list__debug.o
[CC] src/dwi/fmls__debug.o
[CC] cmd/5ttgen__debug.o
[CC] src/gui/mrview/tool/roi_editor/roi__debug.o
[MOC] src/gui/mrview/tool/connectome/selection__debug_moc.cpp
[MOC] src/gui/mrview/combo_box_error__debug_moc.cpp
[CC] src/dwi/tractography/connectome/matrix__debug.o
[CC] src/gui/opengl/gl_core_3_3__debug.o
[CC] lib/image/format/nifti1__debug.o
[CC] src/dwi/sdeconv/constrained__debug.o
[CC] src/dwi/tractography/editing/worker__debug.o
[CC] lib/file/dicom/image__debug.o
[CC] lib/args__debug.o
[CC] src/dwi/tractography/connectome/exemplar__debug.o
[MOC] src/gui/mrview/spin_box__debug_moc.cpp
[CC] src/gui/mrview/spin_box__debug_moc__debug.o
[CC] cmd/tsfmult__debug.o
[CC] lib/image/handler/mosaic__debug.o
[CC] src/gui/mrview/tool/connectome/selection__debug_moc__debug.o
[CC] src/connectome/mat2vec__debug.o
[CC] src/dwi/tractography/SIFT2/coeff_optimiser__debug.o
[CC] cmd/mrstats__debug.o
[CC] src/dwi/tractography/mapping/gaussian/mapper__debug.o
[CC] src/gui/dialog/opengl__debug.o
[CC] src/gui/cursor__debug.o
[MOC] src/gui/mrview/mode/ortho__debug_moc.cpp
[CC] src/gui/mrview/tool/odf_preview__debug.o
[CC] cmd/mrpad__debug.o
[CC] cmd/5ttedit__debug.o
[CC] src/dwi/tractography/tracking/tractography__debug.o
[CC] src/dwi/tractography/seeding/dynamic__debug.o
[CC] lib/file/dicom/dict__debug.o
[CC] lib/file/dicom/select_cmdline__debug.o
[MOC] src/gui/mrview/tool/screen_capture__debug_moc.cpp
[CC] src/gui/mrview/tool/screen_capture__debug_moc__debug.o
[CC] lib/file/dicom/quick_scan__debug.o
[CC] lib/image/handler/gz__debug.o
[CC] lib/app__debug.o
[CC] cmd/sh2peaks__debug.o
[CC] src/dwi/tractography/mapping/mapping__debug.o
[CC] lib/image/format/list__debug.o
[MOC] src/gui/mrview/tool/tractography/tractography__debug_moc.cpp
[CC] cmd/mrclusterstats__debug.o
[CC] cmd/fod2fixel__debug.o
[MOC] src/gui/lighting_dock__debug_moc.cpp
[CC] cmd/mrcat__debug.o
[CC] src/gui/color_button__debug.o
[CC] src/gui/mrview/tool/fixel__debug.o
[MOC] src/gui/mrview/tool/connectome/node_list__debug_moc.cpp
[CC] src/dwi/tractography/mapping/fixel_td_map__debug.o
[CC] src/gui/mrview/tool/roi_editor/model__debug.o
[CC] lib/file/dicom/element__debug.o
[MOC] src/gui/gui__debug_moc.cpp
[MOC] src/gui/opengl/lighting__debug_moc.cpp
[CC] src/dwi/tractography/file_base__debug.o
[CC] src/gui/mrview/combo_box_error__debug_moc__debug.o
[CC] src/dwi/gradient__debug.o
[CC] cmd/sh2power__debug.o
[CC] lib/image/format/mgz__debug.o
[CC] cmd/voxel2fixel__debug.o
[CC] src/dwi/tractography/editing/receiver__debug.o
[CC] cmd/tckinfo__debug.o
[CC] src/gui/opengl/lighting__debug_moc__debug.o
[CC] src/dwi/tractography/SIFT/gradient_sort__debug.o
[CC] src/gui/mrview/window__debug.o
[MOC] src/gui/mrview/tool/view__debug_moc.cpp
[CC] lib/file/dicom/patient__debug.o
[CC] lib/image/format/mrtrix_sparse__debug.o
[CC] cmd/dirsplit__debug.o
[CC] src/gui/mrview/tool/tractography/track_scalar_file__debug.o
[CC] src/gui/shapes/cylinder__debug.o
[CC] src/gui/lighting_dock__debug_moc__debug.o
[CC] lib/file/nifti1_utils__debug.o
[CC] src/gui/shapes/halfsphere__debug.o
[CC] src/gui/shview/render_window__debug.o
[CC] src/gui/mrview/tool/screen_capture__debug.o
[CC] cmd/mrcalc__debug.o
[CC] lib/file/key_value__debug.o
[CC] src/dwi/tractography/seeding/basic__debug.o
[CC] cmd/5tt2gmwmi__debug.o
[CC] cmd/afdconnectivity__debug.o
[CC] cmd/tcksift__debug.o
[CC] cmd/fixeldivide__debug.o
[CC] cmd/sh2amp__debug.o
[CC] lib/version__debug.o
[MOC] src/gui/dwi/render_frame__debug_moc.cpp
[CC] src/gui/mrview/mode/ortho__debug_moc__debug.o
[CC] cmd/tcknormalise__debug.o
[CC] lib/datatype__debug.o
[CC] src/dwi/tractography/tracking/write_kernel__debug.o
[CC] src/gui/lighting_dock__debug.o
[CC] src/dwi/tractography/SIFT/track_index_range__debug.o
[CC] src/dwi/tractography/mapping/twi_stats__debug.o
[CC] src/gui/gui__debug_moc__debug.o
[CC] cmd/tck2vtk__debug.o
[CC] lib/file/dicom/series__debug.o
[CC] lib/math/bessel__debug.o
[CC] lib/image/axis__debug.o
[CC] cmd/mrcrop__debug.o
[MOC] src/gui/mrview/tool/tractography/tractogram__debug_moc.cpp
[CC] src/gui/mrview/tool/tractography/tractogram__debug_moc__debug.o
[CC] src/gui/mrview/colourmap_button__debug.o
[CC] src/gui/mrview/tool/connectome/connectome__debug.o
[CC] cmd/mesh2pve__debug.o
[CC] lib/image/format/mrtrix__debug.o
[CC] src/gui/mrview/tool/overlay__debug.o
[CC] src/gui/mrview/tool/connectome/colourmap_observers__debug.o
[CC] lib/image/header__debug.o
[CC] src/dwi/tractography/ACT/act__debug.o
[CC] cmd/mrview__debug.o
[CC] lib/file/mmap__debug.o
[MOC] src/gui/mrview/displayable__debug_moc.cpp
[CC] src/gui/mrview/tool/connectome/node__debug.o
[CC] src/gui/color_button__debug_moc__debug.o
[RCC] src/gui/shview/icons.cpp
[CC] src/gui/shview/icons__debug.o
[CC] src/gui/mrview/tool/connectome/node_list__debug.o
[CC] cmd/dirstat__debug.o
[CC] src/gui/dialog/progress__debug.o
[CC] cmd/mrmesh__debug.o
[CC] lib/image/handler/sparse__debug.o
[CC] src/gui/opengl/gl__debug.o
[CC] cmd/mrresize__debug.o
[CC] cmd/label2mesh__debug.o
[CC] cmd/meshconvert__debug.o
[CC] src/gui/mrview/tool/base__debug.o
[CC] lib/file/dicom/mapper__debug.o
[CC] src/gui/shapes/cube__debug.o
[CC] src/dwi/shells__debug.o
[CC] lib/image/info__debug.o
[CC] src/connectome/config/config__debug.o
[CC] lib/math/SH__debug.o
[CC] cmd/shview__debug.o
[CC] cmd/dcmedit__debug.o
[CC] src/gui/mrview/mode/volume__debug.o
[CC] src/gui/dialog/file__debug.o
[CC] src/gui/mrview/tool/roi_editor/item__debug.o
[CC] src/dwi/directions/set__debug.o
[CC] src/dwi/tractography/roi__debug.o
[MOC] src/gui/mrview/tool/odf_preview__debug_moc.cpp
[CC] cmd/dwi2noise__debug.o
[CC] src/gui/mrview/tool/odf_preview__debug_moc__debug.o
[CC] src/connectome/lut__debug.o
[CC] cmd/fixel2sh__debug.o
[CC] cmd/shbasis__debug.o
[CC] src/dwi/tractography/SIFT2/line_search__debug.o
[CC] lib/image/format/mgh__debug.o
[CC] src/gui/mrview/displayable__debug_moc__debug.o
[CC] src/gui/mrview/tool/view__debug_moc__debug.o
[CC] src/gui/mrview/combo_box_error__debug.o
[CC] lib/file/config__debug.o
[CC] cmd/tckmap__debug.o
[CC] lib/progressbar__debug.o
[CC] src/dwi/tractography/connectome/extract__debug.o
[CC] src/dwi/tractography/SIFT/sift__debug.o
[CC] src/gui/mrview/tool/odf__debug_moc__debug.o
[CC] src/gui/dwi/render_frame__debug_moc__debug.o
[CC] src/gui/opengl/shader__debug.o
[CC] cmd/labelconfig__debug.o
[CC] src/gui/mrview/tool/connectome/node_list__debug_moc__debug.o
[CC] cmd/tckedit__debug.o
[CC] src/dwi/tractography/seeding/list__debug.o
[CC] src/gui/mrview/tool/tractography/tractogram__debug.o
[CC] lib/image/format/pipe__debug.o
[CC] src/gui/mrview/tool/connectome/shaders__debug.o
[CC] cmd/tcksift2__debug.o

clang++ -c -std=c++11 -DMRTRIX_MACOSX -fPIC -DMRTRIX_WORD64 -DMRTRIX_NO_NON_POD_VLA -Wall -O0 -g -D_GLIBCXX_DEBUG=1 -D_GLIBCXX_DEBUG_PEDANTIC=1 -Isrc -Icmd -Ilib -Icmd -I/opt/local/include -DHAVE_INLINE cmd/tckmap.cpp -o cmd/tckmap__debug.o:

In file included from cmd/tckmap.cpp:27:
In file included from lib/point.h:29:
lib/math/vector.h:701:14: warning: implicit conversion turns floating-point number into bool: 'double' to 'bool' [-Wimplicit-conversion-floating-point-to-bool]
      return sqrt (norm2 (V, size, stride));
      ~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lib/math/vector.h:754:21: note: in instantiation of function template specialization 'MR::Math::norm<bool>' requested here
      ValueType n = norm (V, size, stride);
                    ^
lib/point.h:94:15: note: in instantiation of function template specialization 'MR::Math::normalise<bool>' requested here
        Math::normalise (p);
              ^
src/dwi/tractography/mapping/writer.h:223:32: note: in instantiation of member function 'MR::Point<bool>::normalise' requested here
                set_dec (value.normalise());
                               ^
src/dwi/tractography/mapping/writer.h:132:5: note: in instantiation of member function 'MR::DWI::Tractography::Mapping::MapWriter<bool>::~MapWriter' requested here
    MapWriter (const Image::Header& header, const std::string& name, const vox_stat_t voxel_statistic = V_SUM, const writer_dim type = GREYSCALE) :
    ^
cmd/tckmap.cpp:237:18: note: in instantiation of member function 'MR::DWI::Tractography::Mapping::MapWriter<bool>::MapWriter' requested here
    writer = new MapWriter<bool>     (H, name, stat_vox, dim);
                 ^
1 warning generated.


[CC] src/gui/mrview/mode/lightbox__debug.o
[MOC] src/gui/mrview/adjust_button__debug_moc.cpp
[CC] src/gui/mrview/adjust_button__debug_moc__debug.o
[CC] src/gui/mrview/mode/ortho__debug.o
[CC] src/gui/mrview/tool/connectome/file_data_vector__debug.o
[CC] src/gui/dwi/render_frame__debug.o
[CC] lib/exception__debug.o
[CC] lib/image/handler/base__debug.o
[CC] src/gui/mrview/tool/roi_editor/undoentry__debug.o
[CC] src/gui/mrview/volume__debug.o
[CC] lib/file/dicom/study__debug.o
[CC] cmd/dwi2mask__debug.o
[CC] cmd/mrinfo__debug.o
[CC] cmd/mrfilter__debug.o
[MOC] src/gui/shview/render_window__debug_moc.cpp
[CC] cmd/fixelmult__debug.o
[CC] src/gui/shview/render_window__debug_moc__debug.o
[CC] src/gui/mrview/tool/odf__debug.o
[MOC] src/gui/mrview/tool/tractography/track_scalar_file__debug_moc.cpp
[CC] src/gui/mrview/tool/vector__debug.o
[MOC] src/gui/dialog/image_properties__debug_moc.cpp
[CC] src/gui/dialog/image_properties__debug_moc__debug.o
[CC] cmd/maskfilter__debug.o
[CC] src/dwi/tractography/seeding/seeding__debug.o
[CC] lib/image/handler/ram__debug.o
[CC] src/gui/mrview/tool/tractography/tractography__debug.o
[CC] src/gui/mrview/tool/tractography/tractography__debug_moc__debug.o
[CC] lib/image/handler/pipe__debug.o
[CC] lib/math/cholesky__debug.o
[CC] cmd/transformcalc__debug.o
[CC] src/gui/mrview/tool/tractography/track_scalar_file__debug_moc__debug.o
[CC] lib/bitset__debug.o
[LD] lib/libmrtrix-0.3.12__debug.dylib
[CC] src/dwi/tractography/connectome/tck2nodes__debug.o
[LB] bin/tckmap__debug
[LB] bin/dwiextract__debug
[LB] bin/transformcalc__debug
[LB] bin/5tt2gmwmi__debug
[LB] bin/dirstat__debug
[LB] bin/mrstats__debug
[LB] bin/shconv__debug
[LB] bin/dwi2fod__debug
[LB] bin/dirflip__debug
[LB] bin/mrmesh__debug
[LB] bin/fixelcfestats__debug
[LB] bin/dwi2mask__debug
[LB] bin/dirgen__debug
[LB] bin/dcminfo__debug
[LB] bin/tck2connectome__debug
[LB] bin/tensor2metric__debug
[LB] bin/tcksift2__debug
[LB] bin/tcknormalise__debug
[LB] bin/tsfinfo__debug
[LB] bin/tck2vtk__debug
[LB] bin/dirmerge__debug
[LB] bin/peaks2amp__debug
[LB] bin/fixelthreshold__debug
[LB] bin/dwi2adc__debug
[LB] bin/mrfilter__debug
[LB] bin/sh2power__debug
[LB] bin/mrtransform__debug
[LB] bin/dirorder__debug
[LB] bin/label2colour__debug
[LB] bin/roigen__debug
[LB] bin/mesh2pve__debug
[LB] bin/mrmath__debug
[LB] bin/shbasis__debug
[LB] bin/fixel2sh__debug
[LB] bin/tckfixcount__debug
[LB] bin/tsfsmooth__debug
[LB] bin/mrconvert__debug
[LB] bin/sh2amp__debug
[LB] bin/mrthreshold__debug
[LB] bin/dwi2qbi__debug
[LB] bin/mrcrop__debug
[LB] bin/fixeldivide__debug
[LB] bin/mrinfo__debug
[LB] bin/connectome2tck__debug
[LB] bin/tckgen__debug
[LB] bin/dwi2tensor__debug
[LB] bin/tcksift__debug
[LB] bin/mrcat__debug
[LB] bin/tcksample__debug
[LB] bin/meshconvert__debug
[LB] bin/sh2response__debug
[LB] bin/5tt2vis__debug
[LB] bin/amp2sh__debug
[LB] bin/mrclusterstats__debug
[LB] bin/tckedit__debug
[LB] bin/mrresize__debug
[LB] bin/dirsplit__debug
[LB] bin/mrcalc__debug
[LB] bin/tsfthreshold__debug
[LB] bin/labelconfig__debug
[LB] bin/fixel2tsf__debug
[LB] bin/afdconnectivity__debug
[LB] bin/label2mesh__debug
[LB] bin/tckstats__debug
[LB] bin/maskfilter__debug
[LB] bin/fixelmult__debug
[LB] bin/mrpad__debug
[LB] bin/5ttgen__debug
[LB] bin/voxel2fixel__debug
[LB] bin/shview__debug
[LB] bin/tckinfo__debug
[LB] bin/dwi2response__debug
[LB] bin/tsfmult__debug
[LB] bin/tsfdivide__debug
[LB] bin/5ttedit__debug
[LB] bin/sh2peaks__debug
[LB] bin/tckimport__debug
[LB] bin/dcmedit__debug
[LB] bin/dwi2noise__debug
[LB] bin/fixel2voxel__debug
[LB] bin/warpinit__debug
[LB] bin/fod2fixel__debug
[CC] src/gui/mrview/tool/connectome/edge__debug.o
[CC] cmd/meshfilter__debug.o
[LB] bin/meshfilter__debug
[LB] bin/mrview__debug

clang++ src/gui/color_button__debug.o src/gui/mrview/tool/fixel__debug.o src/gui/dialog/report_exception__debug.o src/gui/mrview/displayable__debug.o src/gui/shapes/cube__debug.o src/gui/mrview/tool/tractography/tractogram__debug_moc__debug.o src/connectome/config/config__debug.o src/dwi/tractography/file_base__debug.o src/gui/mrview/combo_box_error__debug_moc__debug.o src/gui/mrview/mode/volume__debug.o src/gui/dialog/file__debug.o src/gui/mrview/tool/roi_editor/item__debug.o src/dwi/tractography/roi__debug.o src/gui/opengl/lighting__debug_moc__debug.o src/connectome/lut__debug.o src/gui/mrview/window__debug.o src/gui/mrview/mode/slice__debug.o src/gui/mrview/displayable__debug_moc__debug.o src/gui/mrview/adjust_button__debug.o src/gui/mrview/tool/view__debug_moc__debug.o src/gui/mrview/combo_box_error__debug.o src/gui/mrview/tool/tractography/track_scalar_file__debug.o src/gui/shapes/cylinder__debug.o src/gui/lighting_dock__debug_moc__debug.o src/gui/shapes/halfsphere__debug.o src/gui/dialog/dicom__debug.o src/gui/mrview/tool/screen_capture__debug.o src/gui/mrview/tool/roi_editor/model__debug.o src/gui/mrview/tool/connectome/connectome__debug_moc__debug.o src/gui/opengl/font__debug.o src/gui/projection__debug.o src/gui/opengl/lighting__debug.o src/gui/mrview/tool/view__debug.o src/gui/mrview/tool/connectome/node_overlay__debug.o src/gui/gui__debug.o src/gui/mrview/tool/odf__debug_moc__debug.o src/gui/mrview/tool/odf_preview__debug_moc__debug.o src/gui/mrview/colourmap_button__debug_moc__debug.o src/gui/mrview/adjust_button__debug_moc__debug.o src/gui/opengl/shader__debug.o src/connectome/connectome__debug.o src/gui/color_button__debug_moc__debug.o src/gui/mrview/mode/base__debug.o src/gui/mrview/icons__debug.o src/gui/mrview/tool/vector__debug_moc__debug.o src/gui/mrview/tool/connectome/selection__debug.o src/gui/mrview/tool/connectome/node_list__debug_moc__debug.o src/dwi/tractography/properties__debug.o src/dwi/tractography/seeding/list__debug.o src/gui/mrview/tool/tractography/tractogram__debug.o src/gui/dialog/list__debug.o src/gui/mrview/tool/base__debug.o src/gui/mrview/tool/connectome/connectome__debug.o src/gui/mrview/tool/connectome/shaders__debug.o src/mesh/mesh__debug.o src/gui/lighting_dock__debug.o src/gui/mrview/mode/lightbox__debug.o src/gui/mrview/tool/roi_editor/roi__debug.o src/gui/mrview/tool/screen_capture__debug_moc__debug.o src/gui/gui__debug_moc__debug.o src/gui/opengl/gl_core_3_3__debug.o src/gui/mrview/tool/connectome/file_data_vector__debug.o src/gui/mrview/spin_box__debug_moc__debug.o src/gui/dwi/render_frame__debug.o src/gui/mrview/colourmap__debug.o src/gui/mrview/tool/roi_editor/undoentry__debug.o src/gui/mrview/volume__debug.o src/gui/mrview/window__debug_moc__debug.o src/gui/mrview/tool/connectome/matrix_list__debug.o src/gui/dwi/renderer__debug.o src/gui/dialog/image_properties__debug_moc__debug.o src/gui/mrview/colourmap_button__debug.o src/gui/mrview/mode/ortho__debug.o src/gui/mrview/tool/connectome/selection__debug_moc__debug.o src/connectome/mat2vec__debug.o src/gui/mrview/tool/overlay__debug.o src/gui/mrview/tool/connectome/colourmap_observers__debug.o src/gui/shapes/sphere__debug.o src/gui/mrview/tool/odf__debug.o src/gui/mrview/tool/vector__debug.o src/gui/dialog/opengl__debug.o src/gui/cursor__debug.o src/gui/dwi/render_frame__debug_moc__debug.o src/gui/dialog/image_properties__debug.o cmd/mrview__debug.o src/gui/mrview/tool/tractography/tractography__debug.o src/gui/mrview/image__debug.o src/gui/mrview/tool/odf_preview__debug.o src/gui/mrview/tool/connectome/node__debug.o src/gui/mrview/tool/tractography/tractography__debug_moc__debug.o src/gui/mrview/mode/ortho__debug_moc__debug.o src/gui/mrview/tool/connectome/node_list__debug.o src/gui/mrview/tool/roi_editor/roi__debug_moc__debug.o src/gui/dialog/progress__debug.o src/gui/mrview/mode/lightbox__debug_moc__debug.o src/gui/mrview/tool/tractography/track_scalar_file__debug_moc__debug.o src/gui/mrview/tool/overlay__debug_moc__debug.o src/gui/opengl/gl__debug.o src/gui/mrview/tool/connectome/edge__debug.o -lmrtrix-0.3.12__debug -lz -g -Wl,-rpath,@loader_path/../lib -Llib -L/opt/local/lib -lgsl -lgslcblas -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -stdlib=libc++ -mmacosx-version-min=10.7 -Wl,-rpath,/Users/medisip/Qt5.5.1/5.5/clang_64/lib -F/Users/medisip/Qt5.5.1/5.5/clang_64/lib -framework QtOpenGL -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtSvg -framework OpenGL -framework AGL -o bin/mrview__debug:

ld: warning: object file (src/connectome/config/config__debug.o) was built for newer OSX version (10.10) than being linked (10.7)
ld: warning: object file (src/dwi/tractography/file_base__debug.o) was built for newer OSX version (10.10) than being linked (10.7)
ld: warning: object file (src/dwi/tractography/roi__debug.o) was built for newer OSX version (10.10) than being linked (10.7)
ld: warning: object file (src/connectome/lut__debug.o) was built for newer OSX version (10.10) than being linked (10.7)
ld: warning: object file (src/connectome/connectome__debug.o) was built for newer OSX version (10.10) than being linked (10.7)
ld: warning: object file (src/dwi/tractography/properties__debug.o) was built for newer OSX version (10.10) than being linked (10.7)
ld: warning: object file (src/dwi/tractography/seeding/list__debug.o) was built for newer OSX version (10.10) than being linked (10.7)
ld: warning: object file (src/mesh/mesh__debug.o) was built for newer OSX version (10.10) than being linked (10.7)
ld: warning: object file (src/connectome/mat2vec__debug.o) was built for newer OSX version (10.10) than being linked (10.7)

gast096e:~ medisip$ gdb --args /Users/medisip/mrtrix3/bin/mrview__debug /Users/medisip/NODDI_shell2.mih r
GNU gdb (GDB) 7.9.1
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin14.5.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /Users/medisip/mrtrix3/bin/mrview__debug...done.
(gdb) 


So it does not find any problem. What went wrong, how can I fix this?

Kind regards,
Kim

**Comment by jdtournier** [comment]
OK, MRView shouldn't crash like this, we should fix that. In the meantime, there are two possible explanations: the mih file produced by `convert_bruker` is badly formed - particularly the `file: ...` line, it looks like it's badly set given the error message (it complains about not finding the file `/Users/medisip//Users/medisip/Dropbox`, which I can clearly see is non-existent). So its either a problem in the mih file itself, or a problem in how the mih format handler interprets this (less likely). If you could post the contents of your mih file, that would answer that question...

**Comment by jdtournier** [comment]
OK, space in filename is causing the problem. I'll need to fix that - and also fix the format handler so it doesn't crash out when the file can't be found...

**Comment by jdtournier** [comment]
Right, there was an issue with the filename handling in the mih format handler when the `file:` was specified as an absolute path. Recent commit should fix this. MRView crashing looks like it might be caused by trying to display the related error message before the GUI is actually ready. Probably the simplest will be to change the order of operations a little to ensure images are loaded later on in the process. 

For completeness, this is what valgrind shows when it crashes (no prior errors - at least none related to our code as such):
~~~
==22918== Invalid read of size 8
==22918==    at 0x636DA4F: QGuiApplication::font() (in /usr/lib/libQt5Gui.so.5.5.0)
==22918==    by 0x6414DC0: QFont::QFont() (in /usr/lib/libQt5Gui.so.5.5.0)
==22918==    by 0x5B5A10F: QWidgetPrivate::QWidgetPrivate(int) (in /usr/lib/libQt5Widgets.so.5.5.0)
==22918==    by 0x5D4DA3A: QMessageBox::QMessageBox(QMessageBox::Icon, QString const&, QString const&, QFlags<QMessageBox::StandardButton>, QWidget*, QFlags<Qt::WindowType>) (in /usr/lib/libQt5Widgets.so.5.5.0)
==22918==    by 0x46ABDB: MR::GUI::Dialog::display_exception(MR::Exception const&, int) (in /home/jdt13/mrtrix3/bin/mrview)
==22918==    by 0x423A6C: main (in /home/jdt13/mrtrix3/bin/mrview)
==22918==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==22918== 
==22918== 
==22918== Process terminating with default action of signal 11 (SIGSEGV)
==22918==  Access not within mapped region at address 0x0
==22918==    at 0x636DA4F: QGuiApplication::font() (in /usr/lib/libQt5Gui.so.5.5.0)
==22918==    by 0x6414DC0: QFont::QFont() (in /usr/lib/libQt5Gui.so.5.5.0)
==22918==    by 0x5B5A10F: QWidgetPrivate::QWidgetPrivate(int) (in /usr/lib/libQt5Widgets.so.5.5.0)
==22918==    by 0x5D4DA3A: QMessageBox::QMessageBox(QMessageBox::Icon, QString const&, QString const&, QFlags<QMessageBox::StandardButton>, QWidget*, QFlags<Qt::WindowType>) (in /usr/lib/libQt5Widgets.so.5.5.0)
==22918==    by 0x46ABDB: MR::GUI::Dialog::display_exception(MR::Exception const&, int) (in /home/jdt13/mrtrix3/bin/mrview)
==22918==    by 0x423A6C: main (in /home/jdt13/mrtrix3/bin/mrview)
~~~

**Comment by jdtournier** [comment]
OK, for this issue, we still need to make sure the error handlers are set _after_ Qt has been initialised. I'll look into it when I have a minute.

**Comment by jdtournier** [comment]
Having had a look at the code, I can't see that this would be an issue any more... I'll close, and if this issue comes up again, we'll look into it with some test data - things certainly don't seem to crash on invalid images at the moment...
