### ISSUE TITLE
Issues with Screen capture tool

### ISSUE THREAD

**Issue by Rishmav** [MRtrix3/mrtrix3#393]
Hi all, 
I seem to be having an issue with my screen capture tool. I think its primarily when i want to capture something in the ortho view format. The Start Index does not progress when I hit the record button to capture the images. Then when I revert to the single view from this the record button still won't work. However if I shut the whole thing down and restart it with the single view, it seems to work. This issue isn't consistent however (which always makes troubleshooting fun!), I remember once many moons ago it did work on the ortho view.
Any hints on what it may be? I don't think i've made any updates that could have affected it.

**Comment by jdtournier** [comment]
Yes, I think I've had similar issues recently. They've tended to be related to how the folder and prefix for the file name are set. I have a sneaky suspicion that if you try to set the name of one of them but press Cancel, it somehow prevents things from working. I've been meaning to look into it, but not enough time...

**Comment by Rishmav** [comment]
Thanks, good to know its not me going mad! I'll play around with the file names and see if it makes a difference. Thanks again for the quick response!

**Comment by Lestropie** [comment]
That should be the directory name problem sorted. If there are still other problems with screen capture, they can be isolated and reported with specific instructions in a new issue.
