### ISSUE TITLE
ROI "layer" is currently visualised "below" overlay

### ISSUE THREAD

**Issue by thijsdhollander** [MRtrix3/mrtrix3#398]
As I originally brought up in https://github.com/MRtrix3/mrtrix3/pull/225#issuecomment-147906230 .  Not a bug, just wondering what makes the most sense in use cases where an image, overlay(s) and ROI editing come together.

**Comment by maxpietsch** [comment]
I am in favour of ROI on top of overlay. Comparing two images, one as main image the other as overlay, hides the ROIs. I reckon ROIs usually cover less area than overlays do. So I don't think the current behaviour makes much sense.

**Comment by maxpietsch** [comment]
The the order of display layers depends on the order of tools in the tool menu. Are there any objections to moving the ROI tool to the end?

**Comment by thijsdhollander** [comment]
Yeah, so I'm definitely also in favour of "ROIs on top": I actually often use combinations of a main image and one or even more overlays to get a good view on certain anatomical features; which I then intend to use for drawing ROIs.  As you mention, it's quite annoying that the ROIs then get covered up (or still difficult to see even when using partial opacity of the/some overlay(s)).

I wasn't aware it simply depended on the order in the tool menu though.  If that's the case, I'd be very happy for the ROI tool to be moved (more) towards the end.  So what do you reckon?  Just swapping the ROI and overlay tools is probably enough?  The other tools don't seem to be able to cause problems, since they're not showing scalar images.

**Comment by maxpietsch** [comment]
Done in c442cc3.
