### ISSUE TITLE
mrview overlay tool threshold box (master branch)

### ISSUE THREAD

**Issue by maxpietsch** [MRtrix3/mrtrix3#401]
The threshold box values are not changed properly and not displayed (empty unless it hits the value typed previously) when clicked inside the field and dragged up or down.
(Qt version 5.2.1, new_syntax-1086-g07c39e50)

**Comment by Lestropie** [comment]
Can anybody reproduce this? I can't trigger it, even in an image with NaNs / infs. It sounds as though the AdjustButton rate was not set properly, so was adding / subtracting NaN to / from the value unless you drag back into the deadzone. But it might have been something weird about a particular image, or it might have been fixed already.

**Comment by maxpietsch** [comment]
If I remember correctly, the issue was not image-dependent and happened on two different machines running ubuntu. Can't reproduce this with dev on macOS or ubuntu so closing due to miraculous self-fix.
