### ISSUE TITLE
Bypass bash completion compilation

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#404]
Add an option to the build script to bypass compilation of the bash completion file. Alternatively, perform this bypass if a target for compiling only a specific binary has been provided. Gets annoying having to wait for this to be pieced together whenever making minor changes to compile a single binary.

**Comment by rtabbara** [comment]
@Lestropie Build script now accepts option <code>-nobashcompletion</code> to bypass generation of bash completion file. If you think the name of the option is a bit cryptic, feel free to rename it to something else.

**Comment by Lestropie** [comment]
No, that's what I was thinking. It should still recognise `-nobash`.
