### ISSUE TITLE
Image shifted in updated syntax MRview

### ISSUE THREAD

**Issue by draffelt** [MRtrix3/mrtrix3#407]
While debugging an issue with failed mrtransform tests, I've discovered that the image is shifted along x *inside* the FOV. In the screenshot below, left is the master branch and right is the updated syntax branch, both displaying the same image.

![image](https://cloud.githubusercontent.com/assets/2948458/11529142/325712f4-993f-11e5-9ece-9fdc1c0827d1.png)

**Comment by jdtournier** [comment]
Can't reproduce... Are you sure everything is up to date? Does this happen for all images, or just a specific one?

**Comment by maxpietsch** [comment]
Can't reproduce either. Probably unrelated but I changed the precision of the header transformation stored in mif and mih files in bbaaec5fe59bd9a1813ea45125c8.

**Comment by draffelt** [comment]
Ok, so it turns out it is only an issue for mif.gz files

**Comment by draffelt** [comment]
It must be a change since Oct 2nd, since this is when I committed the mrtransform tests.  Happy to look into it further tomorrow. For now I'm off to bed.

**Comment by jdtournier** [comment]
OK, issue confirmed for `mif.gz` files... We'll look into it.

**Comment by maxpietsch** [comment]
There is no shift between original and mif.gz in mrview if I use mrtransform mrview from the same branch but if I mix branches then both show the shift. If I gunzip the respecive mif.gz files, then they are not shifted in mrview in any branch.

**Comment by maxpietsch** [comment]
As suggested by @jdtournier: The offset differs between banches for the same image. This is caused by different header.str().size() due to the additional header enrty of the mrtrix_version in the updated syntax branch. The offset shouldn't be changed on load anyway, so I changed that.

**Comment by draffelt** [comment]
Nice work, thanks
