### ISSUE TITLE
MRview tractography tool: Move colour controls

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#409]
Currently the tractography tool is the only one where colour is modified by right-clicking on the list entry; all other tools have a colour button or similar control as part of the UI elements. Should change this to be more consistent with other tools.

**Comment by jdtournier** [comment]
Yes, I've noticed that too. But the other way around... I always shoot for the right click menu, and was annoyed not to find it with the overlay tool. I agree it would be better to make things consistent, but preferably by providing both options in all tools where relevant....

**Comment by Lestropie** [comment]
Somewhat of a duplicate of #326. Will attack that, but assess if it's possible to have colour settings accessible both from the toolbar and context menu across a range of tools.
