### ISSUE TITLE
Gradient table broken in mif.gz

### ISSUE THREAD

**Issue by bjeurissen** [MRtrix3/mrtrix3#429]
Using the update_syntax branch, the gradient table is corrupt when exporting from mif.gz:

```
$ mrinfo output/test/dwi_corrected.mif.gz -dwgrad
mrinfo: [ERROR] error importing diffusion gradient table for image "output/test/dwi_corrected.mif.gz"
```
While the following works fine:
```
$ mrinfo tmp/test/dwi_corrected.mif -dwgrad
```

Inspecting the text header after conversion from mif.gz to .mih reveals funny entries as shown below:
```
dw_scheme: dw_scheme: -0.6069199786,-0.4852501698,-0.6294286395,1199.999071
```

**Comment by jdtournier** [comment]
I can't reproduce - but the chances are it might have something to do with #407... Can you confirm whether the image was generated prior to this commit...?

**Comment by bjeurissen** [comment]
Looks like #407 might have something to do with it. Am rerunning with an image generated after that commit.

**Comment by bjeurissen** [comment]
Problem was solved rerunning with an image generated after that commit.
