### ISSUE TITLE
Scripts: Module import in Python2/3

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#442]
Currently my new `dwi2response` script only works on Python3: Python2 fails to find the modules that have been placed in the `scripts/src/dwi2response` directory.

Currently I'm doing e.g.: `import src.dwi2response.fa`

Anyone know a robust way of doing this that will work in both Python versions?

**Comment by dchristiaens** [comment]
You need to add `__init__.py` files in the directory structure. Otherwise python doesn't recognise the folder as a module. 

I think you can even take it one step further and do
```
if arg == 'fa':
    from src.dwi2response import fa as algorithm
else if arg == 'tournier':
    from src.dwi2response import tournier as algorithm
#...

# and then call
algorithm.x()
```
to obtain a sort of module-level polymorphism.

**Comment by Lestropie** [comment]
... Huh. I swear I tried that. I must have forgotten to put one in the `src/` directory itself and only done the sub-directories.

Yeah I want to do the polymorphism thing at some stage. Ideally I want users to be able to add & execute their own algorithms just by adding a file in the relevant `src/` directory; the main script should scan that directory and build the help page / execute accordingly.
