### ISSUE TITLE
Viewing each volume of a 4D image in Lightbox mode

### ISSUE THREAD

**Issue by draffelt** [MRtrix3/mrtrix3#451]
I was computing an image today storing the elements of a Jacobian matrix in the 4th dimension, and thought it would be nice to see all of the volumes at the same time in a 3x3 grid.  The same would apply to tensor images.

It may also be useful to see all diffusion volumes at once for checking image quality and results of pre-processing (eg failed motion correction). 

When in lightbox mode, we could possibly have a check box in the view tool that enables the user to switch to 4D, where the slice increment becomes the volume increment.

**Comment by rtabbara** [comment]
Added in #694
