### ISSUE TITLE
dwi2mask confused by negative outliers in background introduced by dwipreproc

### ISSUE THREAD

**Issue by bjeurissen** [MRtrix3/mrtrix3#454]
I noticed that on some data sets, dwipreproc introduces large negative values in the background. As they are in the background they are pretty harmless in general but they tend to mislead the thresholding in dwi2mask.

Where should this be dealt with?

Should dwipreproc refrain from outputting negative amplitudes?
Or should dwi2mask ignore them?

**Comment by bjeurissen** [comment]
An easy fix would be to have dwi2mask treat all negative values as zero.

**Comment by draffelt** [comment]
That sounds like a good plan to me Ben. Are you happy to make this change?
I'm currently packing to go camping for two weeks.

Do you know what causes the large outliers, negative Jacobians in topup? If
either eddy or topup is using sinc or cubic interpolation you might expect
some, but they won't be large.

**Comment by bjeurissen** [comment]
Haven't looked into the cause yet. I am happy to do it. Enjoy your camping!
Where are you heading off to?

**Comment by draffelt** [comment]
Thanks. We are off to Merimbula. Our neighbouring camp site is going to
love us with a nocturnal 8 week old.

**Comment by Lestropie** [comment]
I'm wondering if should be _both_; `dwi2mask` should use 0 as the lower search bound if the minimal value is negative, but I'm not convinced that retaining any negative value from eddy is of any use in any context. Any objections?

**Comment by thijsdhollander** [comment]
If there weren't any negative values before `eddy` (which is probably the case), they should indeed also not appear thereafter.  Do we know what causes them?  Like @draffelt mentioned, I wouldn't expect them to be large if caused by negative Jacobians, caused by e.g. cubic interpolation; unless other funny business is happening...

Either way, I'm happy for them to be capped to zero. :+1:

**Comment by Lestropie** [comment]
It'll be wacky jacobians in the `topup` warp field primarily. Had the same issue back when I was trying to solve for the inhomogeneity field myself.

**Comment by bjeurissen** [comment]
ce5b70c fixes dwi2mask as agreed above.

Not sure if dwipreproc _has_ to be changed, though. Maybe it is best to decide on a per-cmd basis whether negative intensities should be treated as zeros? I am happy either way.

**Comment by bjeurissen** [comment]
As `dwi2mask` itself is now fixed, I took the liberty to close the issue.

Most other commands should not be affected by the negative Jacobians as they are in the background.
