### ISSUE TITLE
build: error building single executable

### ISSUE THREAD

**Issue by jdtournier** [MRtrix3/mrtrix3#455]
Just got this error in the build script - although it seemed to complete OK:
~~~ShellSession
$ ./build release/bin/mrinfo 
( 1/60) [CC] release/src/dwi/gradient.o
...
(60/60) [LB] release/bin/mrinfo
Traceback (most recent call last):
  File "./build", line 1138, in <module>
    if dev and stop <= 1:
NameError: name 'dev' is not defined
~~~
Any ideas....?

**Comment by rtabbara** [comment]
I think you'll need to run configure again. The dev option was added to opt into docs/bash completion generation.

**Comment by jdtournier** [comment]
Yep, that fixed it. Sorry...

**Comment by Lestropie** [comment]
On that topic though: We should add checks to the build script that will identify if the config file was generated using an earlier version (presence of outdated flags, absence of new ones), and instruct users to re-run the configure script.
