### ISSUE TITLE
Path on labelconfig tutorial does not match git master

### ISSUE THREAD

**Issue by maedoc** [MRtrix3/mrtrix3#459]
On git master, the path appears to be `mrtrix3/src/connectome/config/fs_default.txt` instead of the given `mrtrix3/src/dwi/tractography/connectomics/example_configs/fs_default.txt`.

I didn't dare edit your wonderful wiki so voila an issue..

**Comment by Lestropie** [comment]
Thanks for the report; I've fixed the path.
I hope you'll agree that the new location of these files is much nicer than the original one...

**Comment by maedoc** [comment]
@Lestropie yup definitely worthwhile
