### ISSUE TITLE
Forum topic title field too small

### ISSUE THREAD

**Issue by maedoc** [MRtrix3/mrtrix3#460]
Sorry for the inane complaint, but in the forum, the title field for a post is too small:

![pic](http://i.imgur.com/sp4kNX1.png)

There's text there, but you can't see it. (This is Firefox & Linux)

**Comment by maxpietsch** [comment]
Confirmed with firefox 44.0.2.
Things look ok when I add `min-height: 28px` to the css:

 from 
~~~~
#reply-control.edit-title .contents input#reply-title {
    color: #222;
    margin: 6px 10px 3px 0;
    padding: 7px 10px;
}
~~~~

to 

~~~~
#reply-control.edit-title .contents input#reply-title {
    color: #222;
    margin: 6px 10px 3px 0;
    padding: 7px 10px;
    min-height: 28px;
}
~~~~

**Comment by thijsdhollander** [comment]
Can definitely confirm as well.  I've actually just been living with it...
But if this is all it needs to be fixed, go for it! :+1:

**Comment by rtabbara** [comment]
Ok, this should be fixed. I extended @maxpietsch suggestion to apply to all input fields that were affected. I'll close for now, but please let me know @maedoc if you're still encountering issues.

**Comment by maedoc** [comment]
@rtabbara it looks fine now, thanks
