### ISSUE TITLE
Readthedocs "Edit on Github" links to `updated_syntax` branch.

### ISSUE THREAD

**Issue by dchristiaens** [MRtrix3/mrtrix3#464]
When editing the User docs online, changes are pushed to the `updated_syntax` branch (which is now legacy I suppose). I didn't see that immediately, which explains the origin of pull request #463. I think the user docs should now be linking to the master branch directly, and it may be better to delete the `updated_syntax` branch altogether. We would still need to make pull requests for all changes as `master` is protected, but at least it would avoid confusing branch naming.

**Comment by draffelt** [comment]
Daan you are right. Rami changed it from master while working on it. Can
you change it back.

Agreed we should delete updated syntax. The old master documentation should
be accessibe via its tag.

**Comment by dchristiaens** [comment]
Thanks Dave, good to know. Now that the pull request is merged, I also noticed the changes don't take effect on the website. Same goes for Rob's updates to the Licence notice earlier today.

I'm not quite sure what I would need to change in oder for readthedocs to track master again, though. It may be better if @rtabbara could take care of that. I wouldn't want to mess up our nice new website on the day of a major update :-)

**Comment by draffelt** [comment]
Ah sorry. I forgot the @rtabbara when asking to change it back. Yes this is
something only he will be able to do.

Rami, maybe we should set the creditials for read the docs to be the same
as digital ocean?

**Comment by rtabbara** [comment]
@dchristiaens This should be fixed. Please let me know whether it works for you.

@draffelt I can give multiple users admin access. You'll need to sign up to readthedocs [here](https://readthedocs.org/accounts/signup/) and then I can add the corresponding usernames to the admin list.

**Comment by dchristiaens** [comment]
Works like a charm. Thanks Rami!
