### ISSUE TITLE
Stop TravisCI from building on push?

### ISSUE THREAD

**Issue by jdtournier** [MRtrix3/mrtrix3#468]
Recently, we had a pull request from a forked repo, so none of its commits had been pushed. At the time, TravisCI was set up to build pushes only, but not pull requests. I've set it to build both now, but I reckon it's overkill. Should we restrict testing to pull requests only?

**Comment by draffelt** [comment]
Don't we need to make changes to master via pull requests now anyway? If so
then I think this is fine that only the master branch is tested thoroughly.

That said, if someone branches for some major changes, it might be nice to
still detect breakages early on.

**Comment by jdtournier** [comment]
That's what I was thinking. For branches that we might want to test, there's nothing stopping us from making a pull request - we just need to flag up that it's not for merging quite yet. What do you think?

**Comment by jdtournier** [comment]
OK, just made the change. Feel free to reopen if it causes problems...
