### ISSUE TITLE
Global tractography threading race condition.

### ISSUE THREAD

**Issue by dchristiaens** [MRtrix3/mrtrix3#477]
As reported recently, multi-threaded `tckglobal` produces funny output on some systems, that occurs if the `SpatialLock` on a proposal is not properly released. As a result, a cubical region around its position is excluded for further processing, resulting in "dark" blocks of low particle density. It only seems to occur on some systems and seems to depend on the parameter settings. In any case, the single-threaded code (enforced with option `-nthreads 1`) works fine without issues.

I'm filing a proper issue here until I can implement a fix.

**Comment by Lestropie** [comment]
If I had to guess, I'd say there's a small discrepancy in the implementation of `std::set`. Your `SpatialLock::unlock()` call is relying on finding equivalence of a floating-point 3-vector to delete an entry for the set, which is best avoided - and the `erase()` call won't flag an error if it fails to delete an entry. You could either round the positions to integers and use that in the set, or you could generate a unique integer for each thread and use that in a `std::map<int, point_type>`.

**Comment by bjeurissen** [comment]
I gave it a spin on my linux system, following the instructions in the workflow manual, and it does not lock but segfaults when using multi-threading (pretty much immediately after the data has been preloaded). Using single-threading it seems to run fine.

**Comment by dchristiaens** [comment]
Hmm, that's not good. So there's definitely something wrong with the multithreading on non-MacOS X systems. I'm a little busy these days and won't be able to investigate this properly before ISMRM, so maybe I should add a warning in the user guide until I do?

@Lestropie, you're right, it might be more safe to unlock any point within the thresholded range. However, the points used in the locking are never subject to any calculations or changes, so I don't think it would make a difference. Or do you reckon the float could be altered upon a simple copy to the set?

**Comment by Lestropie** [comment]
I certainly wouldn't expect the values to change. It's just generally considered best practise to avoid testing equality of two floating-point numbers. There's a chance that precisely how the `std::set` is implemented, in terms of sorting / detection of duplicated entries, may differ between systems, and this could be why it works on OSX but not others. For instance: Whether the manually-defined comparison operator is expected to return true or false for equivalent entries.

It should be pretty easy to see when this is failing: Just test the output of the `erase()` call at `spatiallock.h:85`, and if it's zero, print out the position and the set contents.

**Comment by dchristiaens** [comment]
These commits fix what I expect to have been the root cause of the problem. I'm in desperate need for testers though, because I cannot replicate the issue on my Ubuntu 14.04 VM. @bjeurissen, you're the only developer who replicated the problem. Would you be able to give this a test drive please?

If this still fails, I'll give @Lestropie's suggestion a try. In fact, I might do it anyway since a map with `thread::id` keys indeed seems more elegant here. However, the current `vec_compare` at `spatiallock.h:31` provably obeys the _strict weak ordering relation_ for `std::set Compare` and should therefore technically be sufficient, I think.

**Comment by dchristiaens** [comment]
This should now be resolved in #824.

**Comment by LeeReidCSIRO** [comment]
tckglobal using a HCP dataset is still producing segmentation faults on linux.

My call is as follows:
`tckglobal /somepath/diffusion/data.mif /somepath/diffusion/response_wm.txt -riso /somepath/diffusion/response_csf.txt -riso /somepath/diffusion/response_gm.txt -mask /somepath/diffusion/brainmask_diff_space.nii.gz -niter 1e9 -fod /somepath/diffusion/fod_global_tractography.mif -fiso fiso.mif -nthreads 8 /somepath/diffusion/tracks_global_tractography.tck`

The output is as follows:

> tckglobal: [100%] preloading data for "/somepath/diffusion/data.mif"
> tckglobal: [100%] uncompressing image "/somepath/diffusion/brainmask_diff_space.nii.gz"
> tckglobal: [  0%] running MH sampler...
> tckglobal: [SYSTEM FATAL CODE: SIGSEGV (11)] Segmentation fault: Invalid memory access

This 'running MH sampler' can get to anything between 0 - 100% before the crash occurs. In one instance the crash occurred at 100%, and an empty track file had been generated.

**With threading disabled (-nthreads = 0) the issue vanishes.** 

I am happy to supply images and the scripts used to generate them if required.

This is not an issue that is critical for me, as I'm returning to iFod2 for other reasons, but I thought I should flag it for the sake of others.

**Comment by dchristiaens** [comment]
Hi,

Can I just check that you are using a recent version of MRtrix, with the changes in #824 merged in?
If so, which OS are you using? Could you send me your (anonymised) images if you'd like me to look into it?

Cheers,
Daan

**Comment by LeeReidCSIRO** [comment]
Hi Daan,

I pulled MRTrix about two days back, so it should be up to date. 

It is being run on an interactive cluster node:
SUSE Linux Enterprise Server 12 SP1 (x86_64)
Version 12-SP1
Version ID 12.1

I can also replicate this issue on Ubuntu 12.04

Perhaps there is something I've done wrong when generating my data.mif, but either way an invalid memory access crash is not the ideal outcome.

I will email you files and the script now.

Cheers,
Lee

**Comment by ansk** [comment]
Dear Daan,

I am also facing segfault in `tckglobal`. Commandline and terminal output are the same as with @LeeReidCSIRO .
My `mrtrix` git pull is from 9 may 2017.
My system is Debian Linux 8.3 (jessie).

Antonin

**Comment by dchristiaens** [comment]
This turned out to be new issue, accidentally introduced in #785. Fixed in #998.
