### ISSUE TITLE
Add test for dwi2tensor

### ISSUE THREAD

**Issue by bjeurissen** [MRtrix3/mrtrix3#495]

**Comment by jdtournier** [comment]
@bjeurissen: can we close this...?

**Comment by bjeurissen** [comment]
No, still need to generate the test data based on the current code
On 16 May 2016 5:18 p.m., "J-Donald Tournier" <notifications@github.com>
wrote:

@bjeurissen <https://github.com/bjeurissen>: can we close this...?

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/MRtrix3/mrtrix3/issues/495#issuecomment-219452954>
