### ISSUE TITLE
Command-line parsing: More helpful messages on failed parsing

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#536]
It's reasonably common for users to get confused by the `[ERROR] expected exactly # arguments (# provided)` error.

A relatively common mistake is to omit the preceding dash from options, so that the option (and any subsequent parameters to that option) get interpreted as arguments. When this occurs, it should be possible to search for the presence of command-line options where the option name matches the text provided in one of the arguments, and therefore give the user a hint that they may have forgotten the '-'.

Another possibility to help here would be to print out the command usage _with arguments only shown_; and then print out what the user has provided as arguments ie. _with the provided options & parameters stripped_; that might help users isolate where they've mucked up their command string...?

**Comment by jdtournier** [comment]
Your first suggestion sounds like overkill - there's so many ways to get things wrong...

But the second option is simple enough, and should help users figure out what they've done wrong. Happy enough with that.
