### ISSUE TITLE
generate_user_docs.sh doesn't work with BSD sed

### ISSUE THREAD

**Issue by maxpietsch** [MRtrix3/mrtrix3#543]
Generate_user_doc does not work on default OS X as BSD sed differs from GNU sed. The former does not allow in-place editing without backup file and one cannot use strings that contain escape sequences.

Current sed command: `sed -ie "1i$filename\n===========\n" $filepath/$filename.rst`

The first problem could be fixed by `sed -i ".bak" ...` and then `rm $filepath/$filename.rst.bak`. The second can supposedly be solved with ANSI escape sequences but I can't find a solution for newline and equal signs in the string. So I am stuck with 
`sed -i '.bak' '1i\'$'\n'$filename$'\n' $filepath/$filename.rst` which works except for the missing ===========\n sequence.

Someone with more bash skillz around? Alternative would be to use perl or something else that is more portable.

**Comment by rtabbara** [comment]
@maxpietsch I've got a Mac at home, so I'll give this a *bash* later tonight to see if we can modify this to work with BSD sed. Otherwise, I agree that using something like perl or python might be the better alternative, especially if it allows Win users to also generate docs.

**Comment by Lestropie** [comment]
Bump due to encountering this issue at the OHBM Hackathon in the course of #1626.
