### ISSUE TITLE
dwiextract: Remove output image dimensionality reduction

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#552]
Change `dwiextract` back to produce a 4D image even if there's only a single volume in the input image.

I think I originally did this because I was getting frustrated with the prevalence of [x y z 1] images going all over the place. But it has to be handled explicitly in scripts, and it's confusing users.

This will require corresponding modifications in both scripts and documentation.

**Comment by jdtournier** [comment]
Relates to #344
