### ISSUE TITLE
Add drag/drop files to tools

### ISSUE THREAD

**Issue by chrisk1** [MRtrix3/mrtrix3#560]
It would speed up usage considerably if it were possible to drag/drop files into the tools in mrtrix - i.e. dragging a file into the window to use as an overlay (vs clicking "Open overlay image" and navigating to the file's folder). Thanks!

**Comment by maxpietsch** [comment]
If not too much hassle, it would also be nice if the order of the images can be changed by moving them in the image list. This would be useful when ROIs overlap for instance. Definitely in the "nice to have" category, though.

**Comment by jdtournier** [comment]
OK, both of these require drag & drop support, which already exists for the main image. If anyone is interested in taking this on, [take a look here](https://github.com/MRtrix3/mrtrix3/blob/master/src/gui/mrview/window.cpp#L128-L153) for inspiration...

**Comment by rtabbara** [comment]
@chrisk1 @maxpietsch  This has now been added. Let me know if you encounter any problems.
