### ISSUE TITLE
mrtransform on (unsigned) integers

### ISSUE THREAD

**Issue by thijsdhollander** [MRtrix3/mrtrix3#563]
When applying `mrtransform` to an input image that has, e.g., an unsigned 16 bit integer (LE) data type, the default output seems to also be of that data type... but this is very often not desirable.  I just noticed this when I tried to resample a DWI image with the aforementioned data type to another anatomical image's space: by default, bicubic interpolation is used (makes sense), but this will introduce some negative values (also still makes sense); but the output image still being of that original data type means that

1. accuracy is lost, because interpolation is supposed to introduce decimal values... don't want to lose these
2. the negative values can't be represented
3. the negative values get mapped / wrapped around to the upper end of the range for that datatype... i.e., extremely high values

The issue doesn't happen with `mrresize` ; that one properly goes for a floating point data type.  At the moment, this makes outputs inconsistent between both of these commands as well.  Consider:

```
mrresize original.mif resampled.mif -voxel 1
mrtransform original.mif resampled_doublecheck.mif -template resampled.mif
```

...if `original.mif` is of an integer type and has, e.g., a voxel size of 2.5mm or so, then `resampled.mif` and `resampled_doublecheck.mif` won't match.

**Comment by draffelt** [comment]
Agreed this should be dealt with. 

In the registration branch (for both `mrresize` and `mrregister`) I detect if cubic or sinc interpolation is used, then warn the user if the output data type is signed:
```
WARN ("using cubic or sinc interpolation when the output data type is not signed "
      "may cause values to underflow. Change the output data type with -datatype");
```
However, if the user choose linear interpolation and outputs an integer data type, then yes there will be some loss of precision. 

I'd be happy to just change the default output of these commands to float32.

**Comment by thijsdhollander** [comment]
> I'd be happy to just change the default output of these commands to float32.

Yep, I think that probably makes sense for any command that intends to resample the input data in any way.  (currently `mrtransform` and `mrresize` in master, but `mrregister` definitely as well).  If the user specifically wishes to use another type, they can of course still do so via the `-datatype` option.

**Comment by jdtournier** [comment]
Fully agree with float32 by default (apart maybe from nearest neighbour interpolation?). That's by far the most sensible thing to do. If users genuinely want some other datatype, we can make sure these commands all have a -datatype option available.

**Comment by thijsdhollander** [comment]
Thanks for the fix! :+1:   Maybe worthwhile to check that everything in the registration branch also follows the same logic consistently.
