### ISSUE TITLE
dwipreproc: Option for manual topup/eddy file input

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#569]
For more exotic acquisition schemes that don't fit into one of the current three phase encoding imaging protocol designs, it may still be beneficial to wrap the image pre-processing using the `dwipreproc` script. It should be possible to add a command-line option that allows manual specification of the config and index files required by `topup` and `eddy`.

**Comment by bjeurissen** [comment]
Related to this: for more exotic subjects (e.g. non-brain, small animal imaging, ...), it might be worth adding a mask option to the `dwipreproc` as well. In my experience, masking is what is always going wrong when moving to other things than the human brain.

**Comment by Lestropie** [comment]
Closing this since my preference would be for manual manipulation of image header key-value pairs that encode the phase encoding information prior to running `dwipreproc` by using `mrconvert -set_property`, and then using the `-rpe_header` option in `dwipreproc`, rather than providing `topup` / `eddy` files manually to `dwipreproc`. Relevant documentation added in #1065, awaiting merge of #1101.

@bjeurissen: If this is a known issue with running `dwipreproc` on such data as opposed to a hypothetical one, we'll create a new issue for it.
