### ISSUE TITLE
mrconvert -stride not working when order unchanged

### ISSUE THREAD

**Issue by thijsdhollander** [MRtrix3/mrtrix3#570]
I just started noticing `mrconvert` with the `-stride` option is not changing/applying the requested strides when the order of strides is unchanged relative to the original order, but when a sign change of one or more strides *is* requested.

I may be wrong, but I have a feeling this might have started happening since #557 was merged...

**Comment by jdtournier** [comment]
Crap, yes, you may be right... The `Stride:: get_nearest_match()` function that I rely on to preserve the original strides considers forward and backward strides as equivalent performance-wise, so won't modify when that's the only difference - but clearly that's not the right criterion when this is a direct user request. I'll fix that ASAP.

**Comment by jdtournier** [comment]
closing this, carrying on with #571
