### ISSUE TITLE
Compatibility with Eigen 3.3

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#579]
Although we recommend that people use the stable release version of Eigen, ultimately some people will still install the beta, and eventually 3.3 will become their stable release. So we should get MRtrix3 compatible with it at some stage.

For now, should also alter the documentation to explicitly recommend download / installation of the stable release rather than the beta.

Edit: Following on from #578.

**Comment by jdtournier** [comment]
This issue is still very much current: e.g. #793.

**Comment by jdtournier** [comment]
OK folks, this is now critical: [Eigen 3.3 is now the stable version](http://eigen.tuxfamily.org/index.php?title=Main_Page)...

**Comment by jdtournier** [comment]
Right, a bit of testing suggests that on my system, adding the `-mno-avx` flag prevents the need for 32 byte alignment, reverting back to 16 byte alignment as in Eigen 3.2. I think the quickest fix for now is simply to add that flag to the defaults, which will at least allow us to use Eigen 3.3 without crashes. 

Here's a quick snippet of code to demonstrate. Note the gymnastic involved in trying to figure out the memory allocator's alignment guarantees...

```C++
// To compile :
//
// with AVX enabled:
//
//   g++ -march=native -O2 -DNDEBUG -isystem eigen-3.3 test_alignment.cpp && ./a.out
//
// or with AVX explicitly disabled:
//
//   g++ -march=native -mno-avx -O2 -DNDEBUG -isystem eigen-3.3 test_alignment.cpp && ./a.out


#include <iostream>
#include <Eigen/Core>

#ifndef EIGEN_DEFAULT_ALIGN_BYTES
// If not specified, assume 16 byte alignment (it's hard-coded as such in Eigen 3.2):
# define EIGEN_DEFAULT_ALIGN_BYTES 16
#endif

// guess default alignment:
inline size_t default_alignment ()
{
  size_t default_align = std::numeric_limits<size_t>::max();
  for (size_t n = 0; n < 100; ++n) {
    struct alignas(64) X { char c; };
    X* x = new X;
    size_t align = reinterpret_cast<size_t>(x) & 63U;
    if (align && align < default_align)
      default_align = align;
  }
  return default_align;
}


int main (int argc, char* argv[])
{
  std::cerr << "allocator alignment detected to be: " << default_alignment() << " bytes\n";
  std::cerr << "Eigen3 alignment detected to be: " << EIGEN_DEFAULT_ALIGN_BYTES << " bytes\n";

  return 0;
}

```

I'll work up a fix to include this in `configure` for a quick solution. But I'd like to have this fixed properly long term, we're missing out on a potential 2-fold increase in performance by not using the AVX extensions...

**Comment by jdtournier** [comment]
Closing this for now, see #833 for further discussion.
