### ISSUE TITLE
Meaningful errors on failed RAM allocation

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#586]
_Any_ code requesting dynamic memory allocation should be wrapped in a `try {} catch {}`, so that we can produce a meaningful error message (and hopefully clear the stack correctly) if the user doesn't have enough RAM to do what they're trying to do.

This has cropped up on the forum a couple of times in a couple of different manners / contexts, so we should try to cover off as many possible cases as we can.

**Comment by Lestropie** [comment]
I've pushed a change adding exceptions for scratch buffers, SIFT/SIFT2 and CFE. There's already an appropriate check in the [memory-mapping code](https://github.com/MRtrix3/mrtrix3/blob/master/lib/file/mmap.cpp#L130). Anyone think of anywhere else that might be problematic?

**Comment by jdtournier** [comment]
closed with #626
