### ISSUE TITLE
SIFT/SIFT2: Change default behaviour RE: FODs near GM

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#608]
With single-shell single-tissue CSD, the FODs in voxels that are partly WM and partly GM tend to be of a comparable size as those in deep WM. However, only the WM fraction of the voxel may contain streamlines. As a consequence, these FODs would typically be under-represented by streamlines. As a heuristic correction, I multiply the integrals of all FOD lobes in such voxels by (1.0 - GM). However with methods such as MSMT, this is no longer appropriate. I think that using this heuristic should now require explicit activation at the command line, and be disabled by default.

**Comment by thijsdhollander** [comment]
Yep, agreed.

**Comment by jdtournier** [comment]
Sounds sensible, go for it.
