### ISSUE TITLE
Merge tckglobal into tckgen

### ISSUE THREAD

**Issue by thijsdhollander** [MRtrix3/mrtrix3#609]
Similar to how `msdwi2fod` functionality is proposed to be merged into `dwi2fod` (as part of #604), it may make sense to merge `tckglobal` functionality into `tckgen`, so as to conform better to the overall compact naming and suffix logic in MRtrix.

**Comment by jdtournier** [comment]
Wow. That's quite a bit merge... Problem here being that the implementations are so different that there will probably be very little overlap in the command line options. We'd need to look at which options relate to both approaches and can hence be merged, but I suspect the approaches will need radically different sets of options, with the only overlap really being about the DW gradient handling... Assuming that's the case, I think that's taking it a step too far - and in many ways, the commands are actually doing radically different operations...

**Comment by thijsdhollander** [comment]
...which maybe highlights another potential wish list feature: for commands that pack multiple algorithms, this (several options being unique to a (subset of) algorithm(s)) may be bound to happen at some point, as new algorithms appear and are included.  I can see this happening for `dwi2fod` at some stage in the future as well.

In the scripts, this is handled quite nicely, with the possibility of selecting the algorithm first and then basically getting an algorithm-specific command/script/interface with its own help.

...so would this approach actually be good to have in the commands/apps as well?  It could even make the algorithm selection more explicit: just running the command (or its help option) could only provide the list of algorithms.  Running the command followed by the algorithm (which would then typically be the first mandatory parameter), yields just the help and options relevant to that algorithm.

**Comment by jdtournier** [comment]
:unamused:

How about we implement a full ncurses-based documentation browser? Then we could compete with GNU texinfo...? :stuck_out_tongue_winking_eye:

Kidding aside, I can obviously see the attraction here, but I find this cumbersome. Personally, I'd rather have the scripts pipe a full help page through to `less -X` like the main executables do. I find it much easier to browse a full _paginated_ help page than flicking between different pages - I can search the whole documentation easily (use '/' to search, BTW), and the option sections make it pretty clear what's what. Just my 2 cents...

**Comment by Lestropie** [comment]
I think the sheer volume of command-line options in `tckglobal` would make this clumsy. Even though having per-algorithm-based options like the scripts currently do is an interesting idea, you wouldn't necessarily want to hide the per-algorithm options from the user if no algorithm were selected, particularly given the paginated output.

Eventually I want the script help output to more closely mimic the binaries. But I think I need to deal with the output help page formatting / subparser inheritance to remove some remaining command-line order dependencies / interrogating subparsers when generating the `.rst` files before I get to the pagination.

**Comment by thijsdhollander** [comment]
Ok, so I agree it's not an urgent matter at this time... but I do still see things potentially getting trickier in the future, as more algorithms to do thematically similar kinds of tasks pop up, but some of them having a bunch of algorithm-specific options...  But we can always revisit the issue if/when that time comes around.  I'll close for now, and make a mental note. :wink:
