### ISSUE TITLE
Bugs in mrfilter gradient

### ISSUE THREAD

**Issue by thijsdhollander** [MRtrix3/mrtrix3#642]
Some weird things going on in the gradient filter:

- Not supplying the `-stdev` option, the command complains
- Supplying `-magnitude`, the command doesn't complain about not supplying `-stdev`
- ...but supplying `-magnitude` as well as `-stdev`, the `-stdev` value gets ignored

...and maybe other stuff.  But there's clearly something wrong with the ordering of certain actions in the filter: the magnitude option/code gets considered first, and quits before the smoothing (using stdev) can even take place...

**Comment by maxpietsch** [comment]
Just came across this bug and had a go at fixing it. 

Turns out there was also a [bug](https://github.com/MRtrix3/mrtrix3/commit/87663f5ac4432f56473d97e442414225e2472299#diff-c12b7db079cffcebb210a071b705b9feR115) in the smooth filter not setting the stdev values if a vector of length 3 was supplied.

**Comment by maxpietsch** [comment]
Added tests and fixed another issue use of `-scanner ` not being propagated to gradient filter if `-magnitude` is set. (fc0b6a5b4489a)

**Comment by thijsdhollander** [comment]
I may be completely wrong (it's been a quite while since I was looking into this stuff), but: does the latter actually matter?  As in: isn't the magnitude just the same irrespective of it being computed with respect to the scanner space versus the image space?

**Comment by maxpietsch** [comment]
If you have a location in image space `x,y` then the gradient of image `u` in this space wrt x is `du(x,y) / dx` of as central differences:

    du/dx:=(u(x+h, y)-u(x-h, y))/2h

If we want to have the gradient in a scaled space x'=a*x, then the gradient in this space is

    du/dx' = du/dx * dx/dx' = 1/a * du/dx

So if the voxel spacing is not 1mm isotropic then the magnitude of the  gradients wrt image and scanner space should differ.

**Comment by maxpietsch** [comment]
Besides, the main issue was that the `-scanner ` setting is off by default for `mrfilter` called without the `-magnitude` option but was on for `mrfilter -magnitude` as gradient.h is initialised with `wrt_scanner (true)`.

**Comment by thijsdhollander** [comment]
Ah, yep, the units are indeed different (but the contrast shouldn't be).  Agreed it makes sense then to just make things work consistently. :+1:
