### ISSUE TITLE
Get MRtrix3 working with Eigen 3.3 beta

### ISSUE THREAD

**Issue by jdtournier** [MRtrix3/mrtrix3#648]
I've just pushed a [new branch port_to_eigen_3.3](https://github.com/MRtrix3/mrtrix3/tree/port_to_eigen_3.3) with changes to make things work with the latest Eigen 3.3 beta. So far things compile and mostly run (initially, nothing worked at all, as [reported in this community post](http://community.mrtrix.org/t/mrview-segmentationfault-core-dump-ubuntu-16-04/185/22?u=jdtournier)), with the only exception being a few of the tracking commands. It's quite difficult to figure where the problems are, but the main issue is that this new version of Eigen is clearly much more sensitive to alignment issues, so we need to help the compiler out a bit - it's all [explained here](https://eigen.tuxfamily.org/dox-devel/group__DenseMatrixManipulation__Alignement.html). The main issue so far is ensuring alignment for `Eigen::Transform` (aka `transform_type`), it seems. 

I'll try to figure out what's going on with the remaining commands when I have the chance. By the way, `tckconvert` seems to fail a test for the VTK output, but it's purely about machine precision. The test runs a straight diff, with no tolerance for slight deviations. So it's not actually failing, we would need to figure out a way to relax that test somehow...

**Comment by Lestropie** [comment]
Closed by #712. Devs are encouraged to install and use the Eigen beta to assist in detecting any additional issues.
