### ISSUE TITLE
Documentation: single page per command/script

### ISSUE THREAD

**Issue by jdtournier** [MRtrix3/mrtrix3#670]
Right now, all the command help pages come out [concatenated in one giant page](http://mrtrix.readthedocs.io/en/latest/reference/commands_list.html). I'd personally prefer it if each command had its own page, I think it would be cleaner and easier to navigate. Is there any way we can fix this...?

As an example of the kind of awkwardness I'm talking about: on a mobile phone, the button to show the sidebar is at the top of the page. So if I'm looking  at say `tckmap`, and I now want to find the doc for `dwiextract`, I need to either scroll through that enormous page to find it, or scroll all the way to the top of the page to hit the sidebar button so I can then find a link to `dwiextract`. If each command was a single page, the distance to the top of the page wouldn't be such a problem, it would be much easier to navigate through to another command's help page via the sidebar.

_[EDIT] I notice you can reproduce the above on the desktop by simply making the browser window sufficiently narrow..._

**Comment by Lestropie** [comment]
:+1:

**Comment by jdtournier** [comment]
Nice! Good work.

**Comment by jdtournier** [comment]
@rtabbara: any chance we could do the same for the scripts...? :grin:

**Comment by Lestropie** [comment]
Already coming: 600bbf5.
