### ISSUE TITLE
dwi2response tournier algo goes beyond supplied mask

### ISSUE THREAD

**Issue by thijsdhollander** [MRtrix3/mrtrix3#673]
The `tournier` algorithm is able to use / select voxels beyond the initial supplied mask (or, in principle, beyond the automatically computed brain mask if no `-mask` is supplied; but this is very unlikely in practice).  I'm about 99.9% sure it's because of the dilation step (of the greater number of top single-fibre voxels, 3000 by default).

This could simply be fixed by multiplying the mask output from that dilation step with the original supplied (or computed) `mask.mif`; but I'm just checking with everyone here if this would indeed be the intended behaviour (as opposed to what can happen now).

**Comment by jdtournier** [comment]
Good point. Happy to trim back down to the supplied mask, it makes sense and is simple enough...

**Comment by thijsdhollander** [comment]
Ok, it's been fixed in 7b163db5059bc3c03031eb1c8b151e55cc03ca0f ; works as I would expect it to!
