### ISSUE TITLE
OSX homebrew formula

### ISSUE THREAD

**Issue by maxpietsch** [MRtrix3/mrtrix3#680]
It would be neat to host a homebrew formula to make installing mrtrix on OSX easier. I have put together a formula that should reduce installing and setting up mrtrix 0.3.15 to:

```
# edited tap from maxpietsch to MRtrix3
brew tap MRtrix3/mrtrix3
brew install mrtrix3
```

For now, the [repo](https://github.com/maxpietsch/homebrew-mrtrix3) lives on my github account but we could just create one here. The repo name has to start with "homebrew-" so I would suggest MRtrix3./homebrew-mrtrix3. We could also think of adding it to one of the existing brew taps (for instance to http://brew.sh/homebrew-science/).

This is a very early mostly untested version. I thought I put it up here to get some feedback. Scripts and binaries are linked to /usr/local/bin. I haven't figured out what to do with the lib folder so I use -noshared. 

Also, an item on the wishlist is to find a way to update mrtrix to the latest version, not just the last tag.
## Info and options

```
brew info mrtrix3
mrtrix3: stable 0.3.15
MRtrix provides a set of tools to perform diffusion-weighted MRI white matter tractography in the presence of crossing fibres,
    using Constrained Spherical Deconvolution (Tournier et al.. 2004; Tournier et al. 2007), and a probabilisitic streamlines algorithm
    (Tournier et al., 2012). These applications have been written from scratch in C++, using the functionality provided by Eigen, and Qt.
    The software is currently capable of handling DICOM, NIfTI and AnalyseAVW image formats, amongst others. The source code is distributed
    under the Mozilla Public License.

    For more information on how to install and use MRtrix go to http://mrtrix.readthedocs.io

mrtrix.org
/usr/local/Cellar/mrtrix3/0.3.15 (68B)
  Built from source
From: /Users/mp/homebrew-mrtrix3/mrtrix3.rb
==> Dependencies
Build: eigen ✔, pkg-config ✔
==> Options
--build_single_thread
    This is useful if your computer has many cores but not enough RAM to build MRtrix using multiple threads.
--without-qt5
    Build without qt5 support
```
## Installation

```
brew install mrtrix3
==> Installing mrtrix3
==> Downloading https://github.com/MRtrix3/mrtrix3/archive/0.3.15.tar.gz
Already downloaded: /Users/mp/Library/Caches/Homebrew/mrtrix3-0.3.15.tar.gz

MRtrix build type requested: release

Detecting OS: darwin
OS X deployment target: 10.11
Checking for C++11 compliant compiler [clang++]: 4.2.1 - tested ok
Detecting pointer size: 64 bit
Detecting byte order: little-endian
Checking for variable-length array support: yes
Checking for non-POD variable-length array support: no
Checking for zlib compression library: 1.2.5
Checking for Eigen 3 library: 3.2.8
Checking shared library generation: yes
Checking for Qt moc: moc (version 5.5.1)
Checking for Qt qmake: qmake (version 5.5.1)
Checking for Qt rcc: rcc (version 5.5.1)
Checking for Qt: 5.6.1
writing configuration to file './release/config': ok

(  1/442) [CC] release/cmd/labelconvert.o
(  2/442) [CC] release/cmd/tckgen.o
(  3/442) [CC] release/cmd/dirmerge.o
(  4/442) [CC] release/lib/formats/pipe.o
...
(436/442) [LB] release/bin/dirmerge
(437/442) [LB] release/bin/dirsplit
(438/442) [LB] release/bin/dirstat
(439/442) [LB] release/bin/dirflip
(440/442) [CC] release/cmd/dirorder.o
(441/442) [LB] release/bin/dirorder
(442/442) [LB] release/bin/sh2amp
🍺  /usr/local/Cellar/mrtrix3/0.3.15: 143 files, 38.5M, built in 25 minutes 26 seconds
```
## install local formula and debug

```
brew reinstall homebrew-mrtrix3/mrtrix3.rb --verbose --debug
```

**Comment by draffelt** [comment]
Sounds like a good idea to me. Is home brew equivalent to the AUR for Arch? Maybe @chunhungyeh and @rtabbara can give it a test. I'll also get Lea my PhD student to give it a try. 

We really should update the general description of MRtrix too (including on the main docs page).

**Comment by chunhungyeh** [comment]
All good on my end (definitely need to update the description though).

**Comment by maxpietsch** [comment]
@draffelt I don't know AUR. Homebrew is a git and ruby based package manager. Short description is here: http://brew.sh/

The idea is to provide a ruby script that contains the recipe on how to install dependencies, from the homebrew repo or external, compile the code, store it in the homebrew cellar and link it to /usr/local/bin. For us, the ruby scripts allows tp perform any kind of python, shell scripts or system calls. For the end-user the main advantage is that it is easy to install and update the package. No PATH variables need to be set and no external packages need to be manually installed.

**Comment by bjeurissen** [comment]
Great idea!

Talking about AUR: I have a PKGBUILD script lying around which should accomplish the same thing for arch linux. For mrtrix-0.2, I had it even included in the AUR, but at some point it was removed (probably because of the lack of votes or because I stopped maintaining it). If anyone is interested, I can upload the new PKGBUILD to the AUR.

It should also not be too hard to create a portfile for macports.

**Comment by jdtournier** [comment]
@maxpietsch: very cool! I just created another repo as suggested: ]MRtrix3/homebrew-mrtrix3](https://github.com/MRtrix3/homebrew-mrtrix3). The whole team has read/write access. 

What's the issue with the `lib` folder? All you'd need is to make sure the `libmrtrix-0.3.15.dylib` file is in the `../lib` folder relative to the _actual_ executables (not the links). Does this not work by leaving them in situ and symlinking to the executables...? Works fine on Linux, not sure about MacOSX, I'd assume it would be just fine. But then I'm struggling a bit to follow exactly what this script is actually doing... 

Also, I'm not sure I like the `--without-qt5` option - that really only makes sense if you know what Qt5 is about in the first place. What's wrong with `--without-gui`, or better yet, `--nogui` to mirror what `build` expects...?

@bjeurissen: great if you can sort out AUR and macports installs. Not too fussed about the AUR one, it's a very small proportion of the user base, and Arch users probably don't need a lot of help anyway...


> definitely need to update the description though

Open to suggestions! This is long overdue, feel free to send me suggestions, I'm just not feeling very inspired at the moment...

**Comment by maxpietsch** [comment]
`--without-qt5` is generated automatically because I set the dependency as not strict. This is because I would like to allow for people to use an existing qt5 installation. Happy to add another option `--nogui` but I haven't figured out how to change dependencies based on options (if --nogui is set, it should not check the qt5 dependency). As I have written the qt dependency as a separate class, I guess that this is somehow possible but my Ruby is extremely elementary.... Also brew naming conventions urge to use options starting with "with" or "without" for consistency reasons.

I don't know what is going on with the lib folder. I copied it to the cellar in the same directory as the bin folder. Also tried to copy all binaries into release/bin. Calling mrview directly (no links) from the cellar did not work. I'll have to see why that is. Problem is that each attempt takes 15 minutes compile time...

**Comment by jdtournier** [comment]
> --without-qt5 is generated automatically because I set the dependency as not strict

No problem. Makes sense, leave it as-is.

> I don't know what is going on with the lib folder.

Not sure what it's actually doing, but the linker flags I set up for the MacOSX install are supposed to allow for relocation - things should work fine provided the library is located in `../lib` relative to the executables. So the fact that it's not working when you copy over to the cellar (whatever that is) is worrying. Just to check: you are copying over the `release/lib` folder, not the `lib/` folder, right...?

Any chance you could try copying over the `release/bin` folder from your existing install over to some random folder, then copying the `release/lib` folder so that `lib/` is alongside `bin/`, and try invoking some commands directly from that folder? If that works, see if creating a symlink to that command in some totally different location and invoking that works. If it doesn't, this needs to be fixed upfront...

> Problem is that each attempt takes 15 minutes compile time...

You think that's a long time?!? I've been trying to compile MRtrix3 on my piddly Win10 netbook - it's been chewing on it for the last 3 hours, and there's still a long way to go...

**Comment by jdtournier** [comment]
Just to follow up on the linker issue: on MacOSX, the command to inspect the linker path (technically the _rpath_) for a given executable is `otool -l` (see [this post for details](http://stackoverflow.com/questions/12521802/print-rpath-of-executable-on-osx)). Might be an idea to run that on some random executable, make sure everything is as expected...

**Comment by dchristiaens** [comment]
@maxpietsch This is awesome, great work! I'll give it a spin in the next few days. This is exactly what we needed for the macOS install, but I was sort of holding off until we hit official "release". Hence my main question is how we'll keep the formula updated once we hit release; of course for now it doesn't matter too much.

**Comment by maxpietsch** [comment]
> Not sure what it's actually doing, but the linker flags I set up for the MacOSX install are supposed to allow for relocation - things should work fine provided the library is located in ../lib relative to the executables. So the fact that it's not working when you copy over to the cellar (whatever that is) is worrying. Just to check: you are copying over the release/lib folder, not the lib/ folder, right...?

@jdtournier Uhm, yes. I copied the wrong lib folder. When I use the correct one I get this output

    Changing dylib ID of /usr/local/Cellar/mrtrix3/0.3.15/lib/libmrtrix.dylib
     from @rpath/libmrtrix.dylib
     to /usr/local/opt/mrtrix3/lib/libmrtrix.dylib

`/usr/local/opt/mrtrix3` is a symlink to  `/usr/local/Cellar/mrtrix3/0.3.15` and all I did was copy the content of release/lib to `/usr/local/Cellar/mrtrix3/0.3.15/lib/`. Seems to work.

> You think that's a long time?!? I've been trying to compile MRtrix3 on my piddly Win10 netbook - it's been chewing on it for the last 3 hours, and there's still a long way to go...

Maybe it's time for an upgrade? 
![image](https://cloud.githubusercontent.com/assets/10046944/16285225/52096c92-38d5-11e6-9120-fa32329d7725.png)

@dchristiaens 

> how we'll keep the formula updated once we hit release

Do we want users to update mrtrix everytime they update homebrew or only when we release a new tagged version? Homebrew allows to freeze a package via `brew pin mrtrix3` which is useful if one wants to process a trial with consistent tools.

The formula lives here on github so can easily be updated by us. I used the latest tagged version of mrtrix in the formula. That means when we have a new tag, we would need to update our homebrew formula with the correct tag url and checksum. This allows users to update mrtrix to the latest tagged version with `brew update; brew upgrade`. This has the advantage that users can get specific versions of mtrix (for whatever reason, [link](http://stackoverflow.com/questions/3987683/homebrew-install-specific-version-of-formula/4158763#4158763)). 

If we want to deliver the latest version then that works too (I've added `head 'https://github.com/MRtrix3/mrtrix3.git'` to the formula). This allows to clone mrtrix and install the master branch via `brew install --HEAD mrtrix3`. In the past there was no good way to update packages installed with the head keyword [link](https://github.com/Homebrew/legacy-homebrew/issues/13197) and I am not sure whether that has been resolved:

    brew upgrade --HEAD mrtrix3
    Error: mrtrix3 HEAD already installed
    Error: Kernel.exit

I don't get any error with `brew upgrade --HEAD`. I guess I'll wait for a commit to master and see whether mrtrix gets updated.

I've moved the script to https://github.com/MRtrix3/homebrew-mrtrix3/. The default is to install the latest tagged version.

Phew, I already learned more about homebrew than I hoped I would...

**Comment by lvinokur** [comment]
Oh wow, is this my first comment on Github? Nooice. 
Anyway, I've tried installing MrTrix (on a fairly freshly formatted Mac) as per the instructions [here](https://github.com/MRtrix3/homebrew-mrtrix3), 

```
leavinokur$ brew install --HEAD mrtrix3
==> Installing mrtrix3 from mrtrix3/mrtrix3
mrtrix3: Homebrew was unable to find an installation of Qt 5. You can install it manually or with
brew install qt5
Error: An unsatisfied requirement failed this build
```

Once I installed eigen and qt5 manually as per the instructions [here](http://mrtrix.readthedocs.io/en/latest/installation/mac_install.html) though it all went well :)

hope it's all helpful?

**Comment by maxpietsch** [comment]
Hello @lvinokur, glad it worked. As the error message says, it should have sufficed to type `brew install qt5` as this homebrew package installs eigen if it is not already installed.

This formula is still very new and mostly untested. Let us know if you have any problems!

**Comment by maxpietsch** [comment]
@lvinokur, I just fixed an issue with the scripts so please reinstall mrtrix3 with `brew reinstall --HEAD mrtrix3`. Unless you want to help debug the homebrew installation, I would recommend to install mrtrix3 as described in readthedocs.

**Comment by maxpietsch** [comment]
I would suggest changing the homebrew formula to default to installing the latest version of mrtrix and offer a second formula `mrtrix_stable` for the last tagged version. 


The main advantage is that users get the latest version default and users only need to either `brew update; brew upgrade` or `brew update; brew upgrade mrtrix3` to upgrade mrtrix. This requires a manual change of the `version` field in the formula to trigger the upgrade. I think this could be easily automated. 

 With the current solution (`brew install --HEAD mrtrix3`) they would need to manually run `brew reinstall --HEAD mrtrix3` to get the latest version of mrtrix.

**Comment by maxpietsch** [comment]
Just to keep this thread up to date: Turns out having two formulas installing the same software is not a good idea as binaries are linked to the same folder. Merged `mrtrix3_stable` into `mrtrix3` one formula that has an option `--stable` to install the latest stable version.
