### ISSUE TITLE
Floating-point type changes

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#684]
Started some work in branch `float_type_changes`. I've done what I needed to do to get my own code compiling again since `updated_syntax`, but there's more I'd like to change.

Questions:
1. Stats code is using single precision throughout. Do we want it using `default_type` instead? (Not for the CFE connectivities though)
2. If yes: Do we want to leave the floating-point type templates in place (so devs could potentially use those classes in single precision if they really wanted to)? If they were fixed to `default_type`, a lot of code could move out of headers and into cpp's, reducing the load on the compiler.
3. I've changed the stats code to use `Eigen::Array` rather than `std::vector`, but have templated in such a way that code _should_ work with either (as long as it's used consistently). But like 2, if it were fixed to the former, then a lot of code could move into .cpps; it would also mean that Eigen reductions could be used.
4. Previously the empirical statistic vector was fixed to `std:vector<double>`, even though everything else was various uses of floats; I'm guessing this was deliberate due to summing floating-point numbers in its calculation. This is now `typedef`'d as `Stats::PermTest::empirical_vector_type`, so will remain as a double even if single precision is used everywhere else. But this could be revised depending on points 2 and 3.

Still to do:
1. Define a base Enhancer class, that provides the virtual function interface necessary for performing statistical enhancement. This would really help my code that provides a selection of enhancement algorithms, since currently the enhancement class is a template parameter and so I have to branch based on enhancement algorithm every time I call a library function.
2. I'm not a big fan of the way the permutation stack is const ref'd and accessed directly by the stats processing classes. I'd rather have the permutation stack send each `std::vector<size_t>` permutation down the queue: more modular, which might just come in handy if fancier permutation handling is implemented (as was requested recently).
3. Not stats-related, but still fits in the title: `DWI::Directions::Set` is currently also hard-coded to float. Any objections to me hard-coding it to `default_type`? It would mean running a `.cast<default_type>()` on anything calculated from a `DWI::Tractography::Streamline<>`; but currently I'm doing a whole lot of the opposite.

**Comment by draffelt** [comment]
> Stats code is using single precision throughout. Do we want it using default_type instead? (Not for the CFE connectivities though)

I'm happy to change all (aside from connectivities) to default_type. 

> If yes: Do we want to leave the floating-point type templates in place (so devs could potentially use those classes in single precision if they really wanted to)?

No I can't see any reason why I'd need to use single precision. 

> I've changed the stats code to use Eigen::Array
Happy for it to be fixed

> Previously the empirical statistic vector was fixed to std:vector<double>, even though everything else was various uses of floats; I'm guessing this was deliberate due to summing floating-point numbers in its calculation. This is now typedef'd as Stats::PermTest::empirical_vector_type, so will remain as a double even if single precision is used everywhere else. But this could be revised depending on points 2 and 3.

Your guess was correct. Happy for it to be a default_type too. 

> Define a base Enhancer class, that provides the virtual function interface necessary for performing statistical enhancement. This would really help my code that provides a selection of enhancement algorithms, since currently the enhancement class is a template parameter and so I have to branch based on enhancement algorithm every time I call a library function.

Let's have a chat about this. 

> I'm not a big fan of the way the permutation stack is const ref'd and accessed directly by the stats processing classes. I'd rather have the permutation stack send each std::vector<size_t> permutation down the queue: more modular, which might just come in handy if fancier permutation handling is implemented (as was requested recently).

Let's chat about this too. I was also thinking of changing this recently.

**Comment by Lestropie** [comment]
@draffelt: Just pushed some changes that you'll most likely want to look over at some stage. There were a lot of functions in .h files / inlined that really didn't need to be, and the computational expense of those functions far outweighed any possible benefit of inlining, so hopefully having the bulk of code in .cpp files helps the compiler out a bit. But best run a speed / RAM test just to be sure. Will discuss base Enhancer class and possible permutation stack changes with you at some point.

**Comment by Lestropie** [comment]
This has all been included in #785.
