### ISSUE TITLE
transformcompose: A command to compose any number of linear and non-linear transforms

### ISSUE THREAD

**Issue by draffelt** [MRtrix3/mrtrix3#691]

**Comment by bjeurissen** [comment]
Any progress on this? I would like to compose inter-subject (between timepoints using mrregister) with intra-subject transformations (obtained with population_template on the average midpoint inter-subject registrations).

**Comment by draffelt** [comment]
It's literally up the top of my list. Will tackle it today

**Comment by draffelt** [comment]
@bjeurissen check out [transformcompose](http://mrtrix.readthedocs.io/en/tag_0.3.16/reference/commands/transformcompose.html) in the tag_0.3.16 branch.  

Let me know if you have any issues, or if the help page could be improved. Will close this issue off when I add tests tomorrow.
