### ISSUE TITLE
branches in testing data

### ISSUE THREAD

**Issue by maxpietsch** [MRtrix3/mrtrix3#693]
As discussed [here](https://github.com/MRtrix3/mrtrix3/issues/602#issuecomment-225533742), we could make changes to the testing data to avoid breaking tests when working on a separate branch. Opening this issue to move this discussion over from #602.

**Comment by jdtournier** [comment]
Sorry, I'm not sure what action you're suggesting might be needed here...? The only way to avoid breaking the test data is to use branches on the `test_data` repo - there's nothing preventing us from doing this right now, we just need to be mindful of this in those rare cases where we modify existing data. Thankfully this is a rare occurrence, but really the only thing we can do is make sure we're all aware of the issue, and figure out the git-fu required to do this safely...

**Comment by maxpietsch** [comment]
I guess there is no need for changes as the testing readme has been [updated](https://github.com/MRtrix3/mrtrix3/commit/d044049d0019857712e213e85788d4a5e91c3afe). Any objections against closing this?

**Comment by jdtournier** [comment]
Well, it might be an idea to document in the `README`  the best way to handle _modifications_ to _existing_ test data - which is what caused problems here...?

**Comment by jdtournier** [comment]
closed via #846
