### ISSUE TITLE
helper functions to replace set_ndim() and set_DW_scheme

### ISSUE THREAD

**Issue by draffelt** [MRtrix3/mrtrix3#697]
As discussed previously, it would be nice to make these functions similar to the rest of the API. So we could change dimensions using:  `header.ndim() = 4;` 

Would be good to get these finalised before the SoftwareX paper.

**Comment by jdtournier** [comment]
OK, added `Header::ndim()` handling. Not so sure about `Header::set_DW_scheme()` though. All the handling for getting the DW scheme has been moved over to [`src/dwi/gradient.h`](https://github.com/MRtrix3/mrtrix3/blob/master/src/dwi/gradient.h) ([`DWI::get_DW_scheme()`](https://github.com/MRtrix3/mrtrix3/blob/master/src/dwi/gradient.h#L143) and [`DWI::get_valid_DW_scheme()`](https://github.com/MRtrix3/mrtrix3/blob/master/src/dwi/gradient.h#L173)). I reckon it would be more consistent to actually move `Header::set_DW_scheme()` over to that file too, and call it `DWI::set_DW_scheme (Header&, const MatrixType& G)` - what do you think?

**Comment by draffelt** [comment]
Sounds good to me

**Comment by Lestropie** [comment]
Closed by #698.
