### ISSUE TITLE
registration: move from lib to src folder

### ISSUE THREAD

**Issue by maxpietsch** [MRtrix3/mrtrix3#704]
The registration code is since 6200c50f2583c72eca002c59b8e5ad8f25eb87d7 in the `lib` folder. @draffelt Why did you move it there? I think `registration` qualifies as a separate module and should not necessarily be part of the MRtrix3 core. 

Currently, when I build `mrinfo` after a `./build clean` the following registration related object files get also compiled (doubling compile time) because they are part of the lib folder:

    lib/math/average_space.o
    lib/registration/transform/initialiser.o
    lib/registration/transform/initialiser_helpers.o
    lib/registration/linear.o
    lib/registration/transform/rigid.o
    lib/registration/transform/affine.o
    lib/registration/nonlinear.o

**Comment by draffelt** [comment]
Because Donald was talking about ditching src altogether. Happy for it to
move back of that's not the case any more.

**Comment by jdtournier** [comment]
> Because Donald was talking about ditching src altogether

Was I?!? I must have been drunk... No plans to ditch `src` any time soon...

**Comment by maxpietsch** [comment]
:+1: I'll move it.

**Comment by draffelt** [comment]
@jdtournier. Yes, if I recall correctly it was to accommodate easy installations of MRtrix into linux /usr/lib or /usr/include

**Comment by jdtournier** [comment]
Ah, OK. Yes, if we want to allow MRtrix3 to be installed as a regular library, then only the stuff in `lib` would be available - all the stuff in `src` remains as regular objects that need to be injected into the binaries. I guess in due course, if we want to go down this road, we'll probably need to split things up into domain-specific libraries: the core one (as it is currently), then one for registration, one for DWI, etc. But I don't anticipate we'll be in a position to do this for quite some time. The current approach is probably easier for developers anyway, I'd argue to keep it that way for the foreseeable future. Maybe we'll revisit when MRtrix becomes a household name...
