### ISSUE TITLE
mrview Tractography tool: Display geometry option

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#708]
Currently the tractography tool is 'locked' to displaying track data as pseudo-streamtubes. Similar to other `mrview` tools, it should be possible to re-compile the shaders and branch in the main `draw()` call to display different geometries, selectable using a combobox. E.g.:
- Pseudo-streamtubes (i.e. current)
- Lines (i.e. pre-geometry-shader), for when you absolutely must be able to see all tracks in a large dataset, and don't care about line thickness
- Points (I get asked all the time about the ACT paper figures displaying dots for the streamline endpoints, currently the only solution is MRtrix 0.2's `mrview` with depth blend enabled; would also be handy for assessing tracking algorithms / track resampling)

Supersedes #14.

**Comment by draffelt** [comment]
Points could be handy. I needed this recently for debugging something

**Comment by Lestropie** [comment]
Closed by #1073.
