### ISSUE TITLE
scrolling in an empty mrview segfaults

### ISSUE THREAD

**Issue by samuelstjean** [MRtrix3/mrtrix3#709]
Nothing major, if you happen to open an empty mrview, say from the command line, without loading an image volume, everything seems fine. Scroll, and it will segfault without any particular error message other than segfault, core dumped (freshly tested on latest master). Could be related maybe to unitialized stuff like in #323 

Opening mrview, then loading an image and scrolling works perfectly fine, so it is really only when there is nothing loaded that it crashes, but then again not a dealbreaker bug.

**Comment by jdtournier** [comment]
Thanks for the report, I'll look into it - it's probably a very simple fix...

**Comment by jdtournier** [comment]
I can't reproduce this on my system... Arch Linux, Qt 5.7.0, g++ 6.1.1. Are you sure everything is up to date, and you're on the latest `master`...?

**Comment by jdtournier** [comment]
Ah, sorry, I thought you were talking about scrolling with the mouse. Indeed, I also get a crash using the up/down arrow keys on an empty viewer. I'll fix that up now.

**Comment by jdtournier** [comment]
See fix in #710.
