### ISSUE TITLE
mrtransform: -replace option & matrix import

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#718]
1. Since the move to Eigen, `mrinfo -transform` produces a 3x4 matrix text file. But `mrtransform -linear` expects a 4x4. We should probably be able to import the transformations we're exporting.

2. I don't like how replacing the header transformation is done using `mrtransform -linear <text file> -replace`. I'd rather the `-replace` option be used independently of `-linear`. It would also then be possible for this option to take as its argument _either_ a matrix text file, _or_ a template image from which to take the header transform.

For reference, error is arising [here](https://github.com/MRtrix3/mrtrix3/blob/master/scripts/dwipreproc#L380).

Want people's opinions on this, since `mrtransform` is usually pretty contentious.

**Comment by draffelt** [comment]
Happy with those modifications.

**Comment by Lestropie** [comment]
OK, thinking 1 is probably `mrinfo` using `std::cout <<` rather than `save_transform()`. Still, allowing `load_transform()` to import a 3x4 might not be a bad thing.

**Comment by Lestropie** [comment]
@draffelt `transform_file_handling` branch will need to be checked carefully to make sure I haven't borked a particular code path.

**Comment by maxpietsch** [comment]
@Lestropie 
> Allowing load_transform() to import a 3x4 might not be a bad thing.

I did not notice this thread. I changed load_transform() to accept 3x4 matrices in 7be6580d2555172c6b3.
