### ISSUE TITLE
New command: data vector stats

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#724]
For users interested in global connectome network metrics, it should be possible to:
1. Run `connectome2metric` (#714) on each subject, producing a scalar value per subject.
2. Concatenate these values into a data vector.
3. Run a new _MRtrix3_ command (naming suggestions welcome) that will perform permutation testing on those values.

**Comment by draffelt** [comment]
Close this off? Or do you need to run tests?

**Comment by Lestropie** [comment]
We should probably test it - both for itself and for testing the GLM more generally.

There's a whole lot of issues that will get triggered as closed once the commits are merged to master, since the reference in the commit message doesn't trigger the issue to close until it gets merged to master.
