### ISSUE TITLE
mrthreshold optimal threshold with -mask option bug

### ISSUE THREAD

**Issue by thijsdhollander** [MRtrix3/mrtrix3#738]
When running `mrthreshold` with the `-mask` option, the idea is that the algorithm only uses the data inside the mask to compute the optimal threshold.  That works ok (so no need changing), but there's a bug in initialising the golden section search.  The latter would need to be initialised with the minimum and maximum values, but for this step it accidentally uses the whole image (rather than just the data in the provided `-mask`).  That becomes problematic when the minimum or the maximum of the whole image is (much) lower or higher than the actual minimum or maximum of the data in the mask's region.

What basically needs fixing is the `min_max` function, that would need to offer a mask option.  @draffelt and I took a brief look at it, somewhere at the end of a long day several weeks ago; but we stuffed up somewhere.  What we had done is https://github.com/MRtrix3/mrtrix3/commit/c2fabb087c5269cff5f6b59e57221797871762a9 in the `optimal_threshold_tweaks` branch back then, but we must've made a mistake somewhere, as it introduces random other bugs here and there.

I don't have the time to look into it, sadly... so just putting it up here now that I just remembered it again...

**Comment by jdtournier** [comment]
Discussed in #1481 - closing.
