### ISSUE TITLE
'stats': Command naming

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#739]
```
$ ls -la release/bin/ | grep stats
fixelstats
fixelcfestats
mrclusterstats
mrstats
tckstats
```
Soon to be joined by (proposed in #723 at least):
```
connectomestats
vectorstats
scalarstats (maybe)
```

Some of these are calculating _summary statistics_ from data; others are performing _statistical inference_. Should this be reflected more directly in the command names (e.g. `fixelinfer` / `fixelinference` / `fixelglm`)? '`cfe`' and '`cluster`' relate to statistical enhancement, but I'm not sure if it's precise enough: e.g. `mrclusterstats` could produce statistics (mean, max, etc.) on cluster sizes.

**Comment by draffelt** [comment]
I appreciate it's getting crowded. However, I guess I'd prefer not to rename `fixelcfestats` given we mention this is what it's called in the CFE paper. 

I personally associate the word stats with statistical inference, but then I'm clearly biased.

I guess `mrstats` could just as well be `mrsummary`.

**Comment by thijsdhollander** [comment]
I'm not sure the average user even thinks about this being an issue, to be honest... The clarity of the names is mostly there to help users *find* the command(s) they're looking for.  Both the phrases "summary statistics" and "statistical inference" contain "stat(s)".
If, for instance, I needed to do something with fixels, I'd type "fixel", hit tab, and get every single command that does things with fixels (as an input).  I'd immediately be drawn towards `fixelstats` and `fixelcfestats`.  It's pretty clear from both of those names what they probably cover.  If I still weren't sure, I'd type one of them, hit enter, and see the description to confirm.  Once I've learned then what that command does, I will remember it forever (or at least a long foreseeable future :-)).

What's in a name, I guess.  I reckon good documentation is more important than making the names super-specific, yet unwieldy long or cryptic.

**Comment by Lestropie** [comment]
I think what I'm stuck on is that `fixelcfestats` and `mrclusterstats` use the statistical enhancement method to disambiguate from 'summary' statistics (i.e. `fixelstats` and `mrstats`), but I don't want to do `connectomenbstfcestats`, partly because it's ugly as hell, partly because long-term it'll have different enhancement mechanisms. But connectome 'summary' statistics don't really exist, there'll be `connectome2metric` instead. So I guess we'll just leave things be, even if `connectomestats` (& others) are slightly inconsistent with what's there already.
