### ISSUE TITLE
Set config file options in any command

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#744]
Just had this idea while playing with NIfTI-2 support.

We could have an option as part of the standard option set: '`-config key value`', that would allow you to override any configuration file parameter just for that one command execution. This would expand the capabilities of customising individual calls without having to manually edit the config file. It wouldn't even extend the list of standard options, since `-failonwarn` would be removed as a consequence (though admittedly that probably should have been only a config file option in the first place).

**Comment by jdtournier** [comment]
:+1: Sounds like a good idea.
