### ISSUE TITLE
scripts: don't cleanup on error

### ISSUE THREAD

**Issue by maxpietsch** [MRtrix3/mrtrix3#752]
I find myself often having to rerun scripts with the `-nocleanup` option after an error occurred to figure out what exactly went wrong. How do people feel about defaulting to not deleting the temporary directory after an error? 

The downside of this is that it would fill up `tempdir` for people developing or debugging scripts but I think users having to rerun possibly very long running scripts (dwi_preproc, population_template) outweighs this.

**Comment by maxpietsch** [comment]
population_template with the above changes : 

    $./population_template template/anat out.mif
    population_template: Generating a population-average template from 20 input images
    population_template: [WARNING] no masks input. Use input masks to reduce computation time and improve robustness
    population_template: Generated temporary directory: /tmp/population_template-tmp-HZTQ4A/
    population_template: Changing to temporary directory (/tmp/population_template-tmp-HZTQ4A/)
    population_template: [ERROR] ahhh
    population_template: Changing back to original directory (/home/mp14/mrtrix3/scripts)
    population_template: Contents of temporary directory kept, location: /tmp/population_template-tmp-HZTQ4A/

    

    $./population_template template/anat out.mif -cleanuponerror
    population_template: Generating a population-average template from 20 input images
    population_template: [WARNING] no masks input. Use input masks to reduce computation time and improve robustness
    population_template: Generated temporary directory: /tmp/population_template-tmp-J5U505/
    population_template: Changing to temporary directory (/tmp/population_template-tmp-J5U505/)
    population_template: [ERROR] ahhh
    population_template: Changing back to original directory (/home/mp14/mrtrix3/scripts)
    population_template: Deleting temporary directory /tmp/population_template-tmp-J5U505/

**Comment by Lestropie** [comment]
Generally makes sense to me. Anyone developing scripts should be cluey enough to run a manual cleanup every now and then.

- Not sure about the `-cleanuponerror` option though: is there really a use case for knowing _a priori_ that you explicitly _don't_ want to keep the script directory contents if it fails to complete? It might just be help page bloat otherwise.

- Could change the terminal message when keeping the temporary directory, depending on whether the user requested to keep it, or whether the script failed to complete successfully. That would give additional feedback over and above the preceding '`[ERROR]`' message that something went awry.

**Comment by draffelt** [comment]
I think this is a good idea. I've had a number of cases were RAs have come across a script error later in the processing, however I can't help them debug it until they run it again.

**Comment by maxpietsch** [comment]
Ok, I removed the option `-cleanuponerror` in 9fa9ff9a38d4cb and made the exit a bit more verbose for failed commands 4132212ce:

`runCommand('mrregister -bogus')` leads to the script exiting with

    testscript.py: [ERROR] Command failed: mrregister -bogus
    testscript.py: Output of failed command:
    mrregister: [ERROR] unknown option "-bogus"
    testscript.py: Changing back to original directory (~/scripts/)
    testscript.py: Script failed while executing the command: mrregister -bogus
    testscript.py: in the directory: /tmp/testscript.py-tmp-YP1Z2W
    testscript.py: For debugging, inspect contents of temporary directory: /tmp/testscript.py-tmp-YP1Z2W/

**Comment by Lestropie** [comment]
I don't think there's any need to include the 'in the directory' line: That will almost always be the same as the temporary directory so it looks kind of redundant in the command-line output. And even if it were different, that difference is unlikely to give much leading information regarding what went wrong. Personally I'd lose that line.

**Comment by maxpietsch** [comment]
Printing the working directory line becomes useful when you start nesting scripts. For instance, I have a rather long script that operates partly in a temporary directory, calls other scripts such as `dwipreproc` and `dwiintensitynorm`, which in turn calls `population_template`. There I find it useful to know in which directory the error occurred but this is a rather edge case and would not be necessary for most scripts.

**Comment by Lestropie** [comment]
I figured that was the case; but then shouldn't you be able to tell what happened from the terminal log? I.e. the 'slave' script errors out, printing the location of _its_ temporary directory, changes back to the working directory from which it was called (which is the temporary directory of the 'master' script) _then_ the 'master' script gives its own error, with the location of _its_ temporary directory?

**Comment by maxpietsch** [comment]
Yes, it is kind of redundant as long as the script operates in its temporary directory when the error occurs.  Removed it in 88197f0e245074987.

**Comment by maxpietsch** [comment]
@Lestropie As it came up again in the forum, are you happy with me merging #763?

**Comment by maxpietsch** [comment]
Thanks!
