### ISSUE TITLE
scripts headerInfo fails if mrinfo not in path

### ISSUE THREAD

**Issue by maxpietsch** [MRtrix3/mrtrix3#754]
Fixed it in 8a1f40d756146586c5744c in the scripts_keeponerror branch but it might make sense to use extend `runCommand` instead: 

Something like `out = ""; runCommand('mrinfo ... ',  stdout = out)` might be handy and keeps the mrtrix bin path parsing in one place.

**Comment by Lestropie** [comment]
In the `stanford` branch I have `runCommand()` returning the stdout and stderr contents as its result, so that should simplify this.

**Comment by Lestropie** [comment]
Should be fixed after merging #785.
