### ISSUE TITLE
Indiced beyond range provided to mrconvert -coord result in segfault

### ISSUE THREAD

**Issue by thijsdhollander** [MRtrix3/mrtrix3#757]
Just ran into this in the morning: when running `mrconvert` with `-coord axis index/indices`, if the specified index (or one of the indices) is out of range, this seems to not be checked for.  This results with very high probability in a segfault (or maybe otherwise, unexpected behaviour).

**Comment by jdtournier** [comment]
:grimacing: ahem, very shoddy programming indeed...

**Comment by thijsdhollander** [comment]
Resolved by #789 ?

**Comment by jdtournier** [comment]
Yes, sorry, got distracted just at the wrong moment...

**Comment by jdtournier** [comment]
Sorry, thought this was a different issue! Far too early in the morning to be making sensible decisions...
