### ISSUE TITLE
Problem with square bracket syntax for multi-file image

### ISSUE THREAD

**Issue by jdtournier** [MRtrix3/mrtrix3#759]
The [multi-file image syntax](http://mrtrix.readthedocs.io/en/latest/getting_started/image_data.html#multi-file-numbered-image-support) works fine when matching all images by _not_ providing a number sequence, e.g.:

    mrinfo in-[].bio

but won't work when trying to select specific volumes with a [number sequence](http://mrtrix.readthedocs.io/en/latest/getting_started/command_line.html#number-sequences-and-floating-point-lists), e.g.:

    mrinfo in-[3,5,10:12].mif

It looks like it's only matching the first volume, ignoring the rest. Something must have got screwed up in the handling of these cases...

**Comment by draffelt** [comment]
Wow. 8 years working with MRtrix and I never knew you could do that. Makes sense! 

Wonder how many minutes of life I lost to piping mrconvert -coord 3 0 into stuff.

**Comment by thijsdhollander** [comment]
Confusion all over the place.  Is that notation not for selecting files (i.e., matching file names with numbers in them), rather than volumes *within* a file?  I remember using it in MRtrix 0.2, but I haven't been using it since as well.

**Comment by draffelt** [comment]
Ah, yeah. I wrote this in a haze this morning. Surrounded by hungry squealing kids, and after being up all night with Charlie. I just saw the word 'volumes' and got excited.

**Comment by jdtournier** [comment]
Just had a quick look into this, I can't even reproduce the error. Looks like it magically fixed itself... I'll quietly close this off...
