### ISSUE TITLE
mrview segfault unknown/bad options

### ISSUE THREAD

**Issue by maedoc** [MRtrix3/mrtrix3#764]
```bash
$ mrview -version
== mrview 0.3.15-179-g77ed15eb ==
...
$ mrview b0.nii.gz -overlay.load gmwmi.mif -overlay.opacity 0.3 -mode 2 -overlay.load aparc+aseg-d.nii.gz -overlay.colormap 3
mrview: [ERROR] unknown option "-overlay.colormap"
Segmentation fault: 11
```
I didn't expect incorrect options to work, but neither should they cause a segfault? Or is this a joke on Americans? ;)

This is on OS X, built with Qt 5 & Eigen from Homebrew.

**Comment by jdtournier** [comment]
Hehe... No, I'm afraid our jokes are rarely intentional...

We have seen segfaults with incorrect options in MRView, we should do something about it. Thanks for reporting and making sure it doesn't drop off the list.

**Comment by Lestropie** [comment]
> Hehe... No, I'm afraid our jokes are rarely intentional...

Speak for yourself :-P

Yes, GUI apps don't like when an error is thrown before QT elements are actually initialised. I originally logged it back in #323: I'm marking this issue as a duplicate (since #323 has more info), and raising #323 to be a prerequisite for release so it doesn't get forgotten.

**Comment by Lestropie** [comment]
@maedoc Fixed! Thanks for the bump :+1:

**Comment by maedoc** [comment]
wow, that was quick
