### ISSUE TITLE
mrmath with multiple inputs has issues

### ISSUE THREAD

**Issue by thijsdhollander** [MRtrix3/mrtrix3#790]
As posted on the community forum in http://community.mrtrix.org/t/intersection-mask-using-mrmath-min/493 :

> I am performing the fixel-based analysis for my dataset, but have a question for calculating the intersection mask...
On the information page the following mrmath command is mentioned with 'min' option:
mrmath input_all_warped_masks_multiple_inputs min output_template_mask_intersection
However, if I inspect this intersection image, it rather looks like a sum image (the 'sum' option creates exactly the same image by the way)...
Whereas if I use the option 'product' instead of 'min', this rather looks like the intersecting mask that is appropriate in all subjects... 

I tested the same scenario and can confirm this.  This is especially problematic in the context of (fixel-based) analysis, where people seem to use this construct for intersecting masks.  (I hope we might not have been doing that ourselves potentially...?)

Unrelated to this bug, but related to the community post, @draffelt : it seems people do still run into some confusions related to crucial aspects of correctly analysing FD/FC/FDC.  Maybe worthwhile checking if some of those aspects can be documented better; so people aren't making crucial mistakes. :-)

**Comment by Lestropie** [comment]
Pretty sure a `min` operation across binary images will give a *union* mask, not an *intersection*? Just a typo?

**Comment by thijsdhollander** [comment]
Hmm, no, right? :confused:  min(0,1) = 0 , so if it isn't all ones (i.e. in the intersection), then it's not in the resulting mask.

Either way, I tested the same example mentioned on the forum by `mrcat`ing first, and then feeding to `mrmath` with `min`: that *did* seem to work.  So it seems to be at least related to (limited to) the case of multiple inputs to `mrmath`, rather than a 4D input.

**Comment by Lestropie** [comment]
... Never mind me.
