### ISSUE TITLE
Scripts: Wrap basic non-command functionality

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#800]
Initially raised in #795.

Provide wrapper functions for basic functionalities such as file copy / move, so that messages of appropriate verbosity can be generated / operations can be logged to file / `-continue` option gets more fine-grained control.

**Comment by Lestropie** [comment]
This turned out to be relatively easy, and requires minimal modification of scripts to make use of (see a4d8993 for examples).

I haven't touched `population_template` though: that's got a lot of `runCommand('rm -f ...')` and the like, which I think needs a more experienced hand to go through and clean up without breaking the script. That script could potentially also benefit from some liberal use of `delFile()` (see e.g. [modifications to `dwi2response tax`](https://github.com/MRtrix3/mrtrix3/commit/a4d8993e65c07a003b4b859c29aa566bd10866b0#diff-3f90b3b7241a08b9ac9d0da30a4aec41)) to reduce overall storage requirements when `-nocleanup` is not specified. Happy to provide assistance, but I've got more than enough of my own scripts to support that I get no credit for :-1:

**Comment by draffelt** [comment]
I'll take the changes to population template when I merge fixel_format into the next tag. I've already made some changes in there that will probably require some manual merging.
