### ISSUE TITLE
-march not a flag for PPC arch

### ISSUE THREAD

**Issue by maedoc** [MRtrix3/mrtrix3#805]
I'm trying to compile MRtrix3 0.3.15 on a PowerPC architecture, but GCC doesn't accept a `-march` flag for that architecture (cf. `man g++`), so `configure` fails. I've commented out the relevant section, but it might be nice to allow user to opt out of the architecture spec by setting the env var to empty string, e.g.

``` bash
ARCH="" ./configure -nogui
```

If desired I can resubmit this change as a PR.

**Comment by maedoc** [comment]
Also, there seems to be a curious hard dependency on x86 intrinsics in `lib/command.h`.

**Comment by jdtournier** [comment]
Wow, last time I came across one of these must be almost 10 years ago... Had no idea they were still going!

> If desired I can resubmit this change as a PR.

Sounds perfectly sensible, go for it.

> Also, there seems to be a curious hard dependency on x86 intrinsics in lib/command.h.

No need to worry about this, it's currently unused, and would only get included when debugging strange issues related to [denormal operations](http://stackoverflow.com/questions/9314534/why-does-changing-0-1f-to-0-slow-down-performance-by-10x)...

**Comment by maedoc** [comment]
It's a POWER8, which is ppc64le. Thanks for the other info.
