### ISSUE TITLE
tcknormalise: Naming

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#810]
I'm currently re-jigging some streamlines mapping / manipulation code. One command that currently strikes me as odd naming, probably because it existed before _MRtrix3_ had image registration, is `tcknormalise`. This is probably the only reference to 'normalisation' in a spatial sense... We tend to talk about 'warps' and 'transforms', with 'normalisation' instead referring to intensity modulation to a common scale.

Would people be happy with renaming to `tckwarp`? Only trouble with that is that I'd probably want to make it compatible with affine transformations also, and it'd seem wasteful to me to also have a `tcktransform` as a separate command, whereas buried within `tckwarp` it might not get spotted. The functionality definitely _shouldn't_ be in `tckedit`, as that introduces an order dependence problem.

**Comment by draffelt** [comment]
Can we just have one `tcktransform` command that does both (like `mrtransform`)?

**Comment by thijsdhollander** [comment]
That seems to make the most sense to me too!

**Comment by jdtournier** [comment]
Happy with `tcktransform` too, go for it.

**Comment by Lestropie** [comment]
`tcktransform` it is. (Won't change on `master` for a while yet though)
