### ISSUE TITLE
tckgen: Early abort mechanism

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#828]
Need this for my own work, but opening it up for comments given #809.

What I'm thinking is to look at the ratio of maximum number of attempts to maximum number of tracks, and if it's looking increasingly unlikely that the requested number of tracks is not going to be reached, abort `tckgen` rather than waiting until a massive number of attempts have been made.

* I think this would need to be an explicit command-line option: e.g. if the user manually specifies both maximum seed and maximum streamline counts, they may well be happy to proceed until one of the two is satisfied.

* Anyone know a good statistic to use in this scenario? Preferably one that handles the stochastic nature of the process, and would appropriately handle the case where streamline count remains at zero? There's scope for a Bayesian predictor but I'm unsure of the distributions.

**Comment by jdtournier** [comment]
That's not a bad idea! The distribution in this case would be a [Poisson distribution](https://en.wikipedia.org/wiki/Poisson_distribution) - nuclear decay being the typical example. Basically, the probability of observing an event (i.e. a successful streamline) is a constant per unit time (iteration, or in our case, seeding attempt). If we know that probability, we can figure out how many seeds we need, or conversely, how likely we are to achieve the desired number within a fixed number of attempts. In our case, we'd need to figure out lambda and its confidence interval from the existing data, and check that against the minimum lambda needed to reach the desired number of streamlines. I _think_ that can be done using the equations on that wikipedia page and maybe [this post](http://stats.stackexchange.com/questions/15371/how-to-calculate-a-confidence-level-for-a-poisson-distribution)...?

**Comment by Lestropie** [comment]
I initially shied away from Poisson because it's probability of 'a given number of events' per unit 'time'; it's not bounded above, whereas here we can't have more tracks than attempts. Here it's more the probability of any one event (streamline attempt) being successful; hence I was mucking about with binomial ([incomplete beta functions](https://en.wikipedia.org/wiki/Beta_function#Incomplete_beta_function)! Yay!) & approximations thereof. But maybe Poisson might behave better when the mean's closer to zero, I don't know. Or maybe I just derped somewhere in my math.
