### ISSUE TITLE
package_mrtrix outdated

### ISSUE THREAD

**Issue by maxpietsch** [MRtrix3/mrtrix3#834]
package_mrtrix needs to be updated. I updated the paths but I am not sure what to do with `lib/libmrtrix*`

    diff --git a/package_mrtrix b/package_mrtrix
    index 691a917..f9d432e 100755
    --- a/package_mrtrix
    +++ b/package_mrtrix
    @@ -42,7 +42,9 @@ read
       echo - collating MRtrix3 executables and library...
       set -e
       mkdir -p _package/mrtrix3/
    -  cp -r bin/ _package/mrtrix3/
    +  mkdir -p _package/mrtrix3/release
    +  cp -r release/bin/ _package/mrtrix3/release/
    +  cp -r scripts _package/mrtrix3/
       mkdir -p _package/mrtrix3/lib
       cp lib/libmrtrix* _package/mrtrix3/lib/

The error is `cp: cannot stat ‘lib/libmrtrix*’: No such file or directory`

**Comment by jdtournier** [comment]
That would be `release/lib/libmrtrix*`, I think.

**Comment by maxpietsch** [comment]
There is no `libmrtrix*` in any subfolder. Shall I copy the full release/lib folder?

**Comment by jdtournier** [comment]
Just a thought: did you configure with `-static` or `-noshared`...? Because in these cases it won't generate a shared library at all...

**Comment by maxpietsch** [comment]
Oops, was a static build.Thought two are better than one...

**Comment by jdtournier** [comment]
OK, so I guess we should test for the existence of the library, or at least not error out if it's not found. Something like this should do it:

    cp lib/libmrtrix* _package/mrtrix3/lib/ || echo "no shared library found"

**Comment by maxpietsch** [comment]
Had to change quite some links. Hope I did not mess up any. Seems to work on my system with static and nonstatic build. Not tested on a different system.

**Comment by jdtournier** [comment]
Good work. Just one thing: I think it would be best to copy into the same folder as before (i.e. not into `release`). The idea of that `release` folder is to hold all of the files generated by the build in one place, and to allow multiple configurations side-by-side (by targeting different folders than `release`). For the standalone install, it makes no sense to maintain that structure, best to just copy into `_package/mrtrix3/bin` (or `lib`) directly...

**Comment by maxpietsch** [comment]
Should be done with 7b9b5c63b8e
