### ISSUE TITLE
mrcalc should complain when 2 volume have the same grid but different header

### ISSUE THREAD

**Issue by romainVala** [MRtrix3/mrtrix3#840]
Hello

I was doing a multiplication of 2 volumes with different header (but the same dimention) and mrcalc did not complain. Since the results may often be wrong, it should stop or at least make a warning (like fslmat). 
A small improvement but usefull for end users

thanks

Romain

**Comment by draffelt** [comment]
Good suggestion. I'll add a warning

**Comment by draffelt** [comment]
Will close this. It has been fixed and will be included in the upcoming release
