### ISSUE TITLE
mrview: add go to specific volume entry

### ISSUE THREAD

**Issue by maxpietsch** [MRtrix3/mrtrix3#848]
It seems we don't look at a lot of fMRI data with thousands of volumes... Going to the last volume in the GUI can take a while, especially over slow connections. It would be nice to have a `go to volume...` menu entry and corresponding shortcut ("G"?).

**Comment by jdtournier** [comment]
Not a bad idea. In the meantime, isn't there a control for that in the View tool...?

**Comment by maxpietsch** [comment]
I didn't think about the View tool. Might be just me but I wouldn't search for it in a tool called "View options".

**Comment by thijsdhollander** [comment]
As I mentioned in the pull request: I really like this.  Even though available in the view options, not everyone may easily discover it there indeed, but also the addition of a key combination to do this quickly is in an of itself a worthwhile thing, I reckon.  It's simple things like this that make the viewer a very powerful multi-purpose tool!

**Comment by jdtournier** [comment]
I like the `G` / `Shift-G` shortcut idea for volume / volume group control. That was always a funny shortcut to set the background colour anyway... Not sure what to assign that action to now, maybe `U` for 'underlay colour'? We could also modify the text in the menu to match...?

**Comment by jdtournier** [comment]
Crap, I guess this issue is obsolete now, should discuss in #852... Let's close this off.
