### ISSUE TITLE
Typo in man page of mrcalc

### ISSUE THREAD

**Issue by ansk** [MRtrix3/mrtrix3#850]
I think there is a typo in man page of mrcalc:

Operands (values or images) are pushed onto the stack in the order they appear (as arguments) on the command-line, and **operands** (specified as options) operate on and consume the top-most entries in the stack, and push their output as a new entry on the stack.

The statement **operands** should be replaced to **operators**.

**Comment by dchristiaens** [comment]
I think you're right. Thanks for reporting 🙂.
