### ISSUE TITLE
Rearrange MRtrix Docs structure

### ISSUE THREAD

**Issue by draffelt** [MRtrix3/mrtrix3#861]
I'm in the middle of updating the FBA docs, and plan to add a few more FBA-related tutorials. It got me thinking about the whole "workflow" and "tutorial" division in the documentation, and how the distinction between the two is not that clear. For example the HCP tutorial could easily be called a workflow, and the MT-CSD workflow is short enough to be a tutorial.

After some discussions with Rob and Donald, we are thinking it might be worth having dedicated sections for specific analysis. E.g. FBA, and Structural Connectivity. We can also have sections for grouping tutorials on "Spatial Normalisation (warping tracks, longitudinal registration etc)", "Model Fitting (DTI, MSMT, etc", and anything else that comes up. 

I think we would still need a standard Tutorials section for things that do not relate to the other categories. 

I plan to change this in the tag 0.3.16 branch unless anyone has any issues

**Comment by dchristiaens** [comment]
I think this is a great idea. Go for it!

**Comment by thijsdhollander** [comment]
Just for reference, as @draffelt is aware, I'm all for this kind of restructuring as well.  The old tutorials and workflows terminology to describe these docs was indeed quite ambiguous; and as we introduce a lot of other documentation, the introduction of more (distinct) categories was definitely needed as well!  So I'm all for it! 👍

**Comment by draffelt** [comment]
See the initial restructuring of the documentation [here](http://mrtrix.readthedocs.io/en/tag_0.3.16/index.html)

My plan is to have these sections under FBA:

* ss_fibre_density_cross-section
* ms_fibre_density_cross-section
* fba_of_other_measures
* displaying_results_with_streamlines
* computing_effect_size_wrt_controls

Since multi-shell FDC analysis has quite a different ordering of pre-processing (bias and intensity normalisation) to single-shell. I was thinking of moving the [explanation of why we do a global intensity normalisation](http://mrtrix.readthedocs.io/en/latest/workflows/DWI_preprocessing_for_quantitative_analysis.html) to a dedicated section under the 'concepts' heading. Then adding the specific steps for preprocessing to the individual single- and multi-shell analysis pages. Any objections?  Speak now as I'll be working on this tomorrow. Cheers.

**Comment by thijsdhollander** [comment]
Makes full sense.  Just having that in a dedicated section will come in very handy on a lot of occasions: it's one of the main things we often have to explain to people in different contexts, so it certainly goes beyond just any specific pipeline.

**Comment by jdtournier** [comment]
> I was thinking of moving the explanation of why we do a global intensity normalisation to a dedicated section under the 'concepts' heading.

Agree with @thijsdhollander here, this sounds like a very good idea. 

Just had a quick look through the current table of contents, and one thing I noticed is that we're missing the basic stuff. There is no page about plain old CSD, or simple tract delineation, or TDI. I can see why this would be the case, they were covered in the basic tutorial section, but this now appears much later on in the docs, so it's not at all obvious where to go for the simple stuff. Not too sure how to fix that, I think we'll need additional pages to cover these topics anyway, but maybe the tutorials also need to come first, before the more detailed sections? And I would probably move the [debugging tutorial](http://mrtrix.readthedocs.io/en/tag_0.3.16/tutorials/advanced_debugging.html) over to the [Troubleshooting subsection](http://mrtrix.readthedocs.io/en/tag_0.3.16/getting_started/troubleshooting.html)  and move that as its own section to after the Concepts section.  

What do you reckon?

**Comment by draffelt** [comment]
> There is no page about plain old CSD, or simple tract delineation, or TDI. I can see why this would be the case, they were covered in the basic tutorial section

Do you mean in the original 0.2 docs? I can't see anything about tract delineation in the master branch docs.

I agree there needs to be a dedicated page for each of these. Maybe we need a "Tractography basics" section, which includes tract delineation. And a separate "TWI" section, which includes TDI and things like TWFC, which is currently in the [FAQ](http://mrtrix.readthedocs.io/en/latest/tutorials/FAQ.html#generating-track-weighted-functional-connectivity-tw-fc-maps) 

Maybe the [Basic DWI Tutorial](http://mrtrix.readthedocs.io/en/latest/tutorials/basic_dwi_processing.html) could be under "Getting Started", and use [the example image](https://github.com/MRtrix3/mrtrix3/issues/227), with some mrview screenshots?

I'll create a troubleshooting section as mentioned.

**Comment by draffelt** [comment]
Should FAQ be under troubleshooting or getting started?

**Comment by thijsdhollander** [comment]
Is an FAQ section typically not separate from either of those?  I can see how it could contain questions that relate to typical *problems* people run into (so that's a troubleshooting aspect), but also more simple questions that new users would typically ask ("How do I generate those cropped tractograms I saw in Raffelt et al.?"; more a getting started kind of question).  Having an FAQ section separately makes it the most flexible, I reckon.  That would allow us to add FAQs of either kind over time (e.g. as we encounter them more than once on the community forum).
