### ISSUE TITLE
dwipreproc: First volume alignment issue

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#874]
Resulting from discussion [here](http://community.mrtrix.org/t/dwipreproc-register-fieldmap-to-dwi-other-questions/621/4).

`eddy` assumes intrinsic alignment between the first of its _b_=0 input volumes, and the first volume that was input to `topup`. There is however a `dwipreproc` usage scenario where this isn't the case: The `-rpe_pair` option (or, more generally, using the `-se_epi` option in 0.3.16). Any mis-alignment between the first volume acquired for susceptibility distortion correction, and the first _b_=0 volume in the DWIs, will result in incorrect inhomogeneity field correction.

There's two ways I can think of that this could be dealt with (that don't require modifying FSL or superseding those commands), but I want to make sure I pick the right one:

### 1. Add first DWI _b_=0 volume to `topup` input

Take the first _b_=0 volume in the DWI series that is to be fed to `eddy`, and concatenate it to the start of the image volumes to be fed to `topup`. That way, when `topup` generates all of its results with respect to this volume, it's intrinsically aligned to the volume that `eddy` subsequently uses as its reference.

* May introduce a bias in `topup`, e.g. estimating the field based on 2 A>>P and 1 P>>A volumes. Could potentially look for this in the phase encoding table and scrub a volume accordingly.

* I _think_ this should intrinsically account for differences in header transform between the single _b_=0 and the other SE EPI volumes, if my assumptions about `topup` and `eddy` are correct, but I'll need to test.

* If FoV size is not identical, would require re-gridding the _b_=0 volume to match the SE EPIs (or the other way around).

* Assumes equivalent TE == equivalent contrast between _b_=0 volume and SE EPIs (which wouldn't be the case for our protocols if I had my way).

### 2. Explicit registration

Perform explicit rigid body registration step to align first _b_=0 volume with first SE EPI volume.

* Would require more exhaustive testing to make sure everything's behaving as it should. E.g. My suspicion is that the b-spline coefficients are derived in image space and then applied in image space with no regard for the header transformations, which means modifying that transformation may do nothing.

* Would be able to deal with differing contrasts between the _b_=0 and SE EPI volumes.

* Registration would be imperfect since the first _b_=0 volume will still be inhomogeneity distorted when the registration is performed, and it's not guaranteed that an SE EPI volume can be found with equivalent distortion. Solving this would require performing iterative registration between the `topup`-corrected brain volume and the `eddy`-corrected volume _during_ `eddy`.

I think Option 1 is winning out having written it down. But open to comments. Also open to help given I'm supposed to be grant writing :-1:

**Comment by thijsdhollander** [comment]
> Registration would be imperfect since the first b=0 volume will still be inhomogeneity distorted when the registration is performed, and it's not guaranteed that an SE EPI volume can be found with equivalent distortion. Solving this would require performing iterative registration between the topup-corrected brain volume and the eddy-corrected volume during eddy.

Essentially, these cases go beyond certain limitations of the whole RPE story: if there's significant motion between all images that you need to relate to each other, you're missing the information to disentangle the effects of (inhomogeneity) distortion and motion, or relate the images used for distortion correction to those other ones that need to be corrected indeed.  Our only lucky hope is that motion can at least be assumed to be rigid.  But the only real rigorous way to tackle this elegantly is optimising a bunch of things "at once" (or iteratively indeed).  This could be done in a framework that doesn't even have to distinguish between these separate scenarios (but indeed not entirely using the fixed-box tools `topup` and `eddy`).

I may be completely wrong here (sorry if I am), but: @dchristiaens, weren't you working or going to work on this topic in general (and include some other acquisition scenarios in it)?  If you've eventually got things on the way, it may not make a lot of sense to put a lot of effort into patching this up now; any relatively-quick fix is at least going to be a bit hacky in one way or another, right?

**Comment by Lestropie** [comment]
The most recent version of `eddy` has this:

#### `--field_mat`

Specifies a flirt style rigid body matrix that specifies the relative locations of the field specified by `--field` and the first volume in the file specified by `--imain`. If my_field is the field specified by `--field`, `my_ima` is the first volume of `--imain` and `my_mat` is the matrix specified by `--field_mat`. Then the command:
`flirt -ref my_ima -in my_field -init my_mat -applyxfm`
should be the command that puts `my_field` in the space of `my_ima`.

-----------

This is clearly FMRIB's solution to the issue. So I'll need to detect the presence of this option (and warn if it's not there), do the necessary registration with `flirt` (preferably using those SE EPI images with distortions most closely resembling the input DWIs), and pass on to `eddy` appropriately.

**Comment by Lestropie** [comment]
Issue with solution 1 raised in #1051 [here](https://github.com/MRtrix3/mrtrix3/pull/1051#issuecomment-316019766). I had recognised that it made an assumption of equivalent contrast between SE-EPI images and DWI *b*=0 images, and that this applied to a possible case where the SE-EPI images were acquired with a reduced TE, but failed to realise that users may acquire single-band SE-EPIs for field estimation and multi-band DWIs, and single-band SE-EPI images and *multi*-band DWI *b*=0 images would *not* have equivalent contrast due to longitudinal relaxation effects.

It's possible in this scenario that SE-EPI images and DWIs may also not have equivalent distortions due to GRAPPA settings. This *should* be picked up using `-rpe_header` (worth double-checking), but will *break* the assumptions of the `-rpe_pair` option, as well as `-rpe_all` *if* used in conjunction with `-se_epi`. This likely warrants a follow-up post to the `3.0_RC2` release announcement.

Separately to that, option 2 in the original post may still be a viable alternative for dealing with misalignment. It would require ensuring that the first DWI *b*=0 volume is also the first volume in the series (as was performed in #1051). I think the alignment issue could possibly be dealt with better than originally described: From the distortion-corrected image, predict how that image would be distorted based on the inhomogeneity field and the phase-encoding of the first *b*=0 volume, and then do a rigid-body registration between that and the actual first *b*=0 volume, using mutual information to account for possible differences in contrast. This would therefore *not* require calling `eddy` iteratively, since `eddy` assumes only that the estimated field is aligned with the first *b*=0 volume. As described previously, would need to make sure that the estimated inhomogeneity field can be transformed and still be handled appropriately by `eddy`.

Would appreciate people's thoughts on this. If I'm overlooking a key assumption as I did with option 1, better to find it sooner rather than later.

**Comment by Lestropie** [comment]
Note: Predicting what the `-se_epi` image would look like if it had the same phase-encoding as the first *b*=0 image in the DWIs will require inversion of the non-linear warp field image provided by `topup`. Looks like we already have code to do it, but this approach will need access to that functionality from the `warpconvert` interface.

**Comment by Lestropie** [comment]
Bumping this since it came into my mind yesterday.

Option 2 is I think beyond my scope. I'm instead thinking about re-raising option 1, which is for the most part already implemented in #1051. The issue with that solution is the potential for differences in contrast between SE-EPI images and DWI *b*=0 images, due to variations in TE or TR (the latter possibly being caused by a change in MB factor), or indeed flip angle. However I'm hoping that these are the vast minority of acquisitions; and given the state of current software available I'd also be strongly advising users against such acquisitions.

So the question then is whether we can use option 1 in order to mitigate the motion issue in the vast majority of cases, but try to explicitly detect those cases where the assumptions of the solution do not hold. There are two possibilities that come to mind:

- After `topup`, calculate e.g. the mean CoV throughout the brain volume. This will be elevated in the problematic case due to both differential contrast between images, and incorrect inhomogeneity field estimation.

- Using `mrhistmatch`, look for non-linearities in the histogram matching curve, which would indicate differences in tissue contrast over and above a linear scaling of image intensities.

I could also start catching TR & flip angle from the DICOMs, and perform additional tests of those in cases where fields are present in both image headers, like what's [already in place](https://github.com/MRtrix3/mrtrix3/pull/1051/files#diff-9a2510352b82dd6f73530274c31a7e1fR384) for TE in #1051.

Opening for thoughts / alternative suggestions.

**Comment by thijsdhollander** [comment]
> The issue with that solution is the potential for differences in contrast between SE-EPI images and DWI b=0 images, due to variations in TE or TR (the latter possibly being caused by a change in MB factor), or indeed flip angle. However I'm hoping that these are the vast minority of acquisitions;

I'm not sure that is the case.  I've come across this already with different users.  I think the significance of the motion really making an important difference is less likely than any of the difference-in-contrast scenarios.  I'm not against the additional implementation of any further strategies, but given how experimental and heuristic the automated strategies to detect the scenarios might be, and given how varied those scenarios could be, we'd need an incredible sample of scenarios to really decently tune this... and then still...

So what I would propose is to have the "option 1" strategy as a (non-default) _option_ to `dwipreproc`.  Users who do expect significant motion (and judge that that motion will significantly impact the distortion estimation's translation to the other images) can consciously switch such an option on, after they've reassured themselves that they understand what the strategy does.  There could even still be warnings if certain heuristics detect a potential problem with the contrast.

I'm still of the opinion we've got to be quite careful here, since we're using external tools.  Users will (and _should_) still refer in their papers to the FSL methods' papers to indicate what they have done.  If due to a strategy that we implemented on top of that, results happen to be suboptimal and it's obvious in the results, I don't want us or our software to be the cause of having such results associated with FSL out there.  That's why I think it's safer to have the *default* operation of the script to reflect the default suggested steps that are outlined in the `topup` and `eddy` manuals.

**Comment by Lestropie** [comment]
Yeah, an explicit option could work. I'd still probably look into the heuristic detections, since I'd like the solution to be applicable in my BIDS App; but I could experiment with that possibility after the fact.

**Comment by thijsdhollander** [comment]
> I'd still probably look into the heuristic detections, since I'd like the solution to be applicable in my BIDS App

Sure, nothing against having such features as options.  You could easily have an option that would use heuristics and then automatically decides based on those.  Or even "hidden" options that would activate such an automated heuristic detection just for the sake of some automated environment, like a BIDS app indeed.  That shouldn't stand in the way of keeping the current default behaviour for users that directly engage with the `dwipreproc` script.

**Comment by Lestropie** [comment]
Closed by #1159.
