### ISSUE TITLE
Problem with mrregister - modification of intensity

### ISSUE THREAD

**Issue by renardfe** [MRtrix3/mrtrix3#880]
Hello,

I performed a registration between two images of CSD (4th order of SH -15 parameters) of the same patient. I used a non linear registration (mrregister -transformed image2_test_NL.nii CSD2.nii CSD1.nii) with CSD1 my target image and CSD2 my moving image.
The transformation works well but I have an important modification in the range of intensity of the first coefficient of my CSD between my moving image CSD2 and my transformed image image2_test_NL (I display the histograms for the image before and after registration).

Moreover I have some negative values in my transformed image, and I think that the first coefficient represents the mean value of the spherical function (which must be positive for CSD?).
I have the same problem with other images and also with other kind of transformation (affine).

Did I perform correctly the registration? Maybe I missed the reorientation step?

Thanks for your response and for this terrific software!!! 
Félix

![image_moving](https://cloud.githubusercontent.com/assets/13638822/21954113/c4d5128e-da48-11e6-9a20-86903f17d508.png)
![image_register](https://cloud.githubusercontent.com/assets/13638822/21954114/c4eb4c52-da48-11e6-9476-1d003d292258.png)

**Comment by maxpietsch** [comment]
Hello Félix,

How do you generate the histograms? What does 1mrstats1 give you for image2_test_NL.nii and CSD2.nii?  

Here is what I did:

    mrregister 1/csd4.mif 2/csd4.mif -transformed_midway /tmp/1h.mif /tmp/2h.mif -transformed /tmp/1_2.mif
    mrhistogram $(mrconvert 1/csd4.mif - -coord 3 0) 1.hist -force -bins 100
    mrhistogram $(mrconvert 2/csd4.mif - -coord 3 0) -template 1.hist 2.hist
    mrhistogram $(mrconvert /tmp/1_2.mif - -coord 3 0) -template 1.hist 1_2.hist -force
    mrhistogram $(mrconvert /tmp/1h.mif - -coord 3 0) -template 1.hist 1h.hist
    mrhistogram $(mrconvert /tmp/2h.mif - -coord 3 0) -template 1.hist 2h.hist

Which looks like this:

![image](https://cloud.githubusercontent.com/assets/10046944/21979777/5fdd95fe-dbd8-11e6-83a4-72c33622fcd9.png)

You are right that the first volume corresponds to the integral of the FOD and it should be non-negative. In theory. Yet there are reasons why negative zeroth components might be valid or desired in practice. See for instance here: #786

**Comment by renardfe** [comment]
Hello,

Thanks for your fast answer!

I generated the histogram with fslview. However I use mrview and I
visualised more coherent values.

Here the values obtain from mrstats
For the CSD2.nii:
 volume         mean       median    std. dev.          min
max             count
 [ 0 ]          0.0139499       0           0.0254416        0
       0.422038      3932160

For image2_test_NL.nii:
volume         mean        median    std. dev.          min
max             count
 [ 0 ]          0.0141052       0           0.0254557   -0.0126766
0.4158          3932160

So it seems also to work well.

Is there any modification in the header of the image or any cast of the
data during the mrregister step?

Thanks again!
Félix


2017-01-16 11:52 GMT+01:00 maxpietsch <notifications@github.com>:

**Comment by maxpietsch** [comment]
Yes, the default cast is to float. Also, the output image does not necessarily have the same stride order as the input image. This might be the reason for the difference in the histograms you see using fsl tools. You can find out the stride order via `mrinfo image` and change it, if desired, using `mrconvert oldimage newimage -stride 1,2,3-4`.
