### ISSUE TITLE
Update and standardise copyright notice

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#9]
The copyright notice on all project files date back to the original release of MRtrix in 2008. They probably need to updated when this new version is released. Not sure how it's supposed to be done - maybe:

`Copyright 2008,2013 Brain Research Institute, Melbourne, Australia and King's College London, UK`

But when the time comes, the simplest thing to do will probably be to strip out all of these comments and preprend the same updated notice to all files...

**Comment by jdtournier** [comment]
OK, now that we're coming close to merging `updated_syntax` and hopefully full release, it would be a good time to revisit this issue. As mentioned above, the original copyright notice dates back to 2008 and assigns copyright to an entity that no longer officially exists... 

So the question now is, who should get copyright? In a collaborative project like this, any one file might have been contributed to by any number of people from different institutions - do we need to list every contributor and their institution for each file...? 

I'm not sure how this is handled, but personally I'd favour assigning copyright to a 'collective' (for want a better word). Maybe we could call _the MRtrix3 posse_...? Although there may be more appropriate words to this effect... I'm guessing other projects must be using a similar approach, but haven't looked into it - would really appreciate someone having a quick look into this, I'm not going to have time any time soon. 

How would people feel about this? I think it would be the fairest thing to do, and also avoids any one contributor or institution standing out over the others. We could have a wiki entry detailing who the contributors are and their corresponding institutions, which we could link to in the copyright notice?

Thoughts welcome.

**Comment by draffelt** [comment]
Happy assigning copyright to a collective. We can also add institution logos to the MRtrix page as discussed previously.

**Comment by Lestropie** [comment]
Only thing I would suggest is removing the author name & date from the notice at the top of each source file. Currently it seems about 50% of MRtrix3 was written on 27/06/08. `git blame` should take up the slack.

**Comment by dchristiaens** [comment]
I did a bit of research, but found surprisingly little information on this. Most relevant are [especially this one](http://ben.balter.com/2015/06/03/copyright-notices-for-websites-and-open-source-projects/) and [this one](http://haacked.com/archive/2006/01/26/WhoOwnstheCopyrightforAnOpenSourceProject.aspx/).

According to these posts, your proposal of assigning copyright to an "MRtrix collective" seems sound to me. As per your suggestion, it is then required to define this collective in a separate file, either on the wiki or in the repository. Thus, all good with me.

I also agree with Rob that the author names in source files can go.

**Comment by jdtournier** [comment]
Great, thanks for digging this up. We'll assign copyright to "the MRtrix3 developers", and remove individual authors from the notice - I agree it's a waste of space...

**Comment by thijsdhollander** [comment]
I'm also all for the collective!  I can think of many cool names; but sadly, none of them are probably suitable for professional use. :cry:  So maybe a standard "the MRtrix3 developers" is the best choice. :+1: 

Also, I wouldn't put much focus on the institution logos; but rather have the institutions pop up "naturally" as the affiliation(s) of each developer (in the MRtrix3 developer list).  The BRI should probably pop up nowhere anymore...?

**Comment by jdtournier** [comment]
Closing this, discussion continues on #31.
