### ISSUE TITLE
Contradictory documentation regarding the -independent option for mtbin

### ISSUE THREAD

**Issue by bjeurissen** [MRtrix3/mrtrix3#911]
``mtbin`` documentation says:
> Intensity normalisation is performed by either determining a common global normalisation factor for all tissue types (default) or by normalising each tissue type independently with a single tissue-specific global scale factor.

with an option ``-independent`` to perform normalise each tissue type independently:
> -independent intensity normalise each tissue type independently

However, the ``Fibre density and cross-section - Multi-tissue CSD`` documentation says:
> This step performs global intensity normalisation by scaling all tissue types based on a single scale factor. A single multiplicative bias field is also estimated and applied to correct the output: foreach * : mtbin -independent IN/fod.mif IN/fod_bias_norm.mif IN/gm.mif IN/gm_bias_norm.mif IN/csf.mif IN/csf_bias_norm.mif

suggesting that the ``-independent`` option should be used to perform intensity normalisation using a single scale factor. I assume the ``-independent`` option has to be dropped in the ``Fibre density and cross-section - Multi-tissue CSD`` docs?

**Comment by draffelt** [comment]
Yep. Good get. My mistake
