### ISSUE TITLE
Memory alignment macro datatype error

### ISSUE THREAD

**Issue by dchristiaens** [MRtrix3/mrtrix3#912]
I just built `tag_0.3.16` on my MacBook Pro with clang++ and Eigen 3.3, and got _thousands_ of compiler warnings related to the new memory alignment macros. All look similar to this:
```
In file included from cmd/mtbin.cpp:22:
./core/transform.h:22:21: warning: integer literal is too large to be represented in a signed integer type, interpreting as unsigned [-Wimplicitly-unsigned-literal]
./core/types.h:150:78: note: expanded from macro 'MEMALIGN'
  FORCE_INLINE void operator delete[] (void* ptr) { if (alignof(__VA_ARGS__)>MRTRIX_ALLOC_MEM_ALIGN) __aligned_free (ptr); else ::operator delete[] (ptr); }
                                                                             ^
<command line>:4:32: note: expanded from here
#define MRTRIX_ALLOC_MEM_ALIGN 18446744073709551615
                               ^
93 warnings generated.
```
It boils down to requiring a `size_t` datatype for the `MRTRIX_ALLOC_MEM_ALIGN` macro, but I can't figure out (1) where it's defined (is it set by the build script?), and (2) how to cast them to the appropriate type. 

For good measure, I tried modifying the `MEMALIGN` macros to
```
// ...
if (alignof(__VA_ARGS__)>size_t(MRTRIX_ALLOC_MEM_ALIGN)) 
// ...
```
but that's obviously insufficient. Defining `MRTRIX_ALLOC_MEM_ALIGN` as
```
#define MRTRIX_ALLOC_MEM_ALIGN 18446744073709551615u
```
might do the trick, but then again I can't find it anywhere in the code or in the build script.

**Comment by jdtournier** [comment]
> It boils down to requiring a size_t datatype for the MRTRIX_ALLOC_MEM_ALIGN macro, but I can't figure out (1) where it's defined (is it set by the build script?),

Almost. Set by configure - look at your `config`. Should be `-DMRTRIX_ALLOC_MEM_ALIGN=16` typically. Sounds like something has gone slightly weird in your configure step. What does the `configure.log` show for the bit that detects the alignment of the memory allocator?

**Comment by dchristiaens** [comment]
Ah, I see. The relevant bit in `configure.log` for some reason detected that big number:
```
REPORT: Detecting allocator memory alignment:

COMPILE /var/folders/31/v3w9vpxx36307g4dlfln4rh40000gn/T/tmpaI77fH.cpp:
---

#include <iostream>
#include <limits>

int main (int argc, char* argv[]) 
{
  size_t default_align = std::numeric_limits<size_t>::max();
  for (size_t n = 0; n < 100; ++n) {
    struct alignas(64) X { double c[8]; };
    X* x = new X;
    size_t align = reinterpret_cast<size_t>(x) & 63U;
    if (align && align < default_align)
      default_align = align;
  }
  std::cout << default_align << "\n";
  return 0;
}


---
EXEC <<
CMD: clang++ -c -std=c++11 -DMRTRIX_MACOSX -fPIC -mmacosx-version-min=10.12 -DMRTRIX_WORD64 -DMRTRIX_NO_NON_POD_VLA -isystem /Users/daan/dev/eigen/3.3.0/ /var/folders/31/v3w9vpxx36307g4dlfln4rh40000gn/T/tmpaI77fH.cpp -o /var/folders/31/v3w9vpxx36307g4dlfln4rh40000gn/T/tmpaI77fH.o
EXIT: 0
>>

EXEC <<
CMD: clang++ /var/folders/31/v3w9vpxx36307g4dlfln4rh40000gn/T/tmpaI77fH.o -mmacosx-version-min=10.12 -lz -o a.out
EXIT: 0
>>

EXEC <<
CMD: ./a.out
EXIT: 0
STDOUT:
18446744073709551615
>>


REPORT: 18446744073709551615 byte

```
Any idea what's going on?

**Comment by dchristiaens** [comment]
It looks like this line:
```
size_t align = reinterpret_cast<size_t>(x) & 63U;
```
is always returning 0. I wonder if this could depend on the system's little/big endianess? According to [this SO post](http://stackoverflow.com/questions/11985399/does-a-pointer-point-to-the-lsb-or-msb), it seems like it can...

Perhaps it is also safer to initialise `default_align` to 63U?

**Comment by jdtournier** [comment]
I can't see how endianness can have anything to do with this... The pointer and 63U should have matching endianness, it should be fine. If you want, you can try modifying to:

    size_t align = reinterpret_cast<size_t>(x - nullptr) & 63U;

This should force to return a difference, which by this point should really behave like any integer.

What this seems to indicate though, is that out of 100 malloc calls, the allocated region was always aligned on 64 byte boundaries (or greater). It would be great if the alignment was in fact determined from the type itself (since it was specified as requiring 64 byte alignment) - that would be a distinct improvement on the current standard... 

What might be worth trying is to initialise `default_align` to 128U, and replace the current 63U with 127U. This should return something no greater than 64 assuming the allocator's alignment isn't wider than that, and 128 otherwise. 

But if the allocator on macOS now actually honours the alignment requirement of the type allocated, that would be quite a change - with lots of scope for unexpected behaviour, unfortunately...

**Comment by jdtournier** [comment]
On that note: I just had a closer look into the issue that @maxpietsch highlighted on #785 regarding the missing `::max_align_t` typedef. According to [the standard](http://en.cppreference.com/w/c/types/max_align_t), that typedef provides exactly the information that this particular test is supposed to figure out: the alignment of the allocator. That mean we should be able to replace all occurrences of `MRTRIX_ALLOC_MEM_ALIGN` with `alignof (std::max_align_t)`. which [should be defined on a C++11 compliant environment](http://en.cppreference.com/w/cpp/types/max_align_t) (even if `::max_align_t` might not be defined, since that's C11, not C++11). I'll give that a shot, see what happens...

**Comment by dchristiaens** [comment]
> What this seems to indicate though, is that out of 100 malloc calls, the allocated region was always aligned on 64 byte boundaries (or greater). It would be great if the alignment was in fact determined from the type itself (since it was specified as requiring 64 byte alignment) - that would be a distinct improvement on the current standard...
>
> What might be worth trying is to initialise default_align to 128U, and replace the current 63U with 127U. This should return something no greater than 64 assuming the allocator's alignment isn't wider than that, and 128 otherwise.
>
> But if the allocator on macOS now actually honours the alignment requirement of the type allocated, that would be quite a change - with lots of scope for unexpected behaviour, unfortunately...

This seems to be the case. When I replace the 63U with 127U I get exactly 64 byte alignment. I am using macOS 10.12.3 with Xcode 8.2.1. Not sure since which version this has been introduced.

On the other hand, when I run the example from [the reference](http://en.cppreference.com/w/c/types/max_align_t), I get 16 byte alignment.
```
Alignment of max_align_t is 16 (0x10)
The address obtained from malloc(123) is 0x7fbe754027d0
```
I don't know what to make of this...

**On a different note**, I also tried replacing `MRTRIX_ALLOC_MEM_ALIGN` with `alignof(std::max_align_t)` in `types.h`, and managed to build, run mrview, and run the tests successfully (except for fixelconvert and fixelreorient). It appears that you were working on it at the same time; I will give your commit a try and see what happens...

**Comment by dchristiaens** [comment]
Works great. Thanks!

**Comment by boegel** [comment]
I'm running into this error at configure time:

```
ERROR: memory alignment of default allocator is not sufficient for Eigen3 to operate correctly
```

I understand this check has now been removed in favour of just using `alignof(std::max_align_t)`.

Is it worth trying to backport this fix to MRtrix 0.3.16 (tried that quickly, apparently not trivial)?
How much different is 3.0 compared to 0.3.16 in terms of functionality?

I would rather not install release candidates (3.0_RC2) for production use.
How far away is the final 3.0 release?

**Comment by Lestropie** [comment]
Given the amount of effort that has gone into getting MRtrix to play ball with Eigen 3.3, and the fact that `0.3.16` is still open beta, I don't really think we'll be back-porting things like this to maintain prior versions.

You can find changes from `0.3.16` to `3.0_RC1` [here](http://community.mrtrix.org/t/mrtrix3-version-3-0-release-candidate-1/851), and `3.0_RC1` to `3.0_RC2` [here](http://community.mrtrix.org/t/mrtrix-3-0-release-candidate-2/1065).

I don't know your exact situation, but it would seem unusual to me to be against use of a release candidate but in favour of a prior beta version. Along with new features, there's invariably a lot of bug fixes along the way. Also, if installing "for production use", one of the changes in `3.0_RC1` was modifying the internal directory structure to conform to the Filesystem Hierarchy Standard, which should make installation more consistent with other packages.

We're historically bad at making predictions about release dates. However we'll be getting ourselves into a bit of a snag if it doesn't happen this year. I'll offer @jdtournier the chance to make a more precise prediction when he gets back from holiday if he so chooses.

Are you trying to configure this older MRtrix version against Eigen 3.3? If so, have you tried instead using Eigen 3.2?

**Comment by boegel** [comment]
@Lestropie I went forward with `3.0_RC2`, since the person who requested the MRtrix installation required tools only includes with `3.0_*`.

Also, I agree it makes more sense to prefer `3.0_RC*` over the beta releases.

Thanks for the feedback!
