### ISSUE TITLE
Docs: include section about DW gradient handling

### ISSUE THREAD

**Issue by jdtournier** [MRtrix3/mrtrix3#916]
As prompted by [this discussion](http://community.mrtrix.org/t/dwi2response-failed/444/24?u=jdtournier).

**Comment by Lestropie** [comment]
[Bump](http://community.mrtrix.org/t/after-the-command-mrconvert-why-changed-the-precision-of-gradient-table/767).

**Comment by jdtournier** [comment]
Yes, I suppose I should just bite the bullet... :weary:

**Comment by jdtournier** [comment]
closed by #932
