### ISSUE TITLE
mrconvert does not honour output strides when converting to nii.gz

### ISSUE THREAD

**Issue by bjeurissen** [MRtrix3/mrtrix3#925]
I noticed mrconvert does not honour strides when converting to nii.gz using the 0.3.16 branch.

E.g. starting with a file with strides ``1,2,3,4`` and running ``mrconvert -stride -1,2,3,4 in.mif out.nii.gz``, will create a ``nii.gz`` file with strides ``1,2,3,4``. This problem does not occur when ``mrconvert``ing to ``.nii``, ``.mif`` or ``.mif.gz``.

@jdtournier suggested it might have been introduced along with the NifTi2 changes.

**Comment by Lestropie** [comment]
By default NIfTI2 will only be used if the image is too large for NIfTI1, and it's a completely separate image handler. So while it might have been due to changes that occurred at the time, it shouldn't be anything in the NIfTI2 code itself.

**Comment by jdtournier** [comment]
Spotted the issue, easy fix. I'll commit in a sec.

**Comment by jdtournier** [comment]
Should be fixed with 821db39a - feel free to close when you've confirmed that solves the problem.

**Comment by jdtournier** [comment]
@bjeurissen: is this fixed? Go ahead and close if it's all OK...

**Comment by bjeurissen** [comment]
Fixed! Thanks!
