### ISSUE TITLE
Position of the Tool menu in mrview toolbar

### ISSUE THREAD

**Issue by thijsdhollander** [MRtrix3/mrtrix3#929]
As the title suggests, this is about a first world problem. (to lighten up everyone's day in between all the more complicated stuff)

So, as you may have noticed, I've recently given the mrview interface, mostly the icons and a few other minor layout related things, a makeover (in `tag_0.3.16`).  Everything should now be easier on the eyes, the intuition, the OCD-related consistency itch, etc...  As part of those updates, I've added a dynamic spacer between the toolbar buttons and the "information" button/menu (see also screenshot below).

While giving everything a fresh rethink anyway, I wondered if the "Tool" button/menu's position could be changed for the better too.  The logic being that about all the other buttons (apart from the "information" one) are either about interacting specifically with the main image(s), or all images at once.  To put it the other way around: to interact with main image(s), everything is needed *but* the "Tool" menu (apart maybe from the view tool).  And even when interacting with a "Tool"-wise overlay (e.g. FODs, tracks, ROIs, ...), one still needs to interact with the main image underneath (or manipulate the overall view / navigate the 3D space).

Long story short: shouldn't the "Tool" menu sit a bit further to the right?  That would also shift the interaction mode buttons and lock to grid controls more to the left; closer to their other main-image buddies.  Now, when thinking about this, I saw another opportunity: why not put the "Tool" button to the far right, beyond the dynamic spacer?  The logic being that after opening a tool, one would probably want to use the actual tool... and these tools are opened by default snapped to the right of the window.  So that way, the "Tool" button would also sit closer to its actual tool buddies. :relieved: 

So, in summary, 3 options:

1. leave as is
2. move to the right
3. move to the far right

![screenshot from 2017-03-06 16-58-23](https://cloud.githubusercontent.com/assets/11952694/23599288/32e31e24-0294-11e7-8ccf-24b1f738342b.png)

**Comment by maxpietsch** [comment]
Uhh a poll :) I'll go for 3. 

By the way, I think it would make sense that when tool actions are performed via command line (I am thinking mainly about `-*.load*` options) it would make sense to open the corresponding tool automatically to allow adjusting of tool related parameters.

**Comment by jdtournier** [comment]
I'm torn. I'd also be happy with option 3 in principle, but in the current political climate, I simply cannot say that I'd like to 'move to the far right'... 

> By the way, I think it would make sense that when tool actions are performed via command line (I am thinking mainly about -*.load* options) it would make sense to open the corresponding tool automatically to allow adjusting of tool related parameters.

That's what they used to do until 1b1e5e76. The reason I opted to hide them was because they interfered so badly with the window size when trying to script screenshots... I'm not sure how to deal with this, open to ideas.

**Comment by Lestropie** [comment]
> I'd also be happy with option 3 in principle, but in the current political climate, I simply cannot say that I'd like to 'move to the far right'...

:rofl: Well played, good sir.

> The reason I opted to hide them was because they interfered so badly with the window size when trying to script screenshots... I'm not sure how to deal with this, open to ideas.

Toggle whether or not utilised tools auto-open depending on whether or not there's a screenshot instruction in `argv`?

**Comment by thijsdhollander** [comment]
Ok, I came up with a commit on the `tag_0.3.16` branch that should unite interface and political desires!  Everything but the Tool and Info menus now sits on the (far) left. :relieved: 

You'll notice that the first time you give this a go, it may field slightly weird (and break all the habits your mouse-hand had become accustomed to).  But it does start working well for a larger window (like the one above), and feels very convenient to be able to open a tool via that menu, and already find your mouse cursor in the general area of where the tool opens up!

**Comment by jdtournier** [comment]
> Everything but the Tool and Info menus now sits on the (far) left.

:rage: fascist tools...

**Comment by thijsdhollander** [comment]
If the tools are already fascist, then I wonder what the Info menu is... :stuck_out_tongue_winking_eye: 

Well, I'll close this specific issue now.  We can always open another issue for the behaviour of `.load` style options.
