### ISSUE TITLE
tckgen: use more appropriate angle for SD_STREAM algorithm

### ISSUE THREAD

**Issue by jdtournier** [MRtrix3/mrtrix3#930]
As discussed [here](http://community.mrtrix.org/t/just-ifod1-and-ifod2-works-fact-not/722?u=jdtournier).

**Comment by Lestropie** [comment]
Note: A similar discussion probably needs to be made for the FACT algorithm, since that does not perform any interpolation, and hence all streamline curvature occurs at the voxel transitions.
