### ISSUE TITLE
Compile on Linux with Anaconda Python distribution

### ISSUE THREAD

**Issue by lgianca** [MRtrix3/mrtrix3#936]
This is not exactly a bug about MRtrix3 but rather an issue with the configuration script (at least in Linux) when trying to compile release/bin/mrview and release/bin/shview with the anaconda python libraries installed (with the python Qt package). What happens is that the the linker fails to generate mrview and shview due to multiple unresolved dependencies.

In my system (Ubuntu 16.04), the reason was that the configure script gave precedence to the Qt libraries in the anaconda directory rather than the system wide Qt libraries. 

A workaround that worked for me was to change 
```
export PATH="/home/lgianca/anaconda2/bin:$PATH"
```
to 
```
export PATH="$PATH:/home/lgianca/anaconda2/bin" 
```

I hope this helps other people running into the same problem.

**Comment by jdtournier** [comment]
Yes, I had a [fair rant about this](http://community.mrtrix.org/t/error-processing-project-file-tmp-tmpexdmto-qt-pro/288/4?u=jdtournier) on the forum a while ago... Like you said, there's not much we can do from our side. However, what might be helpful is if you could post this information on that same thread on the community forum. I expect​ this will be the first port of call for most people, posting there would probably reach more users. I don't expect many users would want to go through the issues here, they tend to be a little too technical for most people...

**Comment by lgianca** [comment]
Hi jdtournier,
Thank you for pointing out the existing rants about it.
I have posted my workaround to the same thread.

**Comment by jdtournier** [comment]
Great, thanks!
