### ISSUE TITLE
scripts: include MRtrix version and date in help text

### ISSUE THREAD

**Issue by maxpietsch** [MRtrix3/mrtrix3#945]
Since they interact with other binaries, it might be worth adding the version string to the script description.

**Comment by Lestropie** [comment]
This is slightly tricky (hence why it's been omitted thus far). For binaries, the version number is written to a variable via `version.cpp`, which in turn is created at compile time via the build script checking the Git version, and goes into the shared library. For the scripts, there's no 'compiled' shared library. Reading that `version.cpp` file directly, or querying the Git version directly, aren't great solutions, since for packaged distributions neither will exist.

I suppose the build script could generate a file `lib/mrtrix3/version.py` (`tag_0.3.16` branch)? This file would then need to be included in packaged distributions.

**Comment by maxpietsch** [comment]
An alternative would be to query the output of `mrinfo -version` in `lib/mrtrix3/app.py`:

```
  def _printHelp(self):
    import subprocess, textwrap

    def bold(text):
      return ''.join( c + chr(0x08) + c for c in text)

    def underline(text):
      return ''.join( '_' + chr(0x08) + c for c in text)

    def appVersion():
      import subprocess, os
      from mrtrix3.run import _mrtrix_bin_path
      p = subprocess.Popen([os.path.join(_mrtrix_bin_path,'mrinfo'),'-version'],stdout=subprocess.PIPE)
      line = p.stdout.readline()
      return line.replace('==','').replace('mrinfo','').lstrip().rstrip()

    w = textwrap.TextWrapper(width=80, initial_indent='     ', subsequent_indent='     ')
    w_arg = textwrap.TextWrapper(width=80, initial_indent='', subsequent_indent='                     ')

    s = 'MRtrix ' + appVersion() + '\t' + bold(self.prog) + '\n'
    s += '\n'
    s += '     ' + bold(self.prog) + ': Script using the MRtrix3 Python library\n'
    s += '\n'
    s += bold('SYNOPSIS') + '\n'
    s += '\n'
    s += w.fill(self.synopsis) + '\n'
    s += '\n'
    s += bold('USAGE') + '\n'
    s += '\n'
    usage = self.prog + ' [ options ]'
```

**Comment by Lestropie** [comment]
That'd assume that the version of `mrinfo` being used corresponds to the version of the script libraries being used. Which *should* always be the case, but isn't *guaranteed* to be the case if the user's done some kind of funky installation. Capturing specifically the version of the *script library* that the script is importing would be more precise; question is whether or not it's worth the hassle...

**Comment by maxpietsch** [comment]
I agree, and I think it would be good warning the user if scripts library and binary versions differ as this can cause problems.

For now, I've pushed changes to create a `-version.py` file at [build](https://github.com/MRtrix3/mrtrix3/commit/2ae45dc7f19e89f75b6e1156d883993d5efeaeb0#diff-b0da275520918e23dd615e2a747528f1R1093). This breaks if someone pulls a new version but does not hit ./build.

>  This file would then need to be included in packaged distributions.

`./package_mrtrix` is currently not up to date with the tag 0.3.16 branch as it still uses the old folder structure.

**Comment by jdtournier** [comment]
> This breaks if someone pulls a new version but does not hit ./build.

Yes, there's unfortunately not a lot you can do about this. Other than maybe a pre-commit hook - but [as it says in the docs](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks), _client-side hooks are not copied when you clone a repository_ - so it's no use to us as a means of enforcing consistency between the version stated in the code and within its own git history....

>> This file would then need to be included in packaged distributions.
>
> ./package_mrtrix is currently not up to date with the tag 0.3.16 branch as it still uses the old folder structure.

Given that you're writing this file to `lib/mrtrix3/share/`, no special handling required. That's where the scripts live anyway... 

But yes, `package_mrtrix` will eventually need to be updated.
