### ISSUE TITLE
Eigen 3.3 memory alignment and std::make_shared

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#957]
Just spent a good while trying to figure out why I couldn't get rid of the dreaded Eigen "Go read this web page!" memory alignment error.

Changing this:
```
files.push_back (std::make_shared<Class> (filename));
```
To this:
```
std::shared_ptr<Class> subject (new Class (filename));
files.emplace_back (subject);
```
fixed the issue.

`std::make_shared` must be requesting memory in some other way that's bypassing the over-ridden `new` operator. [Could be an issue elsewhere](https://github.com/MRtrix3/mrtrix3/search?utf8=%E2%9C%93&q=make_shared&type=). Either need to figure out what's going on and provide the necessary override as part of the `MEMALIGN()` macro, or remove all instances of `std::make_shared` (and look for it in `check_memalign`).

**Comment by jdtournier** [comment]
Crap, it's probably using placement-new over a previously allocated memory region... I think we'll need to forbid the use of `std::make_shared` then... 

BTW, does this only work with `emplace_back()`? I'd assume `push_back()` would also be ok, right? Although I'd agree `emplace_back()` is the better choice in this case...

**Comment by jdtournier** [comment]
See if #960 fixes it... Feel free to reopen if it doesn't.
