### ISSUE TITLE
tckconvert: writes single tract in ASCII file?

### ISSUE THREAD

**Issue by blezek** [MRtrix3/mrtrix3#964]
Not sure if this is a feature or a bug =)

In `tckconvert.cpp` (https://github.com/MRtrix3/mrtrix3/blob/master/cmd/tckconvert.cpp#L165-L168), the output ASCII file is opened and closed for each _streamline_, with the result that only the last streamline is written to the output file.  Makes for good file compression, but not sure that's what the intent of the function was!

Good news is that the reader faithfully converts back to a `.tck` file.

**Comment by dchristiaens** [comment]
This is not a bug, but I can see that this feature is probably not documented properly.

The correct syntax is:
```
tckconvert tracks.tck track-[].txt
```
This will then generate a collection of files `track-0000000.txt`, `track-0000001.txt`, etc. corresponding to individual streamlines. 

The intent of exporting to ascii was really to have a last-resort conversion to interface with other tools. Therefore, we deliberately don't want to come up with our own *ascii separator* between successive streamlines. Instead, we export each streamline to a single text file.

**Comment by jdtournier** [comment]
@dchristiaens is spot on. But I do think we should update the documentation to reflect this, and also detect when the argument for the output isn't in the expected format. I've had a go at this in #966, hopefully that'll sort this out...
