### ISSUE TITLE
fixelcorrespondence critical bug (old *.msf version)

### ISSUE THREAD

**Issue by thijsdhollander** [MRtrix3/mrtrix3#968]
I won't spend a great deal of words on this, since this is essentially already resolved in the `tag_0.3.16` branch.  However, this has the _potential_ to have a big impact in certain FD studies done using the current `master` branch.  The solution is simply to merge `tag_0.3.16` to `master` and make a clear announcement that users should probably update asap and potentially redo studies that may be affected.  We discovered this bug a couple of weeks ago and redid a certain study since (one that wasn't yet done using the `tag-0.3.16` branch; most/all of our other ones are already using that branch by default since half a year or so).

The problem/bug, for reference: when a subject fixel image (FOD warped to template space, segmented in fixels, reoriented) was provided to the old `fixelcorrespondence` command, and in certain voxels the fixel analysis mask that it was supposed to be "mapped to" had fixels that no matching subject fixel was found for, rather than the FD of those fixels ending up to be zero (as it should; and is now inherently doing in the `tag_0.3.16` branch), *the value that the fixel analysis mask image happened to have in those fixels, was retained*.  Following the *old* workflow, that would typically have been a template FOD peak amplitude ("`temp.msf`", following the suggested name of the *old* workflow).  A typical obvious case (upon QA) would be lesions (all images show subject total voxelwise AFD in template space in the background, and subject-to-template-mapped-after-`fixelcorrespondence` as fixel overlay):

![old](https://cloud.githubusercontent.com/assets/11952694/25114257/b53d59a2-2440-11e7-90e8-06a2d4ac8ea2.png)

Even "binarising" the template fixel mask on purpose to make it into a bit more of a real "mask" doesn't help.  In that case, the (binary) "1" is simply retained:

![old_binary](https://cloud.githubusercontent.com/assets/11952694/25114268/d2fc68de-2440-11e7-98e8-827bfb6fc7fe.png)

The problem is resolved inherently for the `tag_0.3.16` branch.  There, the template fixel mask will typically not even have any values/contrast (just an `index.mif` and `directions.mif`, i.e., just fixels, no values):

![new](https://cloud.githubusercontent.com/assets/11952694/25114290/0ea0bb42-2441-11e7-9846-016a00b9ee5d.png)

There are clear cases where this may result in false negative findings due to massively increased variance, or false positive findings due to... quite decreased variance.  CFE may spread the problem, depending on circumstances.  Note it doesn't only happen in lesions, but also on the edges of structures, and potentially other lower FD regions close to the subject-wise threshold chosen to segment the fixels.

**Comment by draffelt** [comment]
Thanks for reporting this Thijs. Agreed that we really need to merge ASAP. Aside from this issue, I'm guessing there are a few people performing FBA studies, and the new format/viewer and documentation is far superior. 

I'm not too worried about this affecting previous/current studies. Lesions aside, fixel correspondence is typically very good in the core WM tracts where alignment is good and it's feasible to do group analysis. 

> or false positive findings due to... quite decreased variance

Again I'm not too worried about this. I guess lesions are typically spatially heterogeneous, so it's unlikely they would be found in the same location and cause decreased variance. Even if they did, the peak AFD value would be larger than the AFD integral on the controls, so assuming a controls > patients 1-tailed test (default), then it would be a FP rather than a FN.

**Comment by draffelt** [comment]
Just to confirm, how far away are we from merging 0.3.16?  Just wondering if I should fix this.

**Comment by thijsdhollander** [comment]
False positives are indeed less likely; and they would indeed show up as an increase in FD of patients vs controls, which is something that not many people would test for.  If, for some reason, they'd be looking at just effect sizes, they may end up being confused as to what contrast they're actually looking at (since the most obvious feature may be a typical lesion area, yet things behave opposite as to what's expected then.
The biggest practical concern is definitely lesions; e.g. MS and AD studies (of which I did see a few recently popping up, and I know some people are eyeing FBA as their next step, or are already attempting it.  Periventricular lesions are quite common in these pathologies, and they do quite often show up in very similar areas though... or are just all over the place (as in: all over many places at once) in certain cohorts.

But in any way, it's inherently fixed in the new format's tools.  I fully agree the experience using the new format and tools (and very good docs!) is so much more user-friendly, better organised, much more convenient especially for the data-management challenge that a FBA can otherwise be.  There's certainly a lot of new people trying their hand at FBA at the moment (or will be doing very soon).  The merge would be a very positive step forwards for them. :+1:

**Comment by thijsdhollander** [comment]
By the way, I'm not sure fixing it still in the old `master` is going to help a lot in practice: we'd still have to make lots of noise about it, so people would update their `master` branch.  That would then end up being 2 times a lot of noise (and questions/issues on the forum) in a short period of time... the effort of making the noise (and supporting people if they struggle with the update) should (I reckon) best be focused on the one good update that brings in all the benefits of the new fixel format. :slightly_smiling_face:

**Comment by draffelt** [comment]
Agreed.

**Comment by thijsdhollander** [comment]
I'll close this issue now: it looks like the merge will happen soon enough so as to not have to bother with it any more on `master`!
