### ISSUE TITLE
DICOM JPEG support

### ISSUE THREAD

**Issue by maedoc** [MRtrix3/mrtrix3#993]
I came across DICOMs with JPEG lossless compression, supported neither by FreeSurfer nor Mrtrix.  I used a `dcmdjpeg` utility from dcmtk (dcmtk.org) to decompress the files.

Their utility is backed by a C++ library, and source code seems provided under a nice license.  It could be helpful either to use their classes to decompress, or at least mention the dcmtk if you run into this error during file i/o.

**Comment by jdtournier** [comment]
Good suggestion. I just had a look into supporting JPEG encoded data directly within _MRtrix3_, it looks like quite a bit of work - it would need a whole new `ImageIO` handler, and there's lots of different encodings and transfer syntaxes to support. Not something I'd undertake lightly. 

As to using their classes directly within _MRtrix3_, I'm always _very_ reticent to add dependencies to the code unless absolutely required, and even then I'd have to guarantee that it works on all platforms with a suitably relaxed open-source license (`dcmtk` would be fine on that front, [it's BSD](https://www.openhub.net/p/dcmtk/licenses)). However, there's a good chance that the way `dcmtk` handles DICOM would clash heavily with _MRtrix3_'s internal handling, making it near-impossible to use `dcmtk`'s JPEG handling within the _MRtrix3_ DICOM handling backend. It certainly sounds like nearly as much work as supporting JPEG decompression directly using [libjpeg](http://libjpeg.sourceforge.net/)... 

Which leaves as a last option your suggestion of mentioning `dcmtk` to convert the data when we encounter a JPEG-encoded dataset. That sounds much easier to do, and is probably going to prove much easier for us to support in the long run... I'll have a go at that in a bit.

**Comment by maedoc** [comment]
Yep, even just a mention would go a long way toward avoiding Googling all that. The alternative seemed to be Oisirix which is Mac only. 

FWIW I set it up on our cluster like so
```bash
wget ftp://dicom.offis.de/pub/dicom/offis/software/dcmtk/dcmtk360/bin/dcmtk-3.6.0-linux-i686-static.tar.bz2
tar xjf dcmtk*.tar.bz2
mv dcmtk* /soft/dcmtk360
```
with usage
```bash
export PATH=/soft/dcmtk360/bin:$PATH
export DCMDICTPATH=/soft/dcmtk360/share/dcmtk/dicom.dic

for img in dcmdir/*
do
  dcmdjpeg $img ${img}.tmp
  mv ${img}.tmp $img
done
```

**Comment by jdtournier** [comment]
That's useful information, might be worth including on the main MRtrix3 documentation? We could add a new RST page in the [troubleshooting section](https://github.com/MRtrix3/mrtrix3/tree/master/docs/troubleshooting) called 'DICOM handling' or something, and then just make sure it's referenced in the [index file](https://github.com/MRtrix3/mrtrix3/blob/master/docs/index.rst). Would you be interested in helping out with that?

**Comment by maedoc** [comment]
PR sent, so closing this issue.

**Comment by jdtournier** [comment]
Cool - although I'll probably end up including your additions into the ones I'm making now...

**Comment by maedoc** [comment]
ok 👍  I wasn't sure what scope you had in mind

**Comment by jdtournier** [comment]
No worries, I'll merge your changes into my branch in a minute - your efforts will not be wasted... :wink:
